### ISSUE TITLE
Minor improvements/corrections for the roadmap page.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#101]
Since we use the word "goals" only for the generic things for v1 and 2.0.0 version sections, I would like to see "planned" added in the "New Features for x.y.z version" sections. Use case: recent attempt to get date in core and the fact that we are debating whether we should postpone things for 1.3.x.

The word "for" kinda implies it, but lets be specific so that people complain less when they don't get what was "promised".

Also, why is the "features" part capitalized?

...and, I think it is more natural to read "version x" rather than "x version"

So, I'd like to see the header for each section be "New **f**eatures **planned** for version x.y.z"  while we are still in dev (emphasis only for the changes to be made - not actually bolded text) end then these changed to "Key features added in version x.y.z" once we release.

For more posterity/consistency, I would also like to change the "Key Features in v1" to "Key **f**eatures in **version** 1.0.x" (no need for the word "added" here - this was the initial release).

**Comment by quicksketch** [comment]
Thanks @klonos! With the 1.2.0 release imminent, it's a great idea to look over this page. I made the changes you suggested as well as turning this page much more into a history/future plans page. I removed the overall goals for the project as they were redundant with the [Philosophy page](https://backdropcms.org/philosophy).

I reworded the past releases in past-tense, the current release in present tense, and the future releases in future tense. Let me know what you think!

**Comment by klonos** [comment]
...just a couple of things here and there:

> Key features version 1.0.0

Should be "Key features **in** version 1.0.0"

> This release was in development for 16 months of development...

Lots of development there :stuck_out_tongue: 

Other than these, looks good. Thanx.

**Comment by quicksketch** [comment]
> Should be "Key features in version 1.0.0"

Thanks fixed!

**Comment by klonos** [comment]
Thank YOU.
