### ISSUE TITLE
Project Browser Server on projects.b.org returns 10 results if text search is used

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/backdropcms.org#1014]
See https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Search.20for.20new.20module

**Steps to reproduce**

1. In a Backdrop instance navigate to `admin/modules/install`
2. Search for a term that is likely to return more than 10 results (e.g. "image" or "menu")
3. Check the results

**Expected results**
All relevant results according to specification - I think it searches on title and description

**Actual results**
A maximum of 10 results is shows

@docwilmot [believes](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Search.20for.20new.20module/near/387124920) it is this line:
https://github.com/backdrop-ops/backdropcms.org/blob/86fcb933471f899af0bb9491c08859c59e74206a/www/modules/custom/borg_pbs/borg_pbs.module#L84

And that the line doesn't need to be there.

**Comment by yorkshire-pudding** [comment]
I've created a PR that implements @docwilmot 's suggestion. Please review/test and merge if appropriate.

**Comment by jenlampton** [comment]
I have tested the PR locally and get 20 items per page, with a pager for both "image" and "menu".

**Comment by jenlampton** [comment]
Merged, and deployed.
