### ISSUE TITLE
Remove the ability for Anonymous users to create Supporter nodes

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/backdropcms.org#1019]
This is causing a lot of spam and I'm not aware of any valid reason for allowing anonymous users to create supporter nodes. 
Any objections?

**Comment by olafgrabienski** [comment]
No objections, quite the contrary. I think, one problem is that the path `node/add` (often used by spammers) redirects to the Create Supporter form.

**Comment by bugfolder** [comment]
I've turned off "_Supporter_: Create new content" permission on the site for anonymous visitors (so node/add now returns a 403).

But this did raise the question in my mind: how do authenticated users (i.e., people we might want to create Supporter nodes) find this capability, and/or find our list of Supporters?

The list is here: https://backdropcms.org/support/supporters. A few suggestions on this page (which i'm happy to add if others agree):

* Add some words to the header explaning what "being a supporter" means
* Add a link to "add your own entry"
* Since there's only one and a bit pages, expand the pager settings to show all on one page, rather than making visitors use the pager to see the last three rows.

Where do we link that page from? It's not in the menus, and it's not linked from the "Ways to Contribute" page https://backdropcms.org/contribute, where I would have expected to find it.

**Comment by yorkshire-pudding** [comment]
@bugfolder - can we close this issue now?

**Comment by bugfolder** [comment]
> @bugfolder - can we close this issue now?

It would be great to get some feedback on [the suggestions above](https://github.com/backdrop-ops/backdropcms.org/issues/1019#issuecomment-1699185740) (which I'm willing to implement if there's support).

**Comment by yorkshire-pudding** [comment]
> * Add some words to the header explaining what "being a supporter" means
> * Add a link to "add your own entry"
> * Since there's only one and a bit pages, expand the pager settings to show all on one page, rather than making visitors use the pager to see the last three rows.

Yes - I agree with all the above.

**Comment by yorkshire-pudding** [comment]
@bugfolder - I guess you've been busy and/or this has dropped off your radar

**Comment by bugfolder** [comment]
Yeah, unfortunately other committments have pushed a lot of things down my radar stack. I'll bump this one back up.

**Comment by bugfolder** [comment]
> * Add some words to the header explaining what "being a supporter" means

And what should we say that "being a supporter" means? It could mean a bunch of things. How about: 

"These organizations support Backdrop CMS, by contributing code, documentation, issues, discussions, and/or financial support."

We have a whole bunch of checkboxes for "ways to contribute" in the user profile, too many to list in this header without making it junky, so we need something broad.

> * Add a link to "add your own entry"

If we just add a link to `node/add/supporter`, then it will take anonymous visitors to the Access Denied page, which is not very friendly. Ideally, we'd show a link for logged-in visitors, e.g., [Add your own organizations to this list](#), and an explanation for anonymous visitors, e.g., "To add your organization to this list, [log in or create an account](#), then return to this page.".

The supporter page uses the Default layout. A way of getting the user-dependent message would be to create two blocks on the Default layout page with the appropriate visibility conditions, though it bugs me to clutter up the layout that's used for every page with blocks used only on a single page. If it were one of my sites, I'd create a tiny module that implements a Token that displays the desired user-dependent text and then put that token into the View header. Any thoughts (or better alternatives) to how to implement that?

**Comment by yorkshire-pudding** [comment]
Lots to think about there. I'll have a proper look in the morning. Thanks

**Comment by yorkshire-pudding** [comment]
> And what should we say that "being a supporter" means? It could mean a bunch of things. How about:
> 
> "These organizations support Backdrop CMS, by contributing code, documentation, issues, discussions, and/or financial support."

I think this could be broader as we are talking about organisations.  How about:

_"These organizations support Backdrop CMS, by contributing staff time, services and/or financial support."_


> If we just add a link to `node/add/supporter`, then it will take anonymous visitors to the Access Denied page, which is not very friendly. Ideally, we'd show a link for logged-in visitors, e.g., [Add your own organizations to this list](#), and an explanation for anonymous visitors, e.g., "To add your organization to this list, [log in or create an account](#), then return to this page.".
> 
> The supporter page uses the Default layout. A way of getting the user-dependent message would be to create two blocks on the Default layout page with the appropriate visibility conditions, though it bugs me to clutter up the layout that's used for every page with blocks used only on a single page.

can't we do a layout override for that page so it doesn't clutter the default layout?

>  If it were one of my sites, I'd create a tiny module that implements a Token that displays the desired user-dependent text and then put that token into the View header. Any thoughts (or better alternatives) to how to implement that?

`b.org` has quite a few custom modules so there is a precedent if that is preferred.

**Comment by bugfolder** [comment]
> can't we do a layout override for that page so it doesn't clutter the default layout?

Ah, yes, of course.

**Comment by bugfolder** [comment]
OK, please take a look: https://backdropcms.org/support/supporters

(Odd behavior I noticed while doing this: you can't clone the Default layout, which seems like a common thing to do.)

**Comment by yorkshire-pudding** [comment]
> OK, please take a look: https://backdropcms.org/support/supporters

Looks good. Many thanks @bugfolder 

> (Odd behavior I noticed while doing this: you can't clone the Default layout, which seems like a common thing to do.)

While there isn't a clone button.  If you create a new layout override and give it the `node/%` context then it will have the same blocks.  I think rather than cloning, it acts as a template as well as a fallback.  However, if you create a new layout override without `node/%` context then it won't have the main content block, but will have the rest of the blocks.

**Comment by bugfolder** [comment]
I think we're done with this, so closing.
