### ISSUE TITLE
hook_node_load() looks wrong

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#102]
Excuse the cryptic title but I was trying to figure project_browser_server's issues and looked at this function. It goes to the trouble of building a `$project_nids` array then never uses that array. Is this correct?

```
/**
 * Implements hook_node_load().
 */
function project_node_load($nodes, $types) {
  $project_nids = array();
  foreach ($nodes as $node) {
    if (project_node_is_project($node)) {
      $project_nids[] = $node->nid;
    }
  }
  if ($project_nids) {
    $result = db_select('project', 'p')
      ->fields('p')
      ->condition('nid', array_keys($nodes))
      ->execute();
    foreach ($result as $row) {
      $project_data = (array) $row;
      unset($project_data['nid']);
      $nodes[$row->nid]->project = $project_data;
    }
  }
}
```

**Comment by quicksketch** [comment]
Yep, I think you're correct. We're querying unnecessarily on the original list of $nids, not the newly created one.

```
->condition('nid', array_keys($nodes))
```

Should be:
```
->condition('nid', $project_nids)
```

**Comment by quicksketch** [comment]
Could you file this against project module as well? I think it's fine to patch production directly, but we want to make sure that fixes are included in project module for when we next update the module.

**Comment by quicksketch** [comment]
Thanks! Merged into project.module and the backdropcms.org repository. Sorry for the long delay.
