### ISSUE TITLE
bee fails on backdropcms.org

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#1020]
Attempting to run any `bee` command on backdropcms.org (e.g., `bee status`), results in this error:

PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_FOUND_ROWS in /home/backdrop/repo/www/core/includes/database/mysql/database.inc:65
Stack trace:
#0 /home/backdrop/repo/www/core/includes/database/database.inc(1797): DatabaseConnection_mysql->__construct()
#1 /home/backdrop/repo/www/core/includes/database/database.inc(1575): Database::openConnection()
#2 /home/backdrop/repo/www/core/includes/bootstrap.inc(2908): Database::getConnection()
#3 /home/backdrop/.bee/includes/miscellaneous.inc(60): backdrop_bootstrap_is_installed()
#4 /home/backdrop/.bee/bee.php(22): bee_initialize_console()
#5 {main}
  thrown in /home/backdrop/repo/www/core/includes/database/mysql/database.inc on line 65

**Comment by bugfolder** [comment]
Yeah, I was wishing that I could find a version somewhere in the bee code. (Maybe even before implementing `bee version` command, just put the version in the header of the bee.php file?)

I do see that the `.bee` folder on the server has a `.github` subdirectory, so it's a git repo. Running `git status` in that repo results in

On branch 1.x-1.x
Your branch is up to date with 'origin/1.x-1.x'.

Oh, but `git log -1` results in

```
commit c21f8f6ffd5f49918e21189336acb2024dbe8e1e (HEAD -> 1.x-1.x, origin/HEAD, origin/1.x-1.x)
Author: indigoxela <***>
Date:   Wed Oct 26 13:29:35 2022 +0200

    Issue #147: Show Bee version when running the status command (#227)
    
    - Add Bee version to status command
```

So that's pretty old.

Just did a git pull.

Tried `bee status` again (from within the `.bee` directory). New error message:

PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /home/backdrop/.bee/includes/render.inc:280
Stack trace:
#0 /home/backdrop/.bee/includes/render.inc(208): bee_get_column_widths()
#1 /home/backdrop/.bee/includes/render.inc(68): bee_render_table()
#2 /home/backdrop/.bee/bee.php(24): bee_print_messages()
#3 {main}
  thrown in /home/backdrop/.bee/includes/render.inc on line 280

Went back to `repo/www`, ran `bee status`, got the original error again:

backdrop@www2:~/repo/www$ bee status
PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_FOUND_ROWS in /home/backdrop/repo/www/core/includes/database/mysql/database.inc:65
Stack trace:
#0 /home/backdrop/repo/www/core/includes/database/database.inc(1797): DatabaseConnection_mysql->__construct()
#1 /home/backdrop/repo/www/core/includes/database/database.inc(1575): Database::openConnection()
#2 /home/backdrop/repo/www/core/includes/bootstrap.inc(2908): Database::getConnection()
#3 /home/backdrop/.bee/includes/miscellaneous.inc(77): backdrop_bootstrap_is_installed()
#4 /home/backdrop/.bee/bee.php(22): bee_initialize_console()
#5 {main}
  thrown in /home/backdrop/repo/www/core/includes/database/mysql/database.inc on line 65

**Comment by yorkshire-pudding** [comment]
Odd that `mb_strlen` is showing as undefined - that is part of PHP; when run outside a backdrop root and without specifying a root (e.g. `--root=/home/backdrop/repo/www`) I would expect it to say:
```
[!] No Backdrop installation found. Run this command again from within a Backdrop installation, or use the '--root' global option.
```

From the www folder, that is odd as it is falling down in the Backdrop code rather than in `bee`.

Try `bee --base-url=https://backdropcms.org --debug  status`

Bee sets a few server settings to let backdrop know it is CLI but I wonder if there is anything peculiar on `b.org` in the way that db settings are defined that is causing this.

**Comment by argiepiano** [comment]
mb_strlen is not enabled by default: https://www.php.net/manual/en/mbstring.installation.php

**Comment by yorkshire-pudding** [comment]
I just created a new account on my reseller account and `mbstring` is selected by default on there (cPanel) for all PHP releases. I appreciate this is a dedicated server so that doesn't apply, but I imagine many distributions may include by default, which is why this has not emerged as an issue in `bee` before now.

**Comment by jenlampton** [comment]
It could be that whatever user we are using on the command line uses a different version of PHP than the webisite does. or a version with different configurations. 

> Bee sets a few server settings to let backdrop know it is CLI but I wonder if there is anything peculiar on b.org in the way that db settings are defined that is causing this.

It could also be that we are using `:localhost` in the `settings.local.php` file?  That's tripped me up a few times and I think the server predates that change we made to core.

**Comment by jenlampton** [comment]
> It could also be that we are using `:localhost` in the `settings.local.php`

This was, in fact, the case.  Here's the related issue for bee:
https://github.com/backdrop-contrib/bee/issues/284

**Comment by larsdesigns** [comment]
Okay, bee is working again. Somehow php8.2-cli was installed and became the default. I removed it and restored php8.1 on both beta and production servers. 

The sites are using 8.1 or 7.4 and are specified in their nginx configuration files.

We should probably set our attention on PHP 8.2.x but we need to test on beta first.

**Comment by larsdesigns** [comment]
Oh, php 8.2 sneaking on was probably my fault during the last OS updates. I will be sure to double check in the future.

**Comment by larsdesigns** [comment]
No further tasks. Closing...
