### ISSUE TITLE
Cleanup for borg_pbs

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#103]
- cleanup messy code comments
- make borg_pbs return image uri's where available
- fix version string return
- fix project type string return.

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop-ops/backdropcms.org/pull/104!

**Comment by quicksketch** [comment]
Oops, I had to revert this change. There was a syntax error, as noted in the PR.

**Comment by docwilmot** [comment]
pushed again
