### ISSUE TITLE
Update README with local install instructions

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#1041]
We should update [the README](https://github.com/backdrop-ops/backdropcms.org/blob/main/README.md) with information on how to set up a local site, including:
* How to run the site WITHOUT CiviCRM, including:
  - which modules need to be disabled, and 
  - what won't work without them
* How to run the site WITH CiviCRM, including
  - special DB permissions needed for the civi install
  - locations of civi settings files / modules / etc

We should maybe also document all the "secrets" that are needed, and what they do, so that people running a site without them will know things that my not work as expected without them. 

Currently this includes: 
```
// Settings for Project GitHub integration. Note, these are deprecated. The should be
// removed after upgrading to the next version of Project module (beta 7), which will
// use the GitHub API module credentials below.
$settings['project_github_secret_key'] = '';
$settings['project_github_access_token'] = '';

// GitHub API module credentials.
$settings['githubapi_client_id'] = '';
$settings['githubapi_client_secret'] = '';
$settings['githubapi_token'] = '';

// RobinPanel credentials. Used to set up QA servers on vpn-private.net,
// which is aliased at qa.backdropcms.org.
$settings['rp_api_password'] = '';

// Gitlc credentials. Used to push QA server information (that was set up by
// RobinPanel) to Gitlc. Gitlc then integrates the information into GitHub.
$settings['gitlc_webhook_api_token'] = '';

// Tugboat.QA credentials. Used to create demo sandboxes.
$settings['tugboat_access_token'] = '';

// SMTP Credentials.
$config['smtp.settings']['smtp_password'] = '';

// CiviCRM Newsletter Signup block
$settings['borg_signup_key'] = '';
$settings['borg_signup_url'] = '';
```

**Comment by bugfolder** [comment]
Double-thumbs-up to this. I didn't know some of these existed.

**Comment by bugfolder** [comment]
I will start working on this.

Since the instructions will probably be rather long, I suggest that rather than putting the information in the README.md file directly, it will go into a separate file, `Setting up a local instance.md`, and then referring to that in the main README.md, in the same way that `Updating BackdropCMS.org.md` is in a separate file and is noted at the end of the main README.md.

**Comment by bugfolder** [comment]
PR created. Seeking review from @jenlampton (or anyone else).

**Comment by jenlampton** [comment]
@bugfolder  this looks really great!

I left a few suggestions on the PR.

The only thing I didn't mention there is the file names. My preference is probably for  `settings.local.example.php instead of `settings.local.generic.php` (same goes for civi settings) but I don't feel strongly about that :)

**Comment by bugfolder** [comment]
`example` versus `generic` is definitely an improvement. My brain was saying "there's a better word out there" but wasn't coming up with it.

**Comment by bugfolder** [comment]
PR updated.

**Comment by jenlampton** [comment]
The PR looks great. 

I think Civi is probably doing something horribly wrong if https://backdropcms.org/project/civicrm_table_prefixes is needed, but since we're using it, it needs to be documented, so I've merged the PR. :)

**Comment by bugfolder** [comment]
OK. Try importing this View and viewing it at path `users-with-display-names` with and without the prefixes. It (ostensibly) displays usernames and their CiviCRM display name in two columns.

[views.view.users_with_display_names.json](https://github.com/user-attachments/files/16091195/views.view.users_with_display_names.json)
