### ISSUE TITLE
Enable telemetry for Bee

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/backdropcms.org#1046]
Pull request: https://github.com/backdrop-contrib/bee/pull/404
Issue: https://github.com/backdrop-contrib/bee/issues/393

Sample data: `{"bee":{"version":"1.x-1.1.x-dev","php_version":"8.2.18","multisite":"No"}}`

Keys:
- `version`
  - Label: Bee version
  - Type: non-numeric (e.g. 1.x-1.1.x-dev, 1.x-1.0.2)
- `php_version`
  - Label: PHP CLI version
  - Type: numeric
  - Precision: 2 (e.g. 7.4, 8.1)
- `multisite`
  - Label: Multisite setup
  - Type: non-numeric (e.g. Yes, No)

**Comment by jenlampton** [comment]
I have added these allowed values for bee 🎉

**Comment by yorkshire-pudding** [comment]
@jenlampton `version` doesn't appear to be working but all the others are coming through. Please can you check. Also. I was hoping `php_version` could have a precision of 2 so things are grouped by minor version (e.g. 7.4, 8.1) rather than patch version.
Thank you.
