### ISSUE TITLE
Contrast issues on individual Showcase pages

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#1047]
![image](https://github.com/user-attachments/assets/18d2756c-2e53-4b32-bd1c-01a2257ad4f6)

The thin font doesn't help, the box behind needs to be more opaque since we can't account for what the background image should be. The visual hierarchy feels off between the title and subtitle, at least on the screenshot above.

**Comment by wesruv** [comment]
Here's where what I did ended up:
![image](https://github.com/user-attachments/assets/e4e407f9-825a-4c3c-8461-108327a09417)

**Comment by bugfolder** [comment]
I tried this out for several showcase sites; a definite improvement on many of them (and OK for the rest). So I'll add this to backdropcms.org shortly. Thanks, @weruv!
