### ISSUE TITLE
Remove release 1.x-2.0.0 for https://backdropcms.org/project/stanford_decanter

### ISSUE THREAD

**Issue by irinaz** [backdrop-ops/backdropcms.org#1057]
Please remove release [1.x-2.0.0](https://github.com/backdrop-contrib/stanford_decanter/releases/download/1.x-2.0.0/stanford_decanter.zip) (1.23 MB)  from listing on the module page  https://backdropcms.org/project/stanford_decanter . This release has been experimental and has been deleted from project page.

**Comment by irinaz** [comment]
@quicksketch , thank you so much for your help today!

**Comment by bugfolder** [comment]
That release has been deleted.

**Comment by quicksketch** [comment]
Thank you @bugfolder!

**Comment by irinaz** [comment]
Thank you, @bugfolder  and @quicksketch
