### ISSUE TITLE
Wrong URL for Bluesky link

### ISSUE THREAD

**Issue by NormPlum** [backdrop-ops/backdropcms.org#1059]
In the footer, the Bluesky link is wrong: https://backdropcms.org/backdropcms.bsky.social

![image](https://github.com/user-attachments/assets/a3a5595a-92ff-404e-82a4-78d729acabe7)

**Comment by Wylbur** [comment]
@NormPlum this feedback is super helpful, thanks for your contribution! 

I have updated the link to direct  to the Backdrop CMS feed:
https://bsky.app/profile/backdropcms.bsky.social

I went back and checked the link, and it is working now.  

Marking this as completed.
