### ISSUE TITLE
Change recommended releases for Decanter theme and Theme Hooks module

### ISSUE THREAD

**Issue by irinaz** [backdrop-ops/backdropcms.org#1060]
Hi, 
Can you change  recommended releases

-  to 1.x-2.0.0-alpha4 (1.22 MB) on https://backdropcms.org/project/stanford_decanter 
-  to 1.x-1.0-alpha2 on https://backdropcms.org/project/theme_hooks  

Thanks!

**Comment by bugfolder** [comment]
Done.

**Comment by irinaz** [comment]
@bugfolder , thanks a lot!
