### ISSUE TITLE
Automatically add comment to pull request when repo is forked

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#11]
Someone wants to help me with an issue I am working on, and they do not yet have a fork of backdrop. They fork my fork. 

The pull request I was working on (on the branch they forked) needs to have a comment added automatically notifying me that someone else is working on the same issue. 

"@whoever has forked your fork and may be working on this issue as well: link"

**Comment by sirkitree** [comment]
Has this actually happened?

I'm just wondering if this is something we're trying to be proactive in solving, or if it's actually a problem. Same with #12... 

If this isn't currently a problem, perhaps we close these issues and reduce the noise, then open again if it actually starts to become a problem. Thoughts?

**Comment by jenlampton** [comment]
It came up because I'm the person who checks her list of PRs, and sometimes works on them. Not realising someone else has opened a new one, which may be more relevant or more correct than my approach.  

If my PR could have been auto-closed or at least auto-commented then I wouldn't have wasted time working in the wrong direction (or maybe duplicating efforts). Of course, if I had clicked back to the original issue I might have noticed the new PR there too. ;)

I'd like to leave this as an open feature-request. We can revisit if people other than me start to have the same problems - I just thought that if adding comments & links was easy we might save some contributors some time and effort - always a good thing :)

**Comment by Gormartsen** [comment]
@jenlampton When somebody just simply fork a code, there is no way to tell that exactly this fork is going to be used for specific issue.

**Comment by BWPanda** [comment]
> I just thought that if adding comments & links was easy...

> I'm not sure this is doable because when a user forks another user's fork, they fork all the branches in the first user's repository.

> ...there is no way to tell that exactly this fork is going to be used for specific issue.

Looks like this *isn't* easy and no one else has had a problem with this. Closing this old issue then.
