### ISSUE TITLE
Create a blog section

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#110]
TODO here:
-  [x]  build a "News & Announcements" Page
-  [x]  add a Tags field (and any other necessary fields) to the post type.
-  [x] add a link from the main nav (now, or after we have a few?)

Things we should post:
* publish each YouTube meeting video with quick notes together
* photos from the latest conference you went to. Short videos would also help.
* Interview posts highlighting contributing developers
* tips, tricks, and short tutorials on smaller things that may not make it to the handbook

ALso: Follow-up from https://github.com/backdrop-ops/backdropcms.org/issues/122

(Previous issue follows)

Currently, the site focuses on being a functional resource (download themes, handbook, press kit etc)

That's fine and all but not good in attracting casual fans wanting to keep tabs on Backdrop, who may one day switch. Might I suggest having a blog so the site doesn't look abandoned and so we can expose some of the activity going on in GitHub to the normal world?

**There's a higher chance for our target audience (non-profit, small-medium biz, etc) to follow along Backdrop via a blog than GitHub, Reddit, etc** (places that naturally attract dev/designers/techie folks)

Most CMSs tend to have sites with a corporate feel and seeing as Drop looks playful and silly...

![drop_lounging_final_black](https://cloud.githubusercontent.com/assets/14132746/10093529/6af9af6a-6319-11e5-995d-f8ff6ee51635.png)

... maybe our blog posts can reflect that nature, kinda like a "by the people for the people" feel? Also, as a way to stand out from the stiff competition. (eh eh, ah forget it ^\_^;)

**Comment by quicksketch** [comment]
We made a start on something like this when 1.2.0 came out, because previously we didn't have any "official" location for announcements. We sent mailers and referenced GitHub, but you're right that it's not the same as being on our own site.

So for now we only have one post: https://backdropcms.org/news/backdrop-1-2-0-released

And I don't even think there's a listing of posts yet. But still, great idea and I think you're right that the site can be used to greater effect for marketing and community purposes.

**Comment by docwilmot** [comment]
+1 for blog.

But I've noticed that Backdrop's Facebook page is a bit scant; I suspect it may be that there is a shortage of time/manpower to keep it updated, and I would fear that the same issue would apply to a blog too.

But it is still a good idea, and should form a part of an overall strategy including also forums and user and support documentation.

**Comment by sutibun** [comment]
I saw that news post by accident while browsing the site. I thought you guys unofficially began a blog. I even went to https://backdropcms.org/news to see more but nothing.

That is what encouraged me to write this issue. I liked that news post but to me that seemed more like an announcement (would fit in well with [this suggestion](https://github.com/backdrop/backdrop-issues/issues/1225) or the homepage too) I guess the "news" part of the URL gives it away.

I just think that with a blog that writes less formally... we can attract searchers looking for a CMS using phrases like "how to create a website", etc. (I know a lil' SEO ^\_^)

And this is where the other shoe drops...

I'm willing to write for the blog, assuming you don't mind my "informal" and silly writing style. (Ah, now you know why I brought in the Drop logo. Such a smart monkey) I'm already writing fairly long posts on GitHub, relatively at least.

What we can do is use IFTTT to automatically publish blog posts to the Facebook page. That's one way to keep it updated.

**Comment by klonos** [comment]
> I even went to https://backdropcms.org/news to see more but nothing.

I think it'd be a good idea to have that as an index page (even if currently there'll only be a single entry listed). I am into the same habit of checking out the parent URLs of websites when they make sense and in this case I'd expect the ```/news``` to be an index. It does leave me with a bad taste when such things happen to website I visit. We are better than that.

> What we can do is use IFTTT to automatically publish blog posts to the Facebook page. That's one way to keep it updated.

There are modules that automatically post things on Twitter and Facebook upon node publish. We can use that because some people are addicted to using those sites as a means of getting news notifications etc. We could port those from Drupal.

**Comment by sutibun** [comment]
Regardless if my writing/style fits, I still think we could have a workflow/process established should the time come. Fairly simple:

draft -> review -> edit -> publish

- Draft status - writer submits content as is
- Review - Someone looks to make sure it's not bad (grammar wise + content itself)
- Edit - draft "sent" back to original writer via backdrop CMS to further edit. What would be cool is if there was a private feedback field that the writer could look at to see what changes are needed
- Publish - well, writer sends back revised content and goes through review process again until good and then published.

This will allow for one time submission and consistent writers.

On a somewhat unrelated note, here is an easy topic to begin the blog: we can create an interview-like series where we ask contributors (and possibly fans) on their experience with backdrop.

- what made them join
- what were initial expectations and how is it in reality
- why continue working + supporting backdrop
- etc

To make it even easier for interviewee, they can either join a Google hangout and simply talk or they can send their answers to the question. I can write up a few questions.

I think the interview series will give a glimpse to other Drupal users and maybe help change their mind. Also, give a more human touch to a site that looks very formal and cold.

**Comment by sutibun** [comment]
By the way, I like how [that news post](https://backdropcms.org/news/backdrop-1-2-0-released) has "... , oh my!" I liked that. I think that's an example of our messages reflecting that silly, quirky personality that our logo embodies. We should have more of this. I think this will really help. Drupal and other CMS have a very corporate feel and I suppose that's right to attract large businesses but I think our audience will better resonate with something down to earth. It'll also make use stand out. (boring vs casual fun)

We don't want to go over the top but enough to show  a personality. I'm thinking something along the lines of [mailchimp](http://mailchimp.com/pricing/)

**Comment by jenlampton** [comment]
Comment from @docwilmot that should not be lost on the other issue:

Would still be wise I'd suspect to get some way to push posts simultaneously to FB, Twitter, (LinkedIn?), as per #133 (comment), but I guess lets walk first then run.

**Comment by jenlampton** [comment]
okay - I reworked the other issue to focus on the sharing part: 
https://github.com/backdrop-ops/backdropcms.org/issues/125

**Comment by jenlampton** [comment]
> I'm thinking something along the lines of mailchimp
Love it, Monkey you are the right primate for the job! :)

**Comment by klonos** [comment]
> ...I'm thinking something along the lines of mailchimp

Of course you would :smile:

**Comment by sutibun** [comment]
Dunno if blog already set up yet but here is monkey's vision of how to organize the blog

![bd-blog](https://cloud.githubusercontent.com/assets/14132746/12081282/e0fe7bcc-b239-11e5-8aa2-ae2289213f55.png)

- Left column will be what you expect from a normal blog. All content types will appear here except the "Meeting" content type. Because Bd meeting videos come every week, they will easily take over and push everything else aside
- On the right column is where we will have a small section listing Bd meetings. This is the best choice because I am confident people won't care to watch a meeting from a month ago. So the plan is to embed the last meeting video for easy access and promote ppl to follow along the "journey". Below that video, we will link to the most recent "Meeting" content. If we use the Video Embed Field, the embedding can be done automatically.
- Also, on the right column, below the Meeting replay section, I suggest we have a section listing the most recent content types that are of the announcement (e.g. Bd 1.2.3 released) or news nature. This is how we can "pin" news types for people who may have missed it.

That's pretty much my vision of the blog. Not too hard to build I think. I also suggest we don't create categories yet... or, at least, not expose them to the public since we aren't 100% sure what posts we will write about frequently.

PS: This is why it's important to create separate content types.

**Comment by jenlampton** [comment]
Thanks @sutibun. I'm not sure that two-column layout will work with our current theme, but I'll give it a shot and we can adjust as necessary.

Also, see related content issue over here: https://github.com/backdrop-ops/backdropcms.org/issues/158

**Comment by jenlampton** [comment]
Initial blog page is up at https://backdropcms.org/news.

I'll work on adding a right sidebar that pulls in all the videos from YouTube.

**Comment by jenlampton** [comment]
Now with more layout action: https://backdropcms.org/news

I think this will do for now, we don't have enough blog content to start dividing items into blog vs announcement vs anything else yet, so instead I'm pulling in videos from YouTube and our Twitter, where most announcements happen.

**Comment by sutibun** [comment]
Ah, forgot about the current layout. Never mind my suggestion. Probably don't go with this then because visually content looks squeezed if you go with the two column layout.

**Comment by jenlampton** [comment]
Since the blog is up and running (mostly) I'm going to close this issue.  Let's open new follow-up issues for improvements to the blog section.
