### ISSUE TITLE
Triangle problems

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#112]
@wesruv 
The triangle icon to the right of the major section links have a faint line on the right edge.

![triangle1](https://cloud.githubusercontent.com/assets/1042283/10109555/304c2996-638d-11e5-9a16-584d9e207291.PNG)

The icon for "System Requirements" link in drawer wraps.

![triangle2](https://cloud.githubusercontent.com/assets/1042283/10109556/304cbae6-638d-11e5-907f-f8f1b290d061.PNG)

**Comment by quicksketch** [comment]
A note that right now we're using a Font Awesome icon that has been cropped off for the triangle. It's actually the "fast forward" icon. This has always bothered me and I'd love it if we replaced this with a CSS-only triangle or SVG.

**Comment by wesruv** [comment]
lol

I'm on it!

**Comment by wesruv** [comment]
That's weird... I can't assign myself this task?

**Comment by klonos** [comment]
Yeah, I can't either. The "Labels", "Milestone" and "Assignee" sections on the right sidebar are disabled.

**Comment by quicksketch** [comment]
> That's weird... I can't assign myself this task?

Sorry, this repository is separate from `backdrop-issues`, so it has separate permissions. I've added both of you as "Authors", which means you can commit to the project (but please don't do that directly). On GitHub that's the only way to make it so you can assign labels, they're tied into the committing permission (which is dumb dumb dumb dumb, but that's what we've got).

**Comment by klonos** [comment]
> I've added both of you as "Authors"...

Thanx!

> ...which means you can commit to the project (but please don't do that directly)

I won't.

**Comment by BWPanda** [comment]
Closing as I believe this is no longer an issue with the new design.
