### ISSUE TITLE
Add Drop mascot in the footer of the site

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#113]
All this time I thought Drop the dragon was the official Bd logo but reading [the presskit](https://backdropcms.org/presskit) closer, I was way off. Makes me a lil' sad.

Maybe it's me but I don't see Drop featured prominently anywhere on the site.

Anyway, I propose we "fix" this by giving him a place in the footer section, centered and resized so it's smaller. I say we go with this image

![drop_lounging_final_black](https://cloud.githubusercontent.com/assets/14132746/10119152/8a4f2bca-6453-11e5-8aa5-05265c71770c.png)

Here, the dragon looks like it just woke up and is about to rise up.

**Comment by Gormartsen** [comment]
I like it!
We need some character here to Identify bd with.

**Comment by BWPanda** [comment]
Closing as Drop's in the footer now.
