### ISSUE TITLE
Typos in 1.2.0 news announcement

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#115]
Found two typos in the [1.2.0 announcement](https://backdropcms.org/news/backdrop-1-2-0-released)

> Improved mobile administration
>
> Though Backdrop has featured responsive layouts since it's release, there's **alwyas** room for improvement. In this **relase**, responsive behaviors have been improved for easier administration from your smart phone or tablet. Check out the sleek and sexy vertical tabs on your phone!

I wasn't going to say anything (my spelling and grammar isn't great) but found two nearby and announcement page is linked to from the homepage.

**Comment by klonos** [comment]
Good catch Monkey :wink:

**Comment by sutibun** [comment]
^\_^) though like to add that I'm not a spelling nazi.

**Comment by quicksketch** [comment]
Thanks fixed!
