### ISSUE TITLE
Materialize's Theme Description has a typo/grammatical error

### ISSUE THREAD

**Issue by clickbox** [backdrop-ops/backdropcms.org#117]
"settings page for serve local style/script files" should possibly be changed to "settings page to serve local style/script files" or "settings page for serving local style/script files"

**Comment by klonos** [comment]
I think that it'd be best to close this issue here and file a separate one over at https://github.com/backdrop-contrib/materialize/issues

**Comment by clickbox** [comment]
possibly. He might not have the permission to edit the backdropcms.org site's content however. This is where @quicksketch said one might put non structurally related issues about the site.

**Comment by klonos** [comment]
Yeah. If it is a general issue with that theme and not limited to bd.org customization, then I believe it should be fixed in that theme and once fixed, we should update the theme used in db.org (I didn't realize we were using that theme).

**Comment by clickbox** [comment]
Cool I made some suggestions in a pull request since I brought it up.

**Comment by quicksketch** [comment]
Great, thanks guys! Closing this. The materialize issue was https://github.com/backdrop-contrib/materialize/pull/2.
