### ISSUE TITLE
Make the "Ways to Contribute" section more accessible.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#118]
I just realized we don't have one!

We could use it for accepting donations, selling t-shirts, pointing developers to the right direction or for https://github.com/backdrop-ops/contrib/issues/110.

**Comment by klonos** [comment]
I'm stupid: https://backdropcms.org/contribute

**Comment by klonos** [comment]
Better to re-purpose this issue, because I was expecting to find a top-level link and the first place I went looking for it was under "Contact". Do you thing that this section deserves a "promotion"? ...perhaps a link to it from the contact us page?

**Comment by quicksketch** [comment]
I added a little description to https://backdropcms.org/contact. We do get the question, "How do I help?" pretty frequently, so I think this makes sense to reference the contribute page.

**Comment by klonos** [comment]
Thanx :wink:
