### ISSUE TITLE
Automatically share (some?) blog posts onto FB & Twitter

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#125]
TODO here:
- port social sharing modules form Drupal
- place them on backdropcms.org
- blog posts (some or all?) should be auto-posted on social media

**Comment by sutibun** [comment]
Dupe :p https://github.com/backdrop-ops/backdropcms.org/issues/110 hehe

I say we set up the blog by creating a content type called:

- "Meeting" post for the weekly meeting videos. I am thinking it should have a title, body, and a video field (using [Video Embed Field](https://github.com/backdrop-contrib/video_embed_field). Love that module) suggested URL pattern: /meeting/POST-NAME
- "Text" posts for your regular blog type posts. suggested URL pattern: /blog/POST-NAME
- "Video" posts for embedding videos that aren't meeting related. Set up prob the same as the "Meeting" type. suggested URL pattern: /blog/POST-NAME
- "News" post for announcing news stuff. Problably similar set up as the "text" post. suggested URL pattern: /blog/POST-NAME
- "Tutorial" post for any how to guides. This way later in the future we can list them separately from the blog if need be. suggested URL pattern: /blog/POST-NAME
- "Gallery" post for where we will posts event photos. Never really set up so not sure how to do it or if possible with Bd. suggested URL pattern: /blog/POST-NAME

Feel free to improve on name, especially the "Gallery" as couldn't think of something better.

**Comment by sutibun** [comment]
Or, dunno if feasible or if wanna, but you can also give monkey an account to bdcms.org so can help set this up.

**Comment by jenlampton** [comment]
I think all that architecture is largely unnecessary, we already have a "post" let's just use that for the blog. All those items can use the same type. We can separate them by tags if we need, that way if we have a camp summary with a video and a tech tip we can tag it with all three ;)

Also! I have added a "Blog schedule" to the weekly meeting.  We can discuss ideas for upcoming posts and make sure there is always a lot of noise on the website. 

The more people we can get involved with this the better!
* Anyone who wants to contribute is welcome, let's get your topic on the list :)
* Would also love some people to draft and/or review the posts before they go up.

**Comment by docwilmot** [comment]
Now we're talking! Sign me up for either task.

**Comment by docwilmot** [comment]
Would still be wise I'd suspect to get some way to push posts simultaneously to FB, Twitter, (LinkedIn?), as per https://github.com/backdrop-ops/backdropcms.org/issues/133#issuecomment-164276676, but I guess lets walk first then run.

**Comment by jenlampton** [comment]
yes!  okay - moving this over to the other issue as it's a dupe of https://github.com/backdrop-ops/backdropcms.org/issues/110

**Comment by jenlampton** [comment]
Acutally - reopening this issue to focus on the sharing part, cause that's important too :)

**Comment by jenlampton** [comment]
Closing this issue since we are sharing manually, on a schedule, instead of automatically. We can reopen later if automatic seems like a better approach in the future.
