### ISSUE TITLE
Glossary of terms in handbook

### ISSUE THREAD

**Issue by jwalling** [backdrop-ops/backdropcms.org#132]
Create a glossary of terms in Backdrop.org handbook.
Link terms to issues where needed for comments or discussion.

**Comment by jenlampton** [comment]
I love this idea. I even have a "Drupal glossary" handout I made for my training classes we can use as a good starting point.

**Comment by docwilmot** [comment]
https://api.backdropcms.org/glossary

**Comment by jwalling** [comment]
@docwilmot do we need two glossaries? I forgot about the api. It's not self-evident for new users.

**Comment by jenlampton** [comment]
Oh, I had forgotten about that. How about a link to it from the user guide?

**Comment by docwilmot** [comment]
@jwalling sorry was just pointing out that this already exists. 

Ideally we need proper enduser documentation on B.org. There's an issue for that long time now (https://github.com/backdrop-ops/backdropcms.org/issues/55), and I started work, but I need the space to be created to put it!

**Comment by jwalling** [comment]
I like the idea of a functional glossary and an alphabetical glossary for end users. A bit awkward to maintain, but cool.

**Comment by jenlampton** [comment]
So, we should close this issue then?
