### ISSUE TITLE
Allow members to sign-up and log-in to backdropcms.org

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#134]
We've been working on a user-profile for Backdrop.  So far, we have lots of fields, and a layout. We're working on a few final touches, but getting this launched is blocked by: 
* [x] |  Large file uploads result in nginx fatal https://github.com/backdrop-ops/backdropcms.org/issues/135
* [ ] |  Emails sent from backdropcms.org are not properly formatted https://github.com/backdrop-ops/backdropcms.org/issues/136
* [ ] |  Clean up the "Edit my account" page experience - @wesruv

**Comment by klonos** [comment]
![so_excited](https://cloud.githubusercontent.com/assets/2423362/11735891/f8245438-a01a-11e5-878c-0806bef5de12.jpg)

**Comment by jenlampton** [comment]
this is done, closing ticket!

**Comment by wesruv** [comment]
The subtasks aren't done I thought?
https://github.com/backdrop-ops/backdropcms.org/issues/163
https://github.com/backdrop-ops/backdropcms.org/issues/136

**Comment by jenlampton** [comment]
yes, but they have their own issues... :)
