### ISSUE TITLE
Large file uploads result in nginx fatal

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#135]
when uploading large files, the webserver responds with:
```
Request Entity Too Large 
```

If we are going to be allowing people to add a banner/header image for their profile page, we should expect large file uploads, and handle exceedingly large uploads gracefully.

**Comment by Gormartsen** [comment]
nginx.conf, 'http ' section
```nginx

    client_header_timeout  15m;
    client_max_body_size 200M;
    client_body_buffer_size 128k;
    client_body_timeout    15m;
    send_timeout           15m;

```

**Comment by jenlampton** [comment]
I think @quicksketch fixed this?

**Comment by quicksketch** [comment]
Yes indeed. Thanks!
