### ISSUE TITLE
Emails sent from backdropcms.org are not properly formatted.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#136]
For some reason new-line characters in these emails are being printed.

```
jenlampton,\n\nA request to reset the password for your account has been made
at Backdrop CMS.\n\nYou may now reset your password by clicking this link or
copying and pasting it to your
browser:\n\nhttp://dev.backdropcms.org/user/reset/2/1449802605/4DQ638hqWuApHeJSR5Cc_Sz75WEYhLa2j7j6hccPOa0\n\nThis
link can only be used once and will lead you to a page where you can set your
password. It expires after one day and nothing will happen if it is not
used.\n\n--  Backdrop CMS team
```

**Comment by wesruv** [comment]
I was about to make a ticket for this :stuck_out_tongue: 

I'd add that it'd be nice if we could change the 'human friendly name' from Apache to Backdrop Team, or Drop... or something.

![image](https://cloud.githubusercontent.com/assets/5607236/11753814/6e28d902-a015-11e5-85d9-9a7e91b349ed.png)

**Comment by jenlampton** [comment]
:+1:

**Comment by BWPanda** [comment]
I'm pretty sure this is no longer an issue. Re-open if I'm mistaken.
