### ISSUE TITLE
Project search does not work with multiple terms.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#137]
This has been reported over in #95 about a month and a half ago. It needs to be fixed ASAP if we don't want to cause bad impressions to newcomers browsing for projects that have already been ported.

Steps to reproduce:

1. visit https://backdropcms.org/modules
2. [search for "simple access"](https://backdropcms.org/modules?keys=simple+access)

Expected result: [Simple Access](https://backdropcms.org/project/simple-access) should be returned as a result.
Actual result: empty results page!?!

3. [search for "simple"](https://backdropcms.org/modules?keys=simple)

Works as expected. Search results include all projects that have "simple" in their name.

**Comment by sutibun** [comment]
Really? That's really bad. What if someone won't try out Bd because their "search" tells them their favorite/required contrib module isn't on Bd (even though it might be)


Is it possible to [implement Google Custom Search](https://developers.google.com/custom-search/) as a short term fix in case fixing the Bd search will take too long?

**Comment by klonos** [comment]
> Really? That's really bad. What if someone won't try out Bd because their "search" tells them their favorite/required contrib module isn't on Bd (even though it might be)

...my point exactly wen I said this needs to be fixed "ASAP".

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop-ops/backdropcms.org/pull/150

**Comment by klonos** [comment]
Confirming this is now fixed in bd.org. Searching for "simple access" now returns [Simple Access](https://backdropcms.org/project/simple-access) as a result. Thanx.

**Comment by serundeputy** [comment]
:smile:
