### ISSUE TITLE
[SURVEY] What are the biggest complaints made against Bd?

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#139]
Monkey hasn't been around Bd for a long time nor socialize with any Drupal users ( T.T) so am wondering:
1. Based on your experience, what have been the **main** complaints Drupal users have made against Backdrop? (why they didn't like it, etc) Don't sugarcoat their complaints. Monkey wanna know.
2. If given the chance, how would you counter/answer their complaints? (if dunno, 'tis ok)
3. If you had a chance to sit down with Drupal user who never heard of Bd, what would you say to convince them to try Bd? <del>If you had a chance to sit down with a skeptical Drupal user who was on the fence, what would you say to convince them to try Bd?<del>

[edit] Updated last question.

**Comment by Gormartsen** [comment]
1. There is no enough contrib and it's hard to port a theme.
2. I explain them that it's really easy to port module and have a benefits from storing settings in JSON file. Also I explain how Layout module actually safe time on building theme. (No need to create separate tpl file for each page with different layout)
3. Nothing. This kind of people does not want to learn. They just look for reason to complain.

**Comment by sutibun** [comment]
ah, thanks.

> Nothing. This kind of people does not want to learn. They just look for reason to complain.

hehe. kk.

Let me change question 3 to the following: If you had a chance to sit down with a **Drupal user who never heard of Bd**, what would you say to convince them to try Bd?

**Comment by Gormartsen** [comment]
I will tell about next :
- no big learn curve to get in. It's almost Drupal 7 with extra API features. 
- update philosophy ( no huge API changes , great for contrib developers and long term projects)
- mobile friendly and much better UX by default 
- layout features and how it makes life easier
- shared hosting friendly
- Json stored settings, better DevOps

**Comment by docwilmot** [comment]
> it's hard to port a theme.

Did anyone say why they thought it was hard?

**Comment by Gormartsen** [comment]
@docwilmot It is hard to shift to Layout concept after Drupal 7.

**Comment by Gormartsen** [comment]
btw, On code level Layout.module is hard to understand. 

I was trying to add extra plugin to Layout module and it was actually hard to read a code. 
To much complexity. It's actually looks like Drupal 8 code.

**Comment by docwilmot** [comment]
> It is hard to shift to Layout concept after Drupal 7

Agreed. I raised this as an issue many months ago https://github.com/backdrop/backdrop-issues/issues/698 because I tried to do a few themes and it is confusing. I thought we should have some standards for layouts to make it easier. Maybe we need to revisit that.

> On code level Layout.module is hard to understand

Sorry to hear; I've done a bit of digging around when doing PRs for layout stuff and it is a bit hard to track. I find part of the problem is the code is separated in a few places (`.class.inc` files, `.module` files, `.theme.inc` files etc) and that makes it a bit of a hunt to follow procedurally. But I am an amateur at this and I assumed it was just me!

Maybe it would help if you could document your problems (raise an issue) so we can fix/document things.

**Comment by Gormartsen** [comment]
@docwilmot Correct. In my own vision OOP is great to incapsulate things but it need to be used wisely.
For example API features. I wrote GitHub integration class for my own project.

When you need to do a call to GitHub, you just init Object, feed it with credentials and call $GitHub->getUsers() for example.

**Comment by sutibun** [comment]
Some comment I picked up

> I’ve been trying to learn Drupal. It has a lot of potential, it’s free and it has a great developer community. **The only problem it’s hard for designers to convert psd layout into well functioning site. There are themes of course, but starting from scratch is a little hard.** There is definitely a steep learning curve. I heard good things about Expression Engine, I just wish it was free.

I dunno about others but when I create a design for a site. I like defining the container divs first (I use [grid system](http://www.thegridsystem.org/)) and go from there. With Wordpress, this is fairly easy. How would this be done with Layouts (something I don't 100% understand)

**Comment by biolithic** [comment]
I'm planning on sprinting on themes/layouts on Jan 1st.  Is anyone else
interested?  Thanks.

On Fri, Dec 25, 2015 at 6:31 PM, Steven Villaverde <notifications@github.com

**Comment by wesruv** [comment]
@biolithic I am!

I think #698 should play into that nicely!

**Comment by quicksketch** [comment]
With no recent updates, let's close out this issue.
