### ISSUE TITLE
Should we theme the logged in version of `/user`?

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#144]
Or do something like redirect logged in /user to something else? Maybe consider where an account/login link would go?

`/user` (if you're logged in as wesruv)
![image](https://cloud.githubusercontent.com/assets/5607236/12004078/19279e34-ab0a-11e5-949d-87ca885efdb8.png)

`/account/wesruv`:
![image](https://cloud.githubusercontent.com/assets/5607236/12004074/0334d9b6-ab0a-11e5-81f1-bca0424ff895.png)

**Comment by klonos** [comment]
Like :+1:

**Comment by wesruv** [comment]
Styling added to profile edit page: https://github.com/backdrop-ops/backdropcms.org/issues/163

**Comment by jenlampton** [comment]
Oh boy, that sure is weird. Long term I think /user should redirect to the account page if you are logged in, but this will do for now :)  Thanks for slipping that in @wesruv!  See https://github.com/backdrop/backdrop-issues/issues/260

**Comment by jenlampton** [comment]
Updated to 1.3.3 and re merged patch!  Thanks @wesruv for all the work here, the page looks *so* much better!

**Comment by opi** [comment]
@jenlampton I guess the patch (https://github.com/backdrop/backdrop/pull/752 ?) is no more applied. (and damn, I'll try to make this PR merged !)

**Comment by opi** [comment]
( and should be listed here https://github.com/backdrop-ops/backdropcms.org/blob/master/PATCHES.md )

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/752 was replaced by https://github.com/backdrop/backdrop/pull/2052, and merged. This issue could be kept closed ;)
