### ISSUE TITLE
[Views] Allow a view output to be used as a menu (or menu item).

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#146]
The idea is to have views create a list of items that are output/used as menu items. This feature should be available to the user a) as a view display option b) from the add menu item screen...

a) So in the create view page (`admin/structure/views/add`):

![backdrop-views-create_menu_display](https://cloud.githubusercontent.com/assets/2423362/12009092/4fbb6b1e-acbe-11e5-9a16-88eb053fcaa3.png)

...as well as the view edit page:

![backdrop-views-add_menu_display](https://cloud.githubusercontent.com/assets/2423362/12009093/59873c4a-acbe-11e5-8d59-313afd35e5cf.png)

b) I'm already using the [Menu Views](https://www.drupal.org/project/menu_views) module in most of the websites I've built. It does this the other way around: it allows to select an existing view as a menu item:

![d7-menu_views](https://cloud.githubusercontent.com/assets/2423362/12009173/bbf38714-acc1-11e5-9294-dc290111a01e.png)

**Comment by sutibun** [comment]
Out of curiosity, is this mostly for creating "mega-menus"?

**Comment by klonos** [comment]
Hmm, now that you mentioned it, I think yes. I haven't actually tried using [Menu Views](https://www.drupal.org/project/menu_views) in order to create mega-menus, but I don't see why not. I'm actually gonna give it a go soon after I type this reply.

My use cases were more for allowing the end user to easily add/remove and rearrange menu items without exposing the entire menu admin UI to them (end then having to deal with permission issues). I'll use a real-life example to explain:

In https://github.com/backdrop-ops/backdropcms.org/issues/129 I had the idea of converting the features to actually be nodes of a "feature" content type. So, we'd have a "features" page generated by Views that would list the feature nodes with their title and a short description. The titles would be links to the actual nodes that would explain each feature in more detail.

Some features would be "major" ones while others less important, so we'd need to have the major features listed first and the less important immediately after them. We'd use [Draggable Views](https://www.drupal.org/project/draggableviews) (needs to be ported first) in order to be able to rearrange them. That would be another "Manage Features" view (more like another display of the same view actually) with just the feature node titles rendered in a list along with the drag handles.

Finally we'd use [Menu Views](https://www.drupal.org/project/menu_views) to create a list of the feature node titles and that would respect the order set by the "Manage Features" view. This view would actually render the child items of a "Features" menu.

This setup would allow people to create various feature nodes that would automatically:

- be listed in the "Features" page to be viewed by site visitors.
- be listed in the  "Manage Features" page so that people with the right permission could rearrange them (without having to give them access to the menu system*).
- have an entry in the "Features" menu (still feature node creators would not need to be granted access to the menu settings*).

*I'm talking about the "Administer menus and menu items" which would give people potential "power" to mess up the site menu.

**Comment by sutibun** [comment]
^ . ^ ); That's more than what I had in mind: hardcoding it all using pages and menus…

Guess your years of Drupal exp shows…

Btw, couldn't you instead create a field called "priority" or maybe "weight" for the "Feature" content type. The views can then use this numbering to sort the features.

**Comment by klonos** [comment]
>Guess your years of Drupal exp shows…

I've been around for a while, yes, but still I don't claim to know everything there is to know nor that I know nearly as much as others that have been around for as long as I have. Plus there's usually more than one way to do things with Drupal...

> Btw, couldn't you instead create a field called "priority" or maybe "weight"...

Yep, that would be another way to go about it, but I thing it is better for the end user to have a visual representation of the ordering and be able to do things in a more WYSIWYG way. Using such a "priority" field would mean that the user would have to remember the weight the other "feature" nodes have.

Another way would to achieve similar outcome would be to use one of the contrib modules that delegate menu administration. One such module is [Menu Advanced Permissions](https://www.drupal.org/project/menu_advanced_permissions) that:

> ...allows you to specify different permissions for roles for all operations related to menu and menu items. **You can delegate permissions for one role to edit the menu items of specific custom menu**. Another role to have all permissions and so on ...

**Comment by sutibun** [comment]
>  it is better for the end user to have a visual representation of the ordering and be able to do things in a more WYSIWYG way

ah good point. i was thinking more on what be easier for me to implement

**Comment by quicksketch** [comment]
I'm not sure about this suggestion. Since menus are placed as blocks, what's the reason for making a view a menu. It seems like a round-about way to make a listing.

The menu system and Views have very little overlap. Although Menu Views looks like it has some uses, the implementation is essentially a hack. It takes over the rendering of menus and just injects the view as part of the theme layer.

**Comment by BWPanda** [comment]
I'm confused as to why this is in the B.org issue queue... Maybe the core issue queue didn't exist all the way back in 2015...? :slightly_smiling_face:

In any case, very old issue with no further updates/feedback so closing for now.
