### ISSUE TITLE
#attached not working for textarea in hook_field_widget_form_alter().

### ISSUE THREAD

**Issue by gifad** [backdrop-ops/backdropcms.org#148]
A library attached with `$element['#attached']['library'][]` does not show.
This is caused by the filter.module, `function filter_process_format($element)`, which erases any previous content (line 1135) : 
`  $element['#attached'] = filter_get_attached($formats);` 
This is fixed by replacing this line by : 
`  if (isset($element['#attached']))`
`    $element['#attached'] = array_merge_recursive($element['#attached'], filter_get_attached($formats));`
`  else`
`    $element['#attached'] = filter_get_attached($formats);`

Thanks for considering...

**Comment by quicksketch** [comment]
Thanks @gifad! Great catch. Would you be interested in filing a PR? It sounds like it would be a simple fix.

**Comment by quicksketch** [comment]
Oh, this should be in the Backdrop issue queue, this is backdropcms.org. I filed a new issue at https://github.com/backdrop/backdrop-issues/issues/1464. Thanks!
