### ISSUE TITLE
KVM Upgrade Pending

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#151]
I would like to schedule a time this week to perform the pending KVM upgrade for the servers.

**Comment by larsdesigns** [comment]
If I receive the go ahead to do this, How about Monday at 11:30pm MST?

**Comment by larsdesigns** [comment]
@quicksketch @jenlampton Shall I proceed?

**Comment by quicksketch** [comment]
Sure @larsdesigns, have at it.

**Comment by larsdesigns** [comment]
@quicksketch, okay, will do.

**Comment by larsdesigns** [comment]
Beginning maintenance, there will be some downtime for each server for the KVM update and reboot.

**Comment by quicksketch** [comment]
Seems like the site is back up. All done?

**Comment by larsdesigns** [comment]
Completed the KVM upgrades on all four hosts. Looks like all of the sites are back online.

**Comment by larsdesigns** [comment]
Completed the Yum updates and reboots. No further tasks. Closing...
