### ISSUE TITLE
Procedure for moving a site

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/backdropcms.org#157]
I tried unsuccessfully to find in our documentation any instructions for moving a Backdrop site from one server space to another. I think perhaps we should add some, or index any that we already have. 

The clearest explanation I have found of the configuration management system is the article 'Build it with Backdrop' by @quicksketch  and @jenlampton  published in Drupal Watchdog and available at https://drupalwatchdog.com/volume-5/issue-1/build-it-backdrop

From my own experience I have tried to write a simple recipe setting out the steps to take. Hopefully I have got this right - text file attached as a possible contribution to backdropcms.org 
[Moving a Backdrop site.txt](https://github.com/backdrop-ops/backdropcms.org/files/78108/Moving.a.Backdrop.site.txt)

**Comment by klonos** [comment]
Thanx for that @Graham-72.

Hopefully we'll have a documentation team and our space in bdcms.org soon so we can place these HowTo's.

**Comment by serundeputy** [comment]
another way without reinstalling.
http://serundrop.staffordtavern.com/backdrop-cmi

not better than your way just another way.

**Comment by Graham-72** [comment]
Yesterday I needed to move a backdrop site and could not find any instructions in our user guide. Fortunately I found my personal note 'Moving a backdrop site' referenced above.

And I had completely forgotten that I had created this issue in Jan 2016 and I was about to create it again! Is this something I can add to our user guide?

**Comment by serundeputy** [comment]
@Graham-72 yes go ahead and create the page! It will be a very useful addition.

**Comment by Graham-72** [comment]
I have created it at https://backdropcms.org/user-guide/moving-backdrop-site and I see that it is already published and included in the user guide index.

**Comment by serundeputy** [comment]
thanks @Graham-72 looks like all actionable items are taken care of here!
closing out; reopen if necessary.

**Comment by klonos** [comment]
@Graham-72 I have moved the doc under the "Backdrop Developer notes" (from the User Guide to the Handbook), as it seemed to be more dev-ops-orientated, while the rest of the docs in the User guide seemed more site-builder-orientated (frontend and backend admin tasks). I hope that that's OK.

**Comment by klonos** [comment]
...I have also renamed it to "Moving a Backdrop site to a new server" and am about to add @serundeputy's https://serundeputy.io/backdrop-cmi as a new doc "Moving Backdrop from your local to a live server".

**Comment by klonos** [comment]
...here it is: https://backdropcms.org/user-guide/moving-backdrop-your-local-live-server-using-cmi

**Comment by Graham-72** [comment]
@klonos I am happy with the move.
