### ISSUE TITLE
Profile page. logo overlap custom header image

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-ops/backdropcms.org#160]
See screenshot:
![bugprofile](https://cloud.githubusercontent.com/assets/5018896/12183342/4c7cb22c-b55c-11e5-9f3f-9372d049986e.png)

**Comment by quicksketch** [comment]
Yeah, this was intentional in the implementation when I spoke with @jenlampton about it. I agree this needs a little more work. Even just hiding the background may be better unless we can find an alternative location for that header.

**Comment by klonos** [comment]
Perhaps leave the backdrop header as is and add the personalized header in the white space between the black header ribbon and the tabs (view/edit) are?

**Comment by jenlampton** [comment]
that could work!

**Comment by jenlampton** [comment]
committed a fix for this in 769496052d0990f57df04fa7e0907ca0f02f948b.

**Comment by jenlampton** [comment]
deployed! closing issue.
