### ISSUE TITLE
Update user membership date (for people involved with Backdrop prior to creating an account).

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#161]
In my newly-created bdcms.org account I show up as a member since a few minutes ago (at the time of writing). Call me vain, but I would like to be shown as a member since I first started being involved with the project. My only way to track an approximate date is [this issue I've opened](https://github.com/backdrop/backdrop-issues/issues/159) that dates Jan 10, 2014 (although I think that I must have actually been following since sometime in December 2013).

Anyways, my point is that a good way to tell would be for everyone that wants their membership date corrected to look at their oldest comment in the queue I guess.

Also, I think that @quicksketch's and @jenlampton's membership dates should be changed to the date when the fork was announced (September 16, 2013 IIRC). Currently it is set back to "1 year 9 months" which I guess is when the website was launched.

**Comment by jenlampton** [comment]
I think this is a reasonable request. Anyone who wants their user account created date updated, please post here with a unix timestamp :)

**Comment by docwilmot** [comment]
1402394940

First post https://github.com/backdrop-ops/backdropcms.org/issues/18

**Comment by jenlampton** [comment]
@docwilmot https://backdropcms.org/account/docwilmot

**Comment by klonos** [comment]
>First post https://github.com/backdrop-ops/backdropcms.org/issues/18

...if we want to be fancy, we can at some point add a "How it all started" field in user profiles and allow people to enter their first post when they've entered Backdrop-land along with an excerpt/quote. I like how @docwilmot started his:

> I was interested in the concept of Backdrop from the start, but I am not sure how to contribute. GitHub seems (to me) to be a place for code, not community, ...

Perhaps we made you change your mind about GitHub. Huh? :smile:

**Comment by klonos** [comment]
Oh, that was rude of me. Thanx @jenlampton ! :heart:

**Comment by mikemccaffrey** [comment]
Well, according to the tweet, it seems that I named Backdrop at 1372293480.

Can please you update my account time, @jenlampton? 
https://backdropcms.org/account/mikemccaffrey

Thanks!

**Comment by jenlampton** [comment]
Seems only fair. @mikemccaffrey https://backdropcms.org/account/mikemccaffrey

**Comment by BWPanda** [comment]
Could you please update mine too? Not sure if it best to use first comment date or first commit date, so here's both:

[Comment](https://github.com/backdrop/backdrop-issues/issues/4#issuecomment-24286684) - 1378981
[Commit](https://github.com/backdrop/backdrop/commit/b8c47793f98301b05f457afe32534d0e03c6052b) - 1412726400

**Comment by jenlampton** [comment]
Comment date will be fine :)
Happily updated :) https://backdropcms.org/account/bwpanda

**Comment by klonos** [comment]
I think that we can close this one now 🙂
