### ISSUE TITLE
Two Redirect Loops

### ISSUE THREAD

**Issue by dougvann** [backdrop-ops/backdropcms.org#162]
FYI:
While on the THEME page
https://backdropcms.org/project/afterlight_tribute
and
https://backdropcms.org/project/cleanish
result in Redirect Loops.

**Comment by biolithic** [comment]
Hi Doug,
Thank you for this report.  I am working on fixing up my themes and
correcting any issues with them right now in preparation for the upcoming
core release this week.
If I was anyone, I would hold off on using these themes until Friday when
things are released.
Thanks!

**Comment by serundeputy** [comment]
@jenlampton I've confirmed the redirect loops on OP;
On my local I just deleted the redirects from the nodes on the vtabs.
That solved the problem.

Obv. I can not do that on production backdropcms.org

**Comment by quicksketch** [comment]
Thanks, weird that was happening. I've removed the redirect from "afterlight_tribute", I think that should fix it.

**Comment by klonos** [comment]
https://backdropcms.org/project/afterlight_tribute now throws a "Page not found". Searching for the theme from the themes page revels its URL to actually be https://backdropcms.org/node/221

https://backdropcms.org/project/cleanish works just fine for me.

**Comment by jenlampton** [comment]
https://backdropcms.org/project/afterlight_tribute is back
