### ISSUE TITLE
Clean up User Edit Page

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#163]
Parent ticket is: https://github.com/backdrop-ops/backdropcms.org/issues/134

**Comment by wesruv** [comment]
So I took a stab at this, there are some serious issues with the draggable table stuff at mobile, and it refuses to bend to my will. I'm suuuper stumped on those things, but the desktop implementation is looking slick.

This should be tested, my local is weird and has some errors popping up that I don't think are happening on the real site. Forms aren't working well for some strange reason...

![profile edit page](https://cloud.githubusercontent.com/assets/5607236/12342397/ffb7c2c8-baf7-11e5-9dae-ba74753e5ffd.png)

Expanded Change PW/Email fieldset
![wesruv - backdrop cms 2](https://cloud.githubusercontent.com/assets/5607236/12342398/022a80cc-baf8-11e5-8b9e-3faa82a746f5.png)

**Comment by wesruv** [comment]
Code is here: https://github.com/backdrop-ops/backdropcms.org/pull/164

**Comment by jenlampton** [comment]
yes yes yes yes yes.

**Comment by jenlampton** [comment]
deployed! :)
