### ISSUE TITLE
Restore Backdrop CMS on wikipedia

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#166]
Our wikipedia page is currently unpublished, we need to make the following changes:

> Unfortunately, the article has a very long way to go to get out onto the main page. At a minimum, the following need to occur before we can consider the possibility.

* All references going to backdropcms.org need to be deleted. That's no a third party site, and as such its disqualified from being a reliable source for the article beyond a mention for the group that owns the software.
* Remove links to youtube. In a similar vein, youtube is blacklisted site, once you try and move the article out to the mainspace it will trip the youtube filter and the site will cause the article to be blocked.
* The bullet point list needs to be converted into paragraph or removed.
* Your three equal sign headers need to be converted to two equal sign headers so as to be consistent with all other wikipedia articles.
* The blog link needs to be removed.

The original complaint: 

> it was deleted for having no credible assertion of notability, and that's not really something citations will help with. Its also a G11 eligible article since it reads as a cooperation promo piece, although that can be worked on with editing. Its your call for how to fix that. TomStar81 (Talk) 21:49, 25 September 2018 (UTC)

---

We need to get Backdrop onto the wikipedia. 
In particular:
- [x] Add a new page for Backdrop CMS
- [x] Add Backdrop CMS to https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] Add Backdrop CMS to https://en.wikipedia.org/wiki/List_of_content_management_frameworks

For reference, here is the page on Drupal https://en.wikipedia.org/wiki/Drupal

**Comment by jenlampton** [comment]
@docwilmot did you have some other places in mind where Backdrop should be added?  I don't seem to remember what those were...

**Comment by herbdool** [comment]
Here's a start: https://en.wikipedia.org/wiki/Backdrop_CMS
and https://en.wikipedia.org/wiki/List_of_content_management_systems#PHP

I didn't add it to the list of frameworks because maybe that's controversial whether it actually fits (or even if Drupal is a framework).

**Comment by klonos** [comment]
:+1: @herbdool

**Comment by stpaultim** [comment]
The BackdropCMS page on Wikipedia was deleted. @herbdool reported the following reasons as stated by a Wikipedia editor:

> "it was deleted for having no credible assertion of notability, and that's not really something citations will help with. Its also a G11 eligible article since it reads as a cooperation promo piece, although that can be worked on with editing. Its your call for how to fix that. TomStar81 (Talk) 21:49, 25 September 2018 (UTC) "

It has been moved here for now: https://en.wikipedia.org/wiki/User:Nubeli/Backdrop_CMS

In my view, the "[G11. Unambiguous advertising or promotion](https://en.wikipedia.org/wiki/Wikipedia:Criteria_for_speedy_deletion#G11._Unambiguous_advertising_or_promotion)" is overstated. I think that it could be fixed by:

1. Changing this header from "Built-in features that are improvements over Drupal 7" to something more neutral like "Features" (removing the comparison to Drupal 7).
2. Rewriting or removing the 3rd paragraph. I think that some folks might object because it is working too hard to compare BackdropCMS to Drupal 7 and/or 8. 
3. Adding some evidence of "notability" - see: https://en.wikipedia.org/wiki/Wikipedia:Notability

**Comment by olafgrabienski** [comment]
> Rewriting or removing the 3rd paragraph. I think that some folks might object because it is working too hard to compare BackdropCMS to Drupal 7 and/or 8.

In my opinion, even more Drupal references should be removed. Looking at the first four paragraphs, there are just too many "Drupal"s, cf. screenshot of today:

![screen-wikipedia-backdrop-2018-09-28](https://user-images.githubusercontent.com/14188307/46195532-e2f82980-c304-11e8-8d30-f5fb99b23c4d.png)

I see that Drupal is an important reference. An idea is to start writing a text without mentioning Drupal and to add necessary references then.

**Comment by herbdool** [comment]
Please feel free to edit the page. It is a wiki after all. 😁

**Comment by olafgrabienski** [comment]
Sure! Only, I won't have time for the next 12 days :-/

**Comment by klonos** [comment]
I will be able to get to this over this weekend ...if not sooner than that.

Rehashing things I mentioned over Gitter:

>...we deserve as much "notability" as https://en.wikipedia.org/wiki/MySQL vs https://en.wikipedia.org/wiki/MariaDB
> ...and for comparison purposes, the term "mysql" is referenced 45 times in the MariaDB Wikipedia page ...18 of them being within the main body of the page:

<img width="891" alt="screen shot 2018-10-12 at 8 45 10 am" src="https://user-images.githubusercontent.com/2423362/46835909-38e7c980-cdfb-11e8-8048-5e7ea35d28de.png">

>...and there are mentions like "MariaDB 5.5 offers all of the MySQL 5.5 features"
>...I think that perhaps it also might be worth adding all the entries that have been added in https://backdropcms.org/news/mentions over time into the Wikipedia page.
>...and links to our release notes.

**Comment by klonos** [comment]
...I have updated our wikipedia article, which now includes only 8 references of the word "Drupal". Please review and let me know what you think: https://en.wikipedia.org/wiki/User:Nubeli/Backdrop_CMS

**Comment by olafgrabienski** [comment]
@klonos Great job! Apart of the reduction of Drupal references I like the addition of section headings.

**Comment by olafgrabienski** [comment]
Being curious, I've also had a look at the [Joomla Wikipedia page](https://en.wikipedia.org/wiki/Joomla), which due to a template message "has multiple issues", amongst them "content that is written like an advertisement". There's also a link to https://en.wikipedia.org/wiki/Help:Maintenance_template_removal with information and links to issues like notability.

**Comment by klonos** [comment]
Thanks for pointing to the Joomla page @olafgrabienski 👍 ...I might borrow the template they are using for the release history.

**Comment by stpaultim** [comment]
We have also been removed from: https://en.wikipedia.org/wiki/List_of_content_management_systems
Because we don't have a page. Looks like we were removed on Sept 28th. 

@jenlampton suggested I put us back on the list to see if that helps get our page re-approved, but I'm afraid it might have the opposite effect. 

![list_of_content_management_systems__revision_history_-_wikipedia](https://user-images.githubusercontent.com/3144571/49910357-06cd0500-fe48-11e8-984e-5075ba4e497f.png)

**Comment by jenlampton** [comment]
This says "any other reference". Maybe you could link to the Drupal and CiviCRM pages where we are referenced?

**Comment by stpaultim** [comment]
I'll give it a try.

**Comment by stpaultim** [comment]
I got this reply:

"Unfortunately, the article has a very long way to go to get out onto the main page. At a minimum, the following need to occur before we can consider the possibility.

- All references going to backdropcms.org need to be deleted. That's no a third party site, and as such its disqualified from being a reliable source for the article beyond a mention for the group that owns the software.
- In a similar vein, youtube is blacklisted site, once you try and move the article out to the mainspace it will trip the youtube filter and the site will cause the article to be blocked.
- The bullet point list needs to be converted into paragraph or removed.
- Your three equal sign headers need to be converted to two equal sign headers so as to be consistent with all other wikipedia articles.
- The blog link needs to be removed.

At this point if you put this out I essentially guarantee that it'll be deleted again, and this time possibly WP:SALTed. Sorry guys, more work is needed. TomStar81 (Talk) 18:35, 13 December 2018 (UTC)"

**Comment by docwilmot** [comment]
Did we really try and submit this as is? It's definitely not ready to publish yet. Pretty sure the latest edit was mine and I left a bunch of topic headers minus any content so we can fill this out a bit before we submit. 
I like this response you've got though, at least we know exactly what we need to do.

**Comment by stpaultim** [comment]
No, we did not officially resubmit it. I guess I did ask whether or not it could be republished. Several of us read through it last night and it was not obvious at the time that it was incomplete, but I see now what mean. See backscroll of discussion last night on Gitter.

**Comment by jenlampton** [comment]
> All references going to backdropcms.org need to be deleted. That's no a third party site, and as such its disqualified from being a reliable source for the article beyond a mention for the group that owns the software.

It might be worth mentioning that this is free and open source software, and that there is no "group" that "owns" it. Our re-write of the page tried to make that clear by mentioning the GPL license right at the top. If it's still not clear we should ask what we should do to clear this up.

It might also be worth pointing out that there are references to drupal.org on Drupal's page, and joomla.org on Joomla!'s page, and wordpress.org on WordPress's page (etc) and that this version of our page was updated by copying what was accepted on the WikiPedia pages for comparable free open source projects. 

I do still think we should do all the things he says, tho :)

**Comment by oadaeh** [comment]
GPL is not necessarily the buzz word/phrase that "open source" is. Everyone talks about how their stuff is open this and open that, so people in general are more used to that than to GPL.

**Comment by jenlampton** [comment]
@oadaeh yeah, that's where we started.

> Backdrop CMS is an Open Source, community-developed, content management system [3], written in PHP, and intended to remain free under the GNU General Public License.[2].

**Comment by jenlampton** [comment]
Looks like this hasn't gotten any attention since December. :( I thought someone had worked on a new draft more recently than that?

**Comment by herbdool** [comment]
Last week I edited it heavily and moved it back https://en.m.wikipedia.org/wiki/Backdrop_CMS.

The article was nominated for deletion again though this time we were actually given time to discuss (which we should have gotten the first time) and the consensus is leaning keep.

The main improvements I made we to remove all the self-promotion, remove external links, added more references, and added more info about how Backdrop is related to other notable sources.

**Comment by jenlampton** [comment]
For those who are interested, here is the discussion: 
https://en.m.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Backdrop_CMS

**Comment by herbdool** [comment]
Yes, it's hard and intimidating. I thought I knew wikipedia well enough but the format is weird and the editors use a lot of acronyms that they assume you already understand. And the editor who originally deleted the article seems to have a real trigger finger. Editors have the option of just flagging the article instead of removing without giving people a chance to improve it. And when I put a lot of work into improving it, the editor still claimed there were no improvements and that it was just advertising. Other editors seem to disagree.

**Comment by klonos** [comment]
The article is live again! 🎉 

Lets close this issue. Thanks @herbdool and everyone who helped restore it!
