### ISSUE TITLE
Code contained in README.md files is rendered funny when pulled and displayed in bd.org...

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#167]
```<?``` converted to ```&lt;?``` and ```?>``` to ```?&gt;```...

[GitHub](https://github.com/backdrop-contrib/juiced_up_layouts/blob/master/README.md#license):

```
<?php if (!empty($content['custom_region'])): ?>
  <?php print $content['custom_region']; ?>
<?php endif; ?>
```

[backdropcms.org](https://backdropcms.org/project/juiced_up_layouts):

```
&lt;?php if (!empty($content['custom_region'])): ?&gt;
  &lt;?php print $content['custom_region']; ?&gt;
&lt;?php endif; ?&gt;
```

**Comment by jenlampton** [comment]
I noticed this too. Less-than and greater-than sumbols are being unnecessarily escaped. It'a particularly noticeable in our RSS feed: https://backdropcms.org/project/rss.xml

**Comment by quicksketch** [comment]
Looks like the provided sample URLs no longer contain angle brackets in the README.md (or project page). Do we have any current examples of this problem?

**Comment by klonos** [comment]
I filed this quite a while ago so seems that things were sorted out. Let's close and re-open if anything similar manifests itself.
