### ISSUE TITLE
Add release dates to project listing pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#168]
A request that came in from email via @xmacinfo:

```
Hi!

Can we add dates to the list of modules and themes (or any list). Just
displaying version number does not mention if that version is old or new.

I would also love to sort by creation date, and modification date for any
list, including themes and modules.
```

**Comment by jenlampton** [comment]
Thanks for the suggestion! Yes, we can certainly add dates. In fact, we are intending to add dates for each release onto the modules page once we get the "releases drawer" working. see https://github.com/backdrop-ops/backdropcms.org/issues/95 for the mockups.

We are showing *only* the newest version of any module, theme, or layout on the listing pages. You'd need to click through to the project page to find older releases.

When you say `creation date` and `modification date`, I'm guessing that's actually the creation date of the module, and then the creation date of the latest release of that module? (None of these items are ever modified, but as new releases are issued on GitHub new release nodes appear on backdropcms.org automatically).

Bigger picture: 
* what is it you are hoping to learn from having a release date on the modules-listing page?  Does it help you choose between two similar projects if you can see that one had a more recent release?
* What about the created-date, does it help you choose between two projects by comparing when the very first version was created?

I'm only asking because it's good for the design/ux to know the why for the feature as well as the what :)

**Comment by xmacinfo** [comment]
The new “releases drawer” should also document the current release creation date. It is nice to see the progress taking up shape in https://github.com/backdrop-ops/backdropcms.org/issues/95.

Agreed, we must show _only_ the latest version of a package.

Dates, along with version, are a way to evaluate the health of a production, along with other meta information like categories, number of downloads, likes, number of stars, number of comments, etc.

I have the impression that the modules pages are currently like a black box (e.g. too few information). This is why each module should display, along with the version number, the `creation date` of that version.

A module (or theme) page for me is also different from the tarball package. When a module is modified, it receive a new version (release version number). On Drupal we also get the modified date for a “dev” version.

So, for module (or themes…) pages:  

- The _creation date_ represents the date the first time the module page was created (hidden date)
- The _modification date_ represents the date the module received a new version (displayed date)

On listing pages, we should display: 

- the _modification date_ (e.g. date of the latest release, along with version number),
- filter by modification date (default filter) to show the latest release first,
- filter by creation date, which would sort the first time the module page was created.

> What about the created-date, does it help you choose between two projects by comparing when the very first version was created?

We are using this filter to sort which module are brand _new_, removing the noise created by all module that released new version in the same time frame.

I am not trying to duplicate Drupal.org module facets and filters. I just want more data to see what's new, what's updated regularly, etc.

**Comment by jenlampton** [comment]
I've taken the first step of adding the **lastest release** date onto the listing page, since that was easy:
https://backdropcms.org/modules

**Comment by klonos** [comment]
Thanx @jenlampton. Can we please have the dates in ```M. j, Y```? ...it's annoying to have to remember that with the current format the month comes before the date. If we use actual names for months (the short ones), it'd be best. Otherwise we'd get into endless bike-shading about numeric month and date order.

**Comment by xmacinfo** [comment]
Thanx @jenlampton this is a very good start.

As for the date formant, I would rather prefer the international ISO-based date format: YYYY-mm-dd
https://en.wikipedia.org/wiki/ISO_8601

**Comment by jenlampton** [comment]
ISO is a good robot standard, but this page is meant for humans :/  I think I prefer @klonos's suggestion of using the word for Month instead of numbers. However, I chose the short date format there instead of medium to keep the information concise (and looking good on smart phones).  For now, I've set the format to `M-j-Y` which I hope will statisfy all demands 
* Don't want to remember order of numbers
* Human readable
* short

**Comment by docwilmot** [comment]
> ISO is a good robot standard, but this page is meant for humans 

That's not really the point though. Belize, Federated States of Micronesia and the United States are the only countries using the MDY format. ISO is meant to be international, which I think is more appropriate. Failing that DMY is a heck of a lot more popular.

**Comment by docwilmot** [comment]
> Otherwise we'd get into endless bike-shading about numeric month and date order.

Let the bikeshedding begin.

**Comment by jenlampton** [comment]
> DMY is a heck of a lot more popular.

Let's gather some metrics on who's actually using our site and measure the actual people - this is not a popularity contest ;)

Unless you have an objection to the current format (which solves the three requirements stated above) I'm tempted to leave it as-is. If you guys want a bike-shed let's open a follow up issue that's not specific to this page, but addresses all dates on backdropcms.org.

**Comment by klonos** [comment]
> Let the bikeshedding begin.

:laughing: I knew it!

**Comment by klonos** [comment]
> Unless you have an objection to the current format (which solves the three requirements stated above) I'm tempted to leave it as-is. If you guys want a bike-shed let's open a different issue that's not specific to this page, but addresses all dates on backdropcms.org.

I concur. Especially since it solved my two main concerns: number order and human readable.

**Comment by jenlampton** [comment]
The remaining task here was to add the module release date too, I was thinking about putting that in the same line as the module name FOR NOW. We can bikeshed design ideas on that later ;)

**Comment by klonos** [comment]
:+1: Get the date there and we can move around and style as we go. I like the "getting things done" approach that we are taking with some issues lately. Like setting up the documentation content types for contributors on bd.org.

@jenlampton :+1:

**Comment by jenlampton** [comment]
Yeah, we are definitely going to need another design pass, but here's a start:
https://backdropcms.org/modules
