### ISSUE TITLE
Add exposed filters to project listings

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#169]
Suggested filters for the modules page are module 'packages' from info file: like Administration, Education, Commerce, etc

parent issue: https://github.com/backdrop-ops/backdropcms.org/issues/95

**Comment by docwilmot** [comment]
can we do https://github.com/backdrop-ops/backdropcms.org/issues/100 so we can actually get good info about modules?

**Comment by laryn** [comment]
If "Packages" end up [getting removed](https://github.com/backdrop/backdrop-issues/issues/3148), this feature would still be important but using "Tags" as the exposed filter.

**Comment by BWPanda** [comment]
Closing in favour of https://github.com/backdrop-ops/backdropcms.org/issues/442
