### ISSUE TITLE
Could not delete temporary file

### ISSUE THREAD

**Issue by amilenkov** [backdrop-ops/backdropcms.org#175]
I moved a Backdrop site from one hosting account to another. Original installation had no problems.

After Cron the following message start to appears:
Could not delete temporary file "temporary://bg.po"

Temporary directory is in the root directory, outside public_html
../tmp

In this directory there was not file "temporary://bg.po" - this directory was empty (only .htaccess file)

I recreate .htaccess file there by saving options in admin/config/media/file-system

Try to manually create empty file with name "temporary://bg.po" in tmp directory with permissions #644

The same error message again and again.

Finally I delete content of the table «file_managed» in DB - there was a line that contained "temporary://bg.po"

Cron error message disappeared.

**Comment by BWPanda** [comment]
Closing this old issue. Future issues should be made to backdrop/backdrop-issues issue queue.

**Comment by stpaultim** [comment]
FYI: https://github.com/backdrop/backdrop-issues/issues/2052
