### ISSUE TITLE
Weird bug on prod - Sidebar disappears

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#179]
This keeps happening very intermittently..
![image](https://cloud.githubusercontent.com/assets/5607236/13011301/242deec4-d174-11e5-94df-4191490283c7.png)

The left menu is consistently gone when this happens, and the main page content shows up.

**Comment by wesruv** [comment]
And now it's fine...
![image](https://cloud.githubusercontent.com/assets/5607236/13011543/435d67f6-d175-11e5-91d8-1460b1c7c893.png)

**Comment by wesruv** [comment]
A friend of mine from a different city was able to reproduce the same result when it was broken and when it was fixed. Very odd.

**Comment by jenlampton** [comment]
I just pushed the latest version of Backdrop core, which should have fixed this issue.  I'm going to close this issue assuming that's the case, but please re-open if you see that behavior again. :)
