### ISSUE TITLE
Bad URLs in https://backdropcms.org/project/rss.xml

### ISSUE THREAD

**Issue by thejimbirch** [backdrop-ops/backdropcms.org#180]
Links are printing as:

https://backdropcms.org/%3Ca%20href%3D%22/project/html5_upload%22%3EMore%20Info%3C/a%3E

**Comment by thejimbirch** [comment]
To close this issue, make the following change in the feed display of the modules view:
https://backdropcms.org/admin/structure/views/view/modules/configure/feed_1

1. Under Fields add: `Content: Path`
2. Under Format, click on **Settings** of "Show: Fields".  In the **Link field *** select `Content: Path`.  Click APPLY button.
3. Under Fields remove: `Content: Link`
4. Click SAVE button to save the view.

**Comment by quicksketch** [comment]
Thanks @thejimbirch! I followed your directions and now the problem is fixed. :smile:

**Comment by thejimbirch** [comment]
W00T!  One of these days soon I will learn the configuration mgmt and be a
little more useful.
