### ISSUE TITLE
Browser server down

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#184]
http://projects.backdropcms.org/query/module/1.x/?requested=30 returns no projects.

**Comment by quicksketch** [comment]
Thanks, it looks like the borg_pbs.module was updated for the API changes at https://github.com/backdrop-contrib/project_browser/issues/21, but the project_browser.module itself has not yet been updated. I'll merge the PR at https://github.com/backdrop-contrib/project_browser/issues/21 and then update the server.

**Comment by quicksketch** [comment]
Okay, finally:

- Project Browser Server updated to the new [1.0.0 release](https://github.com/backdrop-contrib/project_browser_server/releases/tag/1.x-1.0.0)
- Project Browser updated in https://github.com/backdrop-contrib/project_browser/pull/23.
- BackdropCMS.org (borg) PBS module was already updated to the new API.

So now the URL at http://projects.backdropcms.org/query/module/1.x/?requested=30 is working... but "requested" is now "items_per_page", so it is now http://projects.backdropcms.org/query/module/1.x/?items_per_page=30 to get the expected result.
