### ISSUE TITLE
User profile pages: Footer bleeds into sidebar section.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#185]
More obvious just before the breakpoint where it switches to mobile. Could be happening to other pages too, but I've noticed it in the user profile pages:

![backdropcms org-user_profile-foot_bleeding_into_sidebard](https://cloud.githubusercontent.com/assets/2423362/13204069/50b80d28-d91a-11e5-8a38-059db44bf981.png)

**Comment by jenlampton** [comment]
committed a fix for this in 769496052d0990f57df04fa7e0907ca0f02f948b

**Comment by klonos** [comment]
Do you mean this is live? Asking cause I still see the same effect.

**Comment by jenlampton** [comment]
no, I haven't pushed yet.  Hold your horses :)

**Comment by jenlampton** [comment]
okay, just pushed. How's this?
https://backdropcms.org/account/klonos

**Comment by jenlampton** [comment]
Well, I'm going to close this issue now.  Please re-open if there are still issues with layout formatting. :)

**Comment by klonos** [comment]
Yep, fixed now :+1: ...but #210 creeped in.
