### ISSUE TITLE
Allow people to add their own events to backdropcms.org

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#188]
We would like logged-in users to be able to post their own events on the Backdrop site.
- [x] Create a content type (allow logged in to create/edit/delete own)
- [x] Build a list view (3 items) for the sidebar of the News page
- [x] Build a list view (all items) for an 'Events' page

**Comment by jenlampton** [comment]
Events page: 
https://backdropcms.org/events

Events sidebar list:
https://backdropcms.org/news

**Comment by klonos** [comment]
:+1: Thanx.

**Comment by Gormartsen** [comment]
I made time clickable on http://www.drupal.ru/events
When you click time, it creates event in your calendar.

Check this code:
https://github.com/DrupalRu/drupal.ru/blob/master/modules/simple_events/simple_events.module#L428
```php
function simple_events_download_ics($node) {
  drupal_add_http_header('Content-Type', 'application/calendar; charset=utf-8');

  // Set the filename.
  $filename = preg_replace('/[\x00-\x1F]/u', '_', check_plain($node->title));
  drupal_add_http_header('Content-Disposition', 'attachment; filename="' . $filename . '.ics"');

  $start_date = date('Ymd', $node->event->time_from) . 'T' . date('His', $node->event->time_from) . '';

  if (empty($node->event->time_to)) {
    $end_date = $start_date;
  }
  else {
    $end_date = date('Ymd', $node->event->time_to) . 'T' . date('His', $node->event->time_to) . '';
  }
  $description = str_replace("\n", " ", strip_tags($node->body[LANGUAGE_NONE][0]['safe_value']));

  $url = '';
  if (!empty($node->event->url)) {
    $url = $node->event->url;
  }
  else {
    $url = url('node/' . $node->nid, array('absolute' => TRUE));
  }

  echo 'BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
UID:' . $node->type . '-' . $node->nid . '@' . $_SERVER['HTTP_HOST'] . '
DTSTAMP:' . $start_date . '
DTSTART:' . $start_date . '
DTEND:' . $end_date . '
SUMMARY:' . check_plain($node->title) . '
DESCRIPTION: ' . $description . ' - ' . $url . '
LOCATION:' . $node->event->address . '
URL:' . $url . '
END:VEVENT
END:VCALENDAR';

  drupal_exit();
}
```

**Comment by jenlampton** [comment]
We'll likely do a views ical feed too, once we have some more info (like location) to each event. (but we need to add the addressfield module to backdropcms.org first).

For now I just provided a link to the existing google calendar feed for Backdrop Events. Perhaps not as useful as a link for each event...  we'll get there! :)

**Comment by Gormartsen** [comment]
@jenlampton :+1: I did not know about this plan.

**Comment by jenlampton** [comment]
So. Many. Plans.

**Comment by klonos** [comment]
> So. Many. Plans.

We're getting there. We have more reasons to celebrate each time a thing gets fixed or new feature implemented. Besides, it's only just a handful of us.

**Comment by wesruv** [comment]
I hear there are designs? Where are they?

**Comment by jenlampton** [comment]
Not for events. We's just riffing off the existing styleguide.

- - -
Jennifer Lea Lampton | twitter.com/jenlampton | 510-747-8230
Backdrop CMS & Drupal @ Jeneration Web Development
Check out my new website! | www.jeneration.com

**Comment by jenlampton** [comment]
Since event listings are up, I'm going to close this issue. Let's open a follow-up for any changes that might be needed.
