### ISSUE TITLE
Roadmap page: Link for 1.x not created and for 2.0.0 not working.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#191]
https://backdropcms.org/roadmap
- The list at the top does not include a 1.x entry although we do have a "New features planned for future 1.x versions" section (just before 2.0.0) and that section has an id in its `h2` already. So, all we need is to add a `li` with that.
- The link for 2.0.0 does not work.

The reason for the 2.0.0 not working (and for the 1.x too when we add it) is this:

`<h2 id="#2.0.0">Goals for 2.0.0</h2>`

...it should be like so (delete the `#` from the id):

`<h2 id="2.0.0">Goals for 2.0.0</h2>`

The `#` also creeped in the id of the 1.x `h2`, so that should be fixed too.

**Comment by jenlampton** [comment]
fixed :)

**Comment by klonos** [comment]
Sorry I didn't get to this. I guess I filed this issue before we had access to edit nodes on b.org. Could have saved you a couple of minutes there and you could have spent that time doing more important things. I promise I'll be fixing such minor issues myself from now on (provided I have permission to do so).
