### ISSUE TITLE
Consider rewording the "Set up on Pantheon" to include the word "demo".

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#192]
@bd0bd in https://github.com/backdrop/backdrop-issues/issues/1702#issuecomment-194966784

> A newcomer can not know about this demo - there is no any visible information about the demo on the https://backdropcms.org/
> SET UP ON PANTEON - this is not clear what this is all about, would be right to rename it to DEMO - this is simple and understandable for people.

Lets figure out a way to better phrase this for the average Joe that doesn't know what Pantheon is. ...but lets still leave "Pantheon" there for those who know and search for it + for credit to the Pantheon guys that are working so hard in helping to get Drush to work for us for example.

**Comment by klonos** [comment]
How about "Launch a demo on Pantheon"?

...and perhaps a "free registration required" help text underneath the button/link? It's the "polite" thing to do.

**Comment by bd0bd** [comment]
I offer the first word to use - DEMO (not LAUNCH).

**Comment by klonos** [comment]
I don't think it makes sense in English ...unless we just say "Demo on Pantheon". Don't like the way its worded like that though. Not up to me really.

**Comment by bd0bd** [comment]
**Demo on Pantheo** does not sound enough right/good in English?

DEMO WEBSITE
Launch a demo on Pantheon

The key idea is to use word **demo** like a first word and not a second one.
I think people are quickly scanning for key words (the templates they have in their heads) and it is important to give them see this key word on a surface and not after the word **Launch**.

:)

How to make a smile here?

**Comment by klonos** [comment]
> Demo on Pantheo does not sound enough right/good in English?

What I meant is that for consistency with the "Download Backdrop" button, we should use a verb to begin the button label and although "demo" can be a verb, it doesn't sound good IMO. Our current label uses the phrasal verb "set up" and in d.org they use "try":

![backdrop-pantheon_button](https://cloud.githubusercontent.com/assets/2423362/13731303/d9976d3c-e9b9-11e5-9b0d-863fa1584758.png)

![drupal-try_demo_button](https://cloud.githubusercontent.com/assets/2423362/13731310/e2cff950-e9b9-11e5-94be-ed2371221dc9.png)

**Comment by klonos** [comment]
...here's how both things would look like (also added the "requires free registration" subtext, with emphasis on "free"):

![backdrop-pantheon_button-demo](https://cloud.githubusercontent.com/assets/2423362/13731366/f6b9fdac-e9ba-11e5-99b4-26b85284de9f.png)
![backdrop-pantheon_button-launch](https://cloud.githubusercontent.com/assets/2423362/13731367/f6bd3382-e9ba-11e5-950f-d8bbf5a25c19.png)

**Comment by docwilmot** [comment]
"Launch a demo on Pantheon" :+1: 
Or "Try a demo on Pantheon".

**Comment by bd0bd** [comment]
DOWNLOAD BACKDROP
and
DEMO ON PANTEON
 this is right in my mind.

And this variant is more simple and clear and Jakob Nielsen would agree with me.

![bbb](https://cloud.githubusercontent.com/assets/13515302/13731789/4eaa9e46-e983-11e5-9fe3-ca3331de297b.png)

**Comment by bd0bd** [comment]
Also I would like to offer you to add Download and Demo links to the left menu like this is on Piwik's website:

![bbb](https://cloud.githubusercontent.com/assets/13515302/13731882/8603f674-e985-11e5-8ac1-399355fc5bc5.png)

**Comment by klonos** [comment]
:+1:  on adding quick links on the drawer so that people can access these from any page they happen to land to.

Still not sure about the "simplified" button labels though.

**Comment by serundeputy** [comment]
We Backdrop community should not even consider removing the word `Pantheon` from the button as they graciously offer free infrastructure to Backdrop users.

Demo is a fine purpose for this button, but it is not the only purpose, you could host a Backdrop site on this Pantheon instance indefinitely.

**Comment by klonos** [comment]
I'm with you @serundeputy As said in the issue summary:

>...but lets still leave "Pantheon" there for those who know and search for it + **for credit to the Pantheon guys** that are working so hard in helping to get Drush to work for us for example.

**Comment by twmfc** [comment]
The two buttons as they stand offer the choice between downloading & self-hosting Backdrop or running Backdrop via a Platform As A service (PAAS) provider and Pantheon has helped facilitate setting this up on their infrastructure.

Drifting, only slightly, off topic.
 
Given part of the target Backdrop user market a better step at this stage might be to try and get Backdrop included in the Softaculous portfolio so that it can be easily installed on shared hosting via CPanel.

www.softaculous.com/softwares

I’m not sure how you go about this, other than via contacting Softaculous but it may well be worth trying.

If Backdrop was part of the Softaculous portfolio then it looks like a **demo site comes as a standard part of the package** for all applications e.g:

www.softaculous.com/demos/CMS_Made_Simple

Looking at some of the supported CMS’ on their listing Backdrop would stand head and shoulders above many so hard to see why Backdrop could not be on this listing?

Just a thought anyway!

**Comment by docwilmot** [comment]
> try and get Backdrop included in the Softaculous
 
https://github.com/backdrop/backdrop-issues/issues/965#issuecomment-171702312
Already done. They had issues with the fact that Backdrop initial install looked exactly like Drupal, but I think I've convinced them that with our latest release that's changed. Waiting.

**Comment by twmfc** [comment]
> Already done. They had issues with the fact that Backdrop initial install looked exactly like Drupal, but I think I've convinced them that with our latest release that's changed. Waiting.

Sorry, I'd not seen issue #965.....I should have searched a bit more first!

If Backdrop could get on Softaculous then it may be an option to have 3 'buttons' on the home page:

1. Download Backdrop
2. Set Up On Pantheon
3. View Demo {which would point to the Softaculous Backdrop demo url

As each of these 3 options server differing requirements.

**Comment by klonos** [comment]
@twmfc 

> ...try and get Backdrop included in the Softaculous portfolio ...

Already suggested and on our to-do list: https://github.com/backdrop/backdrop-issues/issues/965#issuecomment-109977762

**Comment by bd0bd** [comment]
>1. Download Backdrop
2. Set Up On Pantheon
3. View Demo {which would point to the Softaculous Backdrop demo url

This is what I was going to offer too :smile: 

But I offer not to use word **View**. Only - **Demo**.

**Comment by bd0bd** [comment]
I do not understand why you intend to create additional obstacle for perspective users.
Why to send people to another website (Softaculous) if a demo can be easily launched right here?

**Comment by wesruv** [comment]
I think the core problem is the user experience, I see the point that they're giving away free hosting and helping us by also supporting Backdrop, but if we're sending them users that are having a negative user experience then we're not helping them or us.

I don't think changing the button text or having more buttons is a step in the right direction. I really think this needs a bit more explanation. I'll work up a mock for what I'm thinking.

**Comment by bd0bd** [comment]
Deat **@Backdrop developers**,

You might call and ask [Jakob Nielsen](https://www.nngroup.com/people/jakob-nielsen/)  about this issue. I am pretty sure he would say the best variant for your CMS prosperity is to have 2 simple buttons:

1. Download Backdrop
2. Demo

Thank you!
:smile:

**Comment by wesruv** [comment]
Part of this has to do with what Pantheon prefers, they gave us the wording for "Spin Up on Pantheon", and part of this is that Demo doesn't really describe what your'e getting.

We'd really like something that is actually a quick demo (one click login to a temporary Backdrop site), but we'd need the infrastructure and we'd have to make some sort of process to make sure we don't create spam factory.

I think we can close this one with the upcoming homepage redesign #301 which tries to address the lack of clarity. If there's any feedback on the suggested direction let's continue chatting about it in those issues.

See:
https://github.com/backdrop-ops/backdropcms.org/issues/301#issuecomment-261403373
https://github.com/backdrop-ops/backdropcms.org/issues/314
https://github.com/backdrop-ops/backdropcms.org/issues/315
