### ISSUE TITLE
"Show your support" form: Logo upload button only partially shown.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#198]
There is an issue with the "Show your support" form (shown only to registered and logged in users) where the "Your logo" field is shorter than the rest and so the upload button is mostly hidden:

![backdropcms org-show_your_support_form-upload_logo_button_not_visible](https://cloud.githubusercontent.com/assets/2423362/13895903/dd5717b0-edce-11e5-84e7-5af87d135480.png)

**Comment by serundeputy** [comment]
@jenlampton `PR` https://github.com/backdrop-ops/backdropcms.org/pull/199 needs review.

**Comment by jenlampton** [comment]
deployed :+1: good job team!

**Comment by klonos** [comment]
Thanx @serundeputy :+1: and @jenlampton 

I had to clear caches for the change to take effect, but it looks good now.
