### ISSUE TITLE
Build a long-term issue tracking solution

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#2]
We're using Github for project management right now, but it has a number of limitations:

- PUSH access required in order to assign labels or organize issues.
- After push access is granted, it allows deletion of entire labels in a way that's dangerous with no undo or confirmation (imagine the entire label for "bug" being deleted from hundreds of issues).
- There's no ability to specify version (we could use labels, but we'll end up with dozens of them).

We need to decide on the best way to solve our long-term project management needs. Should we set up project.module on backdropcms.org? Should we try to bend Github to our needs through API integration? Use another project management tool?

**Comment by jenlampton** [comment]
Since we seem to be getting along okay with the github tracker, I'm going to postpone this issue for now.  We can reopen / reevaluate if we start running into insurmountable problems.
