### ISSUE TITLE
User profile assumes all new users are male

### ISSUE THREAD

**Issue by sentaidigital** [backdrop-ops/backdropcms.org#206]
When you create a new account on BackdropCMS.org, the registration page does not ask for your gender, but the profile lists Gender: male. 

One option is N/A, which would be a better default, but not perfect.  Unless you are an IRC bot, gender is applicable, so adding "not specified" (or something like that) and making that the default would be the best solution.

**Comment by jenlampton** [comment]
Thanks for pointing that out, I'm not sure how it got set to male. I just changed the default value back to N/A. The N/A value won't show anything at all on the profile page (works similarly to "not specified") so should do for now, but it would be a good idea to change it from N/A to "Not specified" in the form too.

**Comment by jenlampton** [comment]
There we go, changed that form from `N/A` to `Not specified`.  Great suggestions, thank you!

**Comment by sentaidigital** [comment]
You're welcome.  I'm glad I could help.
