### ISSUE TITLE
Add a second drawer for login 

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#209]
As per this pretty picture: 

![1e9b214a-ed33-11e5-9246-4f0151de2112](https://cloud.githubusercontent.com/assets/397895/14038249/539177be-f20b-11e5-93db-0e274c5e9c44.png)

**Comment by serundeputy** [comment]
we are not using drawers in the new design any longer.
closing ... re-open if necessary.
