### ISSUE TITLE
Dual logo in mobile view.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#210]
I think that this was not there before. Must be a side-effect of 769496052d0990f57df04fa7e0907ca0f02f948b (#185 & #160):

![backdropcms org-dual_logo_on_mobile](https://cloud.githubusercontent.com/assets/2423362/14041623/e9e1337e-f2c6-11e5-8c86-cafe171cf5e0.png)

**Comment by klonos** [comment]
Clarification: this does not actually happen on mobile per se (it's shown fine on my android phone using chrome). It occurs after shrinking the viewport enough to reach the breakpoint from desktop to mobile. Don't know if there'll be an actual, real-life case where this occurs.

**Comment by gifad** [comment]
There are actually two logos drawn here !

First, a CSS construct of two rectangles, (a white rectangle rotated on top of a black rectangle)
Second, a classic img tag, wich comes on top of the css made logo, and makes it usually invisible…

The problem occurs when the container width is greater than the image width : then the css logo (which is responsive) appears partially "behind".
All this occurs at https://github.com/backdrop-ops/backdropcms.org/blob/master/www/themes/borg/css/patterns.css#L86
A quick fix is to make the image responsive, by applying : 
```
.backdrop-mark img {
  width: 100%;
```
at #L123

**Comment by klonos** [comment]
:+1: @gifad! It works with width set to 100%.

**Comment by gifad** [comment]
Done PR #219

**Comment by jenlampton** [comment]
merged, closing.
