### ISSUE TITLE
Request for elevation of permissions on backdropcms.org

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#212]
Scary issue title? ...come on, you know me! :smile: 

Seriously now though. I need to be updating some posts that others are making. Minor things like misspellings and other typos, but also other things like fixing broken links or converting things to lists etc. As it is now, we have permission to edit only our own content + all documentation, basic pages and book pages. I need permissions to also be able to edit all posts and events too. Is that ok?

Also, we have no announcement for 1.3.4. I would be honored to write one (and be able to back-date it to the date of release). I mean if this is not a task reserved to be done by either @quicksketch or @jenlampton that is(?). If yes, do you guys think it is ok to have animated .gifs showcasing features instead of static images, or better not? I know WP uses short videos, but I am not ready to be doing that ...yet :smile: 

Let me know.

**Comment by jenlampton** [comment]
I just granted all editors access to edit all events and all posts.  Please feel free to keep reminding me to increase permissions as we add more new features...  I'm likely to forget again!

> Also, we have no announcement for 1.3.4

I don't think we usually make announcements for bug-fix releases. For minor releases it makes sense to talk about new features, etc, but I don't think we need animated .gifs showing how things that were broken before aren't anymore ;)  But...  if there is anything else you would like to write a post about we would love to have something :)

**Comment by klonos** [comment]
> I just granted all editors access to edit all events and all posts. Please feel free to keep reminding me to increase permissions as we add more new features... I'm likely to forget again!

Thanx and I will do :smile: 

>>Also, we have no announcement for 1.3.4

> I don't think we usually make announcements for bug-fix releases. ...

Silly me! I read the announcements for 1.1, 1.2 and 1.3 and I in my mind these registered as 1.3.1, 1.3.2 and 1.3.3 respectively somehow. I'll just shut up and go get some sleep. It seems that I need it. Either that, or I'm going :stuck_out_tongue_winking_eye: 

It is definitely within my plans to write a post soon(ish).

**Comment by jenlampton** [comment]
doh sorry @klonos! I just made you an admin. Don't break anything ;)

I also back-dated the post and changed the date (incase it is the middle of the night for you) I think we should get the rest of our editors set up with override-node-options too, but for now let's just give you free reign :)
