### ISSUE TITLE
Adding a post for the 1.0 release...

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#213]
In #212 I mistakenly thought that we needed a release announcement for 1.3.4, but as @jenlampton pointed out, we do not publish announcements for bug fix releases.

We've recently added a [post with the initial announcement of the fork](https://backdropcms.org/news/dont-panic) though (#200). But we didn't have one for the release of 1.0...

...Here it is. Mostly a copy-paste from @quicksketch's [post about it on his own blog](http://quicksketch.org/backdrop-cms-release-announcement). Issues with the post I need guidance/help:
- Nate's original post has the link for the "Five reasons to consider Backdrop CMS:" header pointing to `https://backdropcms.org/#node-19` with `node-19` being the article id of our "Backdrop CMS" basic page. That is not very SEO-friendly, but I guess that we hadn't had enabled pathauto back when the node was originally created. I have no permissions to edit the path settings, so I went with adding a `why-use-backdrop-cms` id in the article h2 header on the "Backdrop CMS" node and adjusting the link from Nate's article accordingly. That seems to work fine, but let me know if you want it reverted and done another way.
- Similarly, the link of the "Show your support." header pointed to a `block-formblock-supporter` id that is no longer available. I've changed that to point to `supporter-node-form` instead, but that focuses the page directly on the first field of the form. It would be nice if it was the form h2 title instead, but it has no id to target. Even nicer if it focused on the list of supporters IMO, but again no id to target.
- It shows me as the author. It needs to be Nate, but no permission to change that.
- It also shows Mar 30th 2016 as date. It needs to be Jan 16, 2015 instead. Again, no permission to change that.

**Comment by klonos** [comment]
...also noticed that the release posts for 1.0 and 1.1 have the following URLs:

https://backdropcms.org/news/backdrop-10-released
https://backdropcms.org/news/backdrop-11-released

These might cause issues when we actually release those versions :laughing: 

...joke aside, the respective URLs for the 1.2 and 1.3 announcements are:

https://backdropcms.org/news/backdrop-1-2-0-released
https://backdropcms.org/news/backdrop-1-3-0-released

I think that we should change the version number part of the URLs for the 1.0 and the 1.1 announcements to the use dashes as well.

**Comment by klonos** [comment]
...also noticed that the authoring info says "Posted by by ..." (duplicate "by"). Needs to be corrected.

**Comment by klonos** [comment]
...also Drop's image was copy-pasted in the WYSIWYG editor, so it's URL is http://quicksketch.org/files/articles/6449af58-1672-49e7-99a9-80989a18d601.png - no other way to upload images :disappointed:

**Comment by klonos** [comment]
Can I please haz permizzions for doing all thoze thingz without "poking" other people? Thanx.

**Comment by klonos** [comment]
...also permission to create nodes as unpublished. This "Backdrop 1.0 released!" node is sitting there published at the top of the news list waiting for one of you guys to wake up because I have created it while in a different time zone.

**Comment by jenlampton** [comment]
doh sorry @klonos! I just made you an admin. Don't break anything ;)

I also back-dated the post and changed the date (incase it is the middle of the night for you) I think we should get the rest of our editors set up with override-node-options too, but for now let's just give you free reign :)

**Comment by klonos** [comment]
>I just made you an admin. Don't break anything ;) I think we should get the rest of our editors set up with override-node-options too, but for now let's just give you free reign :)

Thanx. I promise not to.

Also thanx for fixing so promptly the things I pointed out. Our news section looks more complete and richer now :wink: :clap: 

> all of the paths should be 1-0, 1-1, 1-2, etc. Let's do this going forward too! :)

Yep, lets. The path for 1.3 is still 1-3-0 though. I don't mind either way way choose to go (include the 0 or not), but lets either update 1.3 to be 1-3 or the rest to have a `-0`. Do you prefer doing that by directly editing the paths or by adding redirects? Because I have access to edit redirects, but not to edit paths.

...talking about consistency, the release announcements titles are as follows:

What's New in Backdrop 1.3
Backdrop 1.2 released
Backdrop 1.1 released!
Backdrop 1.0 released!

I think that these should be consistent too. I added the exclamation mark on the title of the 1.0 because we simply could not be less excited about it than we were with 1.1. The 1.3 release announcement has a `backdrop-1-3-0-released` URL, but its title is "special".

**Comment by jenlampton** [comment]
The news post for 1.3 didn't go out when it was released, it was late, hence the different tile. I do think we should drop the 0s though, both from the title and from the path. You *should* have access to edit the URLs. If you can't do it on the nodes, can you access it via this page? https://backdropcms.org/admin/config/search/path

**Comment by jenlampton** [comment]
I think we can close this now, but please reopen if I'm mistaken.
