### ISSUE TITLE
Adding a "Press" book page.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#214]
I currently have permissions to add Documentation, Event, Post, Testimonial & Supporter nodes. I would also like to be granted permission to create basic pages and also the "Administer book outlines" & "Add content and child pages to books" permissions.

I want to add a page titled "Press" or something like that with a `https://backdropcms.org/press` URL that will hold a list of links to articles, reviews or videos about Backdrop with a date where available. Should that be a basic page or a book page?

Also, I was thinking that this could instead of a node be a view of a new "Press" content type. That content type can have only a title, link and (optional) date. This way we can have a block that lists the 5 latest press entries about Backdrop for example.

Let me know what you think.

**Comment by jenlampton** [comment]
> Should that be a basic page or a book page?

How about we start with a basic page. This sounds like the perfect case for a content block! (or page-less node). Maybe we should focus on that for 1.6 :)
