### ISSUE TITLE
PR Sandboxes: sometimes the sandbox is not properly installed.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#216]
This is the second time it happens with https://github.com/backdrop/backdrop/pull/1311

First time was with https://github.com/backdrop/backdrop/pull/1315 (already reported in https://github.com/backdrop-ops/backdropcms.org/issues/5#issuecomment-203876413)

**Comment by Gormartsen** [comment]
Thank you @klonos
I will check it out next few days.

**Comment by klonos** [comment]
Thanx @Gormartsen Do you have any plans to allow the QA server to also fire up Backdrop instances + contrib modules without having to make a pull request (like simplytest.me)?

**Comment by klonos** [comment]
...happened again with https://github.com/backdrop/backdrop/pull/1296

**Comment by klonos** [comment]
...here's a case where the sandbox was not created at all: https://github.com/backdrop/backdrop/pull/1317

**Comment by Gormartsen** [comment]
@jenlampton or @quicksketch can you delegate this task to me please?

**Comment by jenlampton** [comment]
Like that?

**Comment by Gormartsen** [comment]
@jenlampton tnx!

**Comment by klonos** [comment]
...another one: https://github.com/backdrop/backdrop/pull/1302

**Comment by Gormartsen** [comment]
@klonos tnx! I assume I know where is issue, but did not have a chance to check it yet.

**Comment by klonos** [comment]
That's great news. Now you know what to look for or at least have an idea.

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/1304 is another case.

**Comment by mikemccaffrey** [comment]
Should this issue be in the backdropcms.org issue queue? Should we perhaps create a separate repo/queue/chatroom in backdrop-ops specifically for our automated testing workflow?

**Comment by jenlampton** [comment]
All the code for our automation is in the backdropcms.org repo, so that's why the issues are here.

**Comment by mikemccaffrey** [comment]
> All the code for our automation is in the backdropcms.org repo, so that's why the issues are here.

Wait, what does the public content website have to do with automated sandboxes?

**Comment by jenlampton** [comment]
our GitHub automation code lives in the borg repo because we do things like create nodes on the borg site when new projects are pushed to github.  The github automation code also drives creation of sandboxes.

**Comment by mikemccaffrey** [comment]
Okay, sorry for the basic questions here, but:

- Is github triggering the automation with push notifications, or is the website polling github?
- Is the b.org site being bootstrapped whenever there is github activity, or are they independent scripts?

**Comment by Gormartsen** [comment]
@mikemccaffrey
> Is github triggering the automation with push notifications, or is the website polling github?

- github send web hook (push) notification.

> Is the b.org site being bootstrapped

I believe backdropcms.org code get updated manually only.

Check this mind map for sandbox activity: 
<img width="1275" alt="screen shot 2016-03-22 at 11 34 56 pm" src="https://cloud.githubusercontent.com/assets/5018896/13974932/bd58e0aa-f086-11e5-90c7-833ffb294712.png">

**Comment by klonos** [comment]
Lately, PR sandboxes are not destroyed once the PR is merged.

**Comment by Gormartsen** [comment]
@klonos tnx. Will check that as soon as I finish test env. I am few days away from finish line.

**Comment by Gormartsen** [comment]
@klonos ha! Found and fixed. It was on gitlc side

**Comment by klonos** [comment]
Did you fix just the sandbox deletion upon PR merge or the problem with the sandbox not being properly installed as well?

**Comment by Gormartsen** [comment]
@klonos only deletion upon PR merge. I broke this part yesterday while was rewriting deploy(undeploy) module on gitlc side.

To fix issue with properly installed, I need to update rp_api module on backdropcms.org side. 
There is a need to wait until domain and database get created. Usually it takes seconds but sometimes it takes a little bit longer and that's where issue is coming from.

**Comment by klonos** [comment]
Makes sense. Thanx for taking the time to explain @Gormartsen

**Comment by klonos** [comment]
@Gormartsen I don't know if this is just a temporary downtime until you do your magic in order to drop our test runs under 10min, but the PR sandbox for https://github.com/backdrop/backdrop/pull/1417 throws this:

![robin_panel](https://cloud.githubusercontent.com/assets/2423362/15565868/fe0fd9ca-2360-11e6-9714-2417ba0c35e4.png)

**Comment by Gormartsen** [comment]
@klonos Issue with deploy phaze. Try to close , wait 10 sec, and open PR again. Should be ok

**Comment by BWPanda** [comment]
It's been quite a while since the last activity here... Can we close this now, or are there still things to do here? Ping @klonos & @Gormartsen.

**Comment by BWPanda** [comment]
Closing then.
