### ISSUE TITLE
[DX/UX] Views: Allow exporting/importing a view code from the UI.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#217]
As per issue title, lets add an "Export view" option in the `views-display-top` div drop button of each view as well as an "Export" option for each view in the views list under `/admin/structure/views`.

This could open a modal with the code where the user could either just select and copy (we could have the text pre-selected) and/or perhaps have a "Save to file" button.

**Comment by klonos** [comment]
...would be useful to also have an "+ Import view code" button next to the "+ Add view" one that opens a modal with a text field where one could paste the exported code of a view.

**Comment by klonos** [comment]
Views 3.x for D7 has the import/export feature:

![d7-views-import_view](https://cloud.githubusercontent.com/assets/2423362/14235991/e9579d08-fa50-11e5-8490-7ea8db895bd6.png)
![d7-views-list-export_view](https://cloud.githubusercontent.com/assets/2423362/14235992/e9592d80-fa50-11e5-814e-3c2d29ac2811.png)
![d7-views-view-export_view](https://cloud.githubusercontent.com/assets/2423362/14235993/e95cbe0a-fa50-11e5-9241-e7a891841587.png)

...but I guess we forked from the version that got into D8 that must have for some reason left this feature out.

**Comment by serundeputy** [comment]
because it is currently done with CMI.

**Comment by klonos** [comment]
...and this is the wrong issue queue :smile:
