### ISSUE TITLE
by by :)

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#218]
originally filed by by @bd0bd (pun intentional) in https://github.com/backdrop/backdrop-issues/issues/1797 :

> May be I am mistaken but I think this is Jennifer's bug :smile: 

> ![byby](https://cloud.githubusercontent.com/assets/13515302/14512724/489067a0-01ea-11e6-8320-332aa57d7208.png)

**Comment by klonos** [comment]
I think that this is on the theme level, so can't fix it myself. @jenlampton ??

**Comment by jenlampton** [comment]
Thank you @klonos !  Fixed: https://backdropcms.org/news

**Comment by klonos** [comment]
Bye-bye "by by" :laughing: ...or at least one of you.
