### ISSUE TITLE
Create a Backdrop Update Server

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#22]
We need to build an update server for the core Update module to use.  It's just a PHP script that returns current versions, and stable releases of core and contrib.

See the associated issue for Update.module in core itself at https://github.com/backdrop/backdrop-issues/issues/396.

**Comment by quicksketch** [comment]
Also related to this issue is adding Backdrop release information to the GitHub hosted packages. See https://github.com/backdrop-ops/backdropcms.org/issues/51.

**Comment by quicksketch** [comment]
Lots of progress on this over in https://github.com/backdrop-ops/backdropcms.org/issues/8#issuecomment-92659415, which is an update on how project.module is coming along. Project release module is now fully working in generating XML release files on cron jobs. I'll continue updating here occassionally, but the main work on this is happening in project module itself: http://github.com/backdrop-contrib/project.

**Comment by quicksketch** [comment]
We flipped the switch on the update server on Monday. Sure is great to see that amazing "Up to date" message!

![updates](https://cloud.githubusercontent.com/assets/100206/7849251/a464d29e-0490-11e5-935a-bb9262b127da.png)

All existing Backdrop sites should now start receiving update information. All versions of core will immediately start getting updates, but only "official" releases of modules will work (those that have had their .info files modified with packaging information).

Looks like @Graham72 noticed as soon as the switch was flipped: https://twitter.com/Oliver7G/status/602827343212711936 :wink:

Let's open new issues dealing with the update server either directly against Project module or in this queue if it's BackdropCMS.org specific.

**Comment by klonos** [comment]
Hurray!!! :tada:
