### ISSUE TITLE
SSL Certificates Using Let's Encrypt

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#220]
Migrate from our current SSL certificate to SSL certificates provided by the Let's Encrypt program: https://letsencrypt.org/getting-started/. 

To Do: 
1. Generate and install a certificate for each sub-domain. 
2. Configure the auto renewal script for each sub-domain. 
3. Create a notification that is triggered when the automatic renewal script runs but only if it does not exist already. The notification should indicate a pass or fail for the renewal. 
4. Begin the migration using https://dev.backdropcms.org as the experimental sub-domain certificate. If all goes well, move on to the other sub-domains.

**Comment by quicksketch** [comment]
Thanks @larsdesigns! Have at it.

Browser support seems okay to me. I am slightly concerned by Chrome on XP not being supported or Blackberries, but considering our audience I think that will be fine. We do need to make sure that server-side requests are not bothered by this cert, but OS support seems to be from Ubuntu 12+, so I don't think that will be an issue.

**Comment by larsdesigns** [comment]
@quicksketch I would like to still implement this. I did notice that new certificates were purchased last October but I am convinced that Let's Encrypt is fantastic long term solution.

**Comment by larsdesigns** [comment]
I am waiting until January so we can install and use the wild card certificates.  https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by serundeputy** [comment]
@larsdesigns are the new servers on letsencrypt? should we close this?

**Comment by larsdesigns** [comment]
@serundeputy, Let's Encrypt certificates have not been implanted as of yet. I think there is a still more than a year on the paid SSL certificates. We had put this on hold for some reason that I am not recalling. 

@quicksketch and @jenlampton, Should I move forward with the Let's Encrypt certificates?

**Comment by jenlampton** [comment]
This is slightly more urgent now, as our certs expire in August.

**Comment by quicksketch** [comment]
I am no longer concerned about Windows XP or Blackberries. lol

**Comment by jackaponte** [comment]
I'll be excited to see us using LE certs!

**Comment by larsdesigns** [comment]
Let's move forward with this.

**Comment by larsdesigns** [comment]
#### Implemented Let's Encrypt certificates for the following:

1. backdropcms.org
1. api.backdropcms.org
1. forum.backdropcms.org
1. localize.backdropcms.org
1. sanitize.backdropcms.org
1. www.backdropcms.org

Checked the certificates using Firefox.

**Comment by larsdesigns** [comment]
Created crontab rule using root account: `0 */12 * * * root certbot renew --quiet`. 

Let check back after more than 12 hours to see that the certificate update using the cron job.

**Comment by larsdesigns** [comment]
Tested the SSL certificate for backdropcms.org using ssllabs.com: 

![Screen Shot 2020-09-10 at 3 23 34 AM](https://user-images.githubusercontent.com/976705/92710448-0ad7d080-f315-11ea-8b98-46b3c7e5a94c.png)

**Comment by larsdesigns** [comment]
![Screen Shot 2020-09-10 at 3 24 45 AM](https://user-images.githubusercontent.com/976705/92710634-335fca80-f315-11ea-9326-880c1eefcd95.png)

**Comment by larsdesigns** [comment]
TO DO: 

1. [ ] Create LE certificates for: 

1. projects.backdropcms.org
1. updates.backdropcms.org

**Comment by larsdesigns** [comment]
1. Created a Let's Encrypt certificate for updates.backdropcms.org. 
1. It is testable at: https://updates.backdropcms.org/modules/contrib/project/project_release/project-release-serve-history.php.

@jenlampton @klonos

**Comment by larsdesigns** [comment]
Verified that https://projects.backdropcms.org/ is using an LE SSL certificate.

**Comment by larsdesigns** [comment]
@jenlampton @quicksketch, Think I got all of the subdomains. Can we close this one?

**Comment by larsdesigns** [comment]
No further tasks. Closing...
