### ISSUE TITLE
SCSS Coding Standards 

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#23]
It would be nice to have a basic SCSS coding standards page in the handbook. Such a page should probably not be specific to SASS or LESS. 

This is assuming that BackdropCMS will officially adopt SCSS in core or allow it in contributed modules.

**Comment by quicksketch** [comment]
Let's close this for now. Coding standards have been moved over the API site in any case, so if we reconsider this later, let's discuss in https://github.com/backdrop-ops/api.backdropcms.org/issues.
