### ISSUE TITLE
Fix ordering of add-on search results

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#232]
[Searching for "devel"](https://backdropcms.org/modules?s=devel), brings these results (Devel is listed 15th):

Plupload
Honeypot
Backup and Migrate
Mime Mail
Automated Logout
EU Cookie Compliance
githubapi
File Resumable Upload
Entity Metadata Wrapper
Project Browser Server
Views Bootstrap
Search404
Responsive Favicons
Views Send
**Devel**
...

**Comment by docwilmot** [comment]
this is the same reason i use google to search for drupal projects. i guess we inherited the same search technology.

**Comment by jenlampton** [comment]
yes, we did. Long term we should set up apachesolr for searching our site, but short term I have adjusted the keyword relevancy. Let's see if that helps at all?

**Comment by Gormartsen** [comment]
> Long term we should set up apachesolr 

Is Sphinxsearch posible option?

**Comment by klonos** [comment]
> Let's see if that helps at all?

...doesn't seem to 😞

**Comment by jenlampton** [comment]
I'm not sure the content has been reindexed yet. Let me invalidate the current index.

**Comment by klonos** [comment]
Invalidating and reindexing does not seem to fix things either.

**Comment by jenlampton** [comment]
BAH. :/

**Comment by jenlampton** [comment]
maybe it's time for apachesolr (or Sphinxsearch)

**Comment by klonos** [comment]
Could be something related to the word "devel" + the fact that this specific exposed filter searches both title and body. Is there any way to set the keyword relevance for combined fields to have a higher value for one of the fields? ...in other words give more relevance points to node title than node body.

https://backdropcms.org/modules?s=nice

**Nice Menus**
Views Bootstrap
WOW JS Such Impress posted Feb-19-2016
Responsive Menus
Setup
Mobile Navigation
Back To Top
Global Redirect

https://backdropcms.org/modules?s=menu

Tag
**Nice Menus**
Node clone
Tweaks
Menu Admin per Menu
Responsive Menus
Coffee
Tab Tamer
Menu position
Agenda
WordPress Menu
Fanciblock
API
Parallax Background
Scroll Reveal
Void Menu
APC - Alternative PHP Cache
Mobile Navigation
Contact Forms
Comments block

https://backdropcms.org/modules?s=nice+menu

**Nice Menus**

**Comment by jenlampton** [comment]
That's a good idea!  I did a quick search and wasn't able to find a drupal module that added relevancy for combined fields filters. Maybe we can do a custom query alter?

**Comment by klonos** [comment]
Yeah. I noticed that the "modules" view (needs to be renamed to "projects" or "project search" by the way - separate issue?) has "(latest) Content: Post date (desc)" as sorting criterion. I tried changing that to "Search: Score (asc)", but still not getting the expected results.

**Comment by klonos** [comment]
This seems related: [Search terms: nodes dont appear when using multiple arguments [#1615438]](https://www.drupal.org/node/1615438). It was filed and fixed against views.

**Comment by jenlampton** [comment]
yeah, that's because we are using exposed filters and not the search, so there's nothing to score. Maybe we should try switching that out? Go back to exposing search term instead of exposed filters?

**Comment by klonos** [comment]
...doh! Yeah, I just remembered that the "Search:" part for the criterion is for when using search. Usability issue there. People would not be able to easily tell/remember the difference.

**Comment by klonos** [comment]
...is there any way to perhaps implement some way to be able to have scoring on exposed search fields? Then we could have that as an available sorting criterion. This seems more straight-forward to me, but I do not know the limitations/implications architecturally-wise.

**Comment by jenlampton** [comment]
I definitely think it's possible, that's why I was searching for a module. I just don't think anyone has ever done it before :)

**Comment by Dinornis** [comment]
In D6 I am using [Search Lucene API](https://www.drupal.org/project/luceneapi) which allows me to set configurable levels of importance on certain items when scoring is calculated for search results. Results having matched items with larger boost factors are returned higher in searches.  For example I set a higher bias for `Title` and lower bias for `Body`.

Unfortunately [Search Lucene API](https://www.drupal.org/project/luceneapi) has reached “end of life” and is deprecated in favour of other projects like:

Core Search module coupled with [Faceted Navigation for Search](https://www.drupal.org/project/search_facetapi) or
[Zend Lucene project](https://www.drupal.org/project/zend_lucene) coupled with [Search API](https://www.drupal.org/project/search_api). I do not have any experience with these.

**Comment by BWPanda** [comment]
'Devel' is now on page 4 of the search results...!

BTW, should this issue be closed in favour of https://github.com/backdrop-ops/backdropcms.org/issues/442, or are they different?

**Comment by BWPanda** [comment]
Changed issue name to differentiate from #442

**Comment by BWPanda** [comment]
Here's a quick attempt at a fix: https://github.com/backdrop-ops/backdropcms.org/pull/669

I removed the combined exposed filter and replaced it with a 'Search' one (it's related to the Project Browser, but I've not used it before, I just found it as an option and it works!). One problem I could fix was that the new exposed field's size is 15 instead of 30. I just couldn't find where to set/override that...

As an example, here's how the search for 'devel' now looks:
![screencapture-borg-lndo-site-modules-2020-03-20-22_32_19](https://user-images.githubusercontent.com/2385329/77204199-e7b52c80-6afa-11ea-8c63-8926f2f292d5.png)

**Comment by jenlampton** [comment]
We switched to the combined fields filter for a reason. Did you review that issue, and make sure this change doesn't revert the previous fix? (I don't remember what the previous problem was...)

**Comment by BWPanda** [comment]
No, but I did notice that the exposed search field has been disabled on the Themes page, and the commit that did that seems to have just been a live config sync, not related to a specific issue... (my PR reverts that to put the search back on the Themes page).

**Comment by BWPanda** [comment]
I can tell you that it was done before Jan 2016: https://github.com/backdrop-ops/backdropcms.org/issues/153#issue-124604932

**Comment by jenlampton** [comment]
Okay, will if @klonos doesn't weigh in (or doesn't remember) let's switch back and see if the old problem returns :)

**Comment by BWPanda** [comment]
Ping @klonos & @jenlampton. Time to try committing this?

**Comment by serundeputy** [comment]
combined filters were for people who don't know the name of the module they are searching for, but have an idea of what they want or hope to do. So if I don't know the name of the `devel` module I might type in `development tools` or something... the combined filter searches the `title` and `body` fields.

**Comment by BWPanda** [comment]
Thanks for pointing that out @serundeputy. I just tested the PR with that in mind and it still seems to work. For example, Devel's project page has this text: `Integrating with XHProf to show what PHP was executed and identify slow calls.` So I searched for 'XHProf' and the single result that came up was Devel. So it does still search the Body/Description field.

**Comment by jenlampton** [comment]
Okay, let's try this for a while. If we run into whatever it was we hit last time we were using search, we can address that next! 

@BWPanda We could form-alter the exposed search field to adjust it's size, I don't think there's a setting. I usually use `views_exposed_form_alter()` and then search the `theme_hook_suggestions` to limit to the form to the one on this specific view.

**Comment by jenlampton** [comment]
@BWPanda I dug up the designs for these pages and the search box is supposed to extend all the way across the page: 
<img width="968" alt="Screen Shot 2020-07-02 at 5 48 24 PM" src="https://user-images.githubusercontent.com/397895/86420745-65f1a500-bc8c-11ea-9b9d-e540984f36a8.png">

I think this means we don't need to worry about the size, because we'll need to set the width in CSS either way.

**Comment by BWPanda** [comment]
@jenlampton So does that mean this is back to 'Needs review', or does the PR need some more changes?

**Comment by jenlampton** [comment]
Ideally, the PR needs a few lines of CSS to the width on the search box (and check all breakpoints?)

**Comment by BWPanda** [comment]
The PR has been updated to make the width of the search field 100%. It works across all breakpoints.

![image](https://user-images.githubusercontent.com/2385329/89710374-9c29ef00-d9c5-11ea-9672-afd64cbab50a.png)

**Comment by BWPanda** [comment]
Fixed merge conflict in PR. It basically just changes the view now, as the CSS changes were made to the repo outside of this PR. Needs review then I think we just push this live and see how it goes in the wild.

**Comment by herbdool** [comment]
For what it's worth I've reviewed and seems fine. So it switches to use the search index basically. Let's try it.

**Comment by BWPanda** [comment]
Merged! Thanks everyone! Backdropcms.org has been updated and now works better: https://backdropcms.org/modules?s=devel

**Comment by jenlampton** [comment]
@herbdool I've added you to the web team so you should have access to labels on issues for all websites now.
