### ISSUE TITLE
Contrib Curators

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#233]
I often find common nits with contrib projects and correct them (where I have the required permissions). Some of these nits are:
- Not properly capitalized project names (we use title case instead of sentence case with exceptions to projects that copy the name of a 3rd party project/product)
- Missing short project description on GitHub (the one at the top of the repository - **not** the one in the README.md)
- Missing project URL on GitHub (temporarily pointing to the d.org project while the project is being ported - updated to point to the one on backdropcms.org once the project has a release)
- Missing project type in the project .info file
- Using text describing the changes included in a release as the release tag (version number should be used instead and optionally prepend the project name).
- ...

**What**

I would like to propose the following things:
- [ ] Establishing of a "Contrib Curator" role and propose myself for it. (sounds vain, I know, but bare with me...)
- [ ] Allow others to request to be assigned this role using the same queue and similar processes as we currently have in place for contrib developers. This will allow to form a team of people doing this "housekeeping" so that we do not rely on a single person. (Pretty words to actually say "I could use some help here.")
- [ ] Update the documentation/task-list of the process of porting/creating a project to include steps for checking these things so that there is no need for any intervention by the Contrib Curators in the first place. It should be a task of the project maintainers if they have time, but the Contrib Curators are there to either help when there is no time or to correct common errors. [Crowdsourcing](https://en.wikipedia.org/wiki/Crowdsourcing) ++
- [ ] Automate the checking of these things where possible (include warnings in the packaging error files generated during releases perhaps?)
- [ ] Create an email account and proper redirects for the members of the Contrib Curators team.
- [ ] Generate email alerts when there is a packaging error, so that Contrib Curators can take action.

Some of the tasks above I can do myself (update documentation), with others I'm gonna need help (automation, creation of email etc.).

**Why**
1. I guess having proper GitHub project descriptions and URLs pointing to backdropcms.org might improve SEO.
2. Keep a high level of consistency in lists of things like the project search results in backdropcms.org and the forthcoming Project Browser.
3. The truth is that I have self-diagnosed OCD that kicks in :stuck_out_tongue_winking_eye: . Especially when things are not consistent. So mainly that for myself and others like me :smile: 

**When**

As soon as possible, but this in not a high priority issue. The sooner we can get some of these things in place though, the better. I mean before the community grows even more and there are so many projects being ported/created that it gets even more overwhelming to do this "housekeeping".

Thanx in advance to anyone that will help with these tasks or will become a Contrib Curator.

**Comment by klonos** [comment]
...to that end. Is it OK if I commit project name changes in the .info files (in order to comply with proper use of case) without waiting for project maintainer approval/action? I mean, it is merely fixing typos actually - not things that effect code execution AFAIK.

**Comment by Graham-72** [comment]
I think this is a good idea and it has my support.

One thing I would like to point out or query is that as a contrib project author it does not seem possible to edit some of these things, e.g. the short description, once we have transferred ownership to backdrop-github. So @klonos seems to have editorial rights that we, the authors, lose.

Some things we cannot enter before transferring ownership e.g. URL on backdropcms.org. Also, we cannot revise our errors and omissions. This is annoying - or am I wrong and have missed something in github?

Which brings me to another point, guidance on doing these things is getting hidden amongst so many issues and URLs. After release of 1.4 we must spend time on the usability of our support infrastructure, particularly for casual users or those like me who are prone to senior moments.

**Comment by klonos** [comment]
> ...prone to senior moments.

:smile:

**Comment by serundeputy** [comment]
@klonos 
> ...to that end. Is it OK if I commit project name changes in the .info files (in order to comply with proper use of case) without waiting for project maintainer approval/action?

I would vote that you file a proper `PR` for any codebase changes even for `README.md` and `*.info` files; that is the point of having maintainer(s) if you trump it the structure is gone.

**Comment by Graham-72** [comment]
@serundeputy a good point. If there is a currently active maintainer let him/her make the changes that are within their power.

**Comment by klonos** [comment]
Fair enough guys. I was expecting that kind of answer. It's tedious that way, but I understand that it's the proper way to do things.

**Comment by jenlampton** [comment]
> One thing I would like to point out or query is that as a contrib project author it does not seem possible to edit some of these things, e.g. the short description, once we have transferred ownership to backdrop-github.

@Graham-72 this is only the case if you also transfer away your access when making the change. If you have any current projects with this problem let us know and we can give you back your access :)

@klonos I love this idea and I am fully in favor of having a contrib squad helping with cleanup and generally engaging our contributors :)  I agree with @serundeputy that you should file PRs whenever possible, but I think getting you a team of people to help with that might make that process less tedious. Great idea!

**Comment by klonos** [comment]
>  I agree with @serundeputy that you should file PRs whenever possible, but I think getting you a team of people to help with that might make that process less tedious.

...and/or also automate what can be automated.

If I have time/energy, I will have a go with the documentation of coding standards, common practices and workflows/how-tos. If people use these as guides, then we need to make sure that they do not miss any steps that would tick all the right checkboxes in order to have tidy(ier) contrib repos. ...but as I said, as time permits.

**Comment by jenlampton** [comment]
👍  sounds great! :)

**Comment by BWPanda** [comment]
This sounds like it can be closed now. Feel free to re-open if I'm mistaken.
