### ISSUE TITLE
Spelling mistake: 'alternaively'

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#238]
This is present on: https://backdropcms.org/handbook/themer-guide/theme-debug-mode
If you're happy to give me access, I can make simple changes like this as I see them... :)

**Comment by klonos** [comment]
Good catch @BWPanda. Thanx, fixed on your behalf. I cannot give you permissions though. Care to open a separate issue for that?

**Comment by BWPanda** [comment]
Sure, thanks @klonos!
