### ISSUE TITLE
How to add GitHub project to BackdropCMS.org?

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#239]
I've looked around but can't find instructions for this (maybe a good place would be https://backdropcms.org/develop/code). How do I add a GitHub project (e.g. https://github.com/backdrop-contrib/compact_forms) to BackdropCMS.org? Do I need to do something special to the GH project? Or does someone need to create a node on BD.org?

**Comment by biolithic** [comment]
Hi Peter, I was tripping on this as well.

Did you at https://github.com/backdrop-ops/contrib/issues/1

   - Establish yourself as the original author/owner by putting a by-line
   credit in the README.md
   - Add a LICENSE file (Github's default is just LICENSE with no .md or
   .txt extension) for GPL v2.


and were you accepted by quicksketch?  Good (or that's the next step).

Try to make a new release like
https://github.com/backdrop-contrib/mathjax/releases - for example, make
the version number 1.x-1.1.0
<https://github.com/backdrop-contrib/mathjax/tree/1.x-1.0.0>

and wait for BD to pick it up (maybe it's a daily cron run or something?)

**Comment by serundeputy** [comment]
@BWPanda you need 

`type = module` in your *.info file: https://github.com/backdrop-contrib/compact_forms/blob/1.x-1.x/compact_forms.info

then tag another release

**Comment by BWPanda** [comment]
@serundeputy Thanks!
