### ISSUE TITLE
Requesting editor permission

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#241]
As per #238 I'd like to request permission to edit nodes on backdropcms.org so that I can fix spelling mistakes, etc. as I come across them.

**Comment by klonos** [comment]
I do the very same thing and we could use a second pair of eyes. In fact, Similarly to #233, I would like to propose forming a team of "Website Curators" and have even more people on-board. It will improve QA of the flagship website and I believe that the team will be handy ...especially with the forum section that is being planned and all.

**Comment by jenlampton** [comment]
Approved. @BWPanda you are now an editor. Let me know if there is something somewhere you can't edit, we may need to adjust permissions as we go :)

**Comment by BWPanda** [comment]
Thanks! I promise to use my new powers for good ;)
