### ISSUE TITLE
Add post text to RSS feed

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#242]
Is it intentional that the RSS feed doesn't include anything other than a link to the post on BdCMS.org? It's kind of annoying not being able to read posts in my RSS reader...

Suggest adding the actual text of the post to the RSS feed.
https://backdropcms.org/news/rss.xml

**Comment by quicksketch** [comment]
Fixed, thanks @BWPanda! Let me know if any adjustments are necessary.

**Comment by BWPanda** [comment]
Looks good to me. Can't test properly until a new post arrives, but I'll let you know if there are issues. Thanks!
