### ISSUE TITLE
Add project usage statistics on their respective pages and on the front page for Backdrop CMS itself.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#243]
Put usage statistics on project pages and maybe also somewhere handy for Backdrop CMS itself

---
PR: https://github.com/backdrop-ops/backdropcms.org/pull/406 
  * merged

PR for PHP 5.4 fix: https://github.com/backdrop-ops/backdropcms.org/pull/411

**Comment by klonos** [comment]
For Backdrop CMS itself, I think that the front page is the place to have some stats shown. Here's what they have in the d.org front page:

![d org-front_page_stats_section](https://cloud.githubusercontent.com/assets/2423362/15410870/977924ba-1e5f-11e6-8c15-e6932cd4da01.png)

**Comment by klonos** [comment]
What other stats can we pull from GitHub real-time?

- GitHub project member count and contrib member count
- PRs and commit count per week
- Comment count per week
- Average time to squash reported bugs
- Project count + new project count last week
- New project *releases* count last week

Stats that we can get from the main site:

- Total user count + new registrations last week

**Comment by jenlampton** [comment]
> What other stats can we pull from GitHub real-time?

@Gormartsen would know best :)

**Comment by Gormartsen** [comment]
@klonos Some of this data need to be counted (like commits per week. we need to have counter and update it every time when new commit happen) but there is data to do so.

So all listed items are possible.

also we can have:
 - lines added deleted (total, per day, per week?, per user?)

Will post more ideas if it have it.

**Comment by klonos** [comment]
I think that this is all yours then @Gormartsen :wink:

**Comment by Gormartsen** [comment]
@klonos :D

**Comment by klonos** [comment]
https://backdropcms.org/project/usage/ is good for now I think. Can we link to that page from somewhere in the front page for starters?

**Comment by jenlampton** [comment]
We now have project usage and other handy things for every project in the right sidebar.  Thanks @serundeputy for making that happen!!! 

For the home page, I would like to roughly mirror what Drupal has and pull:
* total users w/ commits (count core + contrib)
* total commits (since Jan 15, 2015?)
* total comments (on all issues, core + contrib)

At some point we can switch to weekly counts like d.o does, but for the moment I think the totals are going to be more compelling to new users. They will help show that backdrop is (and has been!) an active community with lots going on :)

**Comment by serundeputy** [comment]
I took a look at this today:

>total users w/ commits (count core + contrib)

This is doable the trick is going to be to not double count users as many of us are contributors to multiple projects.

>total commits (since Jan 15, 2015?)

If this is just for core this is done; if we want core + contrib it is a lot harder as we have to have a starting commit hash from each project.  We could have a manual process where we store the desired starting commit per project either in the DB separate table or on the node as field, but that is significantly harder.

We also need to decide which particular commit to start counting from, for example, from this commit `b179787004a9e6faa1621079366176d6d0eabebe` (Feb 11, 2015) to today (27 August 2016) there have been `1124` commits, but I just picked that one as a test case.

>total comments (on all issues, core + contrib)

These are attainable; we need a counter and the data comes in paginated, so we need someway to determine the number of pages to sufficiently count and store the # of comments.

Anyone have thoughts/opinions/desires for implementation or data storage?  If we don't need the data exposed to views or anything like that its own table is simple or a flat file, but if there are ideas about this data beyond what is stated we may want it on the node.


thanks,
~Geoff

**Comment by klonos** [comment]
> At some point we can switch to weekly counts like d.o does, but for the moment I think the totals are going to be more compelling to new users. They will help show that backdrop is (and has been!) an active community with lots going on :)

That 👍 

How is https://backdropcms.org/project/usage/ generated by the way? ...not a view from AFAICT.

**Comment by jenlampton** [comment]
Provided by project usage module.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by klonos** [comment]
Thanx @jenlampton

**Comment by serundeputy** [comment]
@jenlampton @klonos if you are up for a review.

PR: https://github.com/backdrop-ops/backdropcms.org/pull/406

This adds:
* the top level metrics gathering for commits against core and comments against core and contrib
* adds block `backdorp_project_metrics`
  * The block needs to be placed somewhere

For some reason the comment count is increasing by 27 every cron run (when I believe it shouldn't be increasing at all).  I couldn't figure it out.  If someone can see why please let me know.

The users ... I didn't figure out any good way to collect users with commits in core and contrib ... I think ideally we would count users who comment on issues but don't have any commits as part of the users as the are helping the process and backdrop.  For now the number of users is hardcoded in the `borg_project_metrics_update_1002()`.  I think for now we should make a reasonable estimate and update the seed value accordingly.

Long term for users we need to at least kind of say in words who we wish to include then we can work on turning that into an algorithm.

Let me know if you have feedback.

**Comment by klonos** [comment]
@serundeputy I took a quick look and have comments/questions, but I'd rather discuss instead of "polluting" the PR (because some of my comments are newbie questions).

I'm also intrigued by the +27 increment of comments, but could not figure it out.

Not sure how much "workload" you get with your Backdrop office hours, but if you're you up to it, we can discuss the code then and you can help me learn.

**Comment by jenlampton** [comment]
Thanks for working on this @serundeputy it's a great start :) 

I don't see any obvious cause of the off-by-27 error, but there is some funny date handling that may (or may not) be related, which you are fixing now. 

The only other potential issue I can see is a namespace conflict with some of the internal helper functions. With a generic function name like `_get_metrics()` it could be that any other contrib or custom project has defined and is using that function name. We should put the name of this project in there to prevent possible conflicts (both now, and in the future).

**Comment by serundeputy** [comment]
@jenlampton updated the PR: https://github.com/backdrop-ops/backdropcms.org/pull/406/commits

* namespaces all functions
* fix the default date for polling github
* update seeds to initial data
* fix the off by 27 comments count error

I think this is ready to merge.

**Comment by jenlampton** [comment]
Looks great @serundeputy, merged!

**Comment by jenlampton** [comment]
Well, when deploying to production I got a PHP fatal:

```
Fatal error: Default value for parameters with a class type hint can only be NULL in borg_project_metrics/borg_project_metrics.module on line 136
```

**Comment by jenlampton** [comment]
committed a fix, pushed to production. Can we put the new block on the home page? :)

**Comment by serundeputy** [comment]
@jenlampton go ahead and place the block!

**Comment by serundeputy** [comment]
@jenlampton PR: https://github.com/backdrop-ops/backdropcms.org/pull/411
 * Removes all type hints from function definitions to be compatible with PHP 5.4

Once we merge this we should be able to place the block.

----
Fixes:
```
Recoverable fatal error: Argument 1 passed to borg_project_metrics_get_display_metric_from_db() must be an instance of string, string given, called in /app/www/modules/custom/borg_project_metrics/borg_project_metrics.module on line 255 and defined in borg_project_metrics_get_display_metric_from_db() (line 307 of /app/www/modules/custom/borg_project_metrics/borg_project_metrics.module).
```

I've switched to PHP 5.4 in my `.lando.yml` file; replicated the problem and addressed it by removing type hinting.

I'll file a separate PR for committing the PHP 5.4 change for `.lando.yml` for dev production parity.

**Comment by jenlampton** [comment]
Merged the latest PR, will deploy after the Outreach meeting :)

**Comment by serundeputy** [comment]
@jenlampton I've placed the block:
![screen shot 2017-07-13 at 5 03 58 pm](https://user-images.githubusercontent.com/6763671/28187622-545e3a34-67ed-11e7-83fe-e0d0ac907e21.png)

So, you'll need to commit that config, but sounds like that is a process you are used to.

**Comment by jenlampton** [comment]
pushed! :)

**Comment by jenlampton** [comment]
committed and pushed :)

**Comment by jenlampton** [comment]
<img width="1165" alt="screen shot 2017-07-13 at 6 04 21 pm" src="https://user-images.githubusercontent.com/397895/28193958-ba49eb92-67f5-11e7-9218-8c8c62d365e4.png">

I made a few changes:
* contributors instead of users
* Numbers largest -> smallest from L to R
* added users from backdropcms.org to user counts
* code is now php5.3 friendly
* style is now bootstrappy and responsive
* CSS is now in the components stylesheet

**Comment by serundeputy** [comment]
@jenlampton is there more to do here or should we close?

**Comment by jenlampton** [comment]
closing :)
