### ISSUE TITLE
Content: Start a discussion forum?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#249]
It will be important that the forums are helpful to people, and don't just become a place to get lost or a source of noise.  If we start a discussion forum as part of backdropcms.org, how to we want to have it organized?  Should we allow people to create their own forums, or curate a set to start with?

I recommend that we look at [WPs forums](https://wordpress.org/support/) as a model.  I think we should start with these:
- Installation – Problems with getting it running
- How-To and Troubleshooting – Once it's running
- Requests and Feedback – Feature requests; criticism.
- Custom and Contributed modules, themes & layouts – How to extend Backdrop CMS via the API
- Miscellaneous – Almost everything else about Backdrop CMS

**Comment by docwilmot** [comment]
I think module, theme and layout development should have its own forum. Its obviously very popular on both WP and Drupal.

I think requests and feedback should have its own too. I think a lot of the "wouldnt be cool if..."  questions aren't really issues and shouldnt be in the main queue until someone decides its doable. And we have a lot of those in the issue queue.

**Comment by jenlampton** [comment]
> I think module, theme and layout development should have its own forum

One forum, or three forums?

**Comment by docwilmot** [comment]
Was thinking one, considering our smallness, for now.

**Comment by jenlampton** [comment]
That sounds good to me.  How about one named "Contrib" :)

**Comment by jenlampton** [comment]
I've moved this issue over to the forum queue: https://github.com/backdrop-ops/forum.backdropcms.org/issues/6

I'll be closing this issue here, but please feel free to weigh in over there!
