### ISSUE TITLE
Fix font-awesome icons so size classes can be used.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#257]
As requested in https://github.com/backdrop-ops/backdropcms.org/issues/254 by @klonos for [Roadmap](https://backdropcms.org/roadmap)

![backdropcms org-roadmap-fontawesome_icons_added](https://cloud.githubusercontent.com/assets/2423362/15630635/e38b7fbe-2586-11e6-83d7-9d7ea8ae77c1.png)

**Comment by jenlampton** [comment]
@klonos I looked deeper into this and you are right about the icons. In the theme we have adjusted the size of icons in headings so that they are larger and have more space.  I've removed that and instead added the correct classes to the home page to make those icons larger.  (Please keep your eye out for other pages that might need classes added to account for icon sizing.) All should be well with font-awesome now, please let me know if you see anything else awry with them :)

**Comment by jenlampton** [comment]
think we're done: https://backdropcms.org/roadmap
closing this issue. Please reopen if you have more issues! :)

**Comment by klonos** [comment]
Thanx @jenlampton for taking the time to look into this. If I understand correctly, you did not add a `fa-half` class to the borg theme. Right? I still use inline `style="font-size: 1em;"` for the icons within the `<h2>`s in https://backdropcms.org/roadmap. Do you want me to remove those and use some of the fa classes or leave as is?

**Comment by jenlampton** [comment]
> you did not add a fa-half class to the borg theme

That is correct.

>  I still use inline style="font-size: 1em;" for the icons within the <h2>s

You shouldn't need to do that anymore. (I have already removed the font-size from the icons on the roadmap) because I also removed the CSS that made them too-large in the first place :)

For the icons that I wanted larger, I have now properly added the `fa-2x` classes as needed (and updated the font-aswesome version, so those are now available).

**Comment by klonos** [comment]
> No, you shouldn't need to do that anymore. ...

Thought so, but asked just to be sure. Removed those `style="font-size: 1em;"` from the roadmap page. I didn't have to use `fa-2x` because those are `<h2>`s while the front page has `<h4>`s.

Anyways, point is all done! Thanx 😉

**Comment by jenlampton** [comment]
*highfive*
