### ISSUE TITLE
Display user location on profile page

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#258]
This was requested by @klonos over in https://github.com/backdrop-ops/backdropcms.org/issues/251

**Comment by jenlampton** [comment]
I have added user location data into the sidebar (but only city/state/country, no address or zip)

**Comment by klonos** [comment]
Thanx @jenlampton 👍

**Comment by klonos** [comment]
...would be cool to be able to search for people nearby via some "Find backdrop users close to you".

**Comment by jenlampton** [comment]
Yes, that's the idea. It's in a ticket for service providers page :)
