### ISSUE TITLE
Possible solution for more than 10 people on our weekly dev meeting.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#260]
As you know, Google Hangouts limits us to only 10 people. Last time it was a full house, so I saw some people suggesting to jump out in order to make room for "more important" people. We shouldn't have to do that, so I searched a bit and I think there might be a workaround...

We might be able to use the screen sharing feature. So, we start a hangout and then share that hangout (with 10 slots) as a single slot in the main hangout. Not sure if the sound would stream through, but it should.

Anyone wants to help test this?

**Comment by Gormartsen** [comment]
> If you have a Google Business Account (or Gvt. or Education) you can have up to 15 people in the hangout.  

@quicksketch @jenlampton can you contact google representative and ask if we as a open source project legit for some Education account to run more than 10 people ?

**Comment by jenlampton** [comment]
Sure, can you find me a contact for a "google representative" ? :)

**Comment by Gormartsen** [comment]
@jenlampton maybe I said something not correct by not knowing details. Maybe you already tried to contact support to get 15 slots for free. 
Pardon for that.
I just found an information that it is possible to have 15 with educational or work account,

**Comment by jenlampton** [comment]
We haven't tried. Would you please provide a link or support. Contact info?

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by Gormartsen** [comment]
https://apps.google.com/intx/en/contact-form/

Regards,
Gor Martsen
@gormartsen

**Comment by thejimbirch** [comment]
https://zoom.us/pricing is a quality solution.

Free plan offers 40 minute meeting, up to 50 users.
Pro plan is 15$ a month and gets rid of the time limit.

**Comment by jenlampton** [comment]
We use zoom for BADCamp planning, it's pretty good as far as the service goes, but you have to install an app. I'm not sure they have one for linux?

**Comment by jenlampton** [comment]
the real win with google hangouts is the livestream + instant post to youtube.

**Comment by klonos** [comment]
> the real win with google hangouts is the livestream + instant post to youtube.

I was about to ask if zoom supported that.

**Comment by thejimbirch** [comment]
You can record the meeting, but you would have to upload it to the youtubes manually.

**Comment by BWPanda** [comment]
Closing. We're now using Zoom with (I believe) a paid account, so no limit issues anymore.
