### ISSUE TITLE
Require module help

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#27]
Not sure if this is where this should go, but thought I should mention this after hunting help on a Drupal module recenlty. BD should require help of some kind. Drupal has a variety of methods of informing the end user but it is inconsistent and not required. So you might run into a readme.txt file, install.txt file, documentation on site, documentation on a custom site, Drupal help, Advanced. Help, or if youre unlucky, nothing at all and get to Googling.
We should *require* one of the above for contrib modules.

**Comment by quicksketch** [comment]
I think our new standards for requiring a README.md will help with this situation, combined with a sample that at least gets people heading in the right direction: https://github.com/backdrop-ops/contrib

Actually *requiring* (technically) information is a bit of a different thing, but for now policy may be the best tool we have. If you have any ideas on something more that we could do here, please reopen. Thanks!
