### ISSUE TITLE
Contribution Policies and Procedures need some care

### ISSUE THREAD

**Issue by kkomelin** [backdrop-ops/backdropcms.org#277]
Hi there, 

I'd like to ask if you have any procedure for accepting PRs for contrib projects. I mean some reasonable "time to process". I'd like to know how much time the maintainers need to consider my simple PR backdrop-contrib/socialfield#14 
If you do not have any formal rules regarding that, maybe it is time to create them.

P.S. You may port hundreds of projects relatively quickly but their support is much more expensive process.

Thanks.

**Comment by kkomelin** [comment]
@Gormartsen Please add your 5c here

**Comment by Gormartsen** [comment]
moved to https://github.com/backdrop-ops/contrib/issues/169
