### ISSUE TITLE
Broken link in the latest article about the Twin Cities Drupal Camp.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#278]
The "*issue in the Backdrop queue*" link in the paragraph before the last has a `#BackdropCMS` href. If I knew to which issue you are referring @jenlampton, I'd correct this myself.

**Comment by klonos** [comment]
...PS: the fact that I'm reading that article only now (Sunday midnight in AU) should give an indication of my lack of time.

**Comment by klonos** [comment]
...PPS: I've updated that article's title to include "Drupal Camp" in it ...for obvious SEO reasons 😉

**Comment by jenlampton** [comment]
> The "issue in the Backdrop queue" link in the paragraph before the last has a #BackdropCMS href.

It's https://github.com/backdrop/backdrop-issues/issues/2024, updated now :)

> ...PPS: I've updated that article's title to include "Drupal Camp" in it ...for obvious SEO reasons 😉

Good thought! I've changed it from "IN the Twin Cities" to "AT the Twin Cities Drupal Camp" for grammar reasons ;)

**Comment by jenlampton** [comment]
also, thank you @klonos :) for all you do for us in your extremely limited time available :)  Appreciate it so much <3

**Comment by klonos** [comment]
> I've changed it from "IN the Twin Cities" to "AT the Twin Cities Drupal Camp" for grammar reasons ;)

Yeah, as you already know, English is my second language, so it's like 80%. Thus, rookie errors like this might happen from time to time. Now add sleep deprivation and rush due to lack of time on top of that and you have me 😄 😞 

Let me return the thank you in kind for all the time and energy you put in Backdrop. I greatly appreciate that too.
