### ISSUE TITLE
News page (view) shows only 10 items.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#279]
I think we need to show all news with a pager. I've updated the specific display of the view, but have not saved changes (pending approval, @jenlampton??). I have used newest/newer/older/oldest for the labels of the first/previous/next/last pager links. If not appropriate, feel free to change.

**Comment by jenlampton** [comment]
Agree about the pager, thanks @klonos. I'm not sure the pager link name change was necesary as we don't have pager link names on borg: https://backdropcms.org/news

**Comment by jenlampton** [comment]
Marking as fixed :)

**Comment by klonos** [comment]
Thanx 👍
