### ISSUE TITLE
Weekly meeting videos

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#28]
Thought I'd make a suggestion regarding the weekly meeting videos: make a video specifically for introducing new users to Backdrop (basically what Jen says during the first few minutes of each weekly meeting video) and point new users to this rather than giving the same intro spiel each week. This'll make it nicer for regular viewers (like myself) who currently hear the same first few minutes each time, and will also provide a video you can post to BackdropCMS.org.

**Comment by BWPanda** [comment]
Another issue that has been bugging me for a while, but that was most obvious in the first 10-15 minutes of the '[Backdrop weekly 1/8](https://www.youtube.com/watch?v=jcZfTVm2usI)' video is the fact that other participants in the meeting leave their microphones on. This can not only cause unwanted background noise, but also makes the video switch to their webcam (it assumes that they're talking) which is distracting to say the least.

I request asking participants to turn off their microphones when they're not actively participating to make these great videos more professional and less distracting.

**Comment by BWPanda** [comment]
Also, where are the agenda documents kept? Sometimes you mention in the video that you'll add a link to something in the agenda, but it's not linked from the video page...

Is there a page where all agendas are listed publicly?

**Comment by jenlampton** [comment]
@BWPanda good idea!  I'll add a note to the top of the agenda so I don't forget to ask next week :)

Agenda documents are all kept in the "BackdropCMS" / "Agendas" public folder on google docs:
https://drive.google.com/a/jeneration.com/folderview?id=0B_lmQRaaidbnTnY4RUtBQzVxY3M&usp=sharing

We should start adding them to the videos too.  I think I managed to remember that once.

**Comment by BWPanda** [comment]
Thanks for the Agendas link. Can I add another request? Can you name/rename the agendas to start with the date in reverse order? E.g. '2015/01/08 - Backdrop Weekly'. This'll allow them to be ordered correctly and make it easier to find a specific one (latest ones will always be at the bottom). Also, adding the year helps as they span two years currently. Alternatively you could create sub-folders for past years (e.g. '2014').

**Comment by jenlampton** [comment]
Funny, they do appear in alpha order on the folder view.  Usually they are listed by recently-edited date which puts the new ones at the top....  trying something.

**Comment by jenlampton** [comment]
Okay, I updated all the 2015 documents (so they are at least above the 2014 documents) and all their titles start with 2015/01/*.  Hopefully this will buy us a year and google will figure out sort order by 2016!

**Comment by BWPanda** [comment]
Just a reminder to ask participants to mute their microphones, otherwise this happens: http://youtu.be/KzxN_dpHHMg?t=3m40s

**Comment by quicksketch** [comment]
Thanks @BWPanda, I'm usually on muting duty during calls, but I wasn't around for that one. :frowning: 

I think we're good here, now that we've made an official release and the homepage lists exactly what Backdrop is, we've started skipping the little intro at the start of each video.
