### ISSUE TITLE
Create a place (repository?, google docs?) to store various procedure documents and create a pre- and post-release tasks list.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#280]
In the previous dev meeting, I asked whether we have a centralized place to store and have available documents that list the steps required for things like for example creating a minor release of core. In this specific example for instance, besides the actual code commits and tagging the release, there's other tasks that do not necessarily involve core committers. These include things like creating a project release node to be published in the news section, publishing that release announcement along with the release, updating the documentation and perhaps also creating one or more product feature node (??) etc.

Other examples of  procedures that should be documented are the steps on how to host a google hangout meeting, the sources where one can find the community growth stats and how to update them on the weekly dev agenda etc.

I think that we should start creating such documents so that we don't have single points of failure should the people responsible for doing those tasks are unavailable for any reason. Should we have these as google docs or perhaps start a GitHub repo (like `backdrop-ops/procedures`) and have separate .md files there for each task?

**Comment by klonos** [comment]
From https://github.com/kalabox/kalabox/issues/1595#issuecomment-248985426 by @jenlampton

> @pirog yes, I agreed to keep our docker image up to date. I just forgot! Sorry about that, ...

@jenlampton that's why we should have these procedures in place. We should be helping each other with these sorts of tasks so that they don't all fall onto a single person's plate. We need to take some load off of you and @quicksketch

**Comment by jenlampton** [comment]
yes yes and https://github.com/backdrop-ops/procedures
