### ISSUE TITLE
specify font used for the "backdrop" word in presskit

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#289]
-  We had no easy way for site visitors to get to the press kit node, so I edited the node and added it to the Handbook menu. That did not do the trick though for some reason and going to `/admin/structure/menu/manage/menu-handbook` I see that it is not listed there (@jenlampton ??).
- Also, would be helpful to tell people what font we use for the "backdrop" word (@dariusgarza ??) .

**Comment by klonos** [comment]
...or is it perhaps that the "Backdrop CMS Handbook" book is what's rendered in the navigation drawer?

**Comment by klonos** [comment]
I have the "Editor" and "Administrator" roles assigned to me and both these roles have the "Create new books" permission, but I see no "+ Add book" link available in `/admin/content/book` ??

**Comment by jenlampton** [comment]
> I see no "+ Add book" link available

New books are created by adding book pages, in the vertical tab for book you just add a new one.  I'm not sure you can add a book w/o a book page or I would recommend adding an action link there too.

**Comment by jenlampton** [comment]
> We had no easy way for site visitors to get to the press kit node

There's a link in the footer, on every page. 

The press kit isn't a handbook page (it's not something you need people to read when they want to learn "everything" about backdrop). The press kit is intended for press, or people looking specifically for assets.

**Comment by jenlampton** [comment]
> Also, would be helpful to tell people what font we use for the "backdrop" word

The font used in the wordmark is similar to the Source Sans Pro font, but it's not actually using it. @dariusgarza spent a lot of time adjusting the positioning of each letter specifically for our logo. If people want to use Source Sans Pro they will get something that's 'close enough' but not quite as pretty ;)

(feel free to update the presskit node with this info, too!)

**Comment by BWPanda** [comment]
I added a note to the presskit page regarding the font, so closing this issue now.
