### ISSUE TITLE
Support page glitches

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/backdropcms.org#290]
1. ~~Spelling mistake: "excange ideas" under "Coming soon: Forum"~~
2. Alignment is wonky on the books and their titles:
   <img width="527" alt="screen shot 2016-08-25 at 10 00 20 pm" src="https://cloud.githubusercontent.com/assets/871421/17992706/5c0c119c-6b0f-11e6-827a-9b7755cf3754.png">

**Comment by jenlampton** [comment]
Thanks for the feedback @laryn I've fixed he spelling/typo issue,but can't see the alignment problem. Are you still seeing it? https://backdropcms.org/support

If so, which browser, and at about what screen size?

**Comment by olafgrabienski** [comment]
The alignment issue happens above 414px and below 1024px screen width (Chrome on Mac OS).

**Comment by Dinornis** [comment]
I see this in other browsers also.  A quick fix would be to add `<br />` after the title of the first book.  A better long term solution would be to take advantage of CAPTION for images.

**Comment by olafgrabienski** [comment]
Another quick fix:

- add `display: block;` to the links which surround the book covers
- optional: remove `text-align: center;` from `.backdrop-books`

**Comment by BWPanda** [comment]
Alignment issue appears to have since been fixed (I can't see it in any screen size). Closing then.
