### ISSUE TITLE
Make the admin bar sticky on top of page?

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#291]
Previously, (part of) the backdrop logo on the top-left corner of the website used to be hidden behind the admin bar. Sometime during the past week or two, someone must have added the `top: 33px` fix for that, but since the admin bar is not set to be sticky at the top of the page, when one scrolls down, they get this:

![backdropcms org-admin_bar-top_33px_gap_when_not_sticky](https://cloud.githubusercontent.com/assets/2423362/18220403/ee3b9334-71b4-11e6-83ba-751bfc761859.png)

Permission to enable the "Keep bar at top of page" setting please? (`/admin/config/administration/admin-bar`)

**Comment by klonos** [comment]
...If people do not like that setting. Then I'll file a core issue to convert the admin bar settings to be per-user instead of having them be applied globally for all users that have the admin role.

**Comment by BWPanda** [comment]
I have this setting enabled on all my Backdrop sites, and it annoys me that it's not set when I work on B.org and friends.

Here's a PR: https://github.com/backdrop-ops/backdropcms.org/pull/683
