### ISSUE TITLE
[UX] Reaching the navigation menu requires A LOT of scrolling on mobile.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#292]
This is part of #197 ...

Here's an overview:

![backdropcms org-navigation_menu_pushed_way_down_on_mobile](https://cloud.githubusercontent.com/assets/2423362/18221596/5d0c2798-71c3-11e6-866b-b8cbd9ad499d.png)

**Comment by klonos** [comment]
I think that a solution like [Responsive Menus](https://backdropcms.org/project/responsive_menus) or [Mobile Navigation](https://backdropcms.org/project/mobile_navigation) is in order.

**Comment by serundeputy** [comment]
I think this is moot now; closing reopen if necessary.

**Comment by klonos** [comment]
Yep, moot.
