### ISSUE TITLE
Allow more than one tag on blog posts.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#294]
I was trying to write a blog post (@jenlampton, you must be smirking now), and added a few tags separating them by commas. When trying to save the node, an error told me that I can only use a single tag (the task part of this issue is to allow more)

...so I edited my tags and removed the commas. When trying to save the blog post, I got a blank page with this scary error (the bug part of this issue):

EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x84 Y...' for column 'body_value' at row 1 in NodeStorageController->save() (line 304 of /home/backdrop/repo/www/core/modules/node/node.entity.inc).

**Comment by klonos** [comment]
...my post was not saved 😞 ...but that was a copy-paste from a GitHub queue I was typing it before I decided to make it a blog post 😥

**Comment by klonos** [comment]
@jenlampton did you just change the tags field to checkboxes instead of autocomplete? 👍

**Comment by jenlampton** [comment]
yes, I am trying to make it not throw scary errors because it was a BAD WEBSITE.

**Comment by klonos** [comment]
Thanx 👍 😄

**Comment by jenlampton** [comment]
How many tags do you want, is 3 enough?

**Comment by jenlampton** [comment]
I need to fix the CSS. It assumed one tag :/

**Comment by klonos** [comment]
> How many tags do you want, is 3 enough?

Changed that to 5 myself 😉

**Comment by jenlampton** [comment]
👍  CSS time!

**Comment by klonos** [comment]
The bug seems to be caused by the text I'm copy-pasting though and most likely a core/CKeditor/filter one.

**Comment by klonos** [comment]
...will open a separate issue and provide the full text that causes it. Will try to narrow this down. Suspecting GitHub markup. We'll see...

**Comment by klonos** [comment]
Yes, it's the text. Will try to test it on my local...

**Comment by klonos** [comment]
...it's the bloody emojis 😠

**Comment by jenlampton** [comment]
that PR isn't in until 1.5!!!

**Comment by klonos** [comment]
...yeah, I know, but I thought that the issue was simply not supporting rendering them - not crashing the system. That makes it a bug fix and not a feature request.

**Comment by jenlampton** [comment]
Well, tags: https://backdropcms.org/news/introducing-kalabox-warpspeed-backdrop-development

**Comment by jenlampton** [comment]
:D

**Comment by klonos** [comment]
https://backdropcms.org/news/creating-pull-requests-against-core-easy-noob-way 😉

**Comment by jenlampton** [comment]
!!!! :) :) :) :) !!!!
Is it okay to edit for grammar?

**Comment by klonos** [comment]
Yes, of course 😄 

...it's not perfect, but @olafgrabienski could use even the draft (without screenshots etc). Go ahead and publish it when you feel like it's ready-ish.

**Comment by jenlampton** [comment]
this is going to be so useful!!!! :)

**Comment by jenlampton** [comment]
this is going to be so useful!!!! :)

I made only maybe 3 grammar changes. But I think we should add a step about creating a Fork of the project, since you can't create a PR until after that. Otherwise, it's ready for you to publish once you get the links in place. Looking good!

**Comment by klonos** [comment]
> But I think we should add a step about creating a Fork of the project, since you can't create a PR until after that.

GitHub does that for me *while* (or as part of) creating the PR. Perhaps because I am a member of the backdrop group?

**Comment by klonos** [comment]
...or perhaps because I had already made a fork of the project. Hmm.

**Comment by jenlampton** [comment]
> GitHub does that for me while (or as part of) creating the PR. Perhaps because I am a member of the backdrop group?

No, I don't think so. You only need one fork ever, so I expect you pushed the fork button previously.
