### ISSUE TITLE
Implement Server Monitoring

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#30]
Implement Munin to monitor sites, servers and other infrastructure.

**Comment by quicksketch** [comment]
> Which server should I install it on?

Let's put the ci.backdropcms.org server.

**Comment by larsdesigns** [comment]
Okay, will do.

**Comment by larsdesigns** [comment]
@quicksketch Please add my ssh key to ci.backdropcms.org. I am ready to install Munin after configuring and testing it on a CentOS 6.2 VM.

**Comment by quicksketch** [comment]
Hi @larsdesigns! Sorry for the delay. You've been added to ci.backdropcms.org.

**Comment by larsdesigns** [comment]
Awesome, thanks. I am swamped tonight but can implement it this weekend.

**Comment by larsdesigns** [comment]
I am working on installing munin now. I will be updating the OS and installing Munin, nginx, mysql etc. 

I will also configure iptables which is not done yet.

@quicksketch should we create a subdomain for Munin or just use host file entries?

**Comment by quicksketch** [comment]
Super, thanks @larsdesigns. I think a subdomain is appropriate. Maybe just munin.backdropcms.org?

**Comment by larsdesigns** [comment]
Sounds good to me. If you create the A record, I will configure nginx.

**Comment by quicksketch** [comment]
Cool, it should be set up now. http://munin.backdropcms.org/ obviously nginx needs to be set up to actually handle requests.

**Comment by larsdesigns** [comment]
Completed the following tasks: 

For ci.backdropcms.org: 

1. Upgraded over 200 yum packages and restarted the VM. 
2. Installed and configured nginx using yum. 
3. Installed and configure munin and munin-node 
4. installed the munin basic munin monitoring plugins. 
5. Installed the nginx monitoring plugins. 
6. Configured the nginx to server munin web interface at: http://munin.backdropcms.org
7. Installed and configured IPtables with web server rules and custom rules for Munin port 4949. 
8. Configured password protections to access the Munin web interface. 
9. Configured Munin to e-mail @sirkitree, @quicksketch and @larsdesigns monitoring notifications. 
10. Configured Munin to monitor ci.backdropcms.org and backdropcms.org. 

For backdropcms.org
1. Installed pending yum package updates. 
2. Installed Munin node remote client. 
3. installed the nginx Munin monitoring plugin. 
4. Added IPtables firewall rules so that Munin node can be connected to by ci.backdropcms.org. 
5. Configured Munin so that only ci.backdropcms.org can connect to the munin-node daemon. 

I will sending out the credentials to Munin web interface. 

Recommendations: 
1. Install and configure the MySQL plugin. Requires creating a MySQL user for Munin.
2. Install and configure the Memcached plugin.
3. Create Munin git repositories to store configuration. 
4. Configure monitoring of other servers that may exist that I am not aware of.
5. Configure HA local IP addresses for the VMs and configure Munin to use them. This will decrease network expense. 

I think we are off to a good start.

**Comment by larsdesigns** [comment]
Also, I think we should setup the Munin web interface to use https.

**Comment by quicksketch** [comment]
Sounds great! All good ideas. I logged into Munin and looks like it's reporting properly for the main server and the ci.* server.

**Comment by sirkitree** [comment]
http://munin.backdropcms.org is not currently operational. Is this something that was discarded, or did it perhaps go down? Do we need something to alert us when our alerts go down? :wink: 

It's been a while since I've logged into the server so just trying to catch back up a bit.

**Comment by quicksketch** [comment]
My guess is that Munin is still there but didn't restart properly after the most recent Linode maintenance.

**Comment by larsdesigns** [comment]
Ha, I can add an alert to my larsdesigns.net Nagios monitoring to tell me when Munin goes down.

**Comment by larsdesigns** [comment]
I brought Munin back online.

**Comment by larsdesigns** [comment]
Looks like munin-node was running. Nginx did not start up. I added nginx to chkconfig so that it starts on boot.

**Comment by larsdesigns** [comment]
Awe, postfix did not start up either. Which explains why the e-mail notices did not go out. I added it to chkconfig also so it will start on boot.

**Comment by sirkitree** [comment]
@larsdesigns++

**Comment by sirkitree** [comment]
Is there a good place to document all of this?

**Comment by larsdesigns** [comment]
We should probably start a wiki or documentation page for infrastructure. I am not sure where that would be but I am happy to author the content.

**Comment by sirkitree** [comment]
Yeah, there are a couple of other things like this that we should document - like some of the automated processes... I'll open a new issue to discuss.

**Comment by larsdesigns** [comment]
Also performed last night: 
1. Installed SSL certificate for munin.backdropcms.org.
2. Created redirect for the http to https in nginx config for munin.backdropcms.org
3. Scanned backdropcms.org for broken links and other HREFs using linkchecker from my server and posted the results. https://gist.github.com/larsdesigns/1af2d3f59e5bd0b42f55 and https://gist.github.com/larsdesigns/5cb4fcba04ea00c04e2a
4. Bothered @quicksketch with silly stuff.
