### ISSUE TITLE
[META] Random test failures.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#300]
I thought we had an issue for these, but can't find it now. So lets make a list...

- [ ] `Locale: Translation import (LocaleImportFunctionalTest) 138 passes, 1 fail, 0 exceptions, and 44 debug messages`

  ```
  ---- Locale: Translation import (LocaleImportFunctionalTest) ----
  Status Group Filename Line Function
  --------------------------------------------------------------------------------
  Fail      Other      locale.test        873 LocaleImportFunctionalTest->testAut
  Language file automatically imported.
  ```

  Example PRs where it occurs:
  - https://github.com/backdrop/backdrop/pull/1585
  - https://github.com/backdrop/backdrop/pull/1588

- [ ] `Image: Image style flood protection (ImageStyleFloodProtection) 10 passes, 1 fail, and 0 exceptions`

  ```
  ---- Image: Image style flood protection (ImageStyleFloodProtection) ----
  Status Group Filename Line Function
  --------------------------------------------------------------------------------
  Fail      Other      image.test        1690 ImageStyleFloodProtection->testFloo
  Correct number of images (1) return 403 access denied.
  ```

  Example PRs where it occurs:
  - https://github.com/backdrop/backdrop/pull/1589

**Comment by jenlampton** [comment]
Why is this  in the backdropcms.org queue, and not part of https://github.com/backdrop/backdrop-issues/issues/1478?  I think it is a dupe (but please reopen if not).
