### ISSUE TITLE
Some formatting lost on 'No results found' search page

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#302]
When searching for a module and no results come up, some formatting is lost and the page looks slightly different. Not a big deal by any means, but a bit off-putting to a consistency freak like me :wink: 

![firefox_screenshot_2016-10-11t00-19-53 825z](https://cloud.githubusercontent.com/assets/2385329/19254930/b5729792-8fa4-11e6-9e9c-b73cb39d4323.png)

![firefox_screenshot_2016-10-11t00-20-13 442z](https://cloud.githubusercontent.com/assets/2385329/19254931/b573f182-8fa4-11e6-8b2e-cec2d574e783.png)

**Comment by BWPanda** [comment]
To summarise the differences:

- The text `Modules can add to the set of available features on your site, or change the way existing features work.` disappears.
- The light grey background from the search results section disappears.
- The left and right margins disappear (so the `No results found.` text is displayed on the far left).

**Comment by BWPanda** [comment]
You still want to work on this @jenlampton or can I take a stab?

**Comment by jenlampton** [comment]
Go ahead! and thank you :)

**Comment by BWPanda** [comment]
Nevermind, this appears to have been fixed already :smile:
