### ISSUE TITLE
Change the "Name" exposed filter in the user management view so that it searches in both username and full name.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#306]
@klonos at https://github.com/backdrop/backdrop-issues/issues/2302#issuecomment-255508988

> PS: sorry for making the change without filing a proper issue under the borg issue queue @jenlampton. What is the roper way to propose changes for the website? Do we create PRs? If so, how do we do that for views? Do we export the view after we make the changes and provide a diff?

@jenlampton over at https://github.com/backdrop/backdrop-issues/issues/2302#issuecomment-255864372

> ...yes @klonos your change there was a good one. (No need for a PR since it was just a config change, just open an issue in the queue letting us know it was done so we can commit the config to git.)

Thanx Jen. Here's the issue 😉

**Comment by jenlampton** [comment]
committed and pushed. ty!
