### ISSUE TITLE
Webiste missing documentation on files directory

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#311]
This was originally filed as #2328 by @oadaeh  in backdrop/backdrop-issues ... moving here for discussion and implementation.

>I'm not sure if this is the right place for this or not, but here is where I'm leaving it. It seems to me that I recall that a long time ago there used to be a specific issue queue for the backdropcms.org website, but I cannot find it now, so maybe it went away.

>When installing a new site and w/o preparing settings.php and files, the following is displayed:

>File system
The directory files is not writable. To proceed with installation, you must modify the permissions of this directory to make it writable by the web server. If you are unsure how to do this, please see the Installation Instructions page.
"Installation Instructions" is a link to https://backdropcms.org/installation

>When going to that page, there is nothing there that discusses the files directory.

>There is a bit of a disconnect between the site install and the instructions it references.

**Comment by serundeputy** [comment]
Thanks @oadaeh This is a fair ask.  Tagging the documentation gurus @docwilmot @tomgrandy @jenlampton @klonos 

Question becomes wording.  What do we say about the files directory?

things we have to say:

  * it has to be writable by the webserver user (Ubuntu: `www-data`, Centos: `apache`, Mac: `_www`) even so that is just the usual webserver user (not a gaurantee).

Here is the Drupal 7 documentation on the files directory: https://www.drupal.org/docs/7/install/setting-up-the-files-directory They have a multipage documentation with nav to and comprehensive docs on DB, files dir, etc.

Looks like we are using a more streamlined sort of quick start guide (https://backdropcms.org/installation).  So, I'd propose that we add a `files` dir step perhaps before or after **3. Update Backdrop's settings.php file** step with a link to a deep dive on more comprehensive documentation on the intricacies of permissions, users, groups, owners etc.

Here is a first pass at some language:

**4. Set the permissions/ownership on the files directory**
  * The `files` directory in the Backdrop root must be writable by the webserver.
  * If the user that logs (ssh or ftp) into the server is `my-user` and the webserver user is `www-data` then sensible ownership and permissions for the files directory could be:

```
drwxrwx---   13 my-user www-data   442B Nov  5 18:38 files
```

 * You can achieve this configuration either in your FTP client or on the command line with commands like this: `chown my-user:www-data` && chmod 770 files`
  * you may need `sudo` depending on who owns the directory currently

@jenlampton usually has good suggestions about pairing down such language and  getting to speak directly to the people who need it.

Thoughts revisions needed and welcome, but let's get something up on backdropcms.org/installation sooner than later.


thanks,
~Geoff

**Comment by oadaeh** [comment]
Thanks @serundeputy. I thought there would be an easier way to relocate the issue, but I guess not.
I also wanted to add to this to not forget about https://github.com/backdrop/backdrop-issues/issues/1853 when documenting.

**Comment by tomgrandy** [comment]
Better never than late, eh?

I have added the proposed 4th step from @serundeputy above to the Installation Instructions since it looked perfectly fine to me.  Sorry I missed this but am still learning how to navigate around GitHub.  Getting better, though.

If anyone wants to rewrite or correct, feel free but it is out in the wild and available via:

https://backdropcms.org/installation
