### ISSUE TITLE
Get rid of the "Handbook" with the new design

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#312]
The handbook was probably a simple version of "Support" when BackdropCMS.org was yet young. I would like to think we've grown up a little bit, and I feel the concept clashes now with broader "Support" and "Documents" categories. The duplication is inefficient.

- "About Backdrop" should get its own home
- "Add-Ons" is actually information about add-ons rather than a place to find add-ons, so this should now be part of the new docs
- "Developer Guide" should be in the developer docs.

**Comment by jenlampton** [comment]
> "Developer Guide" should be in the developer docs.

The developer docs are on a different website (api.backdropcms.org) so we need to be careful that we are not putting those docs out of reach for those who need them. But bravo to all other suggestions 👍

**Comment by tomgrandy** [comment]
How about:

ABOUT
-- Philosophy
-- Community
-- Leadership
-- Release Cycle
-- Roadmap
-- License

ADD-ONS
-- Modules
-- Themes
-- Layouts

SUPPORT
-- User Guide
-- Developer Guide
-- Ways to Contribute
-- Forum
-- Resources

NEWS
-- Backdrop Blog
-- Weekly Meeting
-- Upcoming Events

**Comment by docwilmot** [comment]
Works for me!

**Comment by jenlampton** [comment]
Looking great.  Also we'll need to add our current `Service Providers` page under Support too.

**Comment by tomgrandy** [comment]
Awesome!  @wesruv can you adjust the menus accordingly?  If it is something I can help with, just let me know.  Not sure if the new site is in dev yet or not.

Thanks @jenlampton !

**ABOUT**
-- Philosophy
-- Community
-- Leadership
-- Release Cycle
-- Roadmap
-- License

**ADD-ONS**
-- Modules
-- Themes
-- Layouts

**SUPPORT**
-- User Guide
-- Developer Guide
-- Service Providers
-- Ways to Contribute
-- Forum
-- Resources

NEWS
-- Backdrop Blog
-- Weekly Meeting
-- Upcoming Events

**Comment by jenlampton** [comment]
We've removed the handbook, so I;m going to close this issue. Ongoing menu chnages are documented at https://github.com/backdrop-ops/backdropcms.org/issues/313
