### ISSUE TITLE
Try Out Backdrop Page

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#314]
Spun off from #301, would like this to be linked from the homepage to have a few of the *easiest* ways to get Backdrop up and running and links to more custom tutorials (e.g. setting up on a Ubuntu Server w/ LAMP via CLI... or whatever)

![image](https://cloud.githubusercontent.com/assets/5607236/20404497/3090e4ce-acd3-11e6-8237-1ff514afbadb.png)

Was thinking the screenshots in the monitors could rotate to show snapshots of the different steps, could be as part of an interaction (pressing/hovering on a step) or just slow rotation. There's a chance that could be too much, but thought it could be cool. Could also just be a GIF.

----
PR: https://github.com/backdrop-ops/backdropcms.org/pull/434

**Comment by serundeputy** [comment]
I've created the unpublised node page here: https://backdropcms.org/try-out-backdrop-cms
PR: https://github.com/backdrop-ops/backdropcms.org/pull/434

The PR has the needed CSS.

**Comment by serundeputy** [comment]
Here is a screenshot of what it looks like with css:
<img width="1702" alt="screen shot 2017-12-03 at 6 16 27 pm" src="https://user-images.githubusercontent.com/6763671/33531085-7a90e18c-d856-11e7-9fe0-20fec73a5460.png">

**Comment by jenlampton** [comment]
The CSS here will need some re-working to be compatible with the more recent changes I made to the borg theme (style sheets that will only be loaded on a single page should begin with `page-` in the filename, for example).

I'm also concerned about all the HTML in node/1591. If we need to add this much markup for layout purposes, this should really be a layout, and not a node. Come to think of it, this page should probably be a layout with a view on it, so we can easily add more ways to try out backdrop and have them appear here, formatted nicely.

Let me see if  I can think up a simple architecure that makes sense... if not ,we'll go with a layout containing custom blocks. I am going to steal all your content though @serundeputy :)

**Comment by jenlampton** [comment]
Hows this? https://backdropcms.org/try-backdrop

**Comment by serundeputy** [comment]
looks great!

**Comment by jenlampton** [comment]
Woot!  Thanks @wesruv for the original design, and @serundeputy  for the original content!  Closing this issue.
