### ISSUE TITLE
/download has incorrect links to Documentation and Issue Queue.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#317]
In the right sidebar under the heading `GitHub`:

* `Issue Queue` links to https://github.com/backdrop/backdrop/issues. I think it should be: https://github.com/backdrop/backdrop-issues/issues

* `Documentation` links to https://github.com/backdrop/backdrop/wiki. This should probably link to our new user-guide: https://backdropcms.org/user-guide or to https://api.backdropcms.org

----

PR: https://github.com/backdrop-ops/backdropcms.org/pull/318

**Comment by serundeputy** [comment]
@jenlampton ^ just giving you a ping as to the existence of this `PR` :)

**Comment by jenlampton** [comment]
TY!  Merged :)

**Comment by jenlampton** [comment]
Reverted - PR needs work, it currently breaks all links for all contrib project wikis + documentation pages. I think we may want to do a theme override in the borg theme that checks the project and changes the links only when the project is backdrop itself.

**Comment by jenlampton** [comment]
Like this https://github.com/backdrop-ops/backdropcms.org/pull/320 :)

**Comment by jenlampton** [comment]
Deployed: https://backdropcms.org/download and other project pages are still correct: https://backdropcms.org/project/rules
