### ISSUE TITLE
No Search on backdropcms.org?

### ISSUE THREAD

**Issue by Dinornis** [backdrop-ops/backdropcms.org#321]
Is there a reason not to have global search or at least the User Guide and Handbook searchable?

Right now it looks like only the Backdrop CMS API Documentation is **somewhat** searchable.

Example:
I was looking for information RE: Date Repeat functionality and had to resort to DuckDuckGo in order to find this: https://api.backdropcms.org/node/43066

This is the type of issue that gives D.org a bad name and not following that path could make a huge difference when attracting new people to Backdrop. Same goes for Forums or the lack thereof.

**Comment by klonos** [comment]
Hello again @Dinornis we have an issue for this already: #193. I guess that the reason why we haven't done anything about it yet is that we are currently working on redesigning the entire site, moving away from the old theme with the drawer on the left side: #301. The new design includes a global search:

![](https://cloud.githubusercontent.com/assets/5607236/21488465/0779bd14-cbae-11e6-9f32-020ff590647f.png)

**Comment by klonos** [comment]
...we also have an issue about starting a forum on backdropcms.org: #250 ...as I told you previously, we have a lot of plans and many tasks on our todo list, but we are a very small community still with not enough "hands on deck". We're getting there though 😄

**Comment by Dinornis** [comment]
Thank you for the links klonos, it is good to know this is on the radar.

Should I open a separate issue for the Backdrop CMS API Documentation search problem?  I don't think https://github.com/backdrop-ops/backdropcms.org/issues/193 will solve that as it covers only the site design.

**Comment by klonos** [comment]
Yep, the global search will be searching only on b.org - not api.b.org. What was the issue with searching in the API site again? Because [searching for "date repeat"](https://api.backdropcms.org/search/node/date repeat) brings the [Date, Date Popup, and Date Views modules now included in Core](https://api.backdropcms.org/node/43066) change notice as the first result for me.

**Comment by Dinornis** [comment]
You are correct, my fault, I typed in date_repeat.
