### ISSUE TITLE
Chess, anyone..? The Vchess module needs maintainer(s)...

### ISSUE THREAD

**Issue by LeeteqXV** [backdrop-ops/backdropcms.org#324]
I am checking out if/how vChess is working under BD 1.5.x, including its dependency: "tsort.

- https://www.drupal.org/project/vchess
- https://www.drupal.org/project/tsort (dependency of vchess)

**When making a draw in VChess, a WSOD is shown along the following message:**

"Fatal error: Call to undefined function rules_invoke_event() in /home/<x......>/modules/vchess/vchess.pages.inc on line 391"

If one then click on the browser's back button, you are taken to the vChess board and can see that the move was indeed registered and it seems that the error did not have any effect.

I did patch the schema.inc file as described here:

Solution for ENUM datatype for MySQL
	https://www.drupal.org/node/1560974
	https://www.drupal.org/files/core-7.x-ENUM_and_TIMESTAMP-1560974.patch

(For reference: "Remove support for date and time types" (open feature request for D7.core)
	https://www.drupal.org/node/866340

(The vChess installation does not give any errors or the like, but in normal usage it seems to contain so many small bugs that this module needs a thorough revision even after getting rid of the porting related issues.)

The other module, TSort, does not cause any errors, but need to explore more of Vchess before I can say for sure.

**Anyone for Chess (maintainership...) ? :-)**

We need at least one gaming module that works with BD also at an early stage, and should pick one like this one that can help us build community easily.

**And merry xmas + a happy and prosperous 2017 everyone :-)**

**Comment by klonos** [comment]
Hello there @LeeteqXV and welcome to the Backdrop issue queues. This queue here is specifically for issues related to the main website at backdropcms.org. Can you please move any issues related to contrib projects (such as this one and https://github.com/backdrop-ops/backdropcms.org/issues/323) over at https://github.com/backdrop-ops/contrib/issues ? Thanx.

**Comment by klonos** [comment]
> And merry xmas + a happy and prosperous 2017 everyone :-)

You too @LeeteqXV

**Comment by Dinornis** [comment]
@klonos Is there a way to move an issue from one project to another?  I could not find anything about that in GitHub Help.  Or did you mean move by opening a new issue in the appropriate project and copy the text into the new issue?  Sorry, still trying to get my head around how GitHub works.

**Comment by klonos** [comment]
> Or did you mean move by opening a new issue in the appropriate project and copy the text into the new issue? Sorry, still trying to get my head around how GitHub works.

**Comment by klonos** [comment]
> Sorry, still trying to get my head around how GitHub works.

No need to apologize @Dinornis. Nobody is born an expert and I surely do not know every aspect of GitHub either. GitHub is a great tool that is provided for free for open source projects and Backdrop uses it for its code. That's all I need to know and I am prepared to learn what needs to be learned. All I have learned so far was from playing around with it + some pointers and help that I got from the community. I'm sure that when you started using the Drupal issue queue, there was some learning and getting used to the interface involved as well. It just takes some time 😉

**Comment by klonos** [comment]
...I guess what I meant by my last comment is that you should start playing around with GitHub too, and if you strike parts of the UI that don't make sense or need help with something, then just ask for help and instructions. Start by asking Google, then [the GitHub documentation](https://help.github.com/) and should any of these two fail, then of course us 😉

**Comment by LeeteqXV** [comment]
Moved issue here: https://github.com/backdrop-ops/contrib/issues/194
