### ISSUE TITLE
Admin bar: ghost "settings" and "edit" menu items for layouts.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#325]
I've noticed that the website has been updated to 1.5.2 👍 

Here's what I see in all Structure -> Layouts -> %layout_name% menus:

![backdropcms org-admin_bar-ghost_menu_items_in_structure-layouts](https://cloud.githubusercontent.com/assets/2423362/21578538/10601f26-cfd8-11e6-9183-15c715c7791c.png)

Tried a cache clear, but it didn't help.

Not high-priority since this is only effecting the backend, access to which only a few of us have, but still annoying. Also worth investigating why this happened and see if we can prevent it from happening to other people's sites. If anyone else has seen this before, let me know and I'll file an issue against core.

**Comment by Graham-72** [comment]
@klonos yes, I get this on my sites too.

**Comment by klonos** [comment]
Closing in favor of the core issue: https://github.com/backdrop/backdrop-issues/issues/2443

**Comment by klonos** [comment]
@Graham-72 can you please chime in the other issue? Did you start having this after a core upgrade?
