### ISSUE TITLE
User guide should consistently use `example.com` for example URLs

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#326]
On the [quickstart](https://backdropcms.org/user-guide/quick-start) guide we are jumping between `mysite.com` (which links out to some commercial service) and `yoursite.com/user`

We should consistently use `example.com` which is reserved for documentation purposes: https://en.wikipedia.org/wiki/Example.com

**Comment by tomgrandy** [comment]
Agree!  Will go through docs and correct.  Excellent point!

**Comment by tomgrandy** [comment]
Went through the User Guide and replaced all references to sample URL with example.com and ensured the URL was styled as monospace.
