### ISSUE TITLE
Add a flag to docs pages for "Needs an update" (or similar)

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#327]
We have a tag on the main issue queue for "needs change records". We should either be using that or invent a new tag for when we add or modify things that require documentation updates. Like entity view modes, messing with the field display page, added a new dropdown menu, etc etc etc.
@tomgrandy @jenlampton @klonos what you think? Whatever we decide will need to be retroactive; we'll need to go back a trawl through all the last year of core commits and see what needs updating, tag them appropriately, and then write and/or re-write stuff.

**Comment by jenlampton** [comment]
Great issue @docwilmot thanks for opening it. I had occasionally been having similar thoughts :) 

Change records are for API changes - things that developers need to know when porting modules. They won't be what we need for changes to the UI of view modes - though that's just as important. We should only need change records from API changes between  D7 -> Backdrop 1, and then Backdrop 1 -> 2. 

Let's use the ` docs - needs work` tag for any change that requires an update to the user guide, or developer documentation. We can add a comment (maybe at the bottom of the parent issue, like we do for PRs?) stating what needs to be updated.

This might be the perfect job for Projects!

**Comment by klonos** [comment]
> We should either be using that or invent a new tag for when we add or modify things that require documentation updates.

We already have a "docs - need work" tag that [I've actually used a few days ago myself](https://github.com/backdrop-ops/backdropcms.org/issues/326#event-908641442). Would that do? It's only available here though, so we'd need to add that label to backdrop-issues as well.

> ...we'll need to go back a trawl through all the last year of core commits and see what needs updating, tag them appropriately, and then write and/or re-write stuff.

Yes, but we should also try to save ourselves some energy by crowd-sourcing the discovery of outdated/inaccurate documentation (on the b.org side). Some websites do this in a "passive" way by providing a way for people to tag documentation pages as outdated, while other sites use more "interactive" (perhaps a bit intrusive) "was this useful" questions in pop-ups.

Usually, out of courtesy I find myself answering "yes, this was helpful" to documentation that helps me ~90% even though some parts of it might be inaccurate, so I think that providing the tags would be the best way to go about it.

Either way we decide to go with this, we should also add some notification system on top of that which would send emails to the members of the documentation team, so one of us can act. After updating the documentation, we could be reseting the status back to "up to date". An extra nice touch would be to be adding an "up to date as of version" field.

Thoughts?

**Comment by klonos** [comment]
...seems that I've somehow lost the functionality of my open GitHub browser tabs auto-updating with other people's comments. Just saw that "docs - needs work" was also suggested by @jenlampton 😄

**Comment by klonos** [comment]
...we already have a "Documentation Status" field available for documentation nodes. How about exposing that to site visitors (or at least registered users) as an actionable link or something (similar to "report as spam")?

**Comment by jenlampton** [comment]
> How about exposing that to site visitors (or at least registered users) as an actionable link or something (similar to "report as spam")?

An interesting idea, we could turn that into a flag! Love it.

**Comment by docwilmot** [comment]
This is done

**Comment by klonos** [comment]
Follow-up: #584
