### ISSUE TITLE
ipv6 Support

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-ops/backdropcms.org#328]
We do have ipv6 record for backdropcms.org but server does not handle ipv6 properly

```
[Mon Jan 09 04:04 PM] ~
luke@lukes-MacBook-Pro$ curl api.backdropcms.org -v
* Rebuilt URL to: api.backdropcms.org/
*   Trying 2600:3c03::f03c:91ff:fedb:2085...
* TCP_NODELAY set
* Connected to api.backdropcms.org (2600:3c03::f03c:91ff:fedb:2085) port 80 (#0)
> GET / HTTP/1.1
> Host: api.backdropcms.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.2
< Date: Tue, 10 Jan 2017 00:05:50 GMT
< Content-Type: text/html
< Content-Length: 3698
< Last-Modified: Mon, 31 Oct 2016 12:37:31 GMT
< Connection: keep-alive
< Vary: Accept-Encoding
< ETag: "58173b0b-e72"
< Accept-Ranges: bytes

```

ipv6 Virtual hosts for nginx need to be properly configured.

Thanks to @cellear for helping with tech details.

**Comment by Gormartsen** [comment]
> @quicksketch Thanks @cellear and @Gormartsen! All fixed now. It was IPv6 configuration in nginx it seems.

**Comment by quicksketch** [comment]
Per https://kovyrin.net/2010/01/16/enabling-ipv6-support-in-nginx/, we had to enable IPv6 listening in the nginx config files. Though the implementation didn't quite match what was described there. We had to leave the old "listen" line as well as add a new one. Definitions for sites now look like this:


```
# Redirects for the www.backdropcms.org to the main site.
server {
  listen       80; # IPv4
  listen       [::]:80; # IPv6
  server_name  www.backdropcms.org live.backdropcms.org;
  return 301 $scheme://backdropcms.org$request_uri;
}
```
