### ISSUE TITLE
Backdrop 1.6 release blog post

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#330]
Backdrop 1.6 is the first release where we know all the new features included before the day we release :)  Let's take advantage of that and draft a blog post ahead of time!

Here's what I think we should highlight in the blog post (open to suggestions/changes!):
* Hamburger menu option (https://github.com/backdrop/backdrop-issues/issues/2369)
* New "Manage displays" page w/ custom view modes (https://github.com/backdrop/backdrop-issues/issues/315) - this name may need to be changed to "Display modes" if that change gets in.
* New file management interface (https://github.com/backdrop/backdrop-issues/issues/2375)
*  Option to add current page as last breadcrumb (https://github.com/backdrop/backdrop-issues/issues/2402)
* X number of user-experience improvements (TBD)

We'll need screenshots of each (if applicable) and once we have the release notes, we can add the links like we did at the bottom of https://backdropcms.org/news/backdrop-15

@klonos I know you had volunteered to write up the blog posts for releases, but it seems like you are exceedingly busy these days. I have asked @tomgrandy to write up the draft of the blog post for us this time, but wanted you to know about it so you can object if you would still like to do it yourself <3

**Comment by jenlampton** [comment]
@jordan8037310 we should have the blog post ready soonish.

**Comment by jordan8037310** [comment]
Can we assume this will be ready by mid-week? We will want to target Tuesday, the 24th, for newsletter. @kvalade

**Comment by jenlampton** [comment]
The newsletter will need to wait for the release of 1.6.1, so can't *really* be scheduled. However, I think that is a realistic ballpark ;)

**Comment by tomgrandy** [comment]
I'll start on it a soon as I have the release notes and an install to capture from.  Should not take me long.  Midweek is realistic.

**Comment by jenlampton** [comment]
Hi @tomgrandy the idea was that the blog post could be long done before we have the release notes (for the first time ever!). The release notes won't exist until the release is out. The blog post can be done before then since we already know what will go in it (the list in this issue).

That said, the release will be out later tonight so I guess we missed the opportunity to be ahead of the game :)  We can try again for the next release!

**Comment by tomgrandy** [comment]
My mistake.  I thought I needed the release notes.

**Comment by klonos** [comment]
Apologies for being unresponsive. Each time I volunteer to do things, it's with the intention to do them if time permits and provided that the universe does not object. From now on, @everybody please feel free to work on anything that I say I want to do. My time is *always* limited and when I get unfortunate in Real Life™, I simply lose motivation to do anything. Sorry.

**Comment by jenlampton** [comment]
No problem, we'l get 'em next time :)

**Comment by tomgrandy** [comment]
Here ya go:  https://backdropcms.org/news/backdrop-16

**Comment by jenlampton** [comment]
Love~!
