### ISSUE TITLE
Importance of BackdropCMS.org Functionality

### ISSUE THREAD

**Issue by Dinornis** [backdrop-ops/backdropcms.org#334]
It is amazing how much you guys accomplished in 3 years.  This may be a good time to step back and see where BackdropCMS.org can be improved overall to help attract a larger user base.

When thinking about ways of attracting more people to Backdrop, you may wish to consider the influence functionality of BackdropCMS.org has on people looking for a CMS.

The focus on making BackdropCMS.org a well functioning, user friendly website would have multiple benefits.

* **Positive First Impression**
In terms of advertising and outreach BackdropCMS.org is your most important asset.  Someone looking for a CMS solution is most likely to judge the CMS based on their first impression when visiting the particular CMS website.  Their main focus will likely be on the basic website functionality, not so much on colours and design aspects of it.  This is because the site structure and functionality reflects the built-in capability of the underlining CMS.  If the basics like navigation, breadcrumbs, search etc. are not there or are not functioning correctly, the potential user will leave and look elsewhere.

* **Less Time Spent on Support**
Improving BackdropCMS.org will make it easier for users to find relevant information which in turn will minimise unnecessary confusion and questions in the issue queue or forums.

* **Better Overall CMS**
The process of improving BackdropCMS.org will help with identifying any limitations in the current version of Backdrop core or contributed modules and by addressing these you will end up with a much better CMS making it more viable CMS solution.

Here are few things that may turn possible newcomers away from Backdrop.  I know that you are well aware of most of these issues. I am just trying to emphasise their importance in the great scheme of things.  Most of you are developers who know Backdrop inside and out and it is hard to see things from a different perspective.

* **No Site Search**
Most websites that need CMS also need well functioning search capability. Someone visiting b.org will rightly assume the CMS is not capable to fulfil that requirement.

* **Bad UX at Module Search**
The current implementation of searching for modules at https://backdropcms.org/modules does not set higher importance of search terms in `Titles` making it harder to find modules.  This is a problem especially for someone trying to figure out which modules are in Backdrop core and which modules will need to be installed when migrating from Drupal.  There is an issue open for this at https://github.com/backdrop-ops/backdropcms.org/issues/232

Having users rely on [DuckDuckGo](https://duckduckgo.com/) to find content on a website suggests substandard CMS.  d.org has suffered this problem for too long and there is no need for Backdrop to continue this trend.

* **No Breadcrumbs**
Breadcrumbs are important part of navigation and can reduce the number of actions needed for a visitor to get to a higher-level page.  Breadcrumbs reduce the overall website bounce rate and improve the findability of sections and pages. 

* **No Forums**
I am really glad to see a discussion on this topic https://github.com/backdrop-ops/backdropcms.org/issues/250 

Best wishes to all in 2017.

**Comment by Dinornis** [comment]
SEO is just as important.
* https://github.com/backdrop-ops/backdropcms.org/issues/343

**Comment by jenlampton** [comment]
I've created follow-up issues for the items @Dinornis pointed out nearly 1 year ago, that have not yet been resolved. Closing this issue as part of my queue cleanup. :)
