### ISSUE TITLE
Server Maintenance Yum Updates

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#335]
I would like to perform yum updates this Sunday night starting at 11:00pm MST and restart the servers.

I will also run rkhunter, have a look at the logs, and check the firewall. 

@quicksketch @jenlampton @sirkitree 

If this sound good to everyone, I will proceed.

**Comment by jenlampton** [comment]
That would be great. Can you also look into what is required for getting multibyte support? I think we need to upgrade mysql. If that can be done at the same time (with low risk) that would be fab!

**Comment by larsdesigns** [comment]
@jenlampton Looks like we are using the following version of MySQL: 
mysql  Ver 14.14 Distrib 5.5.52, for Linux (x86_64) using readline 5.1

I recommend we switch to MariaDB 10x which provides better support for Multibyte. it will also improve stability and performance. 

Can I open a ticket/issue for this?

**Comment by jenlampton** [comment]
> Can I open a ticket/issue for this?

yes please :)

**Comment by larsdesigns** [comment]
I am going to do the maintenance around midnight tonight.

**Comment by larsdesigns** [comment]
Performed the yum updates and reboots for both servers. Reviewed the firewall rules and they seem fine.

 No further tasks.
