### ISSUE TITLE
NRPE Install

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#336]
Can I have permission to install NRPE on the hosts and monitor using my companies Nagios implementation? 

This way I can help respond faster to problems and better keep track of yum updates, load etc. I will provide Nagios site access to the team. 

We can also use NRPE data for our Munin implementation down the road. 

If this is acceptable, I would like to implement NRPE using Yum packages this Sunday during the proposed Maintenance window in ticket #335 ...

@jenlampton @quicksketch @sirkitree

**Comment by jenlampton** [comment]
@larsdesigns that sounds great to me!  Yes please, and thank you.

**Comment by larsdesigns** [comment]
I will complete this tonight along with the updates.

**Comment by larsdesigns** [comment]
1. Completed the installation of NRPE and plugins on both servers.
2. Configured the firewall to allow my Nagios server to connect to NRPE. 
3. Configured Nagios checks for both servers. 
4. Configured backup admin access and notification to the Nagios interface. 
5. I will issue to credentials to @quicksketch and @jenlampton and any other OPS members who are interested.  

No further tasks.
