### ISSUE TITLE
Hosting OS Updates Using Ansible

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#337]
I would like to propose that I author Ansible playbooks to perform automated server maintenance on all of our servers as a batch. 

The Ansible playbooks would include: 

1. Performing Yum updates. 
2. Rebooting the servers. 
3. Checking the firewall rules as output to downloaded log files. 
4. Performing RKhunter check and downloading the logs. 

The Ansible playbooks will only be permitted to run from a workstation with the proper ssh keys. 

The Ansible playbooks will be committed and stored in a public or private Github repository. 

If this is acceptable, will begin coding and hopefully have it ready for ticket #335. 

@quicksketch @jenlampton

**Comment by jenlampton** [comment]
This sounds scary. I defer to @quicksketch

**Comment by larsdesigns** [comment]
Seems like this is not a good fit. I am going to go ahead and close the issue.
