### ISSUE TITLE
New Sandbox Server

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#338]
@jenlampton Requested that I build a new Sandbox server on Linode and document the build using Ansible and/or Linode StackScripts.

Thought I would make a ticket to track progress. 

@quicksketch

**Comment by jenlampton** [comment]
Thank you!

**Comment by larsdesigns** [comment]
I am going to build this tonight around midnight after the updates. I apologize for the delay. I was swamped last night.

**Comment by larsdesigns** [comment]
I got as far as I could tonight. I will work on this later today.

**Comment by cellear** [comment]
Is this sandbox server ready to go?  Should I stage borg theme updates here? (If so, I would need some creds)

**Comment by jenlampton** [comment]
I don't think we have a sandbox server. Just commit your changes to a new
branch and ping me when they are ready for review.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by larsdesigns** [comment]
Ack, I apologize for the delay. I will work on the server this evening.

**Comment by larsdesigns** [comment]
Okay, here we go.

**Comment by larsdesigns** [comment]
Completed the following tasks:

1. Created a 1GB Linode VM
2. Installed and configured a working lemp stack. 
3. Configured IPtables firewall. 
4. Installed certbot. 
5. Created virtual host for test.backdropcms.org using test_backdropcms_org.conf file.
6. Installed nrpe for Nagios and Munin monitoring.
7. Installed Emacs for me :-)
8. Configured MariaDB using secure installation program. 
9. Created sudo users for @jenlampton @quicksketch 

TO DO: 
1. Tune MariaDB. 
2. Contact send credentials to Ops team.

**Comment by jenlampton** [comment]
Will this be an exact copy of the other server?  Will it have
api.backdropcms.org and forum.backdropcms.org too, so we can use it to test
bakery module?

- - -
Jennifer Lea Lampton | 510-747-8230
Jeneration Web Development
Backdrop CMS & Drupal
www.jeneration.com

**Comment by larsdesigns** [comment]
Oh, it is a new server build with updated nginx, mariadb, etc.

However, I can also make a clone of the server that has forum.backdropcms.org too.

**Comment by larsdesigns** [comment]
Cancel the request for the public keys. I found your keys on one of the other servers, created the use and tested.

**Comment by jenlampton** [comment]
We only have one other server.... This should be an exact copy. Can we do
that with linode?

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

On Feb 27, 2017 10:45 AM, "Justin Christoffersen" <notifications@github.com>
wrote:

Cancel the request for the public keys. I found your keys on one of the
other servers, created the use and tested.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/backdrop-ops/backdropcms.org/issues/338#issuecomment-282811227>,
or mute the thread

**Comment by larsdesigns** [comment]
Yes, I will create a clone of the VM this evening. If I run into a snag, I will ask linode to push it along. They have helped me with this before.

**Comment by larsdesigns** [comment]
To clone the server, I will need to halt it for probably an hour. The clone process will not run on a running VM. I will do so tonight around midnight. I will perform a manual backup of the server image also prior to halting the VM.

**Comment by jenlampton** [comment]
Ah okay. Are there smarter ways to copy a whole server? I expect we may need to do this again every so often :)

**Comment by larsdesigns** [comment]
Looks like they have a new Images section but it is in beta. I think we can use Docker but I will look into it.

**Comment by larsdesigns** [comment]
Starting the clone process.

**Comment by larsdesigns** [comment]
The new clone server is up and running. I had to enable "Auto-configure Networking" in the profile and reboot to gain access to it. This setting is not enable by default and leaves our new baby clone without a public IP as I found using a glish session. 

@jenlampton Would you like for me to delete the sandbox server I created last weekend?

**Comment by jenlampton** [comment]
Yes, if you think we won't need it :)

**Comment by larsdesigns** [comment]
It could be helpful. But I can always make another one.

**Comment by larsdesigns** [comment]
Will you be needing any domain or sub domain configured in Nginx? Such as test.backdropcms.org or something?

**Comment by jenlampton** [comment]
yeah, can we do them all with a new subdomain test.?  Something like...

test.www.backdropcms.org
test.api.backdropcms.org
test.forum.backdropcms.org

And we should probably password protect them too... but I wonder how that will affect the bakery testing. Maybe not yet :)

**Comment by larsdesigns** [comment]
I can make the changes in Nginx but I do not have access to the DNS. If you want to send me the credentials, I can make the A records or just send me a list of the A records that were created.

**Comment by jenlampton** [comment]
I don't have DNS access. @quicksketch ?

**Comment by larsdesigns** [comment]
I am going to go ahead and take down the new server I created that we are not using to save confusion later.

**Comment by larsdesigns** [comment]
I took down the host that was not being used after months of being shutdown.

For now, I think that it is okay to make /etc/hosts entries for the domain and subdomains when folks are working with this host.

Should it be decided that test URLs are needed, let's open a new issue for that.

No further tasks. Closing...
