### ISSUE TITLE
transliteration does not work

### ISSUE THREAD

**Issue by huizache** [backdrop-ops/backdropcms.org#341]
backdrop 1.6 fresh install,  marking it in alias patterns settings. it unmarks itself when configuration is saved, and then does not transliterate...

**Comment by docwilmot** [comment]
wrong issue queue still @huizache, should be https://github.com/backdrop/backdrop-issues/issues

**Comment by serundeputy** [comment]
This smells like `system_settings_form()` to me.
possibly related to: https://github.com/backdrop/backdrop-issues/issues/2478

**Comment by huizache** [comment]
had my kid on top of me... sorry will correct
