### ISSUE TITLE
Database Multibyte Upgrade

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#342]
Upgrade to MariaDB 10x and upgrade the databases to support multibyte.

@jenlampton

**Comment by larsdesigns** [comment]
I forgot that the servers are on CentOS 6. I will have to dig a little more to find a good yum repo.

**Comment by larsdesigns** [comment]
Looks like a huge effort to move to MariaDB 10.x. I will plan on performing the multibyte conversion for the existing databases using these instructions: https://www.drupal.org/node/2754539

Please not we need to test, fork, and further develop: https://www.drupal.org/project/utf8mb4_convert.

Anyone have a lead on this?

**Comment by jenlampton** [comment]
That's not necessary, an update is built into backdrop.

**Comment by larsdesigns** [comment]
@jenlampton That is an awesome feature.

No further tasks. Closing...
