### ISSUE TITLE
SEO: Same Content - Two URLs

### ISSUE THREAD

**Issue by Dinornis** [backdrop-ops/backdropcms.org#343]
**Problem:**
Although an alias provides nice clean URLs for paths, Backdrop does not remove the old paths (eg node/208) so there are now two URLs representing the same content. Search engines may penalise b.o for duplicate pages.

**Example:**
The Date (basic) project page shows up in searches under two URLs:
https://backdropcms.org/node/208
and
https://backdropcms.org/project/date_basic

**Solution:**
Install and configure [Global Redirect](https://backdropcms.org/project/globalredirect)

**Comment by klonos** [comment]
@Dinornis it's in the plans for core: https://github.com/backdrop/backdrop-issues/issues/868

...but as it happens for many of the things in our to-do list, there is not enough time. We'll get there 😉

**Comment by jenlampton** [comment]
Now replaced by https://github.com/backdrop/backdrop-issues/issues/2871.

**Comment by jenlampton** [comment]
But also GlobalRedirect has been installed an enabled on backdropcms.org. Closing 🎉
