### ISSUE TITLE
Make location field optional for user profiles.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#344]
Drop seems to be residing in Afghanistan ...which is the 1st country in the list and gets auto-selected. Would be great to either make the field optional (and hide it from the sidebar if empty) or to allow "none" as country and set that as the default.

**Comment by klonos** [comment]
Related: https://github.com/backdrop-contrib/addressfield/issues/6

**Comment by docwilmot** [comment]
> Drop seems to be residing in Afghanistan

I fail to see your point. There are indeed [dragons from Afghanistan](http://www.businessinsider.com/afghan-mythology-is-home-to-monsters-2013-3)

**Comment by BWPanda** [comment]
It seems Drop didn't like the heat and so moved to Iceland :laughing: But I tested the profile form (without saving) and it seems you can now select 'None'. So closing.
