### ISSUE TITLE
"This site may be hacked"

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/backdropcms.org#345]
When doing a Google search for "Backdrop CMS" the result comes up with a warning that "This site may be hacked".

<img width="683" alt="screen-shot-2017-02-01-at-11 13 33-am" src="https://cloud.githubusercontent.com/assets/871421/22515182/4332a80e-e867-11e6-88fe-a3ea3068bfd1.png">

**Comment by Gormartsen** [comment]
Remove this message from your site
The "This site may be hacked" notification won't be removed until the webmaster of the site takes action.

Try these steps to fix your website:

Register and verify your site in Google’s Search Console.
Sign in to Search Console and check the "Security Issues" section to see details of sample URLs that might be hacked. Fix the security issue that allowed your website to be infected. Otherwise, your site is likely to be reinfected.
Read our resources for hacked sites for detailed information on how to fix your website.
Request a review in the Security Issues section in Search Console when your entire website is clean and secure. After we check that your site is fixed, we'll remove the "This site may be hacked" message.

Source: https://support.google.com/websearch/answer/190597?p=ws_hacked&hl=en&visit_id=1-636215624200102475-106610885&rd=1

**Comment by laryn** [comment]
I have a guess.
In the "We support" section somebody added a spammy looking company.

<img width="1127" alt="screen shot 2017-02-01 at 10 19 11 am" src="https://cloud.githubusercontent.com/assets/871421/22515461/25af2888-e868-11e6-8319-e94dcdc9acf4.png">

Maybe that triggers the hacked warning.

**Comment by Dinornis** [comment]
I think @larsdesigns has admin access to the server and can check into this.  It may be just a false flag by google, but would be good to scan the server.

You would think google would contact the site owner before flagging the site this way.

**Comment by larsdesigns** [comment]
I just performed maintenance and did not see any red flags but I will run another scan. 

Let's try to remove the div mentioned above and check the results.

**Comment by larsdesigns** [comment]
I have attached the rkhunter results. Everything looks okay to me. I think it is probably a content problem on the site.

[backdropcms_rkhunter.txt](https://github.com/backdrop-ops/backdropcms.org/files/746151/backdropcms_rkhunter.txt)

**Comment by jenlampton** [comment]
There were also been a few spammy event posts, but they have since been removed.  I'm working through the steps outlined by @Gormartsen now.

**Comment by jenlampton** [comment]
I have addressed all issues, and requested that a review of our site. That message should come down in the next 24 hours :)

**Comment by klonos** [comment]
> I have addressed all issues...

What were they exactly? Was it the spammy-looking entry in the support section?

**Comment by jenlampton** [comment]
> What were they exactly? Was it the spammy-looking entry in the support section?

Yes. Support, showcase, and events. All items have removed, and all naughty users blocked. I also adjusted the content types so everything starts unpublished and needs approval to prevent this from happening again.

**Comment by klonos** [comment]
I believe we should have an email notification that goes out to site admins each time a new node of these types is created (or modified) so that we can act faster rather than having these sit there as unpublished until somebody notices.

**Comment by jenlampton** [comment]
I do make it a practice to check all unpublished nodes every Thursday. We don't have any email notify modules on the site yet but we could add this feature once we add one (or port one).  @klonos can you please make a separate issue for that?

**Comment by serundeputy** [comment]
my google searches still show the subheader `this site maybe hacked`.

**Comment by Dinornis** [comment]
> I do make it a practice to check all unpublished nodes every Thursday. We don't have any email notify modules on the site yet but we could add this feature once we add one (or port one). @klonos can you please make a separate issue for that?

Since D6 I have been using [Actions](https://www.drupal.org/project/actions) and [Trigger](https://www.drupal.org/project/trigger) (now [Rules](https://www.drupal.org/project/rules)) for this exact purpose.

**Comment by jenlampton** [comment]
Can you please put that comment in the other issue?

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by jenlampton** [comment]
> Good news! Your reconsideration request has been approved and Google has removed any manual action on your site.

**Comment by klonos** [comment]
> @klonos can you please make a separate issue for that?

Done 😉

**Comment by laryn** [comment]
@jenlampton I know this issue is closed but just wanted to verify that all the "We support Backdrop CMS" orgs have been combed over -- current view has a few that look quite spammy:

<img width="1185" alt="screen shot 2017-03-18 at 12 57 37 pm" src="https://cloud.githubusercontent.com/assets/871421/24074628/86ca81ae-0bda-11e7-89f5-1d00f9e4a9db.png">

e.g. 

- LoanUncle 
- ThailandVacation.ru
- dart-cn.com
 - maybe others...

**Comment by jenlampton** [comment]
I don't see those on here anymore, maybe someone removed them already? It's likely a few slipped through...  thanks for bringing this to our attention :)

**Comment by olafgrabienski** [comment]
A few posts above - see https://github.com/backdrop-ops/backdropcms.org/issues/345#issuecomment-277537528 - we discussed to add email notifications to better know if spammy posts get published, or if other ones get changed.

@jenlampton suggested to make a new issue for adding a notify feature or porting a notify module. I just noticed that @graham-72 ported the Notify module: https://github.com/backdrop-ops/backdropcms.org/issues/346#issuecomment-278464645. Wouldn't it be good to (test and) use it now for the spam endangered content types on the website?

**Comment by jenlampton** [comment]
I don't think the notify module is the right tool for the job - especially since we don't have anyone with the time to actually respond to those emails right now. I think it would be better to use something like mollom or recaptcha that wouldn't involve any human involvement.

**Comment by olafgrabienski** [comment]
Really? In my opinion Mollom and similar modules are tools to prevent comment and similar spam from anonymous users. I guess that's not the case for Event posts or Support Backdrop statements on the site. Or is it possible to create such content as anonymous users?

**Comment by jenlampton** [comment]
> Mollom and similar modules are tools to prevent comment and similar spam from anonymous users

These modules can prevent spam from all users!

**Comment by olafgrabienski** [comment]
Okay, I don't know Mollom and others well, so if you think they do the job, fine!
