### ISSUE TITLE
IMP: Redo all layouts to remove double sidebar

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#350]
As part of implementing the new home page design, we will need to update all the layouts currently in use, and switch out the templates with core layouts where possible. 

On most layouts the same things will need to be changed:
- Add header block
- Add menu block
- Add search block
- Add powered by backdrop block

There are a few layouts, however, that have custom block placement based on what fields are present, and we need to be careful that those customizations are not lost:
* Showcase node
* User profile

Once all the layouts have been adjusted, we should do a full site export, and then remove only the layout files form the export, zip them up, and post them here so other people can jump right on on other tasks using these layouts.

**Comment by mikemccaffrey** [comment]
I've gone and created a new branch to handle the work of this ticket: https://github.com/backdrop-ops/backdropcms.org/tree/350-new-header-design

The theme styling has obviously changed, and I updated the layouts and the new configuration is in the dev-active directory.

You can check out the progress on my dev site:
http://backdropcms.mikemccaffrey.net/

The home page needs some work since there was a bunch of custom css to get the blocks to go full width. I haven't touched anything other than the header, so there is no powered by block or search form in the footer.

Let me know what needs to be cleaned up. I'd like to launch this modest change before we get into even more complicated design improvement.

**Comment by jenlampton** [comment]
> I'd like to launch this modest change before we get into even more complicated design improvement.

That's a good idea - launch the removal / replacement of the layouts before anything else. 

> Let me know what needs to be cleaned up. 

I don't see any mention in your comment above about the layout customizations mentioned in the ticket, and making sure those things still work after the layouts have been replaced. I checked a showcase node, and it looks like all the block placements have been lost: http://backdropcms.mikemccaffrey.net/showcase/norcal-hunter-jumper-association It's harder to tell with a user profile page since the header image is missing. 

We do need a thorough QA to assure there aren't other customizations (not in the ticket) that may also be affected. Maybe we could get someone who's familiar with the site to check each content type & custom layout? You could use a QA team!

**Comment by jenlampton** [comment]
Maybe the preprocess function will need to be renamed? Don't know, it could require a whole lot more work than that. That issue remains on the `what needs to be cleaned up` list and we can't push the layout changes until it's restored. Same goes for the user/profile, and I expect there are other layout customizations that will need to be addressed as well.

**Comment by jenlampton** [comment]
I've started on a list of design regressions that will eventually need to be addressed: https://github.com/backdrop-ops/backdropcms.org/issues/361

**Comment by jenlampton** [comment]
I pushed a bunch of commits to the branch that fix the showcase node display, and address a few of the other issues in the meta. I'm satisfied with the changes and I think we are go for launch today ~5pm, as long as we can get a smidge more QA to assure nothing else has been overlooked.  

Maybe @tomgrandy or @klonos or anyone who has some time today, would you please give http://backdropcms.mikemccaffrey.net/ a quick look-over?

**Comment by Graham-72** [comment]
I have had a quick look through the site on my laptop and I like what I see. Well done!

A couple of things struck me as a bit odd. First, on the Latest News page one sees Todd Tomlimson's book featured alongside the blog about XAMPP, and the blog says "This cookbook ..." One might get the impression that it is referring to Todd's book if one didn't know any better. Perhaps the columns needs subtitles 'Backdrop Blog' and 'Recent Publications' or something similar.
![backdrop cms backdrop cms](https://cloud.githubusercontent.com/assets/10559274/24055632/a768e70e-0b38-11e7-9e04-f52814f238c7.png)

Second, the log-in page has the widest fields I have ever seen on a log-in page!

![log in backdrop cms](https://cloud.githubusercontent.com/assets/10559274/24055674/d4ae3124-0b38-11e7-92c1-47cf0585f8a5.png)

Please excuse me if I'm being picky. I will now have a look on my tablet, also on smartphone.

**Comment by jenlampton** [comment]
Thanks @Graham-72!  I think we can fix the log-in page. It's also not supposed to have a sidebar ;)

**Comment by jenlampton** [comment]
I pushed a max-width fix for the user login, and removing the sidebar from the default layout also solved another issue on https://github.com/backdrop-ops/backdropcms.org/issues/361, so win win! :)

**Comment by Graham-72** [comment]
Usability is good on tablet and smartphone.  👍

**Comment by jenlampton** [comment]
Thanks @Graham-72 ! Pushed the new layouts code live! Please test on the live site now (for anyone who finds this issue and still wants to help us QA)

**Comment by jenlampton** [comment]
Special thanks to @mikemccaffrey for getting our layouts organized, fixing the theme to work with them, and getting this project moving again!!!
