### ISSUE TITLE
IMP: Add missing header elements from design

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#351]
Updated issue:
- [x]  place user menu block into header + style
- [x]  place social links block into header + style
* See https://github.com/backdrop-ops/backdropcms.org/issues/370 Re adding a search box

---
Original issue:

After the new blocks are in place on core layouts, we will need to theme the header region. I believe most of this work has been done already in Wes's new theme, so the remaining work is to copy CSS and template files as needed from the basis_borg theme.

**Comment by mikemccaffrey** [comment]
Changing this to adding the new header links and social buttons since the styling was done as part of moving things around in #350 .

**Comment by jenlampton** [comment]
Can you clarify what you mean by "adding the new header links"  (and maybe update the ticket description itself?) 

If you mean adding the the user menu, that should maybe be included in https://github.com/backdrop-ops/backdropcms.org/issues/350?) If you mean updating the menu items - I beleve we alredy have another issue for that too: https://github.com/backdrop-ops/backdropcms.org/issues/313

Also, I'm adding search into the issue title so we can add that too (at the same time as the social links).

**Comment by serundeputy** [comment]
@jenlampton 
PR: https://github.com/backdrop-ops/backdropcms.org/pull/435
Adds the GitHub, Twitter, and YouTube social icons block, css, and layout config.

**Comment by jenlampton** [comment]
Pushed these changes to both the forum & live sites last week. Closing issue.
