### ISSUE TITLE
Build new "install backdrop" page

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#354]
The new home page design includes a link to a page that tells people different ways they can install backdrop. We will need to build this page on backdropcms.org. Perhaps as a stand-alone layout?

Tools to include:

For local set-up
* Kalabox
* XAMP
* IZ-WAMP Backdrop

Remote:
* Pantheon
* (any other hosting providers who want to promote a one-click install?)

I believe this is 'done' on Wes's branch, so let's import that and see if any additional work needs to be done.

**Comment by serundeputy** [comment]
@jenlampton do know which branch is `Wes's` branch?

**Comment by jenlampton** [comment]
The one with the best theme borg_basis or basis_borg.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by jenlampton** [comment]
We just got an email today with another tool that we should include on this page:

> I am pleased to announce that I am providing a free "IZ-WAMP Backdrop" program which installs Backdrop locally on a PC or Windows Server x64 with Apache, MySQL and PHP). This program is very convenient and installs everything automatically. https://sourceforge.net/projects/iz-wamp-backdrop/

**Comment by olafgrabienski** [comment]
> We just got an email today with another tool that we should include on this page:

> I am pleased to announce that I am providing a free "IZ-WAMP Backdrop" program which installs Backdrop locally on a PC or Windows Server x64 (...)

Shouldn't we have a look at the tool before we include it on the page? Unfortunately, I'm not on Windows, so I can't try it out.

**Comment by jenlampton** [comment]
yes of course, I'm assuming we have a look, test, and it works as described :)

**Comment by olafgrabienski** [comment]
For local set-ups there is *Lando* now, kind of a *Kalabox* successor. For more information see https://docs.devwithlando.io.

**Comment by serundeputy** [comment]
I think this issue is a duplicate of https://github.com/backdrop-ops/backdropcms.org/issues/314 ; I've filed a PR over in #314.

**Comment by jenlampton** [comment]
This looks like a duplicate of https://github.com/backdrop-ops/backdropcms.org/issues/314
