### ISSUE TITLE
Complete "Key features" content for new home page

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#356]
Our new home page design includes a Key features block with text/left and image/right.  This should be a view of our content type "features" but we need to have text and images created/added for at least 5 key features:
* Mobile-friendly
* Easy editing
* Customizable
* Extendable
* Secure

**Comment by klonos** [comment]
My only concerns with this @jenlampton are a) that we are limited to only 5 items as key features, and b) how would these work on mobile? Ideas/thoughts:

- We could have a section after the *key* features with the rest of the "simple" features, shown as a responsive grid, just font-icon, feature title and feature blurb - no image. It could also be a separate page.
- The key features could either fall back to accordion on mobile, or "merge" with the rest of the features, but bubbled-up on top.

**Comment by klonos** [comment]
https://github.com/backdrop-ops/backdropcms.org/issues/129#issuecomment-288601814

**Comment by tomgrandy** [comment]
Created bulleted items for top five features and added screenshots for Wes to add to homepage rotator.  Believe this is finished.
