### ISSUE TITLE
Automated, sanitized, backups

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#358]
@larsdesigns do you think we could set up backdropcms.org to make it's own daily sanitized DB backups?  Ideally we would place them in a htpasswd-protected directory that was web accessible.

The big idea: we want anyone who wants to help work on backdropcms.org to be able to grab a recent sanitized DB dump, without the bottleneck of asking someone with perms to create one for them.  I'm open to other ways to solve this problem -- the above is what we brainstormed today :)

**Comment by serundeputy** [comment]
@jenlampton this has some todos:
https://github.com/serundeputy/sql-dump-sanitize/issues/1

**Comment by serundeputy** [comment]
@jenlampton I could do a similar thing for `/files`

**Comment by larsdesigns** [comment]
Okay, I will begin working on a script for cron to run.

**Comment by larsdesigns** [comment]
@serundeputy, thanks I will give it a go. 

Will drush sql-sanitize work with the Backdrop database? I

**Comment by larsdesigns** [comment]
Also, I think that @jenlampton wanted to have the dump file available for public download. I am assuming that is without htaccess protection. So we need think a little more about sanitizing. Like, removing data from the cache tables, sessions table. Or perhaps, I am overthinking this.

**Comment by larsdesigns** [comment]
I wonder if this form could be saving sensitive data to the database also: https://backdropcms.org/contact. We should check up on the forms too.

**Comment by serundeputy** [comment]
I think we want .htaccess protection @jenlampton ?

but we do need to make determination on what other tables should be sanitized.
I think there is a branch that has `drush sql-sanitize` but it does not cooperate with drupal (i.e. it breaks the drush commands on drupal sites)

**Comment by serundeputy** [comment]
backdrop `drush sql-sanitize` https://github.com/backdrop-contrib/drush/pull/63

**Comment by jenlampton** [comment]
> I think we want .htaccess protection @jenlampton ?

yes please :)

**Comment by larsdesigns** [comment]
Okay, sounds good to me.

**Comment by klonos** [comment]
We could have these available in the private directory on b.org so that only authenticated uses can access it. Then we could be linking from the "How to contribute" page (and other pages). So long as the filename remains the same, we could have a "download latest db dump" link.

**Comment by Gormartsen** [comment]
@larsdesigns Also there was a talk about to make SANDBOX b.org websites based on branch, PR and this sanitized dump. 
It should be similar to what we have on backdrop/backdrop. 

I need this sanitized dump to be available to download when I am going to setup SANDBOX automation.

Please ping me when it's done.

**Comment by jenlampton** [comment]
> We could have these available in the private directory on b.org so that only authenticated uses can access it. 

erm...  I think trying to tie sessions to the backups location could get super messuy and difficult to maintain. Let's start simple!

**Comment by larsdesigns** [comment]
Sadly, I haven't had time to work on the code for this. @serundeputy your help in improving the script you mentioned above would be awesome. I can make time for testing and implementation this week.

**Comment by serundeputy** [comment]
@larsdesigns I've updated the backup script.  Full details in README.md here: https://github.com/serundeputy/sql-dump-sanitize

hightlights:
* `NUM_KEEP` number of backups to keep before starting to rollover stale copies.
* `--sanitize` option
* `--quiet` option good for running on cron
* `--rollover` run with rollover operation on

I think we should set two cron jobs; one for sanitized backups to be distributed to devs for local development:

```bash
5 8 * * 6 {/absolute/path/to/php} {/path/to/script/}sql-dump-sanitize.php --quiet --sanitize --rollover
```

and one for just backups to restore from:

```bash
5 3 * * * {/absolute/path/to/php} {/path/to/script/}sql-dump-sanitize.php --quiet --rollover
```

Do we have a staging server that we can install and test on?

**Comment by serundeputy** [comment]
FWIW I've installed it on my server and all is well.

- [x] Automated backups on cron
- [x] Automated sanitized backups on cron
- [x] Verified validity of regular backup and sanitized backup (i.e. I can restore and use both types)

**Comment by larsdesigns** [comment]
@serundeputy Awesome, thank you so much. I will install it this evening.

**Comment by serundeputy** [comment]
@larsdesigns backup current DB first just in case ;)

**Comment by larsdesigns** [comment]
Completed the following tasks: 

1. Manually backed up the backdropcms database. 
2. Installed the backup script provided by @serundeputy : https://github.com/serundeputy/sql-dump-sanitize
3. Created crontab job using template.
4. Created config.ini file and completed the configuration. 
5. Tested the script and found that the database user that I have does not have permission to create and drop the temporary database that is necessary to perform the sanitization. @jenlampton and @quicksketch I need either the mysql root user credentials to create a database user that has the permissions needed that we can use for this script or create the user and set the permissions on my behalf.

**Comment by jenlampton** [comment]
I don't think I have root mysql user info, we'll need to ask @quicksketch

**Comment by quicksketch** [comment]
@larsdesigns I'll try to reach out to you via Gitter.

**Comment by larsdesigns** [comment]
Completed the following tasks: 

1. Finished setting up the temp database with user permissions.
2. Configured the sub domain in nginx.
3. Configured password protection for the directory.
4. Creating a download page with download links and cool dragon graphic. 
5. Tested the generation of the database dump. 
6. Tested the download of the dump file. 
6. Enabled cron job that generates the sanitized dumps. 

I apologize for the delay. I will send out credentials later this morning. 

To Do: 

1. Created DNS A record for the sanitize.backdropcms.org.

**Comment by larsdesigns** [comment]
@jenlampton Yikes, I do not have access to DNS. I thought it was in the Linode account. Can you create the A record?

**Comment by larsdesigns** [comment]
Also, we should probably compress the database dumps for download.

**Comment by serundeputy** [comment]
@larsdesigns I've added `gz` compression to the script and cut a tag `1.0.0` so you can either pull down the latest master or checkout the tagged release.

**Comment by serundeputy** [comment]
@larsdesigns I've added files directory compressed backups with rollovers functionality.  To make use of it pull down the latest `master` and add cron job to the server;

```bash
# files directory backup #
##########################
5 10 * * 6 {/absolute/path/to/php} {/path/to/script/}files-backup.php --rollover_files
```

That is just an example time; I'd recommend staggering it from the DB backup.

**Comment by larsdesigns** [comment]
1. Updated the code from @serundeputy and the archives are being compressed with Gzip. 
2. Created cron job for the files archives. 
3. Created download file archive links on the downloads page index.php.
4. Created a new HT password and tested in multiple browsers. 

Everything is working as expected. We only need to the DNS record for sanitize.backdropcms.org to finish up. Also, @jenlampton and @quicksketch it would be a good idea to review the database dumps and archive files for sensitive data. I had a look at the database and it seems sanitized to me. The more eyes the better.

**Comment by jenlampton** [comment]
I don't have DNS access either, only @quicksketch holds the keys.

**Comment by larsdesigns** [comment]
@jenlampton would you like to implement without DNS? Maybe we can use a URL such as api.backdropcms.org/archive-download or something similar?

**Comment by jenlampton** [comment]
No, I think it would be better if we can get @quicksketch to update the DNS.

**Comment by quicksketch** [comment]
A and AAAA records are now set up:

![image](https://cloud.githubusercontent.com/assets/100206/26599932/1a937f98-452f-11e7-8ed1-bea13ea5029c.png)

**Comment by serundeputy** [comment]
DNS is working 👍 ;
Cron jobs are not :(

```
Warning: database_dumps(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/sanitized_databases/index.php on line 3

Notice: Undefined variable: output in /var/www/sanitized_databases/index.php on line 3

Warning: database_dumps(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/sanitized_databases/index.php on line 3

Warning: Invalid argument supplied for foreach() in /var/www/sanitized_databases/index.php on line 3
```

@larsdesigns can you look at the code and see what is being set for `date_default_timezone_set`?

**Comment by larsdesigns** [comment]
Parts of index.php file I created for the download links was missing. I added the parts back in and create a github project for it as backup. Definitely overkill, but whatever...

**Comment by larsdesigns** [comment]
https://github.com/larsdesigns/backdropcms-sanitize-download

**Comment by klonos** [comment]
How does one get access to the dump and files? b.org credentials?

**Comment by serundeputy** [comment]
> How does one get access to the dump and files? b.org credentials?
Ask @jenlampton for them :)

**Comment by jenlampton** [comment]
@klonos do you need a backup?  the un is sanitize, and I've emailed you the password :)

**Comment by klonos** [comment]
Just in case I wanted to help with fixing b.org issues. Not as responsive lately as I used to be and certainly not as much as I'd like 😞

**Comment by serundeputy** [comment]
@larsdesigns this is working great for me for DBs.  I've successfully logged in and downloaded up to date, sanitized DBs for local dev.

Can you check the `files` cron job?  It seems to be stuck back in May.
Once the files piece is complete we can close this out.

**Comment by serundeputy** [comment]
@larsdesigns great thanks!

Would you mind filing an issue and or PR of how you fixed it? So we can fix it upstream at: https://github.com/serundeputy/sql-dump-sanitize/issues

**Comment by larsdesigns** [comment]
@serundeputy, yes will do.

**Comment by serundeputy** [comment]
the DBs are working good for me, but the files cron job has something wrong with it; not sure if it is the cron job or the script itself:

![screen shot 2017-10-05 at 8 21 54 pm](https://user-images.githubusercontent.com/6763671/31258135-0f235a48-aa0b-11e7-8e88-4b41788b78ac.png)

@larsdesigns have a look if you get a chance.

**Comment by larsdesigns** [comment]
@serundeputy okay, I will check tonight.

**Comment by larsdesigns** [comment]
@serundeputy, I fixed the cron job and tested it manually. It seems to be working as expected. I will check to make sure it runs by crond for the next few cycles and then recommend closing the issue.

I set the cron jobs to run every morning at 8am UTC.

I apologize for the delay promise to see this through during this week.

cc @jenlampton

**Comment by larsdesigns** [comment]
@serundeputy: Tonight I checked sanitize.backdropcms.org and both the files archive and database dumps have run successfully for the last two nights. 

I am going to go ahead and close the issue.

cc @jenlampton
