### ISSUE TITLE
Where is the error log?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#359]
hi @larsdesigns, quick question: where does PHP log it's errors on this server? I checked php.ini and it seems to think the error log is `/var/log/php-fpm/www-error.log` -- but that file does not exist. I found a file named `error.log` but it does not contain the errors I'm looking for. Other ideas?

**Comment by jenlampton** [comment]
I couldn't figure out the logs, so I just enabled error logging to the screen and restarted php-fpm. The fatal that's happening on the server (and not on my local) is `Fatal error: Call to undefined function mcrypt_module_open()`.

I guessed like we needed to install mcrypt, so I ran `yum install php-mcrypt` and then restarted php-fpm again. Now Bakery is working!!! :)  But if you could fix the logging that would be fab :D

**Comment by larsdesigns** [comment]
I am having a look.

**Comment by larsdesigns** [comment]
I changed the configuration so that php-fpm www pool is logging to /var/log/php-fpm/error.log. 

The file that it was supposed to be logging to did not exist. So, sorry no log. Also, I checked for a syslog which would be the default but it did not exist either.

**Comment by larsdesigns** [comment]
We looks like logging is now successful. 

larsdesigns@www1 /v/log> sudo tail -f  /var/log/php-fpm/error.log
[05-Mar-2017 03:39:01] NOTICE: error log file re-opened
[10-Mar-2017 08:04:52] NOTICE: Terminating ...
[10-Mar-2017 08:04:52] NOTICE: exiting, bye-bye!
[10-Mar-2017 08:04:52] NOTICE: fpm is running, pid 32031
[10-Mar-2017 08:04:52] NOTICE: ready to handle connections

**Comment by jenlampton** [comment]
Thank you!!!! :)

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.
