### ISSUE TITLE
GitHub download count showing 0 for all projects

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#360]
Did the GitHub API change over the weekend? This was working on Saturday.

I just manually updated core's page: https://backdropcms.org/project/backdrop
but all others are still showing zero: https://backdropcms.org/project/webform

**Comment by serundeputy** [comment]
@jenlampton 
You can either just let this run again tonight and as long as the same problem doesn't happen again it populate the download counts ~2AM EST.

Or if you login to the server and comment out this if statement: https://github.com/backdrop-ops/backdropcms.org/blob/master/www/modules/custom/borg_project_metrics/borg_project_metrics.module#L68 

You can then just run cron from the Backdrop UI.  Put the if statement back in place after so we don't poll github every cron run and exceed API limits.

~Geoff

**Comment by jenlampton** [comment]
that totally worked :)

**Comment by serundeputy** [comment]
and all the projects are zero'd out again :(
https://backdropcms.org/project/backdrop
https://backdropcms.org/project/webform

**Comment by jenlampton** [comment]
what the...  it works at 3pm, but not 2am?

**Comment by serundeputy** [comment]
not all: https://backdropcms.org/project/views_send

I wonder if we are hitting API rate limits?
I will have to investigate further.

**Comment by jenlampton** [comment]
Maybe we need some better checking for that in our code. If we hit a limit and get a non-integer result back from GitHub we shouldn't overwrite the previous value with zero.

**Comment by serundeputy** [comment]
agreed; I'll work on that too.

**Comment by serundeputy** [comment]
@jenlampton 
this pr: https://github.com/backdrop-ops/backdropcms.org/pull/362

Checks for valid json before updating download_count

**Comment by jenlampton** [comment]
deployed to prod!
