### ISSUE TITLE
Home page: Horizontal scrollbar and blank space at the right of the header.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#364]
This is after I have scrolled as far to the right as I could:

![image](https://cloud.githubusercontent.com/assets/2423362/24079691/b4b10586-0ce1-11e7-9766-d112a1192e58.png)

**Comment by klonos** [comment]
...seems to be limited only to the home page.

**Comment by mikemccaffrey** [comment]
Over in backdrop/backdrop-issues/issues/2361 the same problem was reported on sites using Basis, so that means that the problem is not at the theme layer, but the underlying layouts in core.

**Comment by jenlampton** [comment]
There was some screwy stuff in our theme left over from the previous layouts which I've fixed (mostly). I think this is close enough until we get the new home page design implemented. At least it doesn't look quite so broken anymore :)
