### ISSUE TITLE
Main menu: Improve menu item descriptions.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#365]
I'm quickly fixing these right now as I see fit (as we are live), but lets discuss and change accordingly once we have settled. Here's before/after:

- About: "Backdrop CMS Handbook" -> "Enabling people to build highly customized websites, affordably, through collaboration and open source software. Read more about Backdrop CMS..."
- Modules: no description text -> "Add new features to your Backdrop site, or improve the way your existing features currently work."
- Themes: no description text -> "Skins for your site that allow you to change the look, feel, and general appearance."
- Layouts: no description text -> "Divide pages on your site into different columns or regions where content can be placed."
- User Guide: "Backdrop CMS documentation for website architects." -> left as is
- Support: "Find service providers and contractors for hire to support Backdrop CMS" -> "Get help with Backdrop CMS"
- News: "News and Announcements from Backdrop CMS" -> left as is
- Log in/out: no description text-> left as is

**Comment by tomgrandy** [comment]
Excellent work @klonos !  Thanks for cleaning the menu up.

I see you have replaced the somewhat confusing "Handbook" and replaced it with About an About Backdrop CMS on the first page of the About section  However, Handbook rears its head in the sidebar nav.  

Anybody opposed to me changing "Handbook" in the About Backdrop CMS side nav to simply "About" to match the top-level nav name?

Or do I just make the change and ask for forgiveness later?

![screen shot 2017-03-21 at 10 18 25 am](https://cloud.githubusercontent.com/assets/660545/24151832/366011aa-0e20-11e7-98a9-6d2ebef3b8bb.png)

**Comment by olafgrabienski** [comment]
In my opinion it's a good idea to change "Handbook" to "About" in the sidebar. If we do so, we need to have also a look at the page "Backdrop CMS Handbook", which is linked in the book navigation and leads to the page https://backdropcms.org/handbook.

**Comment by tomgrandy** [comment]
I second @olafgrabienski 's recommendation.

**Comment by klonos** [comment]
>In my opinion it's a good idea to change "Handbook" to "About" in the sidebar.

>I second @olafgrabienski 's recommendation.

Done! I've changed the block title to be "About" for that book. This though makes the "Backdrop Dev guide" seem like out of place in this block/book. We could move it to a book of its own. We currently have these books:

- Backdrop Website Style Guide
- Backdrop CMS Handbook
- Backdrop CMS User Guide

We could have these instead:

- Backdrop Website Style Guide
- About Backdrop CMS
- Backdrop CMS User Guide
- Backdrop CMS Developer Guide

**Comment by olafgrabienski** [comment]
Thanks, @klonos !

> We could have these instead:
> 
> - Backdrop Website Style Guide
> - About Backdrop CMS
> - Backdrop CMS User Guide
> - Backdrop CMS Developer Guide

Makes sense in my opinion.

**Comment by tomgrandy** [comment]
Makes sense to me as well.

As for the Backdrop Website Style Guide, that was created by me as a method for maintaining consistency for editors of the BackdropCMS.org site itself.  Can be unpublished or deleted or I could pull it down and place it somewhere else.  It wasn't intended for visitors of the site itself.

**Comment by clouseau** [comment]
Looking through menu item descriptions, there is one with ellipses, most with periods, and two with no periods or ellipses. Perhaps these should be consistent.

**Comment by klonos** [comment]
@clouseau you seem like a man of my kind (I claim to have self-diagnosed OCD) 😄 ...I'll look into fixing these.

**Comment by jenlampton** [comment]
I did a quick check of the top-level links in our menu today, and it looks like they all have great descriptions (and consistently end with a period). Thank you to whoever fixed them!
