### ISSUE TITLE
Improve the About section

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/backdropcms.org#366]
If you click on the main menu item https://backdropcms.org/about, you get a page with two nearly identical lists, one in the main content and one in the sidebar:

![screen-backdropcms-about](https://cloud.githubusercontent.com/assets/14188307/24173179/609b5464-0e8b-11e7-9126-ce02504d6571.png)

In my opinion, there should be real content on this important page. We could write a summary. If that's too difficult, we could even show immediatly the sub page [Philosophy](https://backdropcms.org/philosophy) when a visitor chooses the "About" item.

If we do so, I'd suggest some related changes:

- Change the URL alias of `philosophy` to `about/philosophy` (and comparable for the other sub pages).
- Check if the URL change provides an `active-trail` class on the "About" menu item, and style it like an `active` item (2px border-bottom).
- Change the sidebar heading from "Handbook" to "About" -- already discussed in https://github.com/backdrop-ops/backdropcms.org/issues/365#issuecomment-288093352.
- Style the `active` item in the sidebar, for instance just bold.

Screenshot of suggested changes:

![screen-backdropcms-about-suggestions](https://cloud.githubusercontent.com/assets/14188307/24173878/4caca05e-0e8e-11e7-8484-15c934fdae3c.png)

**Comment by tomgrandy** [comment]
I posted a comment about the duplicates in another thread, but I really like your idea @olafgrabienski !  Makes so much more sense to land on the first page than a duplication of the outline of pages.  

I vote yes!  (Still trying to figure out if we should just do it or wait for consensus).

**Comment by tomgrandy** [comment]
Well, I tried but it looks like I have pretty limited permissions to what I can change.

**Comment by olafgrabienski** [comment]
Same here, or: a mix of limited permissions and not enough knowledge to handle the Book navigation without making mistakes. I'd prefer to leave the changes to the person(s) who built the book structure.

**Comment by jenlampton** [comment]
Main navigation `About` link now goes to philosophy page.

**Comment by olafgrabienski** [comment]
Thanks @jenlampton . Can we reopen the issue to discuss two improvements mentioned in the first post which aren't yet discussed?

- Change the URL alias of `philosophy` to `about/philosophy` (and comparable for the other sub pages).
- Check if the URL change provides an `active-trail` class on the "About" menu item, and style it like an active item (2px border-bottom).

**Comment by klonos** [comment]
Yeah, I think lets keep this open till these are addressed as well.

**Comment by klonos** [comment]
...if we change the URL, then we should add a redirect from the old one too.

**Comment by jenlampton** [comment]
Again...  no URLs have changed.

**Comment by jenlampton** [comment]
Hm, I had left a comment here yesterday, but seems to have gotten lost!  Sorry about that folks. 

* Changing URLs is a bad idea, not only for SEO, but for humans. There is value in knowing that the Philosophy page is at backdropcms.org/philosophy.
* No URLs have changed, instead the link is the text "About", and points to the philosophy page. 
* The current link does have an active trail  class (and is styled correctly) but we should not worry about the current classes as this menu is about to be replaced with a responsive drop-down menu, as per the home page redesign.

Closing this issue as none of the comments above are relevant (or possible).

**Comment by klonos** [comment]
> -No URLs have changed, instead the link is the text "About", and points to the philosophy page.

I meant the we'll need a redirect from backdropcms.org/philosophy to backdropcms.org/about/philosophy **if** we decide to make the change proposed by @olafgrabienski

**Comment by jenlampton** [comment]
Right, but we won't :)

**Comment by olafgrabienski** [comment]
> The current link does have an active trail class (and is styled correctly) ...

As the sidebar link has `active` and `active-trail` classes, not changing the URL is perfectly fine.

I'd however suggest to highlight the active sidebar link, using for instance bold text:

![screen-backdropcms-about-sidebar-active](https://cloud.githubusercontent.com/assets/14188307/24412665/62823e84-13d9-11e7-8120-f6ad2825a369.png)

**Comment by klonos** [comment]
Yes, I think that @jenlampton has no objection with making the current section bold in the sidebar index. The objection is with changing the URL.

**Comment by jenlampton** [comment]
yes, that's a great idea :)

**Comment by jenlampton** [comment]
I've added the bold text for active links in the sidebar menu: https://backdropcms.org/philosophy
