### ISSUE TITLE
Account page: Fix position

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/backdropcms.org#367]
When I go to my account page on backdropcms.org, the position of `.l-wrapper-inner` is too high and overlays the navigation:

![screen-backdropcms-account](https://cloud.githubusercontent.com/assets/14188307/24201068/5063aa04-0f0f-11e7-94e6-a9e5d0a39275.png)

In Firebug I can fix the issue by removing `position: relative;` or `top: -250px;` from `body.account-page .l-wrapper-inner`. Don't know if this would have side effects. Can anyone with file access try to fix it?

**Comment by tomgrandy** [comment]
Saw the same.  Thanks for reporting the issue as well as the fix.

**Comment by klonos** [comment]
Did someone work on fixing this? It's not currently as depicted in the screenshot by @olafgrabienski above. Here's how it looks when logged out:

![image](https://cloud.githubusercontent.com/assets/2423362/24226602/76586e6e-0fbb-11e7-9449-6c6e13dcf052.png)

...and when logged in:

![image](https://cloud.githubusercontent.com/assets/2423362/24226566/458fe6c2-0fbb-11e7-95f6-232d287fe7cf.png)

**Comment by klonos** [comment]
...perhaps it's related to whether the banner image has been set or left empty. Either way, it would be better if the local tasks bottom border was aligned with the bottom of the banner.

**Comment by olafgrabienski** [comment]
Oh, wasn't aware of the banner image!

With the banner image the page is better but still not good. Seems also to depend on size of the image. I tried some big images but strangely they don't cover the full width of the screen. (Bug?) I guess we need some instructions about the image dimensions here.

The design should however work with and without banner.

**Comment by olafgrabienski** [comment]
> With the banner image the page is better but still not good. Seems also to depend on size of the image. I tried some big images but strangely they don't cover the full width of the screen. (Bug?)

I saw now, that the banner image gets scaled on the server to a width of 1500px, that's why it looks strange on wider screens. See an example here (screen width 1600px):

![screen-backdropcms-account-banner-screen-1600](https://cloud.githubusercontent.com/assets/14188307/24244322/ab5ccad0-0fbe-11e7-83ab-4b0da2c14023.jpg)

**Comment by jenlampton** [comment]
I just pushed a fix for the header image, removing it as a block and adding it back as a background image.

**Comment by olafgrabienski** [comment]
Looks good now, thanks!
