### ISSUE TITLE
Array coding standard question

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#37]
Is this acceptable/recommended:

```php
function simplify_config_info() {
  $prefixes['simplify.global'] = array(
    'label' => t('Global fields'),
    'group' => t('Simplify'),
  );
  $prefixes['simplify.nodes'] = array(
    'label' => t('Node fields'),
    'group' => t('Simplify'),
  );

  return $prefixes;
}
```

Or should this be placed at the top of that function:
`$prefixes = array();`?

This page should be updated once we work out what the standard should be: https://backdropcms.org/develop/php-standards#arrays

**Comment by quicksketch** [comment]
You know, I always thought it was weird that you didn't have to declare an array before you started using it, but PHP doesn't have any problem with it at all.

I think it's a good idea to initialize the variable as an array, but it's not a requirement. Do you think it's something where we need a standard? Seems like either is fine to me.

**Comment by BWPanda** [comment]
Possibly not, I just wanted to know what to do in this situation. If both are fine, than we'll just leave it up to the individual.

**Comment by quicksketch** [comment]
Let's see what @jenlampton thinks on this one. I'm ambivalent, since this doesn't seem to have much impact. I think in the case of a hook like this (where there's no chance of another variable with the same name), I'd call it okay.

**Comment by jenlampton** [comment]
Yeah, either way is fine with me. since we don't have a standard already, let's leave it as-is.

**Comment by quicksketch** [comment]
Cool, let's close this then, sounds like we're all pretty much in agreement.
