### ISSUE TITLE
New B.org layouts: Tags get detached from teaser views when logged out

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#371]
when logged in:

![dorgtags](https://cloud.githubusercontent.com/assets/1042283/24299757/37349c72-1078-11e7-9bab-08e9c820e6c3.PNG)
when logged out:

![newdorg](https://cloud.githubusercontent.com/assets/1042283/24299770/3e06a4f0-1078-11e7-99ed-8083c596df48.PNG)

**Comment by jenlampton** [comment]
weird!  yes, we should fix this :)

**Comment by jenlampton** [comment]
Thanks for pointing this out @docwilmot !  I just pushed a fix to the live site.

**Comment by jenlampton** [comment]
hm, I don't see the changes there yet, but I expect we need to wait for the cache to clear out.

**Comment by klonos** [comment]
Seems fixed when visiting https://backdropcms.org/news and while logged out. Thanx @jenlampton 👍
