### ISSUE TITLE
New B.org layouts: Remove max-width from article.content

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#372]
```
article.node.view-mode-full .content {
  max-width: 680px;
}
```

Not needed if `.container` already has a `max-width`

Before:

![before](https://cloud.githubusercontent.com/assets/1042283/24300632/170d0670-107b-11e7-8b15-5eee668e3250.PNG)

Without max-width:

![after](https://cloud.githubusercontent.com/assets/1042283/24300654/26f353d2-107b-11e7-8178-5ea723ba7768.PNG)

**Comment by jenlampton** [comment]
No, the max-width on content is to prevent a single line of text from exceeding ~60 characters, which is hard on people's eyes (and brains). This is a usability improvement.
