### ISSUE TITLE
Porting Draggable Views Module

### ISSUE THREAD

**Issue by tomgrandy** [backdrop-ops/backdropcms.org#376]
Is anyone in the process or interested in porting Draggable Views over to Backdrop?

I did see in the Draggable Views issue queue that @behindthepage did ask the maintainers in January about this at https://www.drupal.org/node/2845521

Many sites that we have created use Draggable Views and I would be interested in helping to port this over to Backdrop.

**Comment by behindthepage** [comment]
Hi Tom,
I have it 80% done but got stuck with the ctools plugin code then got really busy.

If you want to create a Github project I will make a PR against it with my progress so far. You will need to check everything I have done.

regards Geoff

**Comment by tomgrandy** [comment]
Hi Geoff!

Thanks for the quick reply.  Will be happy to give it a shot!  Need DV in order to migrate a bunch of sites we've done from D7 to Backdrop.

https://github.com/tomgrandy/dvport

Tom

**Comment by behindthepage** [comment]
Yes it is a module that I have often used in the past.
You will need to add the D7 code to your project then I can fork it and PR against it. 
Geoff

**Comment by tomgrandy** [comment]
Try this one:  https://github.com/tomgrandy/git.dvport

**Comment by behindthepage** [comment]
Hi Tom,

Not Drupal core.

Just the D7 Draggable View module code.
Geoff

**Comment by jenlampton** [comment]
Next time, can we post these kinds of issues in https://github.com/backdrop-ops/contrib/issues?  That way everyone else who is also curious about the module status can find this issue more easily :)

**Comment by tomgrandy** [comment]
@behindthepage and @jenlampton - Obviously I am doing this wrong.  Was willing to try, but still navigating the waters here.  Perhaps I need to know more about how git works.  My mistake.

**Comment by tomgrandy** [comment]
Thanks Geoff.

**Comment by tomgrandy** [comment]
@behindthepage - Created a new thread at https://github.com/backdrop-ops/contrib/issues/209

**Comment by jenlampton** [comment]
Thanks @behindthepage :)  Also @tomgrandy no need to apologize, we were all new to GitHub once!

**Comment by behindthepage** [comment]
True dat!

**Comment by tomgrandy** [comment]
🥇
