### ISSUE TITLE
Too much whitespace above page title?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#379]
From @klonos in https://github.com/backdrop-ops/backdropcms.org/issues/375

> Unnecessary big gap between the site header (.l-header) and the page title section (.l-page-title).

**Comment by jenlampton** [comment]
Here's our design for the top of the page: 
![screen shot 2017-04-07 at 10 21 35 am](https://cloud.githubusercontent.com/assets/397895/24811720/0eab44cc-1b7c-11e7-8f07-d792e630811e.png)

Here's a book page from the site:
![screen shot 2017-04-07 at 10 21 35 am](https://cloud.githubusercontent.com/assets/397895/24811773/4f21134c-1b7c-11e7-8525-c4cfe2c03cfd.png)

**Comment by klonos** [comment]
Here's what we currently have (makes me feel like I'm on a different site when switching from section to section):

![borg-modules_vs_user_guide-current_situation](https://cloud.githubusercontent.com/assets/2423362/24833909/390e5386-1d1a-11e7-8cc3-da73ae187284.gif)

**Comment by klonos** [comment]
Here's how it could look like instead:

![borg-modules_vs_user_guide-proposed_changes](https://cloud.githubusercontent.com/assets/2423362/24833915/5052420a-1d1a-11e7-9674-35e5a57ebb10.gif)

**Comment by klonos** [comment]
...so basically, here's a before/after of the user guide pages:

![borg-user_guide-current_vs_proposed](https://cloud.githubusercontent.com/assets/2423362/24833921/6d284d34-1d1a-11e7-83d6-b354df73afc2.gif)

**Comment by klonos** [comment]
PS: sorry for all the "blinking" 😄

**Comment by jenlampton** [comment]
Hm, I really dislike having a hero on every page. I think it makes sense on the home page and on landing pages, but on every page it just seems overdone. I'd prefer that we remove the hero styles on modules/themes/layout pages over adding it everywhere. When it's everywhere it loses it's emphasis.

**Comment by jenlampton** [comment]
Also, can we move these comments into an issue about the hero? It's not really relevant to how much padding is on the H1 tag ;)

**Comment by jenlampton** [comment]
Closing this issue :)
