### ISSUE TITLE
Create a system to automate repetitive aspects of porting modules to Backdrop from Drupal

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#381]
Based on Gitter discussion, use a script, such as designed by @deekayen here: https://gist.github.com/deekayen/14d48f1fadec49039a79
This script does the basic stuff in conversion: change "core = 7.x" to "backdrop = 1.x" in .info files, add a `README` and a licence file, change `variable_get`s etc etc. This could be used as the basis for the following 

Two options were suggested:
V1
- Build a sandbox version of Backdrop contrib
- script to pull top 5000 projects from Drupal contrib one by one, apply @deekayen's script to each, then push them up to the new sandbox contrib
- when a Backdrop user wants to port a project, fork from sandbox, make it work, push to real contrib

V2
- Add a page somewhere where users can sign in to with GitHub credntials
- User selects a project to pull from Drupal, 
- project pulled to server and apply @deekayen's script and push to the user's own GitHub acct.
- Fix it, push to contrib

V2 sounds better, but more technical input would be required to do syncing I imagine. Either would heavily ease the burden of the initial porting steps and improve our porting throughput.

Thanks @Gormartsen

**Comment by deekayen** [comment]
I still feel the need to be abundantly clear that the sed args on Mac work differently from sed in Ubuntu. My gist is for Mac. I've not been able to locate my Ubuntu port.On Apr 13, 2017 7:28 PM, docwilmot <notifications@github.com> wrote:Based on Gitter discussion, use a script, such as designed by @deekayen here: https://gist.github.com/deekayen/14d48f1fadec49039a79
This script does the basic stuff in conversion: change "core = 7.x" to "backdrop = 1.x" in .info files, add a README and a licence file, change variable_gets etc etc. This could be used as the basis for the following
Two options were suggested:
V1
Build a sandbox version of Backdrop contribscript to pull top 5000 projects from Drupal contrib one by one, apply @deekayen's script to each, then push them up to the new sandbox contribwhen a Backdrop user wants to port a project, fork from sandbox, make it work, push to real contrib
V2
Add a page somewhere where users can sign in to with GitHub credntialsUser selects a project to pull from Drupal,project pulled to server and apply @deekayen's script and push to the user's own GitHub acct.Fix it, push to contrib
V2 sounds better, but more technical input would be required to do syncing I imagine. Either would heavily ease the burden of the initial porting steps and improve our porting throughput.
Thanks @Gormartsen

**Comment by klonos** [comment]
@Gormartsen ...another one for your to-do list. As discussed on Gitter: no stress 😄

**Comment by jenlampton** [comment]
Don't forget that we already have coder_upgrade, so all the script really needs to do is run that project on a module, and deliver the results! :)

**Comment by docwilmot** [comment]
Yep Coder Upgrade should be enough. And there was very little interest in this, so closing.
