### ISSUE TITLE
Problems with documentation

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#39]
* New docs are ending up in change records for some reason. See the last few "change records".
* Plus I did a book page on converting modules and it isn't showing up under the parent book (should be under creating modules) in the sidebar menu.
* Code wrapped in `<?php` tags are displaying HTML instead of links. See "Let Backdrop know about your module's config" on https://api.backdropcms.org/node/28621.

Needs fixing.
Also reminder:
https://github.com/backdrop-ops/api.backdropcms.org/issues/8
https://github.com/backdrop-ops/api.backdropcms.org/pull/7

**Comment by quicksketch** [comment]
> New docs are ending up in change records for some reason. See the last few "change records".

Thanks, added a filter for the change record content type.

> Code wrapped in `<?php` tags are displaying HTML instead of links. See "Let Backdrop know about your module's config" on https://api.backdropcms.org/node/28621.

Thanks we had an issue with the filters out of order. Fixed now.

> Plus I did a book page on converting modules and it isn't showing up under the parent book (should be under creating modules) in the sidebar menu.

I think the block in the sidebar is actually a menu, rather than a display of the book pages. I granted your account admin menu permissions so you can rearrange the menu as needed as well.

**Comment by cellear** [comment]
Yikes, that sounds like my fault!  I've been out of touch for the last week (admittedly not good timing on launch week) but I'll check in this evening and clean up issues like this, if they're still open.

**Comment by quicksketch** [comment]
I think we're all cleared up here. Though https://github.com/backdrop-ops/api.backdropcms.org/issues/8 and https://github.com/backdrop-ops/api.backdropcms.org/issues/7 still need addressing.
