### ISSUE TITLE
Fix the "Wear" section 

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#391]
https://backdropcms.org/contribute#wear

![image](https://cloud.githubusercontent.com/assets/2423362/25776471/41cb1538-3302-11e7-9664-a079cdc35a66.png)

...as you can see, the dragon hoodie image is to the far left while the respective "donate" button is on the other end.

**Comment by klonos** [comment]
...as the page gets narrow, it gets even more garbled:

![image](https://cloud.githubusercontent.com/assets/2423362/25776495/de031298-3302-11e7-9213-5cbe57fa0109.png)

**Comment by klonos** [comment]
...seems that both images and donation widgets get a `donate-right` class. Perhaps some of them should be `donate-left`??

![image](https://cloud.githubusercontent.com/assets/2423362/25776513/778d53e2-3303-11e7-9087-6c3bdc9744ed.png)

**Comment by klonos** [comment]
...not fixed, but at least less broken:

![image](https://cloud.githubusercontent.com/assets/2423362/25776531/20e340d2-3304-11e7-897d-a8570fb5e564.png)

pinging @jenlampton

**Comment by jenlampton** [comment]
> Perhaps some of them should be donate-left??

No, there is no `donate-left` class. The donate stuff was only ever on the right.

**Comment by jenlampton** [comment]
Hm, I wonder if we can use our new bootstrap classes here!  Let me give that a go...

**Comment by jenlampton** [comment]
tah dah https://backdropcms.org/contribute

**Comment by jenlampton** [comment]
desktop large: 
<img width="730" alt="desktop" src="https://cloud.githubusercontent.com/assets/397895/25776889/565a7d90-3280-11e7-80bf-497c498afe24.png">
desktop medium:
<img width="561" alt="screen shot 2017-05-06 at 5 19 51 pm" src="https://cloud.githubusercontent.com/assets/397895/25776891/5b32492e-3280-11e7-8a8d-7d2dc708cb58.png">
tablet: 
<img width="591" alt="screen shot 2017-05-06 at 5 20 10 pm" src="https://cloud.githubusercontent.com/assets/397895/25776892/6175b05a-3280-11e7-8596-3394f5421621.png">
mobile:
<img width="368" alt="screen shot 2017-05-06 at 5 20 24 pm" src="https://cloud.githubusercontent.com/assets/397895/25776893/679f9dc4-3280-11e7-804a-9adabb559d7d.png">

**Comment by jenlampton** [comment]
I think this is fixed, closing :)

**Comment by klonos** [comment]
Not 100%:

![image](https://cloud.githubusercontent.com/assets/2423362/26243730/3abbda8e-3cd0-11e7-81d6-183f900a51f4.png)

- Notice how the 2 first "Buy Now" buttons are small while the 3rd is large? Easy to fix, but don't know whether we want to keep the small or the large for all 3 items.
- Notice how the description, size drop-down menu and "Buy Now" button are not aligned? Should be centered I think.

**Comment by jenlampton** [comment]
> Notice how the 2 first "Buy Now" buttons are small while the 3rd is large?

Now all 3 are small.

> Notice how the description, size drop-down menu and "Buy Now" button are not aligned? 

All are aligned left.

**Comment by klonos** [comment]
Looks good 👍 ...tiny nit about the elements that would perhaps look better center-aligned, but I guess that's a matter of preference. Closing 😄

**Comment by jenlampton** [comment]
> the elements that would perhaps look better center-aligned

yeah, but only on desktop. Seemed not worth it since we are about to get a new theme anyway :)
