### ISSUE TITLE
Add a "Backdrop on the web" section.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#392]
...with links to articles about Backdrop in other 3rd party sites and/or in other languages.

**Comment by olafgrabienski** [comment]
Beginning to collect links to respective articles. Feel free to add more!

---

**Articles in English**

- Jonathan Daggerhart: [Backdrop CMS](http://www.daggerhart.com/backdrop-cms)

---

**Articles in other languages**

German

- Olaf Grabienski: [Do the right thing. Mein erster Commit für Backdrop CMS](https://www.olafski.de/2016-10-04/do-the-right-thing-backdrop-cms)

**Comment by jenlampton** [comment]
@klonos we could do this now. Do you want to set up a content type (maybe called, "External link" or "External article" or something?  Fields would be title + URL. Then we can make a block view and throw it on the news page :)

**Comment by klonos** [comment]
...on to it 😉

**Comment by klonos** [comment]
I have created a "External mention" content type with the following fields (besides the stock title that is):

"Link to mention" -> required link field where the link to the article/video/podcast/tweet/what-have-you is entered
"Link to author" -> required link field where the name of the author and a link to their personal site or d.org or b.org or GitHub profile is entered. Only a name/nickname can be entered, with the URL being optional. 
"Mention date" -> required field defaulting to "now" if the mention comes with no date.
"Mention language" -> required text list field, defaults to "English". In lack of https://www.drupal.org/project/languagefield I have used the list provided [here](http://stevehardie.com/2009/10/list-of-common-languages). We can add/remove as needed and eventually perhaps switch this to a "proper" language field if/when that contrib module is ported 😉 

Created a "Backdrop on the web" view with a page:

https://backdropcms.org/backdrop-on-the-web

@jenlampton thoughts? Should we make this a block and add it to the sidebar in https://backdropcms.org/news ?? There's quite a few other sections there, so where do we place it?

**Comment by jenlampton** [comment]
Nice work @klonos!!  

How far back should we go with articles?  Here are a few others we may want to include:
* https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time
* https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2
* https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-3
* https://friendlymachine.net/posts/drupal-8-and-backdrop-cms-brief-comparison
* https://www.drupalwatchdog.com/volume-4/issue-1/backdrop-cms
* https://yellowpencil.com/blog/drupal7-vs-drupal8-vs-backdrop/
* https://groups.drupal.org/node/433933
* http://www.jenlampton.com/blog/introducing-backdrop-cms-drupal-fork
* https://www.quora.com/Will-BackDrop-CMS-the-fork-of-Drupal-7-be-a-viable-alternative-to-Drupal-8-or-will-it-fail-What-factors-will-determine-its-success-or-failure
* https://civicactions.com/blog/a-first-look-at-the-backdrop-cms/
* https://www.isovera.com/blog/random-thoughts-backdrop-cms
* https://www.lullabot.com/articles/porting-drupal-7-modules-to-backdrop
* http://enzolutions.com/articles/2014/12/29/backdrop-cms-first-impressions/
* https://www.monarchdigital.com/blog/2015-07-06/first-look-backdrop-cms

**Comment by klonos** [comment]
> How far back should we go with articles? Here are a few others we may want to include:

I'll try to find some time within the week to get these added. I don't think we should be struggling to get *every* single article out there in the list. I'm sure that as we come across more, this list will get larger 😄 

> Yeah, I'd love to see that. Maybe just as a list of links to the posts, with a "more" link to get to the full page?

Will work on that soon as I can.

**Comment by olafgrabienski** [comment]
@klonos Thanks for creating the "Backdrop on the web" page. In my opinion, the language list is quite overwhelming for visitors. Is it possible to reduce the list to the languages actually used in the web articles?

**Comment by jenlampton** [comment]
I'm not sure the language is necessary as an exposed filter. Maybe we just list it next-to or below the article title.

**Comment by klonos** [comment]
> I'm not sure the language is necessary as an exposed filter.

If you think non-English audience, it is. Once this list gets more entries, it will be hard for people to find articles in their language if they are not English speakers. I expect that list to have more than 90% of articles in English, so non-English articles will be like searching for a needle in a haystack without a language filter.

**Comment by klonos** [comment]
@olafgrabienski that list is pulled from the values that are available when adding an article mention. I could reduce that list to only the most "popular" languages, but that would then seem "discriminating" to anyone that doesn't find their language available in the list.

**Comment by klonos** [comment]
...in d.org there's https://www.drupal.org/project/views_selective_filters

> This module allows to have an exposed filter only show options that belong to result set.

If we had that ported, then we could use it to limit the options in that drop down only in the view. Once an article mention would be added for a non-available language, then that language would automagically become available as an option.

**Comment by jenlampton** [comment]
> If you think non-English audience, it is.

Once we have the list up for a while people will only care about the content that's new, so that would be maybe ~5 items or so at the top of the list. By printing the language the article is written in, people will know if they can read the article as it is, or if they will need to use google translate (or similar). Either way, they have information they need to decide if they want to read the article.

Backdrop's language is English. Our website is in English. Our code is in English. This is not a multi-lingual website (that's likely another issue ;)). Our priority is the user experience, and we care about the most about the experience of the majority of site visitors. If adding this unnecessary select list hurts the user experience for the majority, we shouldn't have it.  Please remove it :)

**Comment by olafgrabienski** [comment]
> [The Views Selective Filters module] allows to have an exposed filter only show options that belong to result set. If we had that ported, then we could use it to limit the options ...

@klonos Yes, Views Selective Filters would be a good approach, maybe in combination with a filter reset button. I agree however with @jenlampton that a language filter isn't important at the moment. That certainly may change having much more articles in other languages than English some day, and we can resume the work then.

**Comment by klonos** [comment]
Fair enough @jenlampton. I will return to work on that after I finish with testing https://github.com/backdrop/backdrop-issues/issues/2541

**Comment by klonos** [comment]
OK...

- language exposed filter removed
- added all linked articles that @jenlampton has posted above
- added a block on the right sidebar in https://backdropcms.org/news showing the latest 5 mentions with a link to view more

The block needs styling. @jenlampton ??

**Comment by klonos** [comment]
...oh, I forgot to mention that I've converted the "Author" link field to accept multiple values to cover the case of multiple authors.

**Comment by klonos** [comment]
Ideas/todos:

- Fix the block style
- Rewrite the language field so that it doesn't output anything when the language is English (the default)
- Google "Backdrop CMS" and add any articles in the first 2-3 pages of results that are missing from our list.
- ???

**Comment by olafgrabienski** [comment]
Great! One idea regarding the styling: build the block for the *News* page as a list (not as a table).

**Comment by docwilmot** [comment]
Personally I think the main list would look nicer as an unformatted list than as a table. The author names could instead link to a list of articles buy that author, to account for authors without a Backdrop profile.

**Comment by jenlampton** [comment]
I did the following today:
* Fix the block style - as a list (not as a table) ✅ 
* Allow (registered) users to create "external mention" content. Perhaps have them be unpublished by default and moderate? ✅ 
* Make mention page into a list, too ✅ 
* Sort by mention date (not post date)✅ 
* Change the URL to news/on-the-web (and add a redirect) ✅ 
* Allow (registered) users to create "external mention" content (this was done already) ✅ 
* Perhaps have them be unpublished by default and moderate? yes! ✅

**Comment by klonos** [comment]
> Personally I think the main list would look nicer as an unformatted list than as a table.

Definitely 👍. Was only trying to get this started.

> The author names could instead link to a list of articles by that author, to account for authors without a Backdrop profile.

The authors are a multi-value link field with the URL part being optional. So, it can be just plain text or external links to their personal websites 😉

There's only 2 things I would change:
1. I was trying to have the language shown only if it is different from the default English which is implied. I guess that this would be possible only if the rewriting of the field could allow PHP (but dangerous).
2. I feel that the language is better to be appended to the article title rather than the date.

**Comment by jenlampton** [comment]
I'm going to close this issue since we have the mentions section (now at news/mentions) but we should open a followup issue if people feel strongly about moving the language to the title line (instead of the date line)
