### ISSUE TITLE
Create Add Ons Page

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#394]
Per our design/navigation update we want to add an Add Ons menu item, and page to go along with it.

So we need some content for that page that summarizes what Add Ons are and links to Modules, Themes and Layouts. If needed we can brainstorm on content and design together if that'd be helpful in coming up with content/ideas.

cc: @tomgrandy

**Comment by tomgrandy** [comment]
Can do.  Leaving for a race down near you today and will work on this on my return.

**Comment by klonos** [comment]
Hey @wesruv! FYI, @tomgrandy has already created https://backdropcms.org/user-guide/add-ons-modules-themes-and-layouts for our documentation.

**Comment by klonos** [comment]
@tomgrandy you are crazy!! 😄

**Comment by tomgrandy** [comment]
@wesruv - Is what @klonos posted above enough of a description for what you need?

@klonos - Survived the race and can confirm ski slopes are meant for going down, not up.

**Comment by klonos** [comment]
@tomgrandy 😄 ...I went up mount Olympus once because my mate didn't get anyone else to go with him. He was training for a couple of months before, while for me it was a last minute "I'll come with you. How hard can it be?" ...never doing that again.

**Comment by BWPanda** [comment]
I believe this is done now: https://backdropcms.org/add-ons Can we close this issue (and the milestone for it)?

**Comment by wesruv** [comment]
Yep, looks right to me
