### ISSUE TITLE
my new module doesn't appear in backdropcms.org

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/backdropcms.org#399]
My new ported module usertabs (https://github.com/backdrop-contrib/usertabs) doesn't appear yet in backdropcms.org. I wonder if I have something wrong in my code which prevents this. Thanks

**Comment by docwilmot** [comment]
Doesn't look like you've published a new release yet. It will appear there once you have a valid release. 
You should also delete the Drupal tags.

**Comment by robertgarrigos** [comment]
Right, thanks. Done. I guess it will take a few hours now.

**Comment by docwilmot** [comment]
Sorry, not yet. Take a look at other project releases: the naming convention for tags/releases is the format 
1.x-1.0.0. 
I think you should have gotten an error report actually. Maybe @quicksketch or @serundeputy can check.

**Comment by docwilmot** [comment]
Just to be clear, you will get listed on BackdropCMS.org almost immediately if you make a valid release. My comment about getting someone to check was not to suggest you needed to wait.

**Comment by robertgarrigos** [comment]
I din't get any error report, in fact. I changed the format of the release version, anyway (the drush module, however, follows a different pattern and it is listed). Mine is not yet. Is there somewhere a checklist I could follow?

**Comment by docwilmot** [comment]
You're right, don't know why. Did you edit the release or delete and do over?  Maybe try that?

**Comment by serundeputy** [comment]
> (the drush module, however, follows a different pattern and it is listed)
  * drush is an exception that node on bcms.org was created manually


> Is there somewhere a checklist I could follow?
Release docs: https://api.backdropcms.org/contribute#contrib-releases
  * Although those docs don't look very robust, maybe we can bolster them by fixing this release of `usertabs` and documenting.

I checked the release and I don't see a packager error, which is what happens, when like `type = module` is omitted from the .info file.

still poking around, and I don't see it on backdropcms.org either

**Comment by robertgarrigos** [comment]
Fixed. Deleted all releases and tags and started over again. It's listed now on bcms.org. Thanks for your help.
