### ISSUE TITLE
Automatically associate issue numbers between code and issue repositories

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#4]
Right now our repositories are split into code and issues due to limitations of the Github permissions system (see #2). This means that when we reference an issue in a commit, i.e.:

```
Issue #10: Fixes some issue with some module.
```

This commit does not automatically post a comment in issue 10 like it would if the issue tracker and code repository were the same thing. We should be able to leverage the Github API to restore this automatic functionality between repositories.

Note that Github already allows cross-repository linking (per https://help.github.com/articles/issues-only-access-permissions), but the syntax is awkward. We'd prefer that linking was simply automatic based on the names of the repositories. i.e. a pull request on the "backdropcms.org" repository would automatically associate commits in the "backdropcms.org-issues" repository issue tracker.

**Comment by Gormartsen** [comment]
This part is done for PUSH.

Tomorrow will do for PR.

example is here:
https://github.com/itpatrol/test/commit/0d5f03d2d5e2ef0e5509d0fe0c75cc370874b7f5

<img width="807" alt="screen shot 2016-03-12 at 11 16 00 pm" src="https://cloud.githubusercontent.com/assets/5018896/13726880/6aa7e292-e8a8-11e5-9ca4-c003348cf852.png">

Comments will be posted on "backdrop-ci" behalf.

**Comment by Gormartsen** [comment]
@quicksketch @jenlampton This part is ready.
Every commit or PR with #NNN to backdrop/backdrop will get extra comment from githubauto app with proper link like backdrop/backdrop-issues#NNN

See example here and here:
https://github.com/itpatrol/test/pull/6
https://github.com/itpatrol/test/commit/3a563b835f72fe29c961b0cd2257adfc6821cd6e#comments

We need to properly configure http://github.backdrop.expert to use backdrop-ci instead of my "Gormartsen" access to do this comments and properly webhook backdrop/backdrop repo to this app.

**Comment by Gormartsen** [comment]
Code is in this repo: https://github.com/backdrop-ops/github-auto

**Comment by Gormartsen** [comment]
Mind map for PR #13 for this issue.
<img width="807" alt="screen shot 2016-03-22 at 11 13 05 pm" src="https://cloud.githubusercontent.com/assets/5018896/13974631/cd52421a-f083-11e5-9411-66fbe2b8056e.png">

**Comment by Gormartsen** [comment]
one more todo:
- [ ] - fetch all comments for PR and look for #NNN to add message 'Related to backdrop/backdrop-issues#NNN'

**Comment by quicksketch** [comment]
We've merged https://github.com/backdrop-ops/backdropcms.org/pull/201, so this is 90% done! We just have to handle the item Gor mentioned in the previous comment. Very nice!

**Comment by Gormartsen** [comment]
I closed #201

**Comment by quicksketch** [comment]
Let's close this issue as complete and file new issues for any followups.
