### ISSUE TITLE
Wrong "current release" on roadmap

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/backdropcms.org#401]
On roadmap page (https://backdropcms.org/roadmap) 1.6.0 is still pointed as "Current release".

**Comment by serundeputy** [comment]
thanks; updated: https://backdropcms.org/roadmap

**Comment by klonos** [comment]
Updated https://github.com/backdrop/backdrop-issues/blob/master/procedures/docs/create-release-minor.md to add an entire section of "Update the Roadmap page on b.org" tasks, which includes a "Move the "(current release)" pointer to the current release entry" task:

![image](https://user-images.githubusercontent.com/2423362/27515374-2bf88a38-59e5-11e7-9674-73915a1398d2.png)

😉
