### ISSUE TITLE
Error message after updating user profile

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/backdropcms.org#402]
Whenever you update your user profile at the bcms.org site it triggers an error message:

````
Error 404 Not Found for site at https://forum.backdropcms.org/

**Comment by klonos** [comment]
Must be related to our single sign on setup/modules.

**Comment by jlfranklin** [comment]
Just got this myself.

**Comment by jlfranklin** [comment]
I just updated my user profile and got a similar message:

```
    Error 404 Not Found for site at https://localize.backdropcms.org/
    The changes have been saved.
```

**Comment by BWPanda** [comment]
I believe we've since turned off the SSO feature, and I can indeed update my profile without errors. So closing this issue.
