### ISSUE TITLE
Backdrop statistics missing on site

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/backdropcms.org#403]
Could it be nice to have some backdrop statistics on the site, like total downloads and active installs of core. I'm getting ready my presentation of backdrop for nextweek and cannot find an updated statistics on backdrop.

**Comment by serundeputy** [comment]
https://backdropcms.org/project/backdrop Gives downloads and actives.

**Comment by robertgarrigos** [comment]
Thansk @serundeputy I'll use this. It's a shame that this link can not been found
