### ISSUE TITLE
Start a Security mailing list and automate sending of security announcements

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#404]
We should provide a mailing list that people can use to be notified of security updates. Even better, it would be great if this mailing list was an automated process based on security announcements being created on backdropcms.org.

Drupal uses a similar approach for their announcements on Drupal.org, it seems like we should be able to port the solution used there.

**Comment by serundeputy** [comment]
@quicksketch is the d.org code public somewhere so we can look at the `anouncements` to port?

**Comment by serundeputy** [comment]
I think this is it: https://www.drupal.org/project/drupalorg

**Comment by serundeputy** [comment]
I've added this field `field_security_mailing_list` to the user profile and functionality to send email to people who subscribe via that field in `borg_mailers/borg_mailers_security`.

<img width="1225" alt="screen shot 2017-07-19 at 4 37 06 pm" src="https://user-images.githubusercontent.com/6763671/28388446-c2d55044-6ca0-11e7-99f6-fe67a9ae703c.png">

@jenlampton There are these cofig files in `live-active`:

```
	../config/live-active/field.field.field_security_mailing_list.json
	../config/live-active/field.instance.user.user.field_security_mailing_list.json
```

Do I commit those to the PR and they will land in  the right place on the server?

**Comment by jenlampton** [comment]
You should commit them in the `dev-active` directory. The workflow is to `git pull` but then `Config -> Sync` and it should be the sync that copies them into `live-active`.

**Comment by olafgrabienski** [comment]
@serundeputy I just wanted to look if the setting is already on the borg website, and it is, nice! Actually at the first sight I missed it, I guess because there's no label, maybe better to add one?

Screenshot:

![screen-borg-user-edit](https://user-images.githubusercontent.com/14188307/28530651-d850df22-7094-11e7-88fc-4fa6e85fffad.png)

**Comment by serundeputy** [comment]
@jenlampton re https://github.com/backdrop-ops/backdropcms.org/issues/404#issuecomment-317459537 do you think we should move this checkbox for the Security Mailers into the `CONTACT SETTINGS` fieldset?

**Comment by jenlampton** [comment]
That's exactly what I was thinking. But maybe we should also change the label from "Contact settings" to something more general, like "Email subscriptions" or similar?

**Comment by serundeputy** [comment]
@jenlampton PR here: https://github.com/backdrop-ops/backdropcms.org/pull/420
<img width="1301" alt="screen shot 2017-07-25 at 8 59 00 am" src="https://user-images.githubusercontent.com/6763671/28573141-9df52b8e-7117-11e7-9e2e-a4820280f272.png">

**Comment by jenlampton** [comment]
Thanks for the quick turn around on this @serundeputy!

I'm not sure I'd call contact form email a subscription - I know I recommended that earlier, sorry - thinking about it further I think maybe `Notification` might be a better word. 🐼 

I left some feedback on the PR about code style that's less important, just thoughts. Take it or lave it ;)

**Comment by serundeputy** [comment]
PR updated: https://github.com/backdrop-ops/backdropcms.org/pull/420

* simplified code
* fieldset title is now `Email Notifications`

**Comment by jenlampton** [comment]
Merged and deployed, thank you @serundeputy !
