### ISSUE TITLE
Make backdropcms.org dev easy peasy.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#407]
Adding a `.lando.yml` file will allow users to spin up a local dev env with lando (Kalabox v3) with ease.

If a user is not using lando the file will not cause any harm.  If the user is using lando it is a convenience.

Dev gets:

* dev stack
* drush + backdrop drush extension
* db port is set to 3308

Installing lando: https://docs.lndo.io/installation/installing.html

**Comment by jenlampton** [comment]
looks good. go ahead and push :)

**Comment by serundeputy** [comment]
merged; closing.
