### ISSUE TITLE
[DX] Upgrade BackdropCMS.org server to PHP 7.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#412]
Consider upgrading BackcdropCMS.org production server to PHP 7.

In #243 I got into trouble using type hinting on function definitions which is incompatible with the servers current PHP 5.4.

Upgrading to PHP 7 will allow developers/BackdropCMS.org to take advantage of new features of PHP and should give us a performance boost too.

If we do update to PHP 7 we should update `.lando.yml` to use PHP 7 as well.

**Comment by klonos** [comment]
php7 => make the site faster => make google ranking happier.

I say lets take the dive and upgrade to php7. It will need to happen at some point, so better sooner than later I guess.

**Comment by quicksketch** [comment]
I think this will be covered in https://github.com/backdrop-ops/backdropcms.org/issues/479.
