### ISSUE TITLE
Change `.lando.yml` to use PHP 5.4 for production parity.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#413]
Change `.lando.yml` to use PHP 5.4 for production parity.

----
PR: https://github.com/backdrop-ops/backdropcms.org/pull/414

**Comment by serundeputy** [comment]
I filed a PR for this and was going to merge it, but then I realized that with PHP 5.4 we can not use drush either on the server (which we currently don't anyway) or on the local.

So, on the one hand this production parity will prevent things like #243, but on the other we can not use drush to speed local dev.

Ultimately I think it is time to upgrade the server to PHP7 #412 .

**Comment by klonos** [comment]
php7 => make the site faster => make google ranking happier.

I say lets take the dive and upgrade to php7. It will need to happen at some point, so better sooner than later I guess.

**Comment by jenlampton** [comment]
merged. thank you!
