### ISSUE TITLE
Node add form in a block causing logged in users to scroll below the fold on page load.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#415]
reported by @klonos in gitter.

>Noticed that when logged in and visiting our home page, the first field of the "Show your support for Backdrop CMS" form is automatically selected, which makes the page scroll all the way down. Not good.

----
PR: https://github.com/backdrop-ops/backdropcms.org/pull/416

**Comment by jenlampton** [comment]
This was deployed today as well.
