### ISSUE TITLE
Quick user guide is wrong about creating layouts

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/backdropcms.org#417]
On this page https://backdropcms.org/user-guide/quick-start it gets it wrong about creating a layout for an existing node. The wrong way is to try create a static path with the same alias.

**Comment by jenlampton** [comment]
Thanks @herbdool that was indeed incorrect. I have taken a stab at a correction, can you give it a read and let me know if it makes sense?
https://backdropcms.org/user-guide/quick-start

**Comment by herbdool** [comment]
@jenlampton much better!

**Comment by jenlampton** [comment]
Great! :) Closing this issue.

**Comment by olafgrabienski** [comment]
@jenlampton Had also a quick look at the User guide, looks indeed good!

One little thing: I guess the first slash in `The node ID is the number between '/node' and '/edit'` should be at the end. Not `'/node'` but `'node/'`.

**Comment by olafgrabienski** [comment]
@jenlampton Sorry, but now I'm not sure which one is correct. Got confused by the slashes without the number inbetween, too abstract! (Maybe we could give an example in the guide, like "node/**23**/edit".)

**Comment by jenlampton** [comment]
ooh, that's a better idea! https://backdropcms.org/user-guide/quick-start
