### ISSUE TITLE
"we support Backdrop CMS" not showing entry just added.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#42]
I added twinz.gr + our logo (got a message about success too), but it is not showing up with the rest of the supporters. Does it need to be moderated/approved first or a bug perhaps?

**Comment by quicksketch** [comment]
Hi @klonos! Yes, we review them all manually. Some jokester thought it would be funny to upload a bunch of other people's logos at one point. :stuck_out_tongue: 

Looks like there a whole bunch queued up. I'll go through them and publish. Thanks!
