### ISSUE TITLE
Draft blog post on Backdrop 1.8

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#425]
We need to write a blog post for Backdrop 1.8, so we'll need to pick some new features to highlight. Let's review the list of things that were committed and pick our favorites:

How about:
* Config overview page overhaul
* Progress bar &  Task list (update.php) styling
* Unpublished indicator in Basis
* Expand all checkbox

Relevant issues for these are as follows:
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2803">#2803</a>: Refresh design of progress bar to barber pole style.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/991">#991</a>: Refresh update.php and task list styling.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2269">#2269</a>: Add an unpublished indicator to the Basis theme.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1178">#1178</a>: Add icons to the configuration overview page.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2828">#2828</a>: Fix the sort order on the configuration overview page, and make the page responsive.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2773">#2773</a>: Add 'expand all' checkbox on menu block config form.

Anyone want to take a stab at a post w/ screenshots for us? It should go live on release date, Sept 15th.

**Comment by klonos** [comment]
@jenlampton can you please add the respective issue links for these features. I have not been around lately and have lost track. If I manage to find time to work on the blog post, it would help to have those links. Thanks in advance 😉

**Comment by jenlampton** [comment]
Yes @klonos, added!

**Comment by jenlampton** [comment]
an unpublished indicator to the Basis theme:
<img width="1413" alt="screen shot 2017-09-21 at 4 13 28 pm" src="https://user-images.githubusercontent.com/397895/30722781-e35be0d4-9ee7-11e7-84c3-6c1d2e1d0def.png">

**Comment by jenlampton** [comment]
configuration overview page with new icons, better sort order, and responsive design:
<img width="1413" alt="screen shot 2017-09-21 at 4 13 28 pm" src="https://user-images.githubusercontent.com/397895/30722898-7ef9d686-9ee8-11e7-95df-d6e5e063d2b3.png">

**Comment by jenlampton** [comment]
Here is the 
<img width="587" alt="screen shot 2017-09-21 at 4 25 55 pm" src="https://user-images.githubusercontent.com/397895/30723084-d1aaf9ea-9ee9-11e7-9692-66439ce488db.png">
'expand all' checkbox on menu block config form.

**Comment by jenlampton** [comment]
Update screen: task list and progress bar styling updates:
<img width="865" alt="screen shot 2017-09-21 at 4 47 16 pm" src="https://user-images.githubusercontent.com/397895/30723503-b73afc56-9eec-11e7-9e0a-06e74792f57d.png">
