### ISSUE TITLE
Blog post on Backdrop4Good

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#426]
@serundeputy or @saintlynn would either of you like to do a blog post on backdropcms.org about Backdrop4Good?

**Comment by serundeputy** [comment]
@jenlampton ready for review:
https://backdropcms.org/news/backdrop-4-good

**Comment by jenlampton** [comment]
@serundeputy this looks great!  I added a featured image, do you think thats okay? https://backdropcms.org/news/backdrop-4-good
If so, we are good to publish :)

**Comment by serundeputy** [comment]
@jenlampton thanks published!
