### ISSUE TITLE
Add Links to Hangout and Gitter On Developers Page

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-ops/backdropcms.org#428]
I initially went to https://backdropcms.org/developers to look for the weekly meeting links or info. I ended up clicking around and found them linked to the resources page in the sidebar of https://backdropcms.org/news. 

I think adding a link to the developer page pointing to https://backdropcms.org/resources makes sense. Also adding the Gitter link (https://gitter.im/backdrop/backdrop-issues) to the resources page would be handy.

**Comment by alexfinnarn** [comment]
I guess this could also be a request for editorial access, if you don't think I'm too crazy...

**Comment by jenlampton** [comment]
We've recently added the resources sidebar pretty much everywhere on b.org. But if you still want editorial access, let me know!
