### ISSUE TITLE
"Extend with Modules" page doesn't explain where to install modules

### ISSUE THREAD

**Issue by behindthepage** [backdrop-ops/backdropcms.org#43]
https://backdropcms.org/guide/modules

>Upload the module to your site.
>* Move the extracted files to your web server. You can do this using FTP, but we highly recommend using Git.

This would be better:

>Upload the module to your site.
>* Move the extracted folder into the modules directory in your site root. You can do this using FTP, but we highly recommend using Git.

Or like the theme instructions (but I think this is confusing for noobs)

>Upload the module to your site.
>* FTP/Copy/SCP/Git pull the extracted folder into the modules directory in your site root.

Regards
Geoff

**Comment by quicksketch** [comment]
Thanks @behindthepage! Fixed to use your first suggestion.
