### ISSUE TITLE
[UX] A "my account" link is missing from the main menu

### ISSUE THREAD

**Issue by opi** [backdrop-ops/backdropcms.org#432]
When logged out from backdropcms.org, I can see a "Login / register" link, sending me to the `/user/login` page.
Once logged in, I'm redirected to the `/account/opi` page, which is nice. The previous "Login / register" link is replaced with a "Log out" link, which is also nice. But now, there is no link to view (and edit) my profile, nowhere.

Solution : Add a "My account" link before the "log out" one, and maybe replace the latest with a cross (X) for saving extra width.

**Comment by opi** [comment]
Related issues: https://github.com/backdrop-ops/backdropcms.org/issues/351, https://github.com/backdrop-ops/backdropcms.org/issues/301

**Comment by docwilmot** [comment]
I'm considering the same issue on the forum website. Would a footer menu help here?

**Comment by jenlampton** [comment]
I'm going to close this issue as the account link should now be in the header for both b.org and f.b.org

**Comment by opi** [comment]
Thank you very much
