### ISSUE TITLE
Add breadcrumbs to the User Guide (book) pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#441]
This is a follow-up to https://github.com/backdrop-ops/backdropcms.org/issues/334

> Breadcrumbs are important part of navigation and can reduce the number of actions needed for a visitor to get to a higher-level page. Breadcrumbs reduce the overall website bounce rate and improve the findability of sections and pages.

Breadcrumbs were left out of the design specifically because we are going for an aesthetic that reads "simple". Too many bells and whistles clutter the page, and go against that part of our brand.

That said, I think it would make sense to include breadcrumbs on pages where they might actually add some value - like maybe the User Guide - but they aren't necessary on most places on backdropcms.org. Since Backdrop itself includes them out of the box, I don't think it's necessary to put them all over backdropcms.org just to prove we can. There are hundreds of features in Backdrop and it wouldn't make sense to demonstrate them all :)

**Comment by docwilmot** [comment]
I think this is unnecessary; the guide already has the book navigation at the bottom of each article, plus theres a sidebar table of contents. Thast enough I'd say.

**Comment by jenlampton** [comment]
fair enough.
