### ISSUE TITLE
Make the backdropcms.org home page easier to read

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#444]
Summary of changes in the screenshots below (for consideration)
- [x] center-align text in left column
- [ ] ~ALL CAPS the longer headings in the left column~
- [ ] ALL CAPS the shorter headings in the right column
- [ ] decrease the size of the icons for comments, commits, and members

Got this via email from Tom:

> I am not a designer by trade but I had an art background. Either way I spent about 15 minutes changing at things and was just curious on your thoughts. There is nothing big just changes for consistency and readability etc.

![unnamed](https://user-images.githubusercontent.com/397895/37072003-2e040742-2174-11e8-9e92-2b2bccdd615e.jpg)

**Comment by jenlampton** [comment]
I also prefer the left-aligned text, but I find the ALL CAPPS headings harder to read, especially for the longer headings in the left-hand column. I'm also not sure that the ALL CAPPS style goes with our brand, which is supposed to be simple and friendly. 

I can't tell what other changes have been made, but maybe if we can get a list we'll be able to discuss each, and reproduce!

**Comment by olafgrabienski** [comment]
Agreed, the left-aligned text is much better.

**Comment by tommyent** [comment]
First it looks like I sent the wrong screenshot but off the top of my head. 
Left align text
Capitalized headings.
Added background to call to action buttons. (download and demo)
Top social icons white to match the rest of the menu.
Background and border color on buttons, links and icons pulled from hero background.
Thinned out headings
??

**Comment by klonos** [comment]
👍 for left-aligning the text.
👎 to ALL CAPS in general
👍 to smaller icons for comments, commits, and members
👍 for white social icons to match the menu (although not sure about what the hover-over effect should be)
...would have to see higher-res mockups to tell for button color (would also like to know what the hover color would be). same for thinned headings.

**Comment by docwilmot** [comment]
Yes to left-aligning, no to all else.
I think the larger comments, commits, and members icons fit the space better
I think the white social icons would clutter the header.

**Comment by Graham-72** [comment]
I very much prefer the main tagline (A free and Open Source CMS for small to medium sized businesses and non-profits) to be mainly in lower case and centred as it is now, but to me it looks too long on a desktop screen and could do with a line-break to split it more evenly over two lines. It looks much better on my phone in both portrate and landscape because the lines are shorter.

**Comment by jenlampton** [comment]
I've left aligned the text in the left hand column based on feedback from our designer during the more recent home page changes. Since there is no consensus on the other items here, and the home page is quite different now than it was when this was opened, I'm going to close this issue.
