### ISSUE TITLE
[Docs] Add a new link field to the "Documentation" content type.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#448]
This is for cases like #377, where we need to add documentation originally posted in a 3rd party site, but still need a way to offer credit attribution to the original author.

I would like to add a link field to the "Documentation" content type, called "Original source".

@jenlampton ^^ ??

**Comment by jenlampton** [comment]
go ahead! do you have access?

**Comment by klonos** [comment]
https://backdropcms.org/user-guide/moving-backdrop-your-local-live-server-using-cmi :) ...now we need some minor theming changes in order to make the new field match the 2 existing ones (Documentation Level/Status): https://github.com/backdrop-ops/backdropcms.org/pull/450

PS: I have merge permission! ...I feel dangerous 😈 😁

**Comment by jenlampton** [comment]
=P

**Comment by klonos** [comment]
This is done :)
