### ISSUE TITLE
Include security release info in the Timeline section of the Release Cycle page

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop-ops/backdropcms.org#454]
We might want to add a dedicated section to the Release Cycle page about security releases, describing the embargo for releasing information about the vulnerabilities, how we will give notification that a security release is coming out at a scheduled time, and how people can get on the list to get those notifications.

https://backdropcms.org/releases

**Comment by mikemccaffrey** [comment]
Okay, I seem to have re-written the entire Timeline section of the Release Cycle page. Please let me know what you think of it, especially @jenlampton, @serundeputy, and @quicksketch who will actually be doing the releases.

# Timeline

### Minor releases

Minor releases that provide new features, API additions, and UX improvements will be made every 4 months on the 15th of January, May, and September.

There is a two-week feature freeze that precedes each minor release, during which no new features will be committed and development efforts will be focused on testing changes and fixing technical issues.

### Patch releases

**Bug-fix releases** will be made as necessary to to fix any technical or functional issues that have been identified in previous versions. Since no features will be introduced or changed, they are usually released when ready and not scheduled ahead of time.

**Security releases** are made shortly after any vulnerabilities have been identified and a technical fix has been prepared. Details about any vulnerabilities that have not been publicly disseminated will be embargoed until a scheduled release date (concurrent with Drupal when applicable) and announcements will be made ahead of time to notify site maintainers that they will need to take action.

 _Link: Learn more about our security process and subscribe to security update emails._

### Major releases

Any changes to core features or APIs that would break currently-installed Backdrop sites are reserved for major releases, in order to give site owners and contributed module developers time to upgrade their code and systems to work with the new platform. 

No major releases are currently planned, but in the future they may happen every 2 to 3 years as the needs of our users evolve over time. 

After a major version is released, only minimal changes will be made to previous versions of Backdrop, although security releases will continue to be provided for all supported branches whenever a vulnerability is identified.

**Comment by jenlampton** [comment]
Looks great @mikemccaffrey !

**Comment by olafgrabienski** [comment]
Nice! As far as I know, UX improvements go also in patch releases.

**Comment by mikemccaffrey** [comment]
> @serundeputy : I'm not super opinionated about it, but my brain wants to switch the order of the Minor releases and Patch releases sections so that they are in order.

That is how the site currently is, but it seems kinda weird to start a "Timeline" section with something that happens randomly, rather than the releases that happen according to schedule. 

There is plenty of other content on that page that puts the major, minor, and patch releases into context, so I'd like to keep minor releases as the leading item in the timeline section, unless anyone seriously opposes.

> @olafgrabienski: Nice! As far as I know, UX improvements go also in patch releases.

Okay, I changed the text to say that significant UX improvements will happen in minor releases, and that some small UX changes will happen in patch releases. 

Since there was general approval of the text, I'm going to go ahead and make the change to the b.o site.

**Comment by BWPanda** [comment]
@mikemccaffrey The issue I mentioned is still there:

"Bug-fix releases will be made as necessary to to fix any technical issues..."

Two 'to's.

**Comment by serundeputy** [comment]
thanks @BWPanda I've removed on of the `to`s.
