### ISSUE TITLE
Link Download Backdrop To "Try Backdrop"

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-ops/backdropcms.org#459]
I saw https://github.com/backdrop/backdrop-issues/issues/2759 while browsing through issues, and I looked more at it because I'm recommending using Lando for Backdrop development over any other dev solution.

I think it'd be great if the "Download Backdrop" link on https://backdropcms.org/ became "Try Backdrop" and linked to https://backdropcms.org/try-backdrop. There you could list the download info in more detail and the Pantheon + local dev links are already there.

If I'm a new user, I might just click download and be confused about how to run a local site. One of my issues with Drupal was the multitude of dev environment tools and the decision fatigue of evaluating them and trying to keep up-to-date about which one was "best".

I follow Laravel somewhat, and I like that they recommend the PHP built-in server for starters, Valet for simple but better setup, and then Homestead for a VM solution if you need that to really configure your application. I didn't have to evaluate 10 different solutions and each "use case" only had one recommended option. 

Anywhoo, I think new users would miss the "Try Backdrop" page and have to search for a local dev solution with the current frontpage set up...Also, then you could have a "Contribute" button that could list ways to contribute, e.g. https://backdropcms.org/contribute. 

I think "how can I try this out quickly for a demo and then locally for development?" and "how can I contribute if I like this?" are two good action buttons/links for that hero section.

**Comment by klonos** [comment]
@alexfinnarn I hear you re introducing a "Contribute" link, but I think that we should keep the download button/link as is. If there's something that needs to change IMO, then that is the "Try a demo" button. We are currently using that to redirect people to Pantheon. Pantheon does not include us in the list of supported CMSs:

<img width="1016" alt="screen shot 2018-07-25 at 6 06 31 am" src="https://user-images.githubusercontent.com/2423362/43163257-f524beaa-8fd0-11e8-8392-d3ed15d9bae5.png">

...while ddev list us [on their home page](https://www.drud.com), and in their [promo video](https://youtu.be/rj4WTnZcjjY?t=57):

<img width="1228" alt="screen shot 2018-07-25 at 5 57 03 am" src="https://user-images.githubusercontent.com/2423362/43162927-e000b8a4-8fcf-11e8-91c4-0f10cb04c273.png">

<img width="800" alt="screen shot 2018-07-25 at 5 58 39 am" src="https://user-images.githubusercontent.com/2423362/43162988-12c15e10-8fd0-11e8-8911-a49394af9d1f.png">

...same goes for Lando:

https://docs.devwithlando.io/tutorials/backdrop.html

https://github.com/lando/lando#then-try-out-one-of-our-preconfigured-recipe-start-states

**Comment by jenlampton** [comment]
I think this issue may no longer be relevant since the the new "Demo" button provides a clear choice for those who want to try Backdrop.

See https://github.com/backdrop-ops/backdropcms.org/issues/422
