### ISSUE TITLE
Spelling mistake (bares -> bears)

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/backdropcms.org#465]
https://backdropcms.org/why-fork-drupal

> the code underneath **bares** very little resemblance to the Drupal of yesteryear...

Should be "bears".

**Comment by BWPanda** [comment]
Thanks, fixed!

**Comment by BWPanda** [comment]
(funny how I can make edits on backdropcms.org, but I can't close issues here...)

**Comment by serundeputy** [comment]
closing.
