### ISSUE TITLE
Wrong path to config directory on multisite installation

### ISSUE THREAD

**Issue by petiar** [backdrop-ops/backdropcms.org#47]
Hi everybody,

after installing Backdrop CMS as multisite installation I am getting this error:

`Exception: The configuration directory in settings.php is specified as 'files/config_6e725e8138933c0593de000d7d5bb4e7/active', but this directory is either empty or missing crucial files. Check that the $config_directories variable is correct in settings.php. in _backdrop_bootstrap_configuration() (line 2668 of /data/web/backdrop/core/includes/bootstrap.inc).`

while trying to access the homepage. After some digging I have found out that although my config files are successfully created in `sites/studiozavodou.sk/files`, Backdrop is trying to get them from `files/ directory` in installation root. I have proved this by copying my config files to this directory and this error disappeared.

I have tried to changed the config directory path in `settings.php` so I added the `sites/studiozavodou.sk` part at the begining of it, however, this caused another error, because it seems to that when Backdrop is trying to **update** config files, it uses correct base directory (`sites/studiozavodou.sk`), so this part got duplicated and Backdrop threw another exception, trying to update file in `sites/studiozavodou.sk/sites/studiozavodou.sk/files...`.

## Long story short (conclusion): ##
On multisite installation, Backdrop does not take the multisite base path into account while reading config files, but it does while trying to update them.

**Comment by petiar** [comment]
## Possible solution??? ##

On the line 2666 in `core/includes/bootstrap.inc` I have changed the code like this and now all works fine (although I do not not if this won't break something on non-multisite installation):

`$directory = conf_path().'/'.$GLOBALS['config_directories']['active'];`

**Comment by klonos** [comment]
@petiar: please close this issue here and copy it over at https://github.com/backdrop/backdrop-issues/issues

**Comment by petiar** [comment]
I am sorry for any inconvenience I have caused, I copied this issue over at the link you suggested and closing this one.
