### ISSUE TITLE
Warn users that they need to be "logged in" to Pantheon to set up a Demo

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#476]
We just got a question about this in the forums. 

https://forum.backdropcms.org/forum/so-whats-demo-icon-your-splash-page

If you click on the demo link without being logged into Pantheon, the results are not very helpful. 

This was discussed in this issue: https://github.com/backdrop-ops/backdropcms.org/issues/192

I recommend that we provide some wording on the BackdropCMS page that the demo will require account creation. While this may seem obvious, I don't think that the actual process is very clear.

**Comment by olafgrabienski** [comment]
I agree that the link to the Pantheon login page isn't very helpful for people who don't know this service. I'd suggest to point the link to https://backdropcms.org/try-backdrop instead. Pantheon is listed at top of this page, with respective instructions. (There are also other options -- Lando and DDEV at the moment -- which is also helpful im my opinion.)

**Comment by jenlampton** [comment]
As a quick fix I changed the text on the button to "Install on Pantheon" but longer term we want a demo site that doesn't involve signing up (or logging in) to anything other than the demo site. Nate is working on that in https://github.com/backdrop-ops/backdropcms.org/issues/422

**Comment by stpaultim** [comment]
We have the new TugBoat demos. I would consider this issue fixed.
