### ISSUE TITLE
A way to follow/watch backdrop-contrib (for new projects added).

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#48]
Can we figure a way so that people can be informed of new additions to https://github.com/backdrop-contrib please?

**Comment by klonos** [comment]
...I was talking about GitHub notifications, but we should have something on the official website. An RSS fee we could pull from github perhaps? Anyways, here's how they do it over at d.org in their [Download & Extend page](https://www.drupal.org/download):

![drupal org-download_and_extend_page](https://cloud.githubusercontent.com/assets/2423362/5986850/d17beb12-a961-11e4-83f3-3aaee12ea105.png)

**Comment by quicksketch** [comment]
We can't get started on this until we port the main site (https://github.com/backdrop-ops/backdropcms.org/issues/38) and have information pulled into the site in the first place (https://github.com/backdrop-ops/backdropcms.org/issues/8). However, after that, this may happen as a side-effect.

**Comment by sirkitree** [comment]
If you're a part of the backdrop-contrib group, you actually get email notifications for every repo added. But I assume we want to get this information out to others who may not be part of the group. We could accomplish this through the github api, either integrate the list into the site with JS or create some sort of RSS feed.

**Comment by klonos** [comment]
Yeah, I was talking about having this available on the main website for unregistered site visitors (also the ones with out a GitHub account). The idea is pretty much to do the same as the "Ne Modules" section of d.org.

**Comment by jenlampton** [comment]
We could set up a RSS feed for the modules/themes/layouts pages. As well as one for all projects. What do you think?

**Comment by thejimbirch** [comment]
An RSS feed would be good to tweet out too this information too. @jenlampton

**Comment by mikemccaffrey** [comment]
Well, we could also mention new contrib modules on our weekly calls. We've been listing numbers of modules created and released, so it doesn't seem that much extra to quickly say what the new ones are.

**Comment by klonos** [comment]
Anyone up for a "Daily (or Weekly) Dose of Backdrop" website?

**Comment by jenlampton** [comment]
I like that, we can announce which projects are new to the party! but also: https://backdropcms.org/project/rss.xml

**Comment by thejimbirch** [comment]
Could you either add to, or duplicate the functionality for themes and layouts?  I think new themes would be a really good thing to promote.

**Comment by jenlampton** [comment]
This list is all projects (modules, themes, and layouts)

**Comment by thejimbirch** [comment]
https://media.giphy.com/media/p09CHJZLR0L4s/giphy.gif

I am just going to quietly leave the room.
