### ISSUE TITLE
Add Backdrop usage count in our Showcase page

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#482]
We should be grabbing the total count of sites using Backdrop and adding it dynamically in [our Showcase page](https://backdropcms.org/showcase). Mockup:

<img width="1107" alt="screen shot 2018-11-14 at 11 35 20 am" src="https://user-images.githubusercontent.com/2423362/48452072-817f1200-e801-11e8-815a-df3ecc293cd9.png">

...we could link the number to https://backdropcms.org/project/usage or https://backdropcms.org/project/usage/backdrop

--------

PR: https://github.com/backdrop-ops/backdropcms.org/pull/496

**Comment by klonos** [comment]
related: #481

**Comment by quinnanya** [comment]
I really like tying that number to that page -- I know you can get to that number elsewhere, but it's helpful to see it in the context of specific examples.

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop-ops/backdropcms.org/pull/496

![image](https://user-images.githubusercontent.com/6763671/51793616-25395680-2191-11e9-8183-75a6decfb107.png)

Not sure if I got the CMI part correct; my local wouldn't work if I pointed my `active` directory to `dev-active`; so I pointed to `live-active` placed the block then copied the changes to `dev-active` and committed that. :woman_shrugging:

**Comment by jenlampton** [comment]
You can always import a fresh db, and then manually copy everything from live-active to dev-active and commit it all.

**Comment by klonos** [comment]
(not tested the actual thing - from the screenshot): It seems that we have too many titles and too much text in the header section of that page (and I also do not like the words "use" and "using" here). We could shorten the whole thing to something like:

> 730 websites currently built with Backdrop CMS
> Here are a few examples. [Add your own!](https://backdropcms.org/node/add/showcase)

**Comment by jenlampton** [comment]
What about:
`Number of websites running on Backdrop CMS:730`
`Here are a few examples. Add your own!`

**Comment by BWPanda** [comment]
Here's a new PR inspired by @serundeputy's: https://github.com/backdrop-ops/backdropcms.org/pull/712

And here's what it looks like:

![image](https://user-images.githubusercontent.com/2385329/95074515-6c475f80-075a-11eb-8554-895008ab8e17.png)

Rather than displaying the exact number (which looked odd in a title), I rounded down to the nearest hundred. And I aslo added a '+' after the number since that's only the number of sites that report back, there are likely more we don't know about.

**Comment by BWPanda** [comment]
I wonder if we should put a link to the source of that number in there somewhere...? Something like:

![image](https://user-images.githubusercontent.com/2385329/95075080-52f2e300-075b-11eb-92e7-f6b079c8db17.png)
