### ISSUE TITLE
January 2019 Newsletter

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#491]
See topic: [Send Regular Newsletters](https://github.com/backdrop-ops/backdropcms.org/issues/177)

Starting a specific issue for thoughts on content for a January newsletter. I am thinking that it might make sense to try and publish monthly. In the January Newsletter, I would include:

1. Information about the pending Birthday and links to blog post and discussion about hosting events.
1.1 https://forum.backdropcms.org/forum/backdrop-birthday-party-jan-15th-2019
1.2 https://backdropcms.org/news/help-celebrate-backdrop-cms-birthday-your-community 
2. Notes about how people can help with the release of v 1.12.0
3. Some highlights of features that should be expected in v. 1.12.0
4. Software Conservancy (??)
5. Links to some recent topics in the forum
5.1 [A feedback from a novice](https://forum.backdropcms.org/forum/feedback-novice)
5.2 [Feedback on Backdrop 1.11](https://forum.backdropcms.org/forum/feedback-backdrop-111)
5.3 [Typical day user experience -- a future-state story](https://forum.backdropcms.org/forum/typical-day-user-experience-future-state-story)
5.4 [How do I Test a Pull Request](https://forum.backdropcms.org/forum/how-do-i-test-pull-request)
6. [Virtual User Group](https://forum.backdropcms.org/forum/virtual-backdropcms-user-group)
7. New modules or themes
7.1 [Corporate KISS Theme](https://github.com/backdrop-contrib/corporate_kiss)
7.2 [Geocoder Module](https://backdropcms.org/project/geocoder)
7.3 [Prism Module](https://github.com/backdrop-ops/contrib/issues/304)
7.4 [Vimeo Link Formatter](https://backdropcms.org/project/vimeo_link_formatter)
7.5 [Headless](https://backdropcms.org/project/headless)

**Comment by klonos** [comment]
I cannot think of anything specific to add to the list @stpaultim, but please go ahead and produce a draft if you have the time/energy. Ping me on Gitter if you need a review 😉

**Comment by serundeputy** [comment]
@stpaultim 

* not sure about mailchimp or not, but the footer of a previous email newsletter from Backdrop does have mailchimp in the footer so probable

* I think for `7`. you should include new releases as well, one such release is: 
  * [headless 1.x-1.1.0](https://github.com/backdrop-contrib/headless)

**Comment by stpaultim** [comment]
Here is a rough draft. It would be great to send something out before the virtual user group on Tuesday.

https://us8.campaign-archive.com/?u=0cc417ae7c070ec2adedbd87b&id=b0174e06d2

**Comment by stpaultim** [comment]
I went ahead and move the content into a Google Doc that anyone can edit. It was helpful for me to start in the newsletter format, but this is easier for group editing. What is missing or needs to be changed?

https://docs.google.com/document/d/1gnJBWqvf5L8kzUgk4r4LviW6Sm9_mak4wY3Oh-EumAg/edit#

**Comment by serundeputy** [comment]
@stpaultim did this go out? ready to close?

**Comment by stpaultim** [comment]
I'm not sure that this particular newsletter ever went out. But, I think it's safe to close this issue as it's too late to send out the January newsletter and the content has all changed. 

We might want to open an issue like this each month in the future as we get back into a newsletter routine.
