### ISSUE TITLE
10 day virtual sprint on backdropcms.org and forum.backdropcms.org

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#494]
**UPDATE:**
As per the discussion on the outreach call yesterday, some of us (@serundeputy, @jenlampton and @stpaultim)  are going to try to focus energy on www.backdropcms.org and forum.backdropcms.org over the next 9 days. 

Nov 16-24

In addition to working on our own, as we have time, have set some specific times to work together this Sunday and next Sunday. Please, feel free to join us:

Nov 17th - Time zone info = https://bit.ly/2CJz0ib
Nov 24th - Time zone info = https://bit.ly/352Z04b

I set this up for 12:00pm - 4pm (Central Time USA - both days) Some users may start earlier or work later on either day. This is just the best time to participate. We will probably open a zoom conference room for at least part of this time.

----
**ORIGINAL POST**

I'm going to propose that we take a week in late ~~January or early February (after 1.12 release)~~ and focus on backdropcms.org and forum.backdropcms.org.

Trying again in Nov 2019. 

I'll even nominate ~~Feb 1 - Feb 10~~ Nov 16-24, which is just over a week and includes two weekends. The idea is simply that for that 10 days, we strongly encourage the community to offer feedback and contributions to help improve these important outreach tools for our community. 

Some ideas:

- Use ~~Jan 31 and Feb 7~~ Nov 21 Design/UX ~~and Outreach~~ meeting to really focus on these two websites and how we can use them better. Instead of simply addressing issues in the issue queue, schedule an open discussion on how to improve these sites (and create new issues). Promote these meetings to members of the community who don't come every week, might be interested in these topics. 
- Schedule lots of Tweets promoting issues in the backdropcms.org and forum.backdropcms.org queues and soliciting help.
- Schedule a virtual sprint (core mentoring style) on Saturday February 2nd to help onboard folks who would like help but need some guidance. 
- Blog about our work. Share usability tasks, ask the community to try a number of these tasks and report back to us. https://github.com/backdrop-ops/backdropcms.org/issues/492

Just a few of the current issues that need attention and/or discussion:

- [Usability Testing](https://github.com/backdrop-ops/backdropcms.org/issues/492) 
- [Create a Contributors Guide](https://github.com/backdrop-ops/backdropcms.org/issues/486)
- [Add Backdrop usage count in our Showcase page](https://github.com/backdrop-ops/backdropcms.org/issues/482) 
- [Home page “Demo” link update](https://github.com/backdrop-ops/backdropcms.org/issues/422)
- [Improve UX for modules / themes / layouts search pages](https://github.com/backdrop-ops/backdropcms.org/issues/442)
- ["Find Me Online" section of profile is broken](https://github.com/backdrop-ops/forum.backdropcms.org/issues/73)
- [META - Improve UI for following and unfollowing forums and conversations](https://github.com/backdrop-ops/forum.backdropcms.org/issues/74)
- [Make sidebar on forum collapsible](https://github.com/backdrop-ops/forum.backdropcms.org/issues/72)
- Many more.....

If there is interest. I can help with a lot of these items.

**Comment by serundeputy** [comment]
https://github.com/backdrop-ops/backdropcms.org/pull/496 `Add Backdrop usage count to /showcase page`

**Comment by larsdesigns** [comment]
Interesting...

**Comment by stpaultim** [comment]
I'm still interested in this. Clearly, we missed the dates I originally proposed. I've been super busy lately. I'd like to try and put this on the calendar sometime soon. Want to do this before we get close to next Backdrop CMS release.

**Comment by larsdesigns** [comment]
Still interesting...

**Comment by klonos** [comment]
This has now passed. OK to close @stpaultim ?

**Comment by stpaultim** [comment]
Gitter has been really busy the last week or two and the forum is getting more traffic than usual. We've heard from a few people about confusion in the forum and the need to fix some UX problems. 

I'm going to put another 10 day sprint on the calendar for myself to focus on working on the forum, addressing issues in the forum issue queue, and making it work better. If anyone else wants to help focus on that during this time frame, I welcome the help. 

Nov 16-24th, covers two weekends and one UX/Design meeting. I'm going to suggest that we make time during the Nov 21 UX/Design meeting to focus on the forum and how to improve it.

**Comment by stpaultim** [comment]
In Gitter today:

> As one of the newbies in question: part of the problem was, when I got to the forum, the activity there is pretty low compared to other dev forums I've been in. Which led to two possible conclusions, both of them off-putting: 1) very few people adopt this platform and come here to ask questions about it, and/or 2) the forum isn't the best place to ask questions and I should be looking somewhere else.

> Problem complicated by juggling tons of resources and having to keep straight where I should be for which. I'm in chats for Backdrop, D8, CiviCRM, and OpenSocial, and offhand I can recall being posted to hosted forums, StackExchange, Facebook groups, Twitter tags, Slack, Gitter, and likely a few I'm forgetting. Was Mattermost here or for someone else? I set up an account and don't think I ever actually looked there.

> So while having multiple options to find a support community is great, too many without a map can be daunting. Being invited to fill up the forum—yup, get that entirely, as a lot of my work offline is making sure that the community site I'm building will also avoid the ghost town effect.

> Suggestion (because I'm not sure who here is staff and who gets paid for this, if anyone): if the problem is a slow forum, but other areas are active, crossposting like you did with my questions is a fine idea. Each one of those "fills up" the last comment timeline, and would have pointed me here sooner than I found you.

**Comment by klonos** [comment]
Damn it! ...so many interesting things to work on, and only 24hrs in a day (to accomodate for work/rest as well). I wish I had more time to help ...and I always seem to gravitate around fixing UX issues in the admin UI of Backdrop the product 😅

**Comment by serundeputy** [comment]
@stpaultim 

If people are using lando for the sprints.

I know for me to recently work on backcdropcms.org issues I had to update the `.lando.yml` file to `mariadb:10.3` in order to import the databases from sanatize.backdropcms.org.

That fix is in https://github.com/backdrop-ops/backdropcms.org/pull/604 so if that does not get merged before your sprint that could be a blocker to people getting work done.

If we merge it you are fine.
If not merged you can manually add the config to your `.lando.yml` file:

```yaml
services:
  database:
    type: mariadb:10.3
    portforward: 3308

```

the forum site might need similar treatment.

**Comment by stpaultim** [comment]
@serundeputy - Thanks for this. I've yet to do any development or serious configuration for either backdropcms.org or the forum, so part of this sprint for me will be figuring out the process and workflow and potentially getting a local environment running. 

Thanks for sharing your lando config. 

I'm going to look at creating a github project today or tomorrow and I'll start to triage issues that I think are important or interesting. I'd welcome feedback from others. I also hope to use time during weekly meetings, this week and next, to talk about these issues.

**Comment by BWPanda** [comment]
Closing this old issue. I think if future sprints want to be organised, perhaps Zulip is better, or at least a new issue.
