### ISSUE TITLE
Hosting Updates

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#497]
To Do: 

I am running a little behind with creating the new Debian VMs. So I am planning to perform the following maintenance tomorrow night at around 11pm MST 01/31/2019 on the existing servers.

1. [x] Performing OS package updates and reboot. 
1. [x] Reboot the hosts. 
1. [x] Check Linode account for free upgrades.

I will also try and catch up the Sanitize project for the Forum site. If it has not been addressed yet.

**Comment by larsdesigns** [comment]
Just going to do it now.

**Comment by klonos** [comment]
Thanks @larsdesigns 👍
