### ISSUE TITLE
Errors when using unicode chars in content - no UTF8 support

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#498]
I tried creating a blog post that had 😊and 🐉in the body. When saving the node, I got an "unexpected error" and the content was not saved. This is what was logged:

```
EntityStorageException: SQLSTATE[HY000]: General error: 1366
Incorrect string value: '\xF0\x9F\x98\x8A\xF0\x9F...'
for column 'body_value' at row 1 in NodeStorageController->save()
(line 320 of /home/backdrop/repo/www/core/modules/node/node.entity.inc).
```

```
PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value:
'\xF0\x9F\x98\x8A\xF0\x9F...' for column 'body_value' at row 1:
INSERT INTO {field_data_body} ...
...
in field_sql_storage_field_storage_write() (line 444 of
/.../core/modules/field/modules/field_sql_storage/field_sql_storage.module).
```

I then navigated to the site status page, only to find that we have no UTF8 support enabled 😞("This feature is not supported on your system.")

**Comment by serundeputy** [comment]
confirmed.

**Comment by quicksketch** [comment]
As part of the Hosting Upgrades (#497) We now have Emojii (UTF8MB4) support on all BackdropCMS.org sites (Forum, API, Flagship).
