### ISSUE TITLE
Add a block on the sidebar of the dev section to allow/promote demoing the latest non-stable, pre-release version of core.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#499]
better summary to be added :)

**Comment by BWPanda** [comment]
We now have this: https://backdropcms.org/try-backdrop/dev (linked to from the Try Backdrop page). Considering the feedback we got when adding this was to not make it too prominent, I don't think we want to add it to a block in the sidebar... So closing.
