### ISSUE TITLE
Link support/services/contractors from somewhere so that people can find it

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#500]
Part of #194 

@jenlampton mentioned this during the outreach meeting today. We should link to it from the home page or the main nav menu.

**Comment by jenlampton** [comment]
Linked.... but the main menu only shows the top 2 levels. Should I change it to 3?

**Comment by BWPanda** [comment]
I think this is fine as-is now. The Contractors blocks shows up a lot on different pages, so is easily accessible that way too. Closing as done.

**Comment by jenlampton** [comment]
Does the block have a link to the contractors page now?

It didn't when was opened, and since there's no link in the menu to the
full page -- that page was impossible to find.

**Comment by BWPanda** [comment]
Yes:

![IMG_20220707_184241](https://user-images.githubusercontent.com/2385329/177731260-05b71e2f-17c0-4c15-901a-0115754395b5.jpg)

**Comment by jenlampton** [comment]
Great!

Hopefully people will be able to find that. It's not intuitive, if your
looking for contractors, to go to a different page and look for a block
with a link.

We can reopen this issue when we get complaints again.
