### ISSUE TITLE
Backdrop CMS Mini Camp

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#503]
PROPOSAL: That we partner with an upcoming Drupal Camp to host a 1 day mini-camp on a day normally used for trainings or summits. That we keep it pretty simple and use the day to host a full day of curated sessions, I assume just a single track.

GOALS: 

1. To have a focused in-person event for anyone considering Backdrop to attend tied to a larger Drupal event. 
2. To encourage the backdrop community to develop sessions beyond "Intro to Backdrop" and to record those events and get them on YouTubes. 
3. To get as many active members of Backdrop CMS community together in one place as possible.
4. To promote this as a Backdrop event co-located at a Drupal event as opposed to simply a session/training.  
5. To get 10 active members of the Backdrop CMS community in one place at one time. 

LOCATION: 

I think the two most likely locations are Twin Cities Drupal Camp OR Badcamp, because of the fact that we have active members in those communities to handle logistics and to coordinate with the camps. Also, we know these camps to be very Backdrop CMS friendly. Other camps might also qualify. 

(Not sure if we are ready for this, but wanted to raise the idea for discussion early enough to potentially include in TC Drupal this year. I am adding this to outreach agenda for today.)

**Comment by jenlampton** [comment]
Yes please! I like the idea of a mini camp :)

**Comment by stpaultim** [comment]
We discussed this idea briefly near the end of the last [outreach meeting](https://www.youtube.com/watch?v=sA6xXbtugac&index=51&t=0s&list=PLE6f8hiqhhJnxKG-_r9TP2UanfWpvFFmk). 

There seems to be interest in the idea. There was some discussion about whether to focus on 1 or 2 camps, with Twin Cities Drupal Camp and Badcamp the strongest contenders. We decided to pitch the idea to Twin Cities Drupal Camp first and gauge interest, before making any decisions. As I'm at least marginally involved in planning Twin Cities Drupal Camp, I'm planning to reach out to the committee this week for feedback.

**Comment by klonos** [comment]
I really like this idea as well 👍 ...I just wish there was an easy way to tell how many Backdrop people are based down-under, so we can organize something in the land of plenty 😄

**Comment by jackaponte** [comment]
I really like this idea! I'd somewhat selfishly wish for it to be hosted adjacent to BADCamp, at least at first. (I think it also makes good sense for a variety of other reasons besides me not having to pay to travel elsewhere to attend, lol!)

**Comment by AmyJuneH** [comment]
I'm sure FloridaCamp would be alright with this... but that's not until Feb 2020!

I can add it to the BADCamp planning agenda??

**Comment by jenlampton** [comment]
Yes please!

**Comment by AmyJuneH** [comment]
I put a comment on the next agenda.
https://docs.google.com/document/d/1ZT_UtCYY2pqi4RtIBAFxmsSVL-35gayhhYxjwc8XOxs/edit#heading=h.5fnf5z2rq7gh

**Comment by stpaultim** [comment]
https://www.drupal.org/project/tcdrupal2019/issues/3037824

**Comment by stpaultim** [comment]
We had the first mini-camp in JUNE at Twin Cities Drupal. I need to write up a blog post.

**Comment by oadaeh** [comment]
@stpaultim did you write that blog post? Does it even matter at this point? Should this just be closed now?
