### ISSUE TITLE
Improve "Upgrade from Drupal 7" documentation

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/backdropcms.org#509]
On the page https://backdropcms.org/upgrade-from-drupal we have detailed step-by-step instructions about upgrading a Drupal 7 site to Backdrop. I've recently upgraded a D7 site to Backdrop. I had some problems to get the upgrade process running, but at the end I managed to do the upgrade. The instructions were generally helpful. I had however several questions that are not covered by the documentation. Other subjects are covered but not clear enough, in my opinion.

I'll make some improvement suggestions below. Will also post some questions to better understand the upgrade process, and its prerequisites.

**Comment by jenlampton** [comment]
I made a few minor updates to the https://backdropcms.org/upgrade-from-drupal page, but I'd love to know exactly what issues you ran into so we can address those directly.

**Comment by olafgrabienski** [comment]
@jenlampton Thanks for starting to update the documentation, I'll have a look at it.

Regarding the issues, I don't remember them very exactly. I had made four or more attempts to run `update.php`, was quite surprised that it didn't run smoothly and therefore kind of impatient, pasted only some notes in a text file at that day and hadn't much time later on to elaborate the notes. I've made however a *Gist* of it: https://gist.github.com/olafgrabienski/3c05cd07859d4325080016aa88b69744

**Comment by olafgrabienski** [comment]
> post some questions to better understand the upgrade process, and its prerequisites.

Hadn't time to post my questions so far, but there is a forum post with one question I also had: Which D7 contrib modules now part of BD core should be disabled before the upgrade? (See https://forum.backdropcms.org/forum/how-handle-d7-contrib-backdrop-core.)

To put an example, I guess *Admin menu* should (or can) be disabled (because it just gets replaced by *Admin bar*), but *Views* not (holds data which is needed during the upgrade). The difference between such (and other) cases should be explained in the documentation.

There are also cases where I'm not sure if a D7 module is needed during upgrade, and why, e.g. *Token* or *CTools*.

**Comment by olafgrabienski** [comment]
Another module specific question: **Libraries API** isn't needed in Backdrop, which would mean in my understanding, the module should be uninstalled in Drupal before the upgrade to Backdrop. It is however required in my Drupal installation (by Colorbox).

Libraries is ported to Backdrop, so I could keep it. But it has been deprecated some time ago, see the README on https://github.com/backdrop-contrib/libraries. Don't we still need the module for upgrades? And: let's make the answer part of the documentation.

**Comment by olafgrabienski** [comment]
Or **Menu Block**, which was "integrated into System & Menu modules". What does that mean for an upgrade? Can (or should) I keep the module in Drupal before the upgrade? If I had many menu blocks, I'd hope that it works. Does it, i.e. is there an upgrade path? The documentation isn't clear about it (and about similar cases).

**Comment by BWPanda** [comment]
I'll again give a theoretical (untested) answer; to me it seems that if a Drupal module isn't needed in Backdrop, you should still keep it, so then Backdrop knows about it, can convert variables to config, change other settings, etc. Once the site's working you should then be able to safely uninstall unneeded modules.

**Comment by jenlampton** [comment]
> Which D7 contrib modules now part of BD core should be disabled before the upgrade?

IIRC: If you upgrade from Drupal to Backdrop and there is no Backdrop version of the module present, that Backdrop will "Disable" that module for you -- but I'm not 100% positive on this. We should check.

Uninstalling is different, I would recommend only uninstalling modules that have features that you DO NOT WANT TO USE in Backdrop. Anything you might want later, do not uninstall.

> Or Menu Block, which was "integrated into System & Menu modules". What does that mean for an upgrade? Can (or should) I keep the module in Drupal before the upgrade? 

Yes, you should keep it in Drupal. Do not uninstall. (Disabling is okay.)

> If I had many menu blocks, I'd hope that it works. Does it, i.e. is there an upgrade path?

There is not a built-in upgrade path for menu_block, but there should be! See https://github.com/backdrop-ops/backdropcms.org/issues/526

We need to document somewhere -- for for each module that was "integrated" into core -- How to upgrade. We need to include if there is an upgrade path, and if not, how much re-configuring is necessary. Does this belong on [this page](https://backdropcms.org/user-guide/features-added-core)? Or maybe we should create a separate/child page with upgrade instructions for each of those modules? 

> Once the site's working you should then be able to safely uninstall unneeded modules.

This is true if there is a module for Backdrop. But in many cases there are no "modules" in backdrop to uninstall later. Menu block, for example, would leave it's cruft in the db, since there's nothing around that could delete that data (or even knows what it is) once you've upgraded to Backdrop.

**Comment by jenlampton** [comment]
I had a better idea about where to put the upgrade instructions! We already have a "Placeholder" content type  that's specifically intended to appear in searches for modules/themes/layouts, that will inform people that a module/theme/layout is not needed for Backdrop. I've added an additional field to this content type for **Upgrade instructions** where we can note this information. 

For example:
https://backdropcms.org/project/administration-menu

We can also build a view of all these placeholder nodes for people to get the instructions they need for each module they may be running on a Drupal 7 site.

**Comment by olafgrabienski** [comment]
> We already have a "Placeholder" content type that's specifically intended to appear in searches for modules/themes/layouts, that will inform people that a module/theme/layout is not needed for Backdrop. I've added an additional field to this content type for Upgrade instructions where we can note this information.

That's great, it'll be very helpful!

> We can also build a view of all these placeholder nodes for people to get the instructions they need for each module they may be running on a Drupal 7 site.

Yes, this, and/or link the module names on the page https://backdropcms.org/user-guide/features-added-core to the respective placeholder nodes.

**Comment by jenlampton** [comment]
> Yes, this, and/or link the module names on the page backdropcms.org/user-guide/features-added-core to the respective placeholder nodes.

Yes, good idea!

**Comment by olafgrabienski** [comment]
In step 3.2 of the Upgrade instructions people are advised to copy the files directory from Drupal 7 (usually `drupal/sites/default/files`) into the Backdrop site (usually `backdrop/files`).

That's fine, but for reference: Backdrop doesn't take the `files` directory into account after the upgrade. I hope we can fix the issue soon, see the bug report here: https://github.com/backdrop/backdrop-issues/issues/3706

**Comment by jenlampton** [comment]
> Backdrop doesn't take the files directory into account after the upgrade.

This is a documentation problem. You'll need to update that variable in Backdrop to match the new file location, or create & use the files location from Drupal.

I'll update the docs :)

**Comment by olafgrabienski** [comment]
Thanks for updating the upgrade instructions, @jenlampton! Regarding the new steps (see below): Not every Backdrop site is hosted on a system with SSH access to the shell, and creating a symlink (step 3) isn't possible via a (S)FTP client.

Without steps 2 and 3 a site may look a bit broken after the upgrade, but that will however be fixed with step 4. Therefore I suggest to mark steps 2 and 3 as optional, thus encouraging more people to manage the files paths in Backdrop locations (instead of to continue using the Drupal locations).

> 1. Copy the files directory from Drupal 7 (usually `drupal/sites/default/files`) into the Backdrop site (usually `backdrop/files`)
> 2. Create a `default` directory within `backdrop/sites`.
> 3. Create a symlink in your filesystem from `sites/default/files` to  `files` .
> 4. After the upgrade, update the `Public file system path` setting at admin/config/media/file-system to `files`.

**Comment by jenlampton** [comment]
Without the symlinks, any file or image embedded into a body field (or
similarly referenced via Drupal 7) will be broken in Backdrop. That step
isn't optional for most sites.

**Comment by olafgrabienski** [comment]
> Without the symlinks, any file or image embedded into a body field (or similarly referenced via Drupal 7) will be broken in Backdrop.

I see! And I agree that in this case the Drupal locations are a reasonable alternative.

**Comment by jenlampton** [comment]
It looks like we've addressed all the actionable updates that were mentioned in this issue, either by fixing them directly, or creating other broader issues to tackle. I'd like to close this issue, and open others as we find other updates that are needed for this page.

**Comment by olafgrabienski** [comment]
> It looks like we've addressed all the actionable updates that were mentioned in this issue

Is there already the view of "Placeholder" modules which aren't needed for Backdrop? See https://github.com/backdrop-ops/backdropcms.org/issues/509#issuecomment-484747531. Another idea was to link the module names on the page https://backdropcms.org/user-guide/features-added-core to the respective placeholder nodes. This isn't addressed so far, is it?

**Comment by jenlampton** [comment]
We don't have a complete list yet, but this list can replace the features-added-to-core listing once we're ready: https://backdropcms.org/upgrade-from-drupal/contrib-modules

**Comment by olafgrabienski** [comment]
> We don't have a complete list yet, but this (...): https://backdropcms.org/upgrade-from-drupal/contrib-modules

Ah, hadn't seen that page, thank you!
