### ISSUE TITLE
Respond to GitHub release web hook for tagging version and project information in .info files

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#51]
We need a server to respond to the GitHub web hook for the "backdrop-contrib" group when new releases are made. I think this should be the main backdropcms.org site (or an aliased domain) that responds to the creation of releases on GitHub because the site will also need to create/update release information on the matching project nodes.

GitHub gives us the ability to be notified of new releases and modify those packages:

- https://developer.github.com/v3/activity/events/types/#releaseevent
- https://developer.github.com/v3/repos/releases/#upload-a-release-asset

We should set up the "backdrop-contrib" group to use an [Organization-level Web Hook](https://developer.github.com/v3/orgs/hooks/) to affect *all* the projects with the backdrop-contrib group. That will prevent individual modules from needing to specify a web-hook individually.

In the future, we may also consider making a GitHub Service (https://github.com/backdrop-ops/backdropcms.org/issues/8) to facilitate modules that are *outside* the contrib repository, but building an organization-level web hook for the backdrop-contrib group will be a good first step.

**Comment by quicksketch** [comment]
Here's a workflow that summarizes how this would work:

Managing releases
-----------------

- Git release created on GitHub
- Webhook sent to backdropcms.org to immediately notify of the new release
- backdropcms.org queues the list of releases to be updated.
- backdropcms.org also runs cron job to check for new releases based on timestamp
- backdropcms.org runs cron job to process queue of releases.
  - Download current release archive.
  - Expand into temp directory.
  - Modify to add in version information into .info files. e.g. 
```
; Information added by backdropcms.org packaging script on 2014-02-20
version = "1.x-1.0-beta3"
project = "module_name"
datestamp = "1308598915"
```
  - Re-compress all the files back into an archive.
  - Push modified archive back to Github.
  - Mark release as updated in the database.
  - Update project node (if any) with current release information.

**Comment by klonos** [comment]
Everything here makes perfect sense, except one thing... the ```project``` property. This is a static thing that will not change with future releases of the same module. So, I think that this should be added to the .info by the developer and not auto-generated.

**Comment by quicksketch** [comment]
> I realize that d.org contrib also auto-generates this line. Is there any particular reason for doing so?

I think it just saves the developer work from forgetting the project information in their own .info files. It also makes moving modules between projects easier and less error prone. It also assures name-space uniqueness on the project name itself.  I don't see any harm leaving it in there, considering how little effort it is to include.

**Comment by quicksketch** [comment]
When we launched the new BackdropCMS.org last week, it also included the start of this functionality. I enabled the packaging on the contrib group, so we should start seeing packages created as new releases are tagged.

**Comment by quicksketch** [comment]
See the _borg_github_create_package() function and others in the [borg_github.pages.inc file](https://github.com/backdrop-ops/backdropcms.org/blob/master/www/modules/custom/borg_github/borg_github.pages.inc) for details of the packaging. I'd love to improve it to include uploading logs of any errors to the user's project instead of the packaged release. For now, we can get pretty detailed logs from the GitHub itself by looking under the Webhook log history, but only group administrators will be able to access them (currently just @jenlampton, @klonos, and myself).

**Comment by quicksketch** [comment]
With this implemented on backdropcms.org and now affecting releases. I'd love to hear if people experience any oddities with it. Not a lot of projects have tagged releases yet, and this will only affect tags from here on out.

**Comment by docwilmot** [comment]
Worked for Cleanish theme I'd say. After creating a release, the option to "Download cleanish 1.0.0 (zip)" is available on the release page (note the script removed the -1.x from the tag, leaving just 1.0.0) on GitHub, and in the downloaded zip file, the `.info` file has been modified to include:
```
; Added by BackdropCMS.org packaging script on 2015-03-13
project = cleanish
version = 1.x-1.0.0
timestamp = 1426260082
```
Success then?

**Comment by quicksketch** [comment]
:+1: 

Sounds like it did everything. :smile:

Another nice side-effect of this is we get to name the zip file exactly what we like, so were were able to remove the version string from the release zip, so when an end-user extracts it the directory name is just the project name now.

**Comment by quicksketch** [comment]
Let's marked this fixed for now and work on improving it in separate issues.
