### ISSUE TITLE
Add an "upgrade from Drupal 7" section to the home page

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#519]
Three columns including:
* how many of the top 100 Drupal modules are ready
* how many Drupal 7 modules have comparable alternatives in Backdrop core
* Link to Instructions on how to upgrade: https://backdropcms.org/upgrade-from-drupal 

Other ideas:
* Promote a “Backdrop Ready” module (fork off of upgrade_status) when it's ready

**Comment by jenlampton** [comment]
Also related: https://github.com/backdrop-ops/backdropcms.org/issues/509

**Comment by jenlampton** [comment]
Hm, I realize I may need some design help here: 
<img width="1469" alt="Screen Shot 2019-04-04 at 11 53 01 PM" src="https://user-images.githubusercontent.com/397895/55609131-d1b92b00-5734-11e9-9d39-59d00bb2a228.png">

**Comment by klonos** [comment]
I like where this is going 👍 

I don't thing that we should replace the "Sites that use Backdrop" with this new "Upgrade from D7" section. We should have both on the front page.

I propose that we also add the total of contributed projects ported so far? I was thinking to change the design of this block from a header + 3 columns, to header + 3 columns + footer to accomodate that.

Here's how things could look:

![2019-04-06-15-28-backdropcms org](https://user-images.githubusercontent.com/2423362/55664847-eefb1000-5880-11e9-8b7d-d697aa526eaf.png)

Further down the home page, where we list the Backdrop features, we have a "Upgrade from Drupal 7" section. This currently reads as follows:

> Backdrop has a built-in upgrade path from Drupal 7. Backdrop will be familiar to people with Drupal experience because it is so similar to Drupal, but includes numerous usability improvements and new features.

There's too much repetition of "Drupal" and "Backdrop" in that text, and it does not feel to have a natural flow. I've changed it to this, and then used that in the mockup as a subtitle for the "Upgrade from Drupal 7" section:

> Backdrop has a built-in upgrade path from Drupal 7. If you have previous experience with Drupal 7, then working with Backdrop will feel familiar, but easier and more fun. Get things done faster, and enjoy the numerous usability improvements and new features we have added over the years!

**Comment by klonos** [comment]
...the 3 columns should have icons. I was thinking the following:

- Backdrop ready modules:

![material-icons_3-0-1_playlist-add-check_128_0_ffffff_000000](https://user-images.githubusercontent.com/2423362/55664897-bb6cb580-5881-11e9-8ab8-2f2cc5857327.png)

- Modules included in core: 

![icomoon-free_2014-12-23_gift_128_0_ffffff_000000](https://user-images.githubusercontent.com/2423362/55664901-c4f61d80-5881-11e9-81aa-997f6df94343.png)

- Total contrib projects:

![font-awesome_4-7-0_puzzle-piece_128_0_ffffff_000000](https://user-images.githubusercontent.com/2423362/55664905-caebfe80-5881-11e9-8c15-9347bb90e397.png)

**Comment by jenlampton** [comment]
> I don't thing that we should replace the "Sites that use Backdrop" with this new "Upgrade from D7" section. We should have both on the front page.

Oh it's still there, just father down the page.

> Here's how things could look:

Much better, thank you! 

> ...the 3 columns should have icons.

Okay, I'll try that...

**Comment by jenlampton** [comment]
okay, It's up!
![home](https://user-images.githubusercontent.com/397895/55665722-3473fa80-57f9-11e9-9505-5eaceb6376a6.png)
