### ISSUE TITLE
On homepage of b.org new `91% of top modules ready` does not make sense.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#525]
Homepage text `91% of top modules ready` should be `91% of the top 100 modules are ready`

![image](https://user-images.githubusercontent.com/6763671/55830884-ef451680-5adf-11e9-987e-3856b3001285.png)

**Comment by BWPanda** [comment]
I think it makes sense: 'top modules' means the '100 most popular Drupal 7 modules' (as the description text alludes to), and 91% of those (being 91 modules) are Backdrop-ready.

But I think I see what you're saying; that 91% should refer specifically to a number, not an arbitrary term...

Interested to see what others think.

**Comment by docwilmot** [comment]
It should be either 90 of the top 100 modules, or 90% of the top modules.
