### ISSUE TITLE
Cutover localize.backdropcms.org to Debian 9 Server

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#528]
Public issue checklist for server cut-over 4/11/2019:

- [x] Update site to latest version of Backdrop (@jenlampton)
- [x] Pull down code on www2.backdropcms.org (@jenlampton)
- [x] rsync files (@larsdesigns )
- [x] Copy over database (@larsdesigns )
- [x] Ensure crontab is set up for localize user
- [x] Remove crontab from old server for localize user
- [x] Verify files directory is writable
- [x] Verify config directory is writable
- [x] Test by pointing /etc/hosts with this entry (All)
```
66.175.208.83 localize.backdropcms.org
```

- [x] Switch DNS (@quicksketch )

**Comment by quicksketch** [comment]
I set up crontab, looks like we did not previously have it running on www1.

**Comment by jenlampton** [comment]
closing, this one is done, right?

**Comment by quicksketch** [comment]
We're all done here! Looks great, thanks @jenlampton and @larsdesigns!
