### ISSUE TITLE
Improve "Converting modules to Backdrop from Drupal 7" documentation

### ISSUE THREAD

**Issue by VasasA** [backdrop-ops/backdropcms.org#532]
I improved a document from api.backdropcms.org:
Original: [Converting modules to Backdrop from Drupal 7](https://api.backdropcms.org/converting-modules-from-drupal)
[**Improved draft**](https://github.com/VasasA/converting/blob/master/converting.md)
Changes: https://github.com/VasasA/converting/commit/482fd4e28430ae181db65507b4e8944cd6098db0

I hope it will be useful. Please fix the errors :smiley: 

Other sources:
- [Guide 1.](https://www.lullabot.com/articles/porting-drupal-7-modules-to-backdrop)
- [Guide 2.](https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2)
- Suggestions by @herbdool
- Suggestions by @klonos
Thanks!

**Comment by jenlampton** [comment]
Thanks @VasasA this is really helpful!

**Comment by VasasA** [comment]
I created a new commit: https://github.com/VasasA/converting/commit/2f184dfd76da752a94fcf2f86d3a34c67da74da7

**Comment by jenlampton** [comment]
Hi Vassa,
I'm sorry it's been so long since anyone has looked at this issue. Since developer documentation is on the API site, I've moved this issue over into that queue, hoping it will get more attention over there:
https://github.com/backdrop-ops/api.backdropcms.org/issues/114

**Comment by VasasA** [comment]
All right, thank You! :+1:
