### ISSUE TITLE
Make the MailChimp sign up block much more prominent

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#534]
We were just having a conversation in Gitter about the importance of building a mailing list (email list). Our email list dropped from 2000 to a little over 200 because of GDPR compliance rules. 

I think that from an outreach/marketing perspective, we need to focus on two things. 

1) Getting the attention of new people
2) Capturing contact information of those people so that we can stay in touch with them. 

Right now, I think it's VERY possible for someone who is very interested in Backdrop CMS to arrive at our site, navigate around and then leave without ever seeing that we have a newsletter sign up block. Every new visitor on our site should have the opportunity to sign up for the newsletter. 

What can we do to make that block more prominent?

**Comment by oadaeh** [comment]
The block needs to be placed in the upper right hand corner of the home page.
It has been shown in numerous usability/readability tests/studies that, in general, people read web pages in an F-shaped pattern, starting from the top left, going across to the right, then going down and to the right, but less and less to the right until they stop going down, which for most sites is before they get to the bottom of the page.

**Comment by oadaeh** [comment]
I just had another thought: what about adding a newsletter sign up block to the forum site as well?

**Comment by stpaultim** [comment]
Great idea, however I just checked and we already have a Newsletter Signupp block near the footer on the Forum site. I think we could do a better job of highlighting it, just like on this site.

**Comment by jenlampton** [comment]
I just talked to our designer, she has 3 recommendations for us:

1) Add another icon into the header specifically for the newsletter signup. I was thinking [an envelope](https://fontawesome.com/v4.7.0/icon/envelope)

2) Change the design of the newsletter signup form in the footer, by adding a black background...

<img width="1444" alt="Screen Shot 2019-05-03 at 5 34 51 PM" src="https://user-images.githubusercontent.com/397895/57171515-d3c0e900-6dc9-11e9-92c8-8f5ae4124c28.png">

...or maybe a pop of color:

<img width="1442" alt="Screen Shot 2019-05-03 at 5 36 28 PM" src="https://user-images.githubusercontent.com/397895/57171543-184c8480-6dca-11e9-81b6-88c1ccbd6564.png">

3) Create a CTA banner we can use various places around the site (like on the home page) to get more attention. We can model this after the current home page color banner:

<img width="1462" alt="Screen Shot 2019-05-03 at 5 39 12 PM" src="https://user-images.githubusercontent.com/397895/57171598-5fd31080-6dca-11e9-8a1d-2c00cccf728b.png">

or our current CTA style:

<img width="1442" alt="Screen Shot 2019-05-03 at 5 39 45 PM" src="https://user-images.githubusercontent.com/397895/57171607-78dbc180-6dca-11e9-8eb1-d1c6e11b12d1.png">

**Comment by stpaultim** [comment]
I understand the difficulty here and I would agree that some combination or all three of these suggestions together would be helpful. 

I was also thinking that maybe a small icon up near the Twitter icon might be one strategy. I like the other two ideas as well and they are not exclusionary. 

The current button does blend into the background a bit and there are some places on the site where a CTA banner for the newsletter might be appropriate. 

1) https://backdropcms.org/contribute - One way to contribute is to get on our mailing list so that we can keep in touch. 
2) https://backdropcms.org/news - Maybe in right column a small block that encourages users to sign up for ongoing news about Backdrop?
3) https://backdropcms.org/support - Maybe the resources list should include the email newsletter?

I'm just brainstorming here. Anything we do will be an improvement.

**Comment by jenlampton** [comment]
> some combination or all three of these 

I was thinking all 3!

**Comment by stpaultim** [comment]
Sounds excellent.

**Comment by jenlampton** [comment]
@stpaultim I left 2 presents for you on backdropcms.org. (Well, 3, but the 3rd one isn't enabled yet).

**Comment by jenlampton** [comment]
- [x] backdropcms.org/contribute 
- [x] backdropcms.org/news 
- [x] backdropcms.org/support 

I think this is done now. closing. :)
