### ISSUE TITLE
Increased access for this repo

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#536]
I'd like to help organize and/or label issues in this repo, but I'm pretty sure I don't have sufficent access. Either that, or I don't have the skills to figure out how it works. 

Primarily, I'd just like to be able to help manage issues.

**Comment by serundeputy** [comment]
@jenlampton do you have to be an admin to use the labels or can we add @stpaultim to the  `community outreach` team would that work?

**Comment by serundeputy** [comment]
@stpaultim I've added you to `community outreach` team you should receive an email, once you accept the invite, let us know if that gives you access to label and manage issues.

**Comment by stpaultim** [comment]
Yes, I can see that I am now a member of the Backdrop CMS Community Outreach Team. 

But, that does not seem to have any effect on my permissions in this issue queue. At least, I am still unable to change labels on issues.

**Comment by jenlampton** [comment]
It works the same here as for backdrop core - you need to be a committer on the repo in order to manage the labels.

**Comment by stpaultim** [comment]
Thanks. I got it.
