### ISSUE TITLE
https://backdropcms.org/resources broken

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#54]
loads without menu etc.

**Comment by quicksketch** [comment]
Hm, looks okay at the moment. So the sidebar menu was missing?

![resources-page](https://cloud.githubusercontent.com/assets/100206/6682187/90a0bf8a-cc31-11e4-8163-2cd035703419.png)

**Comment by docwilmot** [comment]
Looks fine now. Both the sidebars were missing (black and grey). Will screenshot if it happens again.
