### ISSUE TITLE
Requesting commit access to backdropcms.org

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#540]
From Gitter:

> BWPanda:
What would it take to get more access on https://github.com/backdrop-ops/api.backdropcms.org? On other repositories, I can add labels to issues, change issue titles, etc. Can I ask to do the same here, or would that require giving me more access than what I'm allowed?
> 
> serundeputy Do you know about Github access? I'd love to be able to do more in the various issue queues, but don't want to overstep my bounds...

> serundeputy:
i think jenlampton said you have to be a commiter to use the labels on github
we could mitigate that by making more people commiters and locking down the master branch

> BWPanda:
What does it take to become a committer? (you know, apart from 'commitment' :wink: :laughing: )

> serundeputy:
just granted that perm on GH; for backdropcms.org I think we'd just have to ask Jen
we should ask about stpaultim as well, he is in the same boat

> BWPanda:
I was wondering more, how is it decided who to grant that permission to?
If I'm deemed worthy, I'd love to be able to do more on:
> - https://github.com/backdrop-ops/backdropcms.org
> - https://github.com/backdrop-ops/api.backdropcms.org
> - https://github.com/backdrop-ops/contrib
They're the ones I frequent the most.

> serundeputy:
yeah; as far as I know the process for now is ask Jen
if that is not the process I don't know what it is or where/if it is documented
maybe open an issue in the b.org issue queue with what you just typed and put it on the outreach agenda to call attention to it and get it addressed?

So I'd like to officially ask @jenlampton if I could please be given more access to the above linked repos (mainly so I can tag issues, close old ones, etc.).

**Comment by jenlampton** [comment]
in short: yes! 

in long: 

GitHub access is dumb. you need to be a core/committer on any project to manage labels on the issues.

for backdrop itself we “solved” this problem by having more than one repository, `backdrop/backdrop` and `backdrop/backdrop-issues`. This allows us to grant people commit access to the issue queue, without allowing them commit access to core.

For our other projects, that hasn't been necessary, yet. But if we start having a lot of people who want to manage issues (and/or people we don't trust to commit changes to the sites directly) then we might want to create separate `issues` repos for each of those projects as well.

**Comment by serundeputy** [comment]
@jenlampton we could give them commit access and write protect the `master` branch (or relevant branches for the repo) and avoid have another repo.

**Comment by jenlampton** [comment]
what is `write protect`?

**Comment by serundeputy** [comment]
@jenlampton https://github.com/backdrop-ops/backdropcms.org/settings/branch_protection_rules/5356549

**Comment by jenlampton** [comment]
Thanks @serundeputy!  

@BWPanda you are on the "web team" and should be able to manage all issues in all queues now. Closing this issue.
