### ISSUE TITLE
Check on the GitHub download count.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#544]
Every time I go to grab the download count for backdrop, the number seems to go down. I think we may be pulling download counts from GitHub incorrectly.

I read in [this article](https://stackoverflow.com/questions/4338358/github-can-i-see-the-number-of-downloads-for-a-repo) that when getting the download count, you need to adjust for GitHub's pagination system, so that we don't get only the total for the most recent 30 releases.

Can we check our implementation and make sure we are getting all releases?

----

PR: https://github.com/backdrop-ops/backdropcms.org/pull/547

**Comment by serundeputy** [comment]
can we have @larsdesigns check on the https://github.com/serundeputy/sql-dump-sanitize cron job?

Going to https://sanitize.backdropcms.org/ has DB dumps from 2 April 2019; this is hindering working on b.org issues.

specifically for this issue i'd like to see the DB records going down or fluctuating or whatever the data says.

**Comment by serundeputy** [comment]
I'm blocked w/out the DB. current code state and an old DB do not work together. @larsdesigns once `sql-dump-sanatize` is hooked up assign back to me.

**Comment by jenlampton** [comment]
@serundeputy backdropcms.org is still on the old server. sanitize.backdropcms.org is on the new one. If you add a host record for `23.239.10.5 sanitize.backdropcms.org` you should be able to grab a recent db.

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop-ops/backdropcms.org/pull/547

![image](https://user-images.githubusercontent.com/6763671/58360872-0f931f80-7e59-11e9-8222-545cd45d7870.png)

**Comment by jenlampton** [comment]
It's so beauuuuuuuuuutiful!

**Comment by jenlampton** [comment]
merged, deploying!

**Comment by jenlampton** [comment]
okay, deployed. How do I make it go? I ran cron. Nothing yet...  I'll try again later. 
https://backdropcms.org/project/backdrop

**Comment by serundeputy** [comment]
Cron is the right thing, but it checks to make sure it is late at night
before executing this big job.

**Comment by serundeputy** [comment]
It ran successfully last night, but did expose two logged notices: https://backdropcms.org/admin/reports/event/11252

I'll whip up a fix for that.

**Comment by docwilmot** [comment]
> Cron is the right thing, but it checks to make sure it is late at night before executing this big job.

Its always morning somewhere. 😄

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop-ops/backdropcms.org/pull/548

checks that the Link header `isset` before trying to operate on it.

**Comment by jenlampton** [comment]
well, I merged deployed the fix but now everything's broken :(

**Comment by jenlampton** [comment]
okay - reverted and everything's fixed. looking at the code...

**Comment by jenlampton** [comment]
It looks like we were missing two closing parens. I'm also adding some micro-optimizations and replacing all `"strings"` with `'strings'`.  speed++

**Comment by serundeputy** [comment]
download count appears broken again :( https://backdropcms.org/project/backdrop
it is showing `8494`.

When I get some time i'll look into it again.

**Comment by quicksketch** [comment]
> Should we flip back the DNS for sanitize until the live site gets moved over? Or maybe we should prioritize that instead?

FYI the live site has now been flipped over. So sanitize.backdropcms.org now has the latest databases again.

**Comment by serundeputy** [comment]
@jenlampton there was a problem with the quote updates. I've corrected that and the download counts will be fixed with this PR: https://github.com/backdrop-ops/backdropcms.org/pull/559

**Comment by jenlampton** [comment]
Wow, thanks for catching that :)

**Comment by jenlampton** [comment]
Merged and deployed, let's see if this does the trick :)

**Comment by serundeputy** [comment]
seems like the trick has been done :smile: I think it is ok to close ... reopen if necessary.
https://backdropcms.org/project/backdrop
