### ISSUE TITLE
Add another principle: Security

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#546]
https://backdropcms.org/philosophy#principles

During the weekly meeting today, we decided that this would be best to be placed either between _Focus_ and _Extensibility_, or between _Extensibility_ and _Performance_.

This issue here is to decide on wording.

PS: another idea was to replace the numbered list with a bulleted list, and indicate the number of principles in the H2; something like "Our 8 principles".

**Comment by jenlampton** [comment]
How about:

**Security: Keep sites and people safe.**  Backdrop core should include features that will keep websites, the data within, and the people that use them safe. The majority of security-hardening features should be enabled by default to protect those who know the least, but should not prevent people from going about their daily work. 

here's what Drupal has to say about security
* https://www.drupal.com/feature/security

**Comment by jenlampton** [comment]
I've added this text to the philosophy page, but would love some feedback / improvements on wording :)

**Comment by klonos** [comment]
I'm not that good with making up words. ...I like yours @jenlampton 👍

**Comment by BWPanda** [comment]
I'm going to call this done: 
![image](https://user-images.githubusercontent.com/2385329/108490746-31079080-72f7-11eb-9ff4-0c440533deaa.png)
