### ISSUE TITLE
Issues logging in

### ISSUE THREAD

**Issue by EganSolo** [backdrop-ops/backdropcms.org#550]
I'm not able to log onto the forum.
Here's the sequence:
1. Go to backdropcms.org
2. click on "welcome!"
3. select login
4. Key in my credentials (user name is EganSolo)
5. I'm logged in into my profile.
6. Select Forum
7. The forum page opens up and I'm logged out.
8. Go through steps 2-4 again
9. I get: sorry, unrecognized username.
Could someone help?

**Comment by quicksketch** [comment]
Hi @EganSolo! Thanks for joining our community and sorry for the trouble! We don't have a unified sign-on solution yet, so the forum.backdropcms.org and main backdropcms.org site have separate accounts. You'll need to sign up to each one individually. You can create a new account for the forum at https://forum.backdropcms.org/user/register

**Comment by BWPanda** [comment]
I'm going to close this issue now, but feel free to re-open it @EganSolo if you're still experiencing login issues.
