### ISSUE TITLE
Put something about backdrop being a non-profit on our website

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#557]
I've had a few people ask recently if Backdrop is a non-profit. 

We should state clearly on our about page that yes, we are, and that we are a project of the Software Freedom Conservancy, perhaps with a link to
https://sfconservancy.org/projects/current

**Comment by jenlampton** [comment]
I added a section to the about page, feedback welcome: https://backdropcms.org/about

**Comment by docwilmot** [comment]
i dont see that on https://backdropcms.org/about yet.

**Comment by jenlampton** [comment]
You can get around the cache by adding a unique query string to the end, something like https://backdropcms.org/about?a=b

**Comment by docwilmot** [comment]
Works now, looks good

**Comment by klonos** [comment]
Yup, looks good. Thanks @jenlampton 👍 

Perhaps add a donate button/link in that section as well?

**Comment by stpaultim** [comment]
Looks good!

**Comment by BWPanda** [comment]
Looks like this is complete: 
![image](https://user-images.githubusercontent.com/2385329/108490456-dec66f80-72f6-11eb-8bd1-304420fac10b.png)
