### ISSUE TITLE
Automated distribution installations?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#56]
Over at https://github.com/backdrop-ops/backdropcms.org/issues/55 @Graham-72 posted [this article](http://www.istos.it/en/blog/learning-drupal/how-i-finally-convinced-my-dad-switch-wordpress-drupal) which had me thinking, can our update server serve up distributions as well as modules and themes (and layouts)?
Wouldnt it be great if folks could browse pre-cooked sites (blogs, event sites, church sites, whatever) with all modules and themes and layouts predetermined and configured in a neat package, and just click "install"?
Is that technically feasible?

**Comment by quicksketch** [comment]
> can our update server serve up distributions as well as modules and themes (and layouts)?

Distributions on drupal.org are largely powered using Drush make files, so we won't be able to replicate the exact setup in the immediate future. Beyond that, we definitely can build out packaging tools that host built packages here on GitHub.

As far as I know, update.module already includes some, but not much, support for updating distributions, but it's not great. The entire situation with distributions is really sub-par, as using a distribution often means locking you into old versions of modules until the distribution itself is updated.

There's a larger discussion on handling distributions as a core feature over here: https://github.com/backdrop/backdrop-issues/issues/99

But if the goal you're wanting is simply a "recipe"-like site, I think the practice we should encourage is literally that: a recipe. For example you could download X, Y, and Z modules, then just import a config archive. That would set up all content types, site settings, vocabularies, menus, etc. from the config export. In this regard, "cloning" an existing site will often be trivial. Just export a current site and import it into a new blank one.

**Comment by docwilmot** [comment]
thanks
> you could download X, Y, and Z modules

I wish we should consider whether we can make the process of downloading simpler than the D7 copy the link, paste it, repeat. I'd love to see a browser, where you could just check X Y and Z and then click install.

**Comment by cellear** [comment]
I had my beginning web development class download and try out Backdrop on Pantheon Monday night. When I asked them to try to set up a website, they went to the appearance menu and were surprised that they couldn't just select a theme to download. Seems like a theme browser wouldn't be that hard.

**Comment by quicksketch** [comment]
Yes, a project browser for both modules and themes would be extremely handy. We already have the ability to install modules through the UI over FTP (as scary as that is), but there's no project browser. Of course, before we can do that... we need to set up a project listing on backdropcms.org itself. :wink: That's https://github.com/backdrop-ops/backdropcms.org/issues/8.

**Comment by jenlampton** [comment]
I think what you guys have started talking about is an in-app project browser, and (though it is a good idea) an issue for that needs to be created over at github.com/backdrop/backdrop-issues/issues

The question here was specifically "what are we going to do about distributions?" since we don't currently support those at backdropcms.org.

Distributions started for Drupal before things like composer and drush make files really took off. I think we should re-think the problem space for backdrop, and "distributions" could be as simple as a single info file (or composer file) that would assemble all the parts for us.

Once we figure out what this looks like, then yes, we should to add support for those on backdropcms.org :)

**Comment by biolithic** [comment]
I vote for re-thinking the problem.
It seems like distributions seem like a cool idea but unless they have
great backing (corporate, or rockstars like Dsnopek), they seem to get out
of date and hard to maintain in my experience.  End users who start with
them are confused on how Drupal actually works.

**Comment by mikemccaffrey** [comment]
> Distributions started for Drupal before things like composer and drush make files really took off. I think we should re-think the problem space for backdrop, and "distributions" could be as simple as a single info file (or composer file) that would assemble all the parts for us.

Yes, I think that part of the confusion is that "distributions" in drupal have usually meant not only an install profile, but also include a bunch of very custom sub-modules and themes within them. I don't think that we should go anywhere near this sort of code bundles unless we really have examples of applications that need them.

I agree that we should focus on something simpler, which could involve just an install profile, but would likely also need default config files to be imported and an install file to run arbitrary php code on installation.

I think that this ticket should either be renamed or closed in favor of one that does not have the phrase "distribution" in the title. There is too much drupal baggage with that name, and we should stick to either "install profiles" or something like "recipes".
