### ISSUE TITLE
url_alias column: language or langcode

### ISSUE THREAD

**Issue by dmyerson** [backdrop-ops/backdropcms.org#561]
I documented this in the forum at https://forum.backdropcms.org/forum/d7-conversion-crash, but the short story is that on bootstrap when I am trying to convert my D7 site to backdrop, it is crashing because D7 has url_alias.language while backdrop is querying url_alias.langcode. Sorry it has taken me so long to get this in here.

**Comment by olafgrabienski** [comment]
Hey @dmyerson, thanks for filing the issue! Unfortunately, this queue isn't exactly the right place, it should be https://github.com/backdrop/backdrop-issues/issues instead.

@jenlampton, @klonos, or others: Can this issue be moved to the other queue by you people with adequate permissions?

**Comment by jenlampton** [comment]
@olafgrabienski unfortunately, issues can only be moved within the same group, so a `https://github.com/backdrop-ops` issue can't be moved to `https://github.com/backdrop`. 

@dmyerson I have created the issue there and credited you: https://github.com/backdrop/backdrop-issues/issues/3897
