### ISSUE TITLE
Include screenshots on the themes page.

### ISSUE THREAD

**Issue by boughtonp** [backdrop-ops/backdropcms.org#567]
Backdrop doesn't currently include what themes look like on the themes page, at  https://backdropcms.org/themes 

As per docwilmot on [forum discussion](https://forum.backdropcms.org/forum/theme-gallery):
> We're working on adding more features and information to the project listings
> [here](https://github.com/backdrop-ops/backdropcms.org/issues/487), but this seems like a good request that doesnt have to wait till we've 
> made any more progress there.

**Comment by stpaultim** [comment]
We have screenshots for the individual theme pages. But, I see that this suggestion is that we add them to the page that lists all themes. This is a really good idea and probably not much work.

**Comment by BWPanda** [comment]
This has been fixed and screenshots are now shown on the Themes overview page.
