### ISSUE TITLE
Add graphs to usage pages

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#569]
On project usage pages (e.g. https://backdropcms.org/project/usage/backdrop) it'd be nice to have a pretty graph at the top:

![image](https://user-images.githubusercontent.com/2385329/61438318-dacab280-a947-11e9-8a49-fb5bfe75e339.png)

Something using a JS library like https://www.chartjs.org/ would keep it up-to-date automatically.

**Comment by serundeputy** [comment]
this is a thing too: https://www.drupal.org/project/charts

**Comment by docwilmot** [comment]
Ran the Drupal module through Coder Upgrade this morning to see if it would work right away. Installed fine, and all settings and Views plugins show up, but no charts yet. Will push the code up this evening after work so someone can finish it.

**Comment by BWPanda** [comment]
Going to close this as a duplicate of #98.
