### ISSUE TITLE
Spelling mistake on press kit page

### ISSUE THREAD

**Issue by Drupaldise** [backdrop-ops/backdropcms.org#57]
Hi, it is written down: " The word Backdrop is always spelled with a capital "B" " and after that, the Backdrop Logo is written with "b".
![press kit backdrop cms 2015-04-13 11-21-13](https://cloud.githubusercontent.com/assets/2930705/7112975/a0d07c48-e1cf-11e4-9bef-814d362ff044.jpg)

**Comment by Drupaldise** [comment]
Upps... I have not read the text section under the logo. soory.

**Comment by quicksketch** [comment]
Ha! Good point about the inconsistency, it *is* a little confusing. I took a short stab at improving the text but couldn't come up with a concise, clear way of expressing it. If you have a suggestion on text we're happy to change it.
