### ISSUE TITLE
Problem with File permissions and ownership page

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#571]
I could fix this, but I want to make sure that I don't make it worse. If I get confirmation that I'm correct, I'd be happy to make the fix. 

https://backdropcms.org/file-permissions-and-ownership

In both the strict and looser examples on this page the modules and themes directories appears to be set to 775

```
drwxrwxr-x  8 kris kris  4.0K Aug 27 08:43 core/
drwxrwxr-x 14 kris kris  4.0K Aug 14 17:52 files/
drwxrwxr-x  2 kris kris  4.0K May 24 21:44 layouts/
drwxrwxr-x 19 kris kris  4.0K Aug  2 10:11 modules/
drwxrwxr-x  5 kris kris  4.0K Aug 27 08:43 profiles/
drwxrwxr-x  3 kris kris  4.0K May 24 21:44 sites/
drwxrwxr-x  2 kris kris  4.0K May 24 21:44 themes/
```

But, in both cases, the instructions suggest setting them to 755

```
# Set the permissions for files and directories.
find . -type f -exec chmod 664 '{}' \;
find . -type d -exec chmod 755 '{}' \;
```
Which is correct and how should I fix this?

**Comment by oadaeh** [comment]
Assuming the user and group names refer to the same entity (as they imply), it doesn't actually matter if it's 755 or 775. However, based on the document and for consistency, I would say the `find . -type d -exec chmod 755 '{}' \;` line needs to be changed to `find . -type d -exec chmod 775 '{}' \;`.

**Comment by stpaultim** [comment]
OK, I went ahead and made the change recommended by @oadaeh - which reflected my own thoughts as well.
