### ISSUE TITLE
Issue with php-zip

### ISSUE THREAD

**Issue by tuxrouge** [backdrop-ops/backdropcms.org#572]
I have this message

> Sorry, it seems that the PHP .zip extension is not loaded on your server.
> You will not be able to download any projects using Project Installer until this is fixed.
> Please contact your website administrator. 

but php-zip seems good

```
$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
```
ls -l /etc/php/7.3/apache2/conf.d/20-zip.ini
lrwxrwxrwx 1 root root 35 Aug 13 12:29 /etc/php/7.3/apache2/conf.d/20-zip.ini -> /etc/php/7.3/mods-available/zip.ini
```

```
$ ls /etc/apache2/mods-enabled/
access_compat.load  authz_core.load  deflate.load  mime.load         php7.3.load      status.conf
alias.conf          authz_host.load  dir.conf      mpm_prefork.conf  reqtimeout.conf  status.load
alias.load          authz_user.load  dir.load      mpm_prefork.load  reqtimeout.load
auth_basic.load     autoindex.conf   env.load      negotiation.conf  rewrite.load
authn_core.load     autoindex.load   filter.load   negotiation.load  setenvif.conf
authn_file.load     deflate.conf     mime.conf     php7.3.conf       setenvif.load
```

I tryed

```
sudo phpenmod zip
sudo systemctl restart apache2
```

but nothing change

so, what's wrong with me ?

**Comment by tuxrouge** [comment]
In backdrop, zip is not loaded. a view from my report (in french, sorry)

> Backdrop CMS 1.13.3
> Base de données SQL  MySQL, MariaDB, or equivalent version 5.5.5-10.3.15-MariaDB-1
> php  Version 7.3.4-2 (information PHP)
> Prise en chage de MySQL Database 4-byte UTF-8 Non activé more
> Serveur web Apache/2.4.38 (Debian)
> Accès à update.php Protégé
> Affichage des messages d'erreur désactivé more
> Bibliothèque Unicode  Extension PHP mbstring
> Droits d'accès au nœud  désactivé (Reconstruire les droits d'accès) more
> Effets de rotation et de désaturation de la bibliothèque GD  2.2.5
> **Extensions PHP Activées : date, dom, filter, gd, hash, json, pcre, pdo, session, SimpleXML, SPL, xml**

**Comment by stpaultim** [comment]
I think this is a core issue and a ticket has been opened there:
https://github.com/backdrop/backdrop-issues/issues/3978

I'll close this issue. Please comment there. It does sound like this might be a bug. 

Thanks for reporting.
