### ISSUE TITLE
issue with permissions 

### ISSUE THREAD

**Issue by tuxrouge** [backdrop-ops/backdropcms.org#574]
HI

on a fresh installation, impossible to me to install modules or themes

"Failed to install one project, Permissions are not set up properly."

following https://backdropcms.org/file-permissions-and-ownership 
here is my /var/www/html directory

```
$ ls -al
total 68
drwxrwxr-x  9 aro aro  4096 Aug 16 11:14 .
drwxr-xr-x  3 root    root     4096 Aug 13 11:59 ..
drwxrwxr-x  2 aro aro  4096 Aug 13 11:58 backdrop
drwxrwxr-x  9 aro aro  4096 Aug 13 11:57 core
drwxrwxr-x 10 aro aro  4096 Aug 14 17:23 files
-rwxrwxr--  1 aro aro   578 Aug  7 22:39 index.php
drwxrwxr-x  2 aro aro  4096 Aug 13 11:57 layouts
drwxrwxr-x  2 aro aro  4096 Aug 13 11:57 modules
-rw-rw-r--  1 aro aro   206 Aug 13 16:45 phpinfo.php.old
-rw-rw-r--  1 aro aro  3978 Aug  7 22:39 README.md
-rw-rw-r--  1 aro aro  1216 Aug  7 22:39 robots.txt
-rw-rw-r--  1 aro aro 15990 Aug 13 12:08 settings.php
drwxrwxr-x  2 aro aro  4096 Aug 13 11:57 sites
drwxrwxr-x  2 aro aro  4096 Aug 13 11:57 themes
```

**Comment by stpaultim** [comment]
@tuxrouge - This issue queue is specifically for the backdropcms.org installation, not Backdrop core issues. You should probably take this question/issue to the core issue queue:

https://github.com/backdrop/backdrop-issues/issues

I would also look at the permissions related topics in our forum:
https://forum.backdropcms.org/search/node/permissions

Did you have any luck with this issue yet, I see this is about a month old?
