### ISSUE TITLE
Backdrop CMS Mini Camp at BADCamp 2019

### ISSUE THREAD

**Issue by oadaeh** [backdrop-ops/backdropcms.org#575]
As promoted on a previous outreach or dev call, I am starting an issue to begin the planning preparation for the Backdrop Mini Camp at BADCamp 2019 (sorry for being slow on getting this going).

Here are some potentially relevant links:
- [This year's planning document](https://docs.google.com/document/d/1l_riNLsd2uvIHLRJlBABMZlQ2T6LLGngcUmcZIPTK-A)
- [The badcamp session signup form](https://jenlampton.webform.com/form/27334)
- [The BADCamp page for the event](https://2019.badcamp.org/summit/backdrop-cms-mini-camp)
- [The issue that started it all](https://github.com/backdrop-ops/backdropcms.org/issues/503)
- [The Backdrop CMS Mini Camp page at Twin Cities Drupal Camp 2019](https://2019.tcdrupal.org/trainings/backdrop-mini-camp)
- [The d.o issue for the Backdrop CMS Mini Camp at Twin Cities Drupal Camp 2019](https://www.drupal.org/project/tcdrupal2019/issues/3037824)
- [A Google doc with the Backdrop CMS 2018 Summit Schedule](https://docs.google.com/document/d/1AgbxcHOHqrYQiFIjbc-5TEpIIDhqboop6mTbDjaTPUw/edit?usp=sharing_eip&ts=5d27a0e5)

Let the planning begin!

**Comment by stpaultim** [comment]
I don't think I'm going to be able to make it to BadCamp (although it's still an option). But, I'd like to help out in any way possible. I would love to write a summary of our experience in the Twin Cities and throw out some suggestions.

**Comment by oadaeh** [comment]
I'm willing to help with planning, organizing, and coordination as much as my limited availability will allow.
I am planning on being at BADCamp, but I'm not in the area, so I can't do anything logistically until after I get there late on Tue, Oct 1.
If there is a central repository to create documents and someone can start that (or give me the ability to do it), I can start carrying the ball from there.

**Comment by oadaeh** [comment]
Also, I noticed that there's some discrepancy in the times on the BADCamp site.
On the [Events page](https://2019.badcamp.org/events), it says "Summits registration at 8:30 am". However, on the the [Summits page](https://2019.badcamp.org/summits), all summits have a time frame of "8:00 AM-5:00 PM".
If it's more like the first one, then starting before 9 is unlikely. If it's the second, then starting at 8:30 is possible.
I suspect those times are mostly guesses, but I will want to get a more firm idea of the actual times for planning purposes. I have to assume that by now, they have a better idea of the actual times.

**Comment by oadaeh** [comment]
I created the start of a schedule based on the TCDrupal Mini Camp schedule and the BADCamp 2018 Summit schedule.
Obviously, not everything that happened in the previous two events will happen at this one, but I think the overall structure will still be largely the same, and that's what I created with some filler spots for potential sessions.

There are still some some questions in mind that I will need answered before I go too much further, like:
- Who will likely be attending and presenting
- What hours of the day will we have access to the room (how early may we arrive, and when do we have to be out)
- In the past, we had to account for a fire drill. Is that only a UCB thing, or will that happen at Hotel Shattuck, too?
- Will the room be ready for us when we get in it, or will we need to set it up?
- In lines with the previous question, what do we have to do before we leave it? (Obviously, not leaving a mess is necessary, but how mus tear down will we need to do?)

Most of that information above is necessary to know how much time we really have. For example, if we have to do set up and tear down, then we will likely have 30 to 60 minutes less time to do the mini camp than we have access to the room.
Also, since BADCamp will be at the hotel and not at the university, I personally cannot use past experience to judge future expectaions.

**Comment by oadaeh** [comment]
I just noticed that the training event is on Wednesday and the mini camp is on Thursday. Excellent!
I plan on attending the training to either help or heckle the trainers. Take your pick. :)

**Comment by jackaponte** [comment]
Thanks so much for getting this ticket going, @oadaeh!

After conferring in Gitter we decided to have a substantial meeting next week to start our BADCamp planning.

**Backdrop Outreach/BADCamp Planning Meeting**
Thursday, August 29, 12pm PT
http://bit.ly/backdrop-meetings

We can of course continue conversing here in the meantime, but I think a meeting will be great to help us get on the same page and figure out next steps. Looking forward to talking to folks then!

**Comment by jackaponte** [comment]
Notes from today's BADCamp planning meeting if folks are interested and want to catch up: https://docs.google.com/document/d/1l_riNLsd2uvIHLRJlBABMZlQ2T6LLGngcUmcZIPTK-A

**Comment by stpaultim** [comment]
Event is over. I'm going to close this issue, if there are followup issues I suggest a new ticket or reopen this one.
