### ISSUE TITLE
Recruit more issue advocates for 1.15.0 cycle

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#580]
Part of the reason for this post is just to provide a Github opportunity for community members to provide feedback on the ["advocate" role we tested this recent release cycle](https://backdropcms.org/user-guide/adding-milestones-issues). But also to suggest that we try to reach out and recruit a few more folks willing to act as advocates. 

I'm hoping that as a byproduct of recruiting advocates, we also recruit a few more people to help write pull requests - as adding more advocates without more coders to do the heavy lifting is probably not helpful. I think we only had about 5-6 advocates this cycle, a nice goal might be to see that increase to 8 or 9 (assuming we stick with the process)?

I wrote a [draft blog post](https://backdropcms.org/news/become-advocate-new-feature-backdrop-cms-1150) about becoming an issue advocate (for those who are able to read draft posts). 

Personally, I found the role of issue advocate to be empowering and encouraged me to engage differently than I had in the past. Any other thoughts?

Other ideas on how this might work better?

**Comment by jenlampton** [comment]
Yes, I love this idea :)

**Comment by stpaultim** [comment]
In Gitter today, we got two questions about advocating. 

> @laryn asked "If I want to advocate for an issue do I just add my name in the description and tag it to the milestone?"

I think the answer is yes to that. 

> @oadaeh asked "Is it was "legal" to advocate for your own feature request?"

Again, in my opinion it's absolutely "legal," maybe even encouraged. ;-)

**Comment by BWPanda** [comment]
Considering the 1.15.0 cycle was 12 months ago, should we close this issue now...?
