### ISSUE TITLE
Configure Trusted host pattern for Tugboat demo site

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/backdropcms.org#581]
In version 1.14.0 Backdrop introduced the *Trusted Host Setting*. A *Tugboat* demo site started on https://backdropcms.org/demo/create runs on 1.14.0 (at the time of writing) but the *Trusted Host Setting* isn't configured, which leads to a warning on the *Status report* page -- a not so nice first impression, in my opinion.

Is it possible to (pre-)configure *settings.php* of the demo sites so that the *Trusted Host Setting* is configured correctly or to suppress the warning via `$settings['trusted_host_patterns'] = FALSE;`?

**Comment by BWPanda** [comment]
I believe this has been fixed. Can you confirm @olafgrabienski?

**Comment by olafgrabienski** [comment]
@BWPanda Yep, it is fixed:

> Current hostname is trusted
> Configured to allow the following pattern: `^.+\.tugboat\.qa$`

Backdrop version in the current demo is 1.14.2.

**Comment by olafgrabienski** [comment]
Thanks to the person who fixed it! Closing the issue.
