### ISSUE TITLE
TUGBOAT - Flexible layouts not working correctly

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#582]
Calling this a Tugboat issue and not a core bug, because the behavior on Tugboat is different than in my test installations of core. Is this the best place for Tugboat issues?

Steps to recreate:

1) Spin up new DEMO site (using Tugboat)
2) Create a new flexible layout, keep the defaults (no changes) and save
3) Change the homepage layout to use your new flexible layout
4) All of the blocks are lost and you get the following message "_The following blocks have been reassigned to the region._" which does NOT name the region where the blocks have gone. 

If I do the same thing in my local demo site, the blocks are all in the footer and the messages says: "_The following blocks have been reassigned to the Footer region._" - it includes the region "footer"

![Home_page__home____master-1gntpovi577cj3pc5sj7xokfefklug73_tugboat_qa](https://user-images.githubusercontent.com/3144571/65216352-31eb2180-da76-11e9-8482-796069d84529.png)

I done both processes in serveral Tugboat instances as well as several local clean instances. Every time the results are the same.

**Comment by quicksketch** [comment]
Thanks @stpaultim! I think this was caused by a bad merge on my part. I've replaced the affected file with the one from 1.14.0 and committed it in https://github.com/backdrop-ops/backdrop-tugboat/commit/38d39e40ee6c145a696c136bf62329971f686de8. I'll rebuild the preview on Tugboat and then we can check if it's fixed.

**Comment by quicksketch** [comment]
The tugboat preview is rebuilt. Can you check if this is now fixed?

**Comment by stpaultim** [comment]
@quicksketch - I can't create a Tugboat site at all right now. Did you make things worse? 
:-)

**Comment by stpaultim** [comment]
I just want to confirm that Tugboat is working and that the problem described appears to be resolved. 

Thanks @quicksketch for resolving this quickly.
