### ISSUE TITLE
Strange positioning of tags field on sandbox sites

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#585]
I'm not sure if this is a bug or even a problem, but it looks like a weird anomaly to me and if this is acting weird, what else might be.

If I try to edit the "My first post" post in any of the CI sandboxes, the "tags" field is below the body, I would expect it to be above the body - based upon what happens with Tugboat demo sites and my local sandbox for Backdrop Core.

![Edit_Post_Your_first_post____PR_2911_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/65824711-de759200-e232-11e9-88a3-505a9453ee8c.png)

![Edit_Post_Your_first_post____demo](https://user-images.githubusercontent.com/3144571/65824729-1250b780-e233-11e9-8f7d-c1d5ded2155d.png)

**Comment by BWPanda** [comment]
@stpaultim Is this still an issue? If so, can you provide more info/links to sites that work as expected vs. those that don't?

**Comment by stpaultim** [comment]
I just tested two PR sandboxes and both of them worked as expected today. Maybe this problem has resolved itself over the last 3 years, a lot has changed in our Github CI processes and tools. 

I'll close the issue.
