### ISSUE TITLE
List Bug Squad members via the GitHub API

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#591]
It appears that "Visible" teams are still invisible to those who are not logged into GitHub. We would like to see if we can pull out the Bug Squad members via the API, to list them on this page:
https://backdropcms.org/contribute/bug-squad

Relevant issue: https://github.com/backdrop-ops/contrib/issues/334

----
PR: https://github.com/backdrop-ops/backdropcms.org/pull/604

**Comment by klonos** [comment]
Wondering if for the time being we can manually list them in https://backdropcms.org/user-guide/roles-responsibilities-and-points-contact

**Comment by jenlampton** [comment]
I'm against both those ideas. Anything manual is going to be out of date as soon as we type it, and making a manual thing beautiful might turn out to be a waste of effort. 

What about adding a screenshot? Would that be beautiful enough? It's certainly less work, and would be easy to update :D

**Comment by serundeputy** [comment]
I can get the team members from GitHub api, I then put them in a block, but placing the block goes in a weird place:

![image](https://user-images.githubusercontent.com/6763671/68064987-289dd780-fcf9-11e9-9621-f6eb6c38ed9a.png)

am I better off `_preprocess`ing the page? 

ideas?

**Comment by serundeputy** [comment]
This is what it looks like in the sidebar:
![image](https://user-images.githubusercontent.com/6763671/68071544-c8874f80-fd51-11e9-9710-b4c3df3e6fb9.png)

**Comment by jenlampton** [comment]
That's better, but not as good as it would be in the main content area, just above the book navigation. What do you think @klonos?

**Comment by serundeputy** [comment]
![image](https://user-images.githubusercontent.com/6763671/68246264-714ddd00-ffe6-11e9-83fa-3c4f6a5447c6.png)

**Comment by jenlampton** [comment]
IDK how you got the photos, but it looks great!!!! Can we have a heading? `Big Squad Members` is probably good enough :)

**Comment by serundeputy** [comment]
@jenlampton ready for QA.

Added PR https://github.com/backdrop-ops/backdropcms.org/pull/604

* pulls in bug squad members via api
* renders members and avatar in `borg_field__body__docs` in `template.php`
* adds some css for display

**Comment by jenlampton** [comment]
Merged the PR!

**Comment by jenlampton** [comment]
@serundeputy I just noticed that this PR contains CSS changes to the base theme. These CSS changes are going to be reverted when we replace the borg theme if they were not also included in https://github.com/backdrop-contrib/borg, and I didn't see a relevant issue in that queue.

Do you anticipate any visual regression once the updated theme is deployed? If so, we should hold off on updating all sites to the latest borg theme until the CSS has been applied and merged upstream.

**Comment by jenlampton** [comment]
I've refactored the theme changes to be inline with backdrop coding standards, added safety checks, and removed all the added css. Changes committed to borg theme. Closing issue again.
