### ISSUE TITLE
Reconsider the order of the releases in the Roadmap page

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#593]
...splitting this off of #307. This is also related to #592.

> The [Github page](https://github.com/backdrop/backdrop/releases) lists the releases from newest to oldest, which IMO is the proper way to list releases. [Our roadmap page](https://backdropcms.org/roadmap) though lists from oldest to newest and also includes releases planed for the future. This has effectively put the current release somewhere in the middle of that page, but as more release announcements were created (and as more will be added in the future), the current release will be "pushed" further down the page requiring more scrolling for the users to reach it. It is good that we have the index at the top, so that users can jump to the release they are interested in, but do you think that we should perhaps split the content of this page to a "roadmap" and a "changelog"? Perhaps reverse the order in which releases are listed, so to be from planned to current to passed ones?

Another idea is to have the jump list be a block, and have it be in the right hand sidebar. That way, the first items in the roadmap page will be:

- what's planned for 2.0
- what's planned for 1.x
- what's planned for the next minor release
- key features for the current release
- key features of all the older releases ...

**Comment by klonos** [comment]
> ...have the jump list be a block ...

Perhaps help complete the port of https://github.com/backdrop-contrib/tocbot, and use that?

**Comment by klonos** [comment]
...but also copy-pasting that whole jump list into a custom block would work 😉

**Comment by olafgrabienski** [comment]
> Perhaps help complete the port of https://github.com/backdrop-contrib/tocbot, and use that?

Worth a try - Tocbot looks and works good! Have you seen it in action? There's a demo TOC on the Github page of the library: https://tscanlin.github.io/tocbot.

I'll appreciate any help. Actually I have ideas how to continue. Hadn't much time last week, and I'm not sure about the next one but I'll continue the port as soon as possible.

**Comment by klonos** [comment]
...in the meantime, someone has split the huge roadmap list into https://backdropcms.org/roadmap and https://backdropcms.org/user-guide/project-history ...was it any of you @jenlampton or @stpaultim? ...I love it ❤️ 👍 ...I am also loving the rewording on the 2.0 and 1.x.

So the main _Roadmap_ page holds info about 2.0, 1.x, and the upcoming 1.15, but I think that it should also hold info about the most recently-released/current version each time. Having said that, I realize how having an already-released version on a page titled "roadmap" may be slightly odd.

Also, now that this list there is shorter, I would also like us to consider reverting the order of releases, with 2.0 being at the end of the list. Again, having said that, I realize that we may need to draw people's attention to the fact that we will be supporting 1.x for many years after the EoL of D7.

I will try to get some screenshots of what I am proposing, so we can compare and decide...

**Comment by jenlampton** [comment]
It was me who split the pages, the roadmap page was getting too long. 

I also thought about leaving the current release on there, but waffled and took it off. Happy to put it back if people prefer that.

I also wasn't sure about the order of items on the roadmap page, but thought that if people were going there they would most likely be interested in info about 2.x.

**Comment by klonos** [comment]
> thought that if people were going there they would most likely be interested in info about 2.x.

I think that they may be equally interested to known how recent/old the current release is, compared to the planned date and features for the next release (gives a sense of activity).

**Comment by klonos** [comment]
...here's what I was thinking:

![2019-10-31-08-26-backdropcms org](https://user-images.githubusercontent.com/2423362/67900289-444d9480-fbb8-11e9-958f-c70d3eda5d1c.png)

**Comment by klonos** [comment]
...I wouldn't mind keeping a copy of the most recent release in the project history page.

**Comment by jenlampton** [comment]
I think it looks good both ways :)

**Comment by oadaeh** [comment]
> I think that they may be equally interested to know how recent/old the current release is, compared to the planned date and features for the next release (gives a sense of activity).

I will validate Greg's comment there to say that when I am evaluating software to potentially use, this is one of the things I look for. I want to see both what their plans for the future are (or if they have any) and their recent & past activity has been.
I'm not sure I would necessarily care about the order when looking for that info, as I will scroll down or click around to find what I'm looking for, but I would probably be looking for the most recent/relevant entries first and then going forward and/or backward from there.

**Comment by klonos** [comment]
Cool ...I went ahead and saved that draft: https://backdropcms.org/roadmap

Lets close this one 🙂 

PS: I have left a copy of the entry for the current 1.14 release at https://backdropcms.org/user-guide/project-history
