### ISSUE TITLE
Request for server access

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#601]
I would like to request access to Backdrop's servers (and admin permissions on the sites running on them). This is because I believe I can help with issues relating to the infrastructure (e.g. https://github.com/backdrop-ops/api.backdropcms.org/issues/4) and because I may be able to help take some of the burden off the few others with access (@larsdesigns) when they're busy, etc.

I have experience with server admin (I have setup and currently run/manage two of my own Linode servers (one web server for my own clients and a personal backup server)) but I am the first to admit I don't know everything and can always learn more!

I believe @serundeputy would also like more access than what he has now for the same reasons...?

**Comment by larsdesigns** [comment]
@BWPanda, These decisions are little above me but a ticket is a good place to start.

**Comment by quicksketch** [comment]
This would be great @BWPanda! I'll get you invited to 1Password and put your public key up on the servers.

**Comment by BWPanda** [comment]
Awesome @quicksketch! How would you like me to send my SSH key? PM in Gitter, here (is that safe?), email...?

**Comment by BWPanda** [comment]
@quicksketch has given me access to 1Password and the servers now, so all good.
