### ISSUE TITLE
B.org: Better styling for inline code

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#609]
Once https://github.com/backdrop-contrib/borg/issues/5 is committed to the Borg base theme, we should make sure the backdropcms sub-theme has the appropriate styles for inline code too.

**Comment by Graham-72** [comment]
I need this please for draft guide to use of Basis https://backdropcms.org/news/using-backdrops-basis-theme. This is a re-publication of an original by @wesruv and needs appropriate styling for inline code phrases i.e. ability to apply  `<span>` to words.

**Comment by BWPanda** [comment]
I'll make a PR for this tonight (in 10 hrs) unless someone gets to it before me 😊

**Comment by BWPanda** [comment]
I started looking into this, and it turns out that the custom B.org sub-theme doesn't have any custom styling for code blocks. Therefore closing this as a duplicate of https://github.com/backdrop-contrib/borg/issues/5 (once it's committed this site will be updated too).
