### ISSUE TITLE
Allow user logins to BackdropCMS.org

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#61]
Right now we only have a handful of user accounts on BackdropCMS.org. We should allow login to the site so that users can manage the new project and project release nodes.

In consideration of login, we should provide at least the following:
- Spam prevention to keep out automated account creation (any suggestions here)?
- A sign-on with GitHub or OAuth authentication with GitHub to validate the connection.

Eventually we'll want to make a user profile page, but for starters we'll probably just include a description + basic user fields.

**Comment by klonos** [comment]
> - Spam prevention to keep out automated account creation (any suggestions here)?

Honeypot of course! Seems to be working great for d.org (https://www.drupal.org/software) for quite some time now + it's already ported: https://github.com/backdrop-contrib/honeypot

> - A sign-on with GitHub or OAuth authentication with GitHub to validate the connection.

Have you thought of asking Dries for permission to integrate with d.org accounts?

**Comment by quicksketch** [comment]
> Have you thought of asking Dries for permission to integrate with d.org accounts?

I think we might manage permission if we truly wanted to do that, but there's a technical limitation here in that d.o doesn't provide a centralized login service (afaik) other than Bakery module, which requires shared cookies across subdomains. That's why DrupalCon is https://events.drupal.org/losangeles2015 instead of http://drupalcon.org, they need the shared domain for the single sign-on to work. If d.o did have a true single sign-on, we'd be seeing camps using it instead of requiring new registrations every time.

Technical and permission requirements aside, I'm not sure we'd want to do this. It would be great for transition, but long-term I think we'll see a decreasing overlap between Backdrop and Drupal. Providing a drupal.org login two years from now might seem as out of place as a Wordpress.com login.

**Comment by klonos** [comment]
Fair enough. Was just a thought because, frankly, I believe that 99,9% of Backdrop CMS users will be Drupal users ("converts" if you like) and they most likely have d.org accounts already.

**Comment by docwilmot** [comment]
Off-topic but...
> I believe that 99,9% of Backdrop CMS users will be Drupal users

I've been using comparisons to Wordpress in my postings here and on Reddit more often, because I think we should be changing the mindset of which CMS we need to emulate.

**Comment by klonos** [comment]
> ...I think we should be changing the mindset of which CMS we need to emulate.

I really like the idea behind this comment: keep the back-end (code, DX) the same as Drupal as well as the spirit of the community, but brink the improvements that made Wordpress the end-user's favorite CMS. If these guys created a CMS that [runs 23.7% of the net and more than 60% of all CMS websites](http://w3techs.com/technologies/overview/content_management/all) (compared to only 2% and 5.1% respectively for Drupal), they must have done something better.

**Comment by jenlampton** [comment]
Users are logging in!!!!  closing this issue :)
