### ISSUE TITLE
Fix main menu on Showcase nodes (phones)

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#615]
This applies to phones/small screens.

On the Showcase page, the main menu works well (menu button on the right, drop-down menu centred on screen).

[![Screenshot-20191208-184730-Brave.png](https://i.postimg.cc/ZRk7HM09/Screenshot-20191208-184730-Brave.png)](https://postimg.cc/Z9cxKj8Z)

But on Showcase *nodes*, the menu button is on the left and the drop-down menu goes off the left side of the screen so that none of the links are visible.

[![Screenshot-20191208-184906-Brave.png](https://i.postimg.cc/hjPr2Rct/Screenshot-20191208-184906-Brave.png)](https://postimg.cc/PL9YqcCg)

**Comment by jenlampton** [comment]
This is certainly weird and not intended...

**Comment by BWPanda** [comment]
So the main Showcase page uses the Boxton layout, while Showcase nodes use a custom 'Case study' layout. The Borg theme overrides the Boxton layout to add a 'row' div to the header, so this PR does the same for the 'Case study' layout: https://github.com/backdrop-ops/backdropcms.org/pull/682
