### ISSUE TITLE
Set up Tugboat for testing PRs for backdropcms.org

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#621]
In today's meetings we discussed setting up a tugboat workflow where each PR against backdropcms.org could be tested in a sandbox before merge. 

To do this, someone will need to look at the way we have the demo site set up, and add a similar `tugboat.yml` file into this repo. Then, they will need to log into https://tugboat.qa/ (using credentials from the Backdrop 1Password account -- sysadmin level) and associate a tugboat instance with this repository. 

Related: 
https://github.com/backdrop-ops/api.backdropcms.org/issues/80
https://github.com/backdrop-ops/forum.backdropcms.org/issues/105

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/backdropcms.org/pull/742

**Comment by BWPanda** [comment]
Done. Can't test if it working properly yet as the base preview is already over quota, but I'll ask the Tugboat guys to increase that for use then we can test a PR.
