### ISSUE TITLE
Replace custom Tugboat module with contrib one

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#631]
I re-wrote the custom Tugboat module in use on B.org and released it as a contrib module (for reasons explained [here](https://panda.id.au/posts/introducing-the-first-backdrop-challenge)): https://github.com/backdrop-contrib/tugboat

It'd be great if B.org could start using the contrib module instead of its custom one. Not only so it'd have more eyes on it, feature & pull requests, etc., but also because the contrib module uses Tugboat's new API which I think is better than the old command line tool (and maybe less buggy...?).

**Comment by BWPanda** [comment]
Here's a [PR](https://github.com/backdrop-ops/backdropcms.org/pull/644) that:

- Adds the [Tugboat contrib module](https://github.com/backdrop-contrib/tugboat) and configures it
- Re-purposes the `borg_tugboat` custom module to hold BackdropCMS.org-specific customisations for the main Tugboat module (template overrides, form alters, etc.)
- Changes links from the old `/demo/create` URL to the new `/demo` URL

Some changes to the live database will be needed when this is committed:

- Create a redirect (`/admin/config/urls/redirect`) from `/demo/create` to `/demo`
- Edit the Tugboat platform node (`/node/2330`) to change the 'Create demo' page URLs (as above)
