### ISSUE TITLE
Service Providers page only shows USA by default

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#633]
The [Service Providers](https://backdropcms.org/support/services) page is filtered by Country: United States by default. That seems a bit unfair. Can we make it 'Any' by default please?

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop-ops/backdropcms.org/pull/714

**Comment by laryn** [comment]
Looks good to me.

**Comment by BWPanda** [comment]
Thanks @laryn! https://github.com/backdrop-ops/backdropcms.org/pull/714 has been merged and the live site updated: https://backdropcms.org/support/services
