### ISSUE TITLE
Github API: use the Authorization HTTP header

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#636]
We got this email today from GitHub:

---

Hello there!

On February 3rd, 2020 at 22:19 (UTC) your application (BackdropCMS.org) used an access token (with the User-Agent Backdrop CMS GitHub API module) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/repositories/45898954/readme

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team

**Comment by jenlampton** [comment]
@serundeputy would you have time to work on this?

**Comment by serundeputy** [comment]
Yep; I'll find some time

**Comment by jenlampton** [comment]
thank you!

**Comment by quicksketch** [comment]
Thanks @serundeputy!

**Comment by serundeputy** [comment]
@jenlampton @quicksketch githbapi is a contrib module; I'll do the work over there: https://github.com/backdrop-contrib/githubapi/issues/21
