### ISSUE TITLE
Update Drush in Lando to v1.3.0

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#645]
This repo's Lando file is using an old version of Drush. Can we update it please? :pray:

**Comment by BWPanda** [comment]
PR here: https://github.com/backdrop-ops/backdropcms.org/pull/646

**Comment by BWPanda** [comment]
New PR here: https://github.com/backdrop-ops/backdropcms.org/pull/647

**Comment by serundeputy** [comment]
thanks @BWPanda went ahead and merged this so devs can have the latest `drush`; no effect on b.org just locals.
