### ISSUE TITLE
Remove Tugboat binary

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#648]
As a follow-up to https://github.com/backdrop-ops/backdropcms.org/issues/631, I realised that I forgot to remove the old (and now unnecessary) Tugboat binary from the repo: https://github.com/backdrop-ops/backdropcms.org/tree/master/bin

We should do that.

**Comment by BWPanda** [comment]
And here's an PR: https://github.com/backdrop-ops/backdropcms.org/pull/649

**Comment by klonos** [comment]
...perhaps we should also use something like https://rtyley.github.io/bfg-repo-cleaner to clean the binary(ies) from the git index/history ...takes less time to clone 😉

**Comment by BWPanda** [comment]
@klonos Not sure about that... Don't really understand how it works. Maybe that's a separate issue...?

**Comment by klonos** [comment]
Follow-up here: #686
