### ISSUE TITLE
Allow cropping profile photos

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#653]
Profile photos are currently centred (I believe). It'd be nice to be able to crop them manually.

**Comment by BWPanda** [comment]
Here's a PR that does this: https://github.com/backdrop-ops/backdropcms.org/pull/684

We were using the Medium image style, but I noticed an unused 'Headshot - large' image style. Since the image field on the user profile is called 'Headshot', I re-purposed the 'Headshot' image style with the cropping ability.

Before:
![image](https://user-images.githubusercontent.com/2385329/82370117-b08ec900-9a20-11ea-8c77-31d3537f09cc.png)

After:
![image](https://user-images.githubusercontent.com/2385329/82370238-e7fd7580-9a20-11ea-8762-a4e7c2fbd8a5.png)

**Comment by jenlampton** [comment]
@BWPanda can you please explain what the PR does? It touches 48 files, and that seems like it does a lot more than swapping the current image style for another. 

On the backdropcms.org site our priority is to keep this site easy to maintain, and that often means limiting the number of nice-to-have contirb modules when the core solutions are "good enough".

For profile photos, showing people what their profile photo will look like via the preview is sufficient. As long as we always use the image style we show them in the preview when we render a profile photo, people will be able to adjust their own photos as needed (via cropping or otherwise) until they have one they are happy with.

**Comment by BWPanda** [comment]
Looks like the changes include adding the manualcrop module and its dependencies.

**Comment by jenlampton** [comment]
So, this is probably too big a change. Is there anything we can do to improve the profile photo situation that doesn't add any additional modules?

**Comment by BWPanda** [comment]
@jenlampton So the problem is that users can upload any old image (portrait or landscape orientation), and then the site wants to display it in a square ratio (albeit with rounded corners to look like a circle). As a result, either:

1. Part of the image will be cut off (and that may be an important part - this is what happens currently)
2. Gaps will be visible around the image (if we try to display the whole image inside the square area)

Obviously for consistency option 1 is the best as it means all images will be square and look more-or-less the same. However, since the automated cropping doesn't know what the important part of an image is, the cropping may not result in the best image (and it can't be changed).

So either we allow custom cropping of images (or specifying the important part of an image so it doesn't get cropped), or we remove the cropping altogether and simply resize the uploaded image to fit into the square area. Have I missed any other options?

Since my PR above, I've come across the [Focal Point](https://github.com/backdrop-contrib/focal_point) contrib module. It allows you to specify the important part of an image so that it doesn't get cropped out and it's as centered as possible in the final image. If the 3 modules necessary to use Manual Crop were too much, maybe just one module would be better...?

**Comment by jenlampton** [comment]
We only display the profile image one way across the whole site. As long as people can see how it's displayed immediately when they upload the image, they will be able to select a different image, or crop it differently if they prefer. Most people are familiar with this process.

Modules like focal_point are necessary when the same image is cropped differently in different displays across the site. If the same picture is landscape in one place and portrait in another, that's when we need to add something smarter to determine how the crop should happen in each situation. We don't have those complexities with the profile photo on b.org.

**Comment by BWPanda** [comment]
Ok, so basically the solution here is for people to crop photos first, then upload them. Closing as 'won't fix'.

**Comment by jenlampton** [comment]
That'd be my preference. I'd be happy to include more help text or something if that would help set expectations.

> I believe most people are familiar with this process.

Or, if we end up getting feedback that this is not the case, we can revisit.
