### ISSUE TITLE
"SMTP Error: Could not authenticate." error

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#657]
B.org seems to be struggling to send emails. It's giving an "SMTP Error: Could not authenticate." error...

Originally reported here: https://forum.backdropcms.org/forum/unable-send-e-mail-contact-site-administrator-if-problem-persists-1

**Comment by BWPanda** [comment]
I tested using the "E-mail address to send a test e-mail to" field on this page: https://backdropcms.org/admin/config/system/smtp

**Comment by BWPanda** [comment]
I think @jenlampton and/or @larsdesigns are the ones with knowledge about Backdrop's SMTP...

**Comment by quicksketch** [comment]
So we had a few failures here:

- Our MailJet account (the SMTP provider) seems to have cancelled our account.
- They probably sent us an email about it. But ironically the email forwarding at Namecheap (which receives info@backdropcms.org emails) blocks emails from MailJet.

We previously set up MailJet while trying to get fully validated for DMARC (#607). But we're also fully set up to send email without SMTP at all now. So for now I've just disabled SMTP functionality on backdropcms.org, and we're sending email directly from the Linode server now.

**Comment by BWPanda** [comment]
I was able to send myself an email using my B.org contact form, so I'll close this as fixed.
