### ISSUE TITLE
Send "New Forum Post" messages to Zulip

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#659]
We currently get automatic notifications in Gitter whenever a user posts a new topic in the forum. 

We'd like to move that functionality to Zulip. 

----

- [x] research zulip api
- [x] implement logic f.b.org module to post new forum posts to zulip

**Comment by klonos** [comment]
Pinging @serundeputy, as he was the one to work on the Gitter implementation IIRC.

**Comment by serundeputy** [comment]
i have not found any time to look at zulip available APIs yet :panda_face:

**Comment by BWPanda** [comment]
It'd be nice to get this done, and remove the bot from Gitter:

![Screenshot 2020-03-23](https://user-images.githubusercontent.com/2385329/77337481-9f338400-6d31-11ea-99c1-5a6cb356f7da.png)

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/110

To get this live we need to: 
  - [ ] On live forum disable the `borg_gitter` module
  - [ ] uninstall `borg_gitter` module
  - [ ] merge PR
  - [ ]  enable `borg_zulip` module

@jenlampton or @BWPanda can one of you do those things?

**Comment by jenlampton** [comment]
@serundeputy  where do we get the Zulip API key?

**Comment by BWPanda** [comment]
@jenlampton beat me to it :slightly_smiling_face:

**Comment by jenlampton** [comment]
@BWPanda if you want to take over from here, go for it. I got stuck :)

**Comment by serundeputy** [comment]
i;ll put up a ff secret

**Comment by BWPanda** [comment]
@jenlampton Can you do it? What are you stuck with?

**Comment by BWPanda** [comment]
@serundeputy All done, I think. Want to give it a test?

**Comment by BWPanda** [comment]
I tested, looks like it works! Thanks so much @serundeputy :heart:
