### ISSUE TITLE
Make Tugboat demo links open in a new tab/window

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#667]
Now that [auto-login is working and the admin username/password is displayed](https://github.com/backdrop-ops/backdropcms.org/issues/661) for demo sandboxes, if you navigate away from the 'ready' page then you may lose access to the URL, username or password for the site. Granted, the username and password are always the same now, but still, I think it's best practice to keep that page open when clicking to view the sandbox...

**Comment by BWPanda** [comment]
PR added.

**Comment by quicksketch** [comment]
Sounds good to me! Merged.
