### ISSUE TITLE
New streams in Zulip

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#675]
Use this topic to request a new stream in Zulip. 

We are trying to create as few streams as possible with liberal use of topics. If you are part of a group or project in Backdrop CMS that would like a unique stream, please post your request here. Currently, only Zulip admins can create streams. 

Current public streams include:

1. **Backdrop** - the main stream for discussion of all things Backdrop.
2. **Community Chat** - This is a designated place to talk about things that are happening in the real world and/or tech that are not Backdrop CMS related. _(We are looking for a new name for this stream)._ 
3. **Forum** - This stream is currently for automatic forum notifications and discussion of these issues. _(The future of this stream is under discussion)_
4. **Core Notifications** - This stream was set up to handle automatic notifications from Github about core issues. It is not yet working or being used. This will probably be a read-only stream. 
5. **Contrib** - We are deprecating this stream and made it read only until we delete it. Please use the main Backdrop stream to discuss contrib related issues.

**Comment by BWPanda** [comment]
I think the current list of streams is fairly inclusive, but if more are needed maybe people can just open an issue then. Closing this for now.

**Comment by philsward** [comment]
So more specific streams in Zulip isn't confusing to people, but a group of specific topic repos on github is confusing to people?

I'm so confused...
