### ISSUE TITLE
I Make FOSS

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#676]
Heard about this recently and wondered if some Twitter-savy Backdropper would like to apply to participate...?

https://twitter.com/imakefoss

Apparently the idea is to hand over the IMakeFOSS Twitter account to a different open-source developer each week so they can share what they're working on, their life in open-source, etc.

Possibly more info here: https://youtu.be/I1PpyQWUCVc?t=290

**Comment by stpaultim** [comment]
Interesting idea. I just found this issue and looked at the Twitter feed and website. 

https://imakefoss.org/

I think we should talk about this at an upcoming outreach meeting.

**Comment by BWPanda** [comment]
Closing due to lack of interest (and also not really the right issue queue).

**Comment by stpaultim** [comment]
@BWPanda - For the record, I've been following this account since you drew it to my attention and frequently share and retweet posts from this account. I don't think I've noticed any recent activity.

**Comment by stpaultim** [comment]
@BWPanda the account seems inactive at this time. It's not that I have not had interest in this and I can easily see coming back to this issue if the ticket were to remain open. However, I'm also ok if we close it.

Really, an issue like this one just needs someone interested in pushing it along to make it happen. Someone might find it in the future and push it along.

**Comment by stpaultim** [comment]
Last post tonight. I just went to their websit and dont' see any form to volunteer. Not sure if they are looking for volunteers or how they do it.
