### ISSUE TITLE
[DX] Updte sql-dump-sanitize to add a *-latest.sql.gz and *-latest.tar.gz for automatic downloading feature.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#677]
@larsdesigns Can you

- [x] update the `sql-dump-sanitize` script to either latest `master` or this tag https://github.com/serundeputy/sql-dump-sanitize/releases/tag/1.1.0
- [x] update the cron jobs for files and database backups to include the new `--latest` flag

This will allow me to add tooling to the lando file to add `pulldb` and `pullfiles` commands so users who wish to contribute to the b.org, f.b.org, and api.b.org sites can easily pull databases and files.

**Comment by larsdesigns** [comment]
ok

**Comment by larsdesigns** [comment]
@serundeputy, The tasks have been completed.

**Comment by serundeputy** [comment]
This is great thanks so much @larsdesigns !

**Comment by larsdesigns** [comment]
@jenlampton, I went ahead and made a cron job to perform a git pull from master every five minutes so that @serundeputy can maintain the code.

**Comment by jenlampton** [comment]
@larsdesigns I don't think an automatic pull from master sounds very safe, Can we switch it to use the actual (approved) release? This won't change very often, so checking every 5 minutes seems extreme. Once per day should be enough.

**Comment by jenlampton** [comment]
I guess this ticket can remained closed...  @larsdesigns do you want a new one for the con job work?

**Comment by larsdesigns** [comment]
@serundeputy Please create a release branch and let me know what it will be named.

**Comment by larsdesigns** [comment]
Re-opening the ticket to work on the cron job.

**Comment by serundeputy** [comment]
@larsdesigns the releases ae tags so the latest is https://github.com/serundeputy/sql-dump-sanitize/releases/tag/1.1.0

**Comment by larsdesigns** [comment]
I do not think it is possible to automate tagged releases using cron. Can you create a branch other than master that we can pull from? Like `stable-release` or something like that?

**Comment by serundeputy** [comment]
I'll whip up a script to check for and pull latest release.  For now let's just remove the current cron job. And when I have the script we can put that in as a cron job.

**Comment by larsdesigns** [comment]
@serundeputy, Okay, I have removed the cron job. No further tasks.

**Comment by serundeputy** [comment]
@larsdesigns the files part of this is not working, i.e. the `backdropcms.org-files-latest.tar.gz` link on sanitize.backdropcms.org does not download anything.

I'm not sure if the problem is the cron job, the nginx webpage markup, or sql-dump-sanitze, but I've tested the sql-dump-sanitze part locally and it is working for me ... can you take a look and see if anything is misconfigured?

thanks!

**Comment by BWPanda** [comment]
@serundeputy It was a symlink pointing to a non-existent file. I will work on fixing this as part of https://github.com/backdrop-ops/backdropcms.org/issues/702.
