### ISSUE TITLE
[DX] Add lando tooling to easily grab latest sanitized db.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#678]
In https://github.com/backdrop-ops/backdropcms.org/issues/677 we added the symlink to the `latest` database backup.

In this issue let's add tooling to automate grabbing the latest backup and piping it into our local backdropcms.org lando app.

----

PR: https://github.com/backdrop-ops/backdropcms.org/pull/679

**Comment by serundeputy** [comment]
Added PR for the tooling: https://github.com/backdrop-ops/backdropcms.org/pull/679

@BWPanda care to give this a CR and a merge when you get a chance?

**Comment by BWPanda** [comment]
Thanks @serundeputy. I left a review requesting changes.

**Comment by serundeputy** [comment]
Thanks! I've updated the PR to address some of your concerns.
https://github.com/backdrop-ops/backdropcms.org/pull/679

**Comment by BWPanda** [comment]
Marking as needs feedback to get others' opinions on:

- https://github.com/backdrop-ops/backdropcms.org/pull/679#discussion_r410728217
  (I suspect we don't need the old lines, but it'd be good to hear from whoever added them originally)
- https://github.com/backdrop-ops/backdropcms.org/pull/679#discussion_r410728448
  (I don't think scripts should be in the `config` directory (they're not configuration))

**Comment by serundeputy** [comment]
@jenlampton any input appreciated.

@BWPanda and I are at an impass ... he doesn't like how I did it, but there is no recommendation on what he would like.

**Comment by quicksketch** [comment]
Thanks @serundeputy for this! As I've started using Lando for b.org development I appreciate this change. I added a few comments to the PR.

**Comment by serundeputy** [comment]
@BWPanda @quicksketch I've updated the PR to

* document the `LP_*` variables
* move the `scripts/` directory to the project root
* remove dupe entries in `.gitignore`

**Comment by BWPanda** [comment]
Looks good to me!

**Comment by serundeputy** [comment]
[PR 679](https://github.com/backdrop-ops/backdropcms.org/pull/679) is/was closed w/ no explanation.
@jenlampton are we not doing this?

**Comment by BWPanda** [comment]
Looks like the PR has been merged now. Closing this issue as fixed.
