### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#680]
Email from github:

---

Hello there!

On May 6th, 2020 at 05:50 (UTC) your application (BackdropCMS.org) used an access token (with the User-Agent Backdrop CMS GitHub API module) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/repositories/32948858/readme

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team

**Comment by jenlampton** [comment]
@serundeputy I thought we had fixed this previously?

**Comment by serundeputy** [comment]
it was never reviewed/merged.

**Comment by serundeputy** [comment]
https://github.com/backdrop-contrib/githubapi/issues/21

**Comment by jenlampton** [comment]
ah, ty!
