### ISSUE TITLE
Create a blog post for the Backdrop 1.16

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#681]
* draft blog post
* roadmap page review

**Comment by serundeputy** [comment]
@jenlampton @klonos if no one is working on this I have 2/3s of a post written up that I'll finish tomorrow.

If you want I can put it on BackdropCMS.org as the 1.16 post, but if you folks already have something cooking I'll just post mine on my site.

~Geoff

**Comment by stpaultim** [comment]
This appears to be out of date.
