### ISSUE TITLE
SEO: Update the "Upgrade from Drupal 7" feature on the home page to include the word "alternative"

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#687]
This was suggested at the "Outreach" thread in Zulip: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Outreach/near/198264700

@mazze.ch

> It seems that most people who join this community were looking for a Drupal alternative. Although googling for "drupal alternatives" does not mention Backdrop at all (at least here in Central Europe, German search settings... could be quite different in other locations). I really guess this could be our lowest hanging fruit at all: make Backdrop appear when entering "Drupal Alternatives")
>
>On the other hand, I still got good traffic for "Drupal Alternative" (non-plural) for my german blog post here, who really is targeted at people with good D7 knowledge. https://mazze.ch/backdropcms

@laryn

> Maybe we can get the word "alternative" added on the front page. For example here:
> ![Screen Shot 2020-05-22 at 2 01 39 am](https://user-images.githubusercontent.com/2423362/82614306-33a25180-9bd0-11ea-9428-47184b423268.png)
> Could be:
> >Backdrop has a built-in upgrade path from Drupal 7. Backdrop _is a great alternative_ for people with Drupal experience because it is so similar to Drupal, but includes numerous usability improvements and new features.

**Comment by klonos** [comment]
...I don't like the word "but" in there, but I agree re adding the word "alternative". How's this instead:

>Backdrop has a built-in upgrade path from Drupal 7, which makes it a great alternative for people with Drupal experience not ready to move to Drupal 8 or 9. Its code is compatible with Drupal 7, and the admin interface is so similar that you will feel right at home. On top of that, we have included numerous usability improvements and new features, which should make working with Backdrop easier and faster.

**Comment by olafgrabienski** [comment]
> I don't like the word "but" in there

Or just replace the "but" with "and"? Would keep the text short.

> Backdrop has a built-in upgrade path from Drupal 7. Backdrop is a great alternative for people with Drupal experience because it is so similar to Drupal, **and it** includes numerous usability improvements and new features.

**Comment by klonos** [comment]
My goal was to change that entire "feature" to include the following (what Backdrop offers):

- **upgrade path from D7** (less work for developers, less cost for site owners)
- **backwards compatible code** (developers don't have to learn many new things or rewrite big portions of their code)
- **improved admin UI** (content editors and site administrators should find things easier and more intuitive)
- **new features** (less modules to install to get basic/popular functionality OOTB)

...but I would like us to also tell people what they will gain by upgrading to Backdrop, which is what I was trying to achieve with "make working with Backdrop easier and faster".

> With a built-in upgrade path from Drupal 7 and backwards compatible code, Backdrop is a great alternative for people with Drupal experience. The admin interface is similar to Drupal, with additional usability improvements and new features. Working with Backdrop should be easier and faster out-of-the-box.

**Comment by klonos** [comment]
...or we could add a new feature called "Get things done faster and easier", separate to the "Upgrade from Drupal 7" feature.

> ## Upgrade from Drupal 7
> With a built-in upgrade path from Drupal 7 and backwards compatible code, Backdrop is a great alternative for people with previous Drupal experience.

> ## Get things done faster and easier out-of-the-box
> The admin interface in Backdrop is similar to Drupal, with the addition of usability improvements and new features. We have moved things where people expect to find them; so working with Backdrop should be more intuitive and require less work.

**Comment by jenlampton** [comment]
I have created https://github.com/backdrop-ops/backdropcms.org/issues/1028 so that we can close this issue :) https://github.com/backdrop-ops/backdropcms.org/issues/1028
