### ISSUE TITLE
Fix alignment of logos on 'Try Backdrop' page

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#689]
Currently logos are aligned at the top of the container:
![logos_before](https://user-images.githubusercontent.com/2385329/83055326-6333dc80-a05c-11ea-88e1-0d00dc763c00.jpg)

I suggest aligning them in the middle:
![logos_after](https://user-images.githubusercontent.com/2385329/83055351-6b8c1780-a05c-11ea-86a8-a8d3fdc9175e.jpg)

This is done by simply adding `align-self: center;` to the `.col-md-5` container (but not sure if that's the exact CSS to only affect these logos on this page, hence no PR)...

**Comment by BWPanda** [comment]
Here's a PR that achieves the second screenshot above: https://github.com/backdrop-ops/backdropcms.org/pull/715

**Comment by klonos** [comment]
Thanks @BWPanda ...RTBC 👍

**Comment by BWPanda** [comment]
Thanks @klonos! Merged and pushed live.
