### ISSUE TITLE
Make the listing order on service providers pages random

### ISSUE THREAD

**Issue by AlexShapka** [backdrop-ops/backdropcms.org#690]
Please make the listing order on service providers pages such as  https://backdropcms.org/services/data-migration, https://backdropcms.org/services/consulting, https://backdropcms.org/services/support-maintenance, etc. random, because otherwise companies like Simplo and Innodus are always on top.

If not possible, then I believe it would only be fair if criteria of how the listing order is generated is explained to all organizations supporting Backdrop.

**Comment by BWPanda** [comment]
I agree. This is a similar request to: https://github.com/backdrop-ops/backdropcms.org/issues/633

Currently it seems that those pages are sorted by Post Date (meaning the most recently-added companies are at the top).

**Comment by BWPanda** [comment]
Here's a [PR](https://github.com/backdrop-ops/backdropcms.org/pull/713) that randomises the following views:

- /services/* (e.g. /services/consulting)
- /support/services
- /support/services/agencies

**Comment by herbdool** [comment]
I've reviewed but haven't tested. Looks good to me

**Comment by BWPanda** [comment]
Thanks everyone! https://github.com/backdrop-ops/backdropcms.org/pull/713 has been merged and the live site updated.
