### ISSUE TITLE
BLIVE - Work with Software Freedom Conservancy to determine best method of payment

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#693]
Part of https://github.com/backdrop-ops/backdropcms.org/issues/692

Current plans are to suggest a $20 donation per participant, but not require it. However, we haven't done anything like this before, so we need to figure out how to collect this money. 

* Paypal
* Eventbrite
* Etc

**Comment by olafgrabienski** [comment]
Hm, payment for what?

**Comment by stpaultim** [comment]
@jenlampton - This is pretty important issue. We need to get registration up very soon. I was thinking about testing an Eventbrite form, but we'll have to be able to connect that to SFC (I think).

**Comment by stpaultim** [comment]
We're live. The Software Freedom Conservancy suggested that we use Eventbrite and Paypal, so that is what we have set up. We've learned a few things along the way, but it will be fine.
