### ISSUE TITLE
Drop LinkedIn?

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#696]
I'm listening to the [Outreach meeting discussion](https://www.youtube.com/watch?v=-5s8wIJQpps) about social media/networks Backdrop has (FB, LinkedIn, etc.), and I just wanted to make a comment that, in my opinion, having a poorly-used social media account is worse than not having an account at all.

If you don't have an account, people might try to find you elsewhere :+1:, but if you do have an account and it's old, outdated and has few members, that gives a bad impression :-1: 

I'm referring specifically to LinkedIn, which @jenlampton said has a last post over a year ago.
I'd say either start using it as often as we use Twitter, or delete the account and focus our efforts elsewhere.

**Comment by stpaultim** [comment]
@BWPanda - There is a difference between an organizational account and a "group" on LinkedIn or Facebook. 

We were talking about a Backdrop CMS "discussion group" on LinkedIn, not an official Backdrop CMS organizational account. We don't always have control over discussion groups about Backdrop CMS on a social media platform, but we can try to pay attention. 

In the case of the LinkedIn group, it appears that Jenn Lampton is one of the admins, so she might be able to shut it down. But, it's not clear to me that having an inactive discussion group on LinkedIn is a bad thing. You never know when a group like this (with 73 members) might spring to life. 

I think it would be great if we used it more. But, even if we can't, I'd be very hesitant to remove it (if that is even possible). 

In the case of the Facebook group (with 4 members and almost zero activity), it was formed by a Backdrop CMS user that is not actively involved in the community at all (to my knowledge). I'm not sure that we have the power to turn it off or remove it, nor that we should.
