### ISSUE TITLE
BLIVE - Logo or graphic 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#701]
This isn't too important, but a nice graphic or special logo for Backdrop CMS Live would be nice and help promote the event. 

Things for inspiration or that might be included:

- Drop the Dragon (see [press kit](https://backdropcms.org/presskit))
- Backdrop CMS Logo (see [press kit](https://backdropcms.org/presskit))
- Theme of Backdrop CMS Live 
- 2020
- Release of Backdrop CMS 1.17.0 (very close to event)

Anyone?

Some example of event logos:

![drupalcon_-_Google_Search](https://user-images.githubusercontent.com/3144571/90836024-e0958300-e313-11ea-8f62-1fbbc4bd1d15.png)

![nten_baltimore_-_Google_Search](https://user-images.githubusercontent.com/3144571/90836060-fefb7e80-e313-11ea-9c9f-420b02fc59a3.png)

![wordcamp_usa_logo_-_Google_Search](https://user-images.githubusercontent.com/3144571/90836111-26eae200-e314-11ea-9a04-4826258f23c6.png)

**Comment by BWPanda** [comment]
Guess we can close this now...
