### ISSUE TITLE
Add list of projects to user profiles

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#704]
Drupal profiles have a list of projects people maintain or have contributed to. Can we do something similar for Backdrop?

I'm hoping it can be automated, maybe looking for the username in README files...?

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/backdropcms.org/pull/743

It creates a Views that displays a list of all projects, then filters then using a combined fields filter, based on the Body and GitHub Maintainers fields. So if you enter 'BWPanda' into the search box, you get a list of all project nodes where 'BWPanda' appears in the Body field or as a GitHub maintainer (but it seems this field isn't used yet). It then displays this block on user profile pages.

Then, there's a new B.org-specific module (`borg_profile`) that does a form alter of the Views exposed form on the user profile page, adding the profile's username into the search box and then hiding the exposed form. This way, each user profile only shows the projects where that username appears. If no username is available, then the entire form is hidden (to prevent the list of *all* prokects being displayed).

Here's what it looks like:
![image](https://user-images.githubusercontent.com/2385329/104120182-f837db80-5388-11eb-94a8-75aa77dc7f76.png)

**Comment by stpaultim** [comment]
Having something like this is great. I'm often wished I had access to a list of all the modules I'm listed as a maintainer. I didn't think we had an easy way to do this yet. 

I was hoping that adding fields to the .info file for modules would make this possible. It seems like it's already possible.

**Comment by BWPanda** [comment]
PR sandbox is working, so here's a link to @herbdool's profile: https://pr743-jcrqoftjdohduticn96mogdb0imddo7h.tugboat.qa/account/herb

Note that this functionality depends on someone having the same username on GitHub and B.org. For example, @olafgrabienski https://pr743-jcrqoftjdohduticn96mogdb0imddo7h.tugboat.qa/account/olafski has a different username and therefore doesn't display any projects.

**Comment by olafgrabienski** [comment]
> this functionality depends on someone having the same username on GitHub and B.org

Really nice feature but depending on same usernames would be a pity. Can you also take the *Find me online > Social* field of the B.org user profile into account? Look if there's a Github link in the field and use that name?

**Comment by BWPanda** [comment]
@olafgrabienski Great suggestion! PR updated:

![image](https://user-images.githubusercontent.com/2385329/104244616-e8b6b080-54b6-11eb-95e5-358a975ef0c6.png)

**Comment by olafgrabienski** [comment]
> PR updated

Glad it worked! I've two more (minor) suggestions:

- Display the heading in the same format as the one above in the same column ("Ways in which I contribute ...").
- Make the heading shorter, maybe just "Projects"?

**Comment by BWPanda** [comment]
@olafgrabienski Thanks. I'll update the styling of the heading, but I'm not sure about re-wording it too short... The heading above it, "Ways in which I contribute to Backdrop CMS", is quite lengthy, so I don't think a lengthy heading is a problem. Also, I think it should indicate that there may be modules listed that users aren't active in anymore (e.g. they may have ported it originally but someone else maintains it now).

**Comment by BWPanda** [comment]
PR updated: 
![image](https://user-images.githubusercontent.com/2385329/104294733-ab344080-5513-11eb-8bfc-9cbddeff3afe.png)

**Comment by olafgrabienski** [comment]
Thanks! In the changed format, the lengthy heading looks good.

**Comment by jenlampton** [comment]
I don't think we should do this until we get aouth set up with github. Right now, anyone could put any name they want into the github field, and would get credit for someone else's work. This could be abused to get a job, and I'm concerned Backdrop could be held liable for that misinformation.

**Comment by BWPanda** [comment]
@jenlampton I did consider that, but people can already put any username (or URL) into the GitHub social field... And if we're worried about being liable for others misinformation, how do we handle that with the Bio field?

I understand where you're coming from, but I don't think its reasonable for us to be expected to be responsible for the accuracy of people's profile information...

Is there an issue for oauth? Are close are we with that?

**Comment by BWPanda** [comment]
> If you want I can ask our lawyers about it. Maybe we can get some legally-approved disclaimer text to add there?

Yes please @jenlampton. That'll likely be quicker/easier than setting up GitHub integration, which seems to have been 'in progress' for 5 years now...

**Comment by jenlampton** [comment]
> That'll likely be quicker/easier than setting up GitHub integration, which seems to have been 'in progress' for 5 years now...

Well, getting them to reply about the google ad grants application is going on more than a year now, so ....

**Comment by jenlampton** [comment]
@BWPanda  I may need some help word smithing this, but it sounds like the lawyers will be happy with something like... 

All information displayed on this profile page was collected from the
person who created the profile. If a GitHub username was provided,
that name was used to generate the following list of projects.

... and ...

The existence of a Backdrop CMS profile page is not a recommendation
from Backdrop CMS.

**Comment by BWPanda** [comment]
@jenlampton I'd have thought something a bit simpler and more generic would be enough... Something like:

> The information displayed in this profile is created and maintained by the individual user. As such, Backdrop CMS is not responsible for, and cannot guarantee the accuracy of, this information.

**Comment by jenlampton** [comment]
I'm sure that will be fine, but I'll send it over to them to confirm. 

Their advice was `Let's be sure to state explicitly what information the site is collecting and from where` but since we are collecting information only from the person, your text covers that. Then they also said `You could also specifically say that inclusion in the pages is not a recommendation.`

"Could" though. What do you think?

**Comment by BWPanda** [comment]
I think leave out the recommendation bit.

**Comment by jenlampton** [comment]
Okay, Can you find somewhere to add this to the page?

**Comment by BWPanda** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/2385329/105938423-a8a51f80-60ab-11eb-9bcf-a8aeec34044e.png)

PR updated.

**Comment by stpaultim** [comment]
Thanks for the work on this. Progress is looking very good.

**Comment by olafgrabienski** [comment]
> The information displayed in this profile is created and maintained by the individual user. As such, Backdrop CMS is not responsible for, and cannot guarantee the accuracy of, this information.

I like the text, just one question: Should we say "person" or "member" instead of "user"? IIRC, "user" isn't recommended for real people in the context of Backdrop.

**Comment by BWPanda** [comment]
Good point @olafgrabienski! Wording changed to:

> The information displayed in this profile is created and maintained by the individual member.
> As such, Backdrop CMS is not responsible for, nor guarantees the accuracy of, this information.

**Comment by docwilmot** [comment]
When the user profiles module is disabled the view defaults to displaying every single project on the site, it seems. Unless I really did port 608 projects (I didn't). 

Otherwise very nice work @BWPanda.

**Comment by BWPanda** [comment]
> When the user profiles module is disabled...

Then don't disable it 😄 But seriously, do we need to worry about this? That module was written to provide this functionality. It's natural that if you disable it it's going to break...

**Comment by docwilmot** [comment]
No not a problem I'd think.. Just FYI.

**Comment by TeamTriplo** [comment]
I just tested the current sandbox and the module does not seem to be working at the moment. 
https://pr743-jcrqoftjdohduticn96mogdb0imddo7h.tugboat.qa/account/stpaultim

It seems to be listing a lot of projects for everyone. Not sure if it's listing all the projects or just a sub-set.

**Comment by stpaultim** [comment]
@BWPanda - I don't know if this is a problem or not. BUT, I am getting credit for my involvement with TOCbot module, because I created a screencast. 

I suppose it's not entirely incorrect and it may not be possible to be any more accurate than that?

![tocbot](https://user-images.githubusercontent.com/3144571/108487952-6e234280-7265-11eb-9a5c-4a6bf4783f98.png)

![tocbot2](https://user-images.githubusercontent.com/3144571/108488211-bb071900-7265-11eb-97d1-b4fabc5668da.png)

**Comment by BWPanda** [comment]
> I suppose it's not entirely incorrect...

You are credited as having been involved with that project, as you created a screencast. You might not be the maintainer, but you helped promote it and provided documentation (in the form of a video). So I don't see this as being incorrect.

**Comment by stpaultim** [comment]
@BWPanda - YOu were looking for someone to mark this RTBC. 

I would not feel qualified to mark this RTBC for core, but for BackdropCMS.org I will take the liberty. I've glanced over the code changes, most of which are config settings, and don't see anything obvious. However, I can't entirely vouch for the code in `borg_profile.module`.

Having said that, I'm comfortable enough to mark this RTBC. You can decide if you think we should get more eyes on it before deploying, but I don't think it's necessary.

I would prefer it if the criteria for getting credit were a little more rigid (and I did not get credit for TOCbot), but I see how this is not entirely wrong and may even be preferable. Also, this is something we can fix later, if we choose. 

I'd like to see this get onto BackdropCMS.org.

**Comment by BWPanda** [comment]
I've gone ahead and merged this and updated the live site. Thanks @stpaultim, @olafgrabienski, @jenlampton & @docwilmot for your help with this!
