### ISSUE TITLE
Hosting OS Updates

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#707]
Tasks: 

Perform server maintenance on the production operating systems by completing the following tasks: 

1. 1. [x] Perform updates for packages. 
1. 1. [x] Reboot the servers. 162 day update has been good but let's reboot. 
1. 1. [x] Test to make sure all of the sites come back online. 
1. 1. [x] Check for hosting upgrades provided by Linode.

**Comment by larsdesigns** [comment]
@quicksketch @jenlampton, I am planning on performing these tasks tonight at 9:30pm MDT.

**Comment by jenlampton** [comment]
I can be around after that to QA if needed

**Comment by larsdesigns** [comment]
Getting started...

**Comment by larsdesigns** [comment]
1. Performed the package updates. 
1. Rebooted the VM. 
1. Checked to make sure backdropcms.org came back online.

**Comment by larsdesigns** [comment]
1. Performed package updated on ci.backdropcms.org. 
1. Rebooted the VM.
1. Adjusted the bantime in fail2ban sshd jail. I changed it from a year to a week because IPtables was struggling due to the number of rules. 
1. Checked to make sure it came back online after reboot.

**Comment by larsdesigns** [comment]
1. Checked linode account and I only found a pending disk upgrade for the ci.backdropcms.org VM. I think it can wait for a while because there is still plenty of room.

**Comment by larsdesigns** [comment]
I finished the tasks but did not find a Q/A kinda label. Marked as fixed but @jenlampton please review and make sure everything is running that should be running. Especially on the ci.backdropcms.org.

**Comment by larsdesigns** [comment]
To Do: 

During the meeting yesterday it was decided: 

1. Backup and turn off the ci.backdropcms.org Linode VM. 
1. After a week of the VM being turned off, delete it if there are no blockers.

**Comment by larsdesigns** [comment]
1. Verified the last Linode VM backup was created on 2020-09-10 03:11:49. 
1. Powered down the Linode VM for ci.backdropcms.org.
1. I will check back after a week and delete the ci.backdropcms.org VM.

**Comment by larsdesigns** [comment]
For ci.backdropcms.org VM: 

1. Backed up the backdrop user directory and /var/www to my workstation. 
1. Deleted the ci.backdropcms.org Linode VM. 

No further tasks. Closing...
