### ISSUE TITLE
Replace modules' 'released' date with 'updated'

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#709]
On https://backdropcms.org/modules, modules display the date they were first released. Since this is the only date we see, and since this could be from years ago, it possibly gives a bad first-impression of the module and/or Backdrop.

We should replace the module's 'released' date with its 'updated' date.

This issue was first brought up by @albanycomputers in https://github.com/backdrop/backdrop-issues/issues/4651 (which has been closed in favour of this issue queue instead).

**Comment by bugfolder** [comment]
This will be addressed by PR https://github.com/backdrop-ops/backdropcms.org/pull/798.
