### ISSUE TITLE
BLIVE - Clean up - post event tasks

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#710]
Just getting this started. 

- [ ] Make sure that all videos are posted and linked to.
- [ ] Do a post event blog post
- [ ] Clean up Backdrop-live.backdropcms.org website. It's a bit of a mess right now.
- [ ] Thank you message to all participants

**Comment by BWPanda** [comment]
How's this going @stpaultim ?

**Comment by stpaultim** [comment]
Not good. We have the next iteration of Backdrop LIVE penciled in for March 13th. We can clean up this list as we prepare for the next round. Once 1.18 is out, that should be easier.

https://backdropcms.org/news/events/backdrop-live-1
