### ISSUE TITLE
Typo in alt text for Twitter icon

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-ops/backdropcms.org#720]
The Twitter icon at the top right corner of the homepage reads "Follow os on Twitter". This should be changed to read "Follow us on Twitter".

**Comment by stpaultim** [comment]
I reviewed this one. I think I can handle this.

**Comment by BWPanda** [comment]
Thanks for finding and filing this @Radcliffe. Unfortunately this is the wrong repo. Please open a new issue and PR against the https://github.com/backdrop-contrib/borg repo.

**Comment by Radcliffe** [comment]
New issue: https://github.com/backdrop-contrib/borg/issues/17
