### ISSUE TITLE
Call to undefined function webform_menu_to_arg()

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#724]
@cellear and I were trying to spin up local versions of BackdropCMS.org today with mixed results. However, both of us ran into this error messages when trying to load BackdropCMS locally. We were able to get around this, by going to /user page and logging into the site. 

I don't have any more information to provide, but will update with more info if I find any.

**Comment by docwilmot** [comment]
On the `https://backdropcms.org/admin/modules` Webform is listed as installed, but that module is not in the repo at `https://github.com/backdrop-ops/backdropcms.org/tree/main/www/modules/contrib`. I suspect some syncing needs doing.

**Comment by BWPanda** [comment]
Webform is no longer listed as installed on B.org. I'll close this, unless anyone is still having the same issue.
