### ISSUE TITLE
Add browser server to BackdropCMS.org

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#73]
First PR follows

**Comment by quicksketch** [comment]
Exciting! I'll go ahead and merge this and then test it out locally.

**Comment by quicksketch** [comment]
Well, nothing blew up. :smile:

Want me to flip the switch to turn this on in production?

**Comment by docwilmot** [comment]
Drat, I was expecting catastrophe. Lets turn it on then, and I'll push the browser with the new server address.

**Comment by quicksketch** [comment]
> I'll push the browser with the new server address.

This is something we should think about. Right now for updates, we hit updates.backdropcms.org. This is actually just an aliased copy of backdropcms.org itself, but it's a good idea for us to use a dedicated address for these things so that we can control the caching on them or potentially put in place a separate CDN on them in the future.

So that said, should we set up updates.backdropcms.org to handle these particular requests or should we give it a different address? Seems like keeping it all in the update.* address would be sensible enough to me.

**Comment by docwilmot** [comment]
Good point. I think a dedicated address would be best. So the server address would be then`https://update,backdropcms.org/project_browser/server`.

Incidentally, for this to work permissions to use browser server need to be given to anonymous.

**Comment by quicksketch** [comment]
Okay cool, I'll try to get to it this weekend. The updates server right now is set up in a way that prevents you from using the site as a full-blown copy of the BackdropCMS.org. I'll specifically whitelist that path and have it hit index.php like it would normally as if it were a full site.

**Comment by docwilmot** [comment]
Good.

**Comment by docwilmot** [comment]
Any news?

**Comment by quicksketch** [comment]
Hi @docwilmot, sorry about the delay on this. I'll try to get to this soon.

**Comment by quicksketch** [comment]
Alright, sorry for the long delay. I've set up the server the following location:

`http://projects.backdropcms.org/browser`

This URL maps to `index.php?q=project_browser/server`, without needing to put that in the URL itself. I found that using the same URL as updates.backdropcms.org wasn't a great idea from an infrastructure perspective, as all hits to updates.* aren't cached (as project usage is recorded at the same time). As opposed to this usage, where we'd want all project browser requests to be heavily cached and through a CDN. Considering the differences, I thought it would be better to give it a dedicated subdomain instead.

The DNS hasn't propagated yet. It should show up shortly.

**Comment by docwilmot** [comment]
Unless DNS is really slow today, this URL isn't working, sadly.

**Comment by quicksketch** [comment]
Looks like projects.backdropcms.org is resolving now, but it redirects to api.backdropcms.org for some reason. :stuck_out_tongue: The redirects have been odd for a while. I'll try to figure out what's happening there.

**Comment by docwilmot** [comment]
drat, had the champagne out and everything!

**Comment by quicksketch** [comment]
Okay! It turns out that this was simply because you had to access it via HTTPS. I made it available both over http and https, though I would recommend that when we set up Project Browser module, it should only use the HTTPS URL for the sake of security.

I dropped the "browser" part of the URL, so you can now hit the server via:

http://projects.backdropcms.org/query/module/1.x/?text=webform

Pretty neat! I had to fix an issue in pbs that was causing HTML to be tacked onto the end of the JSON responses. I hope it's okay that I committed the fix directly back into the module: https://github.com/backdrop-contrib/project_browser_server/commit/31d7e000db80fb69f3204a186d7ebcb240f766a5

**Comment by docwilmot** [comment]
Champagne is still chilling; seems project browser server isnt returning the correct number of records. Its returning less than the requested 10 records per page. In testing locally I have only one suspicion: borg_pbs has this line for building the `$projects` array that it returns:
```
    $projects[$node->project['name']] = array(
```
If `$node->project['name']` isn't set, the array would obviously skip that record. But I cant think of any way to check if this is set on all project nodes. Are we sure it is? 

Otherwise, I am stumped.

**Comment by quicksketch** [comment]
> Its returning less than the requested 10 records per page.

Also of note, if you don't pass in any parameters at all, you get a result of ALL projects apparently: http://projects.backdropcms.org/query/module/1.x/

That's currently 61 projects (hey, not bad!), but shouldn't that page into only 10 results? As we get more projects, generating a single JSON response with all of them could cause our server trouble. I think this does indicated that `$node->project['name']` is set for all projects.

**Comment by quicksketch** [comment]
What's a good query for me to test the pagering? It looks like currently, searches are against only the module title and not the description. Something like http://projects.backdropcms.org/query/module/1.x/?text=project gets 3 results back, but I can't think of a query that would return more than 10 items.

**Comment by docwilmot** [comment]
Theoretically
http://projects.backdropcms.org/query/module/1.x/?page=0&requested=40
should return 40 records but returns 28 so far.
The search does not include descriptions so far; I dont know how efficient
it would be to be doing a LIKE query on descriptions.
Still stumped.

**Comment by docwilmot** [comment]
By the way,
> Also of note, if you don't pass in any parameters at all, you get a result of ALL projects apparently

No, the pager count says 61, but only 5 projects are actually in the return (the query should apply the default and return 10).
And if `$projects[$node->project['name']] = array(` is changed to `$projects[] = array(` on my local all works just fine.

**Comment by quicksketch** [comment]
Oh! Well that makes a lot more sense. Sorry I didn't run the response through a JSON decode to actually read the contents. So it does sound as though $node->project['name'] may have an issue. I'll run some more queries locally to see what's causing the problem.

**Comment by docwilmot** [comment]
Still not serving correct paging, and I still don't know why :cry:

**Comment by quicksketch** [comment]
Hey @docwilmot! I merged your latest fix but I haven't deployed it yet.
I'll get that out today!

On Thu, Nov 12, 2015, 3:09 PM docwilmot <notifications@github.com> wrote:

> Still not serving correct paging, and I still don't know why [image:
> :cry:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/backdrop-ops/backdropcms.org/issues/73#issuecomment-156266033>
> .
>
-- 

--
Sent from mobile

**Comment by docwilmot** [comment]
Annoyingly, that didnt help. http://projects.backdropcms.org/query/module/1.x/?requested=30 still serves 16 instead of the requested 30. 

I give up.

**Comment by quicksketch** [comment]
Gar! I did make sure to deploy it and clear caches, so it must be something else. I expect to have a little time soon so hopefully I can sort this out. I hate bringing this up every week with a "no progress yet" report. :frowning:

**Comment by quicksketch** [comment]
Ah! I think I found the primary problem!

Try this URL instead:

**Comment by docwilmot** [comment]
> Try this URL instead:

In my email. Deleted post?

**Comment by quicksketch** [comment]
> In my email. Deleted post?

Yeah, sorry I was afraid that might get your hopes up... So I had thought that the default sort was by "usage", which means that only projects that have data in the project_usage_weekly table would show up. This actually the case, but I tried sorting by title instead and it *still* didn't include all the projects it was supposed to. So sort of a bust on that front too.

**Comment by quicksketch** [comment]
So here's the "slightly better" URL: http://projects.backdropcms.org/query/module/1.x/?requested=30&order_by=title

**Comment by quicksketch** [comment]
Ah, I think I found it. We had this query:

```
SELECT n.* FROM {node} n INNER JOIN {project_release} p ON n.nid = p.project_nid WHERE (n.type = :db_condition_placeholder_0) ORDER BY n.title DESC LIMIT 6 OFFSET 0
```

But that INNER JOIN was resulting in duplicate rows if a project had more than a single release. So we need a GROUP BY in order to remove any duplicates:

```
SELECT n.* FROM {node} n INNER JOIN {project_release} p ON n.nid = p.project_nid WHERE (n.type = :db_condition_placeholder_0) GROUP BY n.nid ORDER BY n.title DESC LIMIT 6 OFFSET 0
```

I'll file a PR.

**Comment by quicksketch** [comment]
Actually just pushed a commit: https://github.com/backdrop-ops/backdropcms.org/commit/aee3093a1b2fb8e38bf246c40fbf3668f934fefb

Woot! http://projects.backdropcms.org/query/module/1.x/?requested=30&order_by=title now lists 30 results!

Actually even http://projects.backdropcms.org/query/module/1.x/?requested=30 returns 30 results as well. Nice! Looks like even the default sort joining on the usage table will still return items that have zero reported installs. Very nice!

**Comment by docwilmot** [comment]
Excellent!!! My oversight there, sorry. 

And found another hiccup (though this one is minor).

`borg_pbs.module` line 136 has 

```
$image_url = !empty($img_field) ? file_create_url($img_field[0]['uri']) : '';
``` 
to serve the url for the theme screenshot. Unfortunately, `file_create_url()` builds a url with `http://project.backdropcms.org...` when should be just `http://backdropcms.org...`

Whats the best way to build that url? Just concatenate strings, like 
```$uri = "https://backdropcms.org/files/theme-screenshots/" . $img_field[0]['filename'];```

Or is there a smarter way?

**Comment by quicksketch** [comment]
Maybe stick with `file_create_url($img_field[0]['uri'])` but `str_replace('project.', '', $url)`? Not sure there's a super-smart way to handle that one.

**Comment by jenlampton** [comment]
As we have a project browser server on backdropcms.org now (woot!) I'd like to close this issue. If there are any lingering follow-ups can we move them to new (appropriately titled) issues?

**Comment by docwilmot** [comment]
Agreed
