### ISSUE TITLE
Backdrop CMS Core Page

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#730]
I frequently use the Drupal Core page on Drupal.org to review recent releases. See when the last release came out. Or if I'm looking for an older release of Drupal 7. 

https://www.drupal.org/project/drupal

![Selection_009](https://user-images.githubusercontent.com/3144571/100308585-5b52e780-2f6e-11eb-9604-2e4ad8d95218.png)

We don't really have the equivalent page on BackdropCMS.org do we? I think we should. Or at least a link to this page where you can find all recent releases, downloads, and release notes.

https://github.com/backdrop/backdrop/tags

**Comment by oadaeh** [comment]
This page has more information about the various releases and is more like the releases page on d.do you are referring to: https://github.com/backdrop/backdrop/releases

There's also this page, which has less information than the Github one: https://backdropcms.org/node/179/releases
It is linked to from this page: https://backdropcms.org/project/backdrop

But, I was not able to locate a link to any of them on the site. I only was able to find them, because I already knew they existed.

**Comment by bugfolder** [comment]
The GitHub page is going to be more user-friendly since it doesn't require clicking-through to see the release notes. Seems like it belongs in the main menu, but there's not an obvious perfect fit. Maybe as an item in "Support", with menu title "Backdrop Releases"?

**Comment by stpaultim** [comment]
@bugfolder - I see your point about the github page getting you the most information the quickest. But, it's also Github - which can be intimidating for some folks who are not used to it. This particular page isn't as bad as some others. 

I would be fine linking to any of the pages that @oadaeh suggests, but I think my mild preference would be in this order. 

1) B.ORG Project Page - https://backdropcms.org/project/backdrop
2) B.ORG Releases Page - https://backdropcms.org/node/179/releases
3) Git Hub Release Page - https://github.com/backdrop/backdrop/releases

The last one gets you to the information the fastest, but the 1st one might be the most understandable for casual users, but still get's you where you want to go. 

My main goal is to have a link to a page where I can find recent releases, which is currently not easy. All of these accomplish this goal and I'd be fine with any of them. 

I think the harder task might be finding a place to put the link. I don't have a better idea than @bugfolder - `Backdrop Releases` under the `Support` menu tab.

**Comment by olafgrabienski** [comment]
> backdropcms.org/node/179/releases

Btw, can we change the path to `project/backdrop/releases`?

**Comment by jenlampton** [comment]
I've added a URL alias for https://backdropcms.org/project/backdrop/releases. 
And added this link into the menu under Support.
