### ISSUE TITLE
Remove outdated Note from https://backdropcms.org/security/advisories

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/backdropcms.org#731]
The note on the top of https://backdropcms.org/security/advisories page says:

> 
**Note**: No new Backdrop core security updates have been released since April 18, 2019. The Backdrop core security advisory emails sent from backdropcms.org on Tue Apr 23 at 10:20pm PDT refer to issues resolved on February 21, 2018 and were sent accidentally while updating security advisory content on backdropcms.org.

However, there were plenty of security updates since April 18, 2019, so the note is definitely outdated and doesn't reflect the facts.

**Comment by klonos** [comment]
Thanks for catching that @alanmels 👍 ...I've manually removed it for now. We can follow up with a PR if required.

**Comment by jenlampton** [comment]
I've committed the config change @klonos (and copied it to the staging directory) no need for a PR.
