### ISSUE TITLE
Upgrade PHP to version 7.4.x on Production Host

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#732]
PHP 7.2 was deprecated in November 2020. We should upgrade to version 7.4.x.

Proposed TO DO: 

1. [ ] Upgrade production environment to PHP version 7.4.

This upgrade will likely depend on progress made on the following: 

Related issues: 
1. Make sure Backdrop works in PHP 8: https://github.com/backdrop/backdrop-issues/issues/4772
1. Complete PHP 7.4 Test Fixes: https://github.com/backdrop/backdrop-issues/issues/4777

**Comment by larsdesigns** [comment]
@quicksketch and @jenlampton It looks like the PHP 7.4 core ticket has been completed: https://github.com/backdrop/backdrop-issues/issues/4777#issue-751803003. 

Can I proceed with the upgrade to php 7.4?

**Comment by BWPanda** [comment]
I'd say go for it. But if you'd prefer to wait for @quicksketch or @jenlampton to give the ok, that's fine too.

**Comment by jenlampton** [comment]
Let's wait until all the Backdrop sites are updated to a version that contains the fix (next wednesday), and we should test the Drupal 7 site on PHP 7.4 before we update the server it's on.

**Comment by larsdesigns** [comment]
Ah, okay. I will plan on next Wednesday or Thursday.

**Comment by larsdesigns** [comment]
As mentioned last week in the developer meeting, I am planning to perform the upgrade this evening.

**Comment by larsdesigns** [comment]
Getting started...

**Comment by larsdesigns** [comment]
Completed the following tasks: 

1. Remove php7.2-fpm
2. Installed and and configured php7.4-fpm
3. Performed OS apt-get packages
4. Rebooted the server.
5. Checked to make sure PHP, nginx, etc. came back online.
6. Checked to make sure the sites came back online after the reboot. 
6. Checked to make sure iptables is loadingo

**Comment by larsdesigns** [comment]
Checked to make sure the https://sanitize.backdropcms.org/ page is loading and password protected.

**Comment by indigoxela** [comment]
Maybe related to the upgrade: no more package creation, when releasing on Github.

I tried three times with a lot of delay. No error, but not zip file creation.

**Comment by findlabnet** [comment]
Maybe too late, but I have one question: why we update PHP only? Any supported distribution should receive security updates, shouldn't it?

**Comment by larsdesigns** [comment]
@indigoxela, It is possible and probably that the upgrade broke the zip file creation. I will check the logs and see what's going on. It should produce an error if there is a PHP problem.

**Comment by findlabnet** [comment]
Which version of Debian?
On my servers:
- old stable - PHP version: 7.0.33-0+deb9u10;
- stable - PHP version: 7.3.27-1~deb10u1 
Both haven't security problems, patched by package maintainers.

**Comment by larsdesigns** [comment]
@findlabnet, We skipped 7.3 because it will be unsupported in a five months. I am referencing: https://www.php.net/supported-versions.php

**Comment by findlabnet** [comment]
You build your own distribution?

**Comment by larsdesigns** [comment]
We are using Debian and Sury for PHP.

**Comment by findlabnet** [comment]
Seems like I misunderstand something - why we need to play in this versioning game? Support of package maintainers from Debian is not meet the needs?

**Comment by larsdesigns** [comment]
PHP Curl extension was not enabled which seems to have caused the problems. I installed the extension and both Tugboat and the Github API implementation is working again.

**Comment by indigoxela** [comment]
> PHP Curl extension was not enabled which seems to have caused the problems. I installed the extension and both Tugboat and the Github API implementation is working again.

@larsdesigns  Confirmed, packaging works again. Many thanks for the quick fix!

> why we need to play in this versioning game? Support of package maintainers from Debian is not meet the needs?

@findlabnet The Sury repo is a widely used one, the maintainer is also PHP maintainer for Debian. I use that repo myself for years.

**Comment by findlabnet** [comment]
@larsdesigns Confirmed too, packaging works. Thank you!
@indigoxela thank you, I know about Sury maintainer, my question was, what is wrong with the default version from distro?
