### ISSUE TITLE
SWAP Is Creeping Up

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#733]
Our monitoring service has notified us that swap is climbing.

1. I am planning to increase the swap space and if we need to go further, we can move to the next level of virtual machine.
1. Examine logged traffic. 
1. Optimize software to free up memory. 

```
***** Nagios *****

Notification Type: PROBLEM

Service: Swap
Host: backdropcms.org
Address: 66.175.208.83
State: WARNING

Date/Time: Thu Dec 3 09:41:50 UTC 2020

Additional Info:

SWAP WARNING - 30% free (149 MB out of 511 MB)
```

**Comment by larsdesigns** [comment]
I am going to take the server down now for a few minutes to add more swap space.

**Comment by larsdesigns** [comment]
1. Increased the swap partition to 2048 megabytes from 512. 
1. Perform OS package updates including updating the sury php package keys: https://packages.sury.org/php/README.txt. I was receiving the following error when trying to update apt packages: 

```
Ign:1 http://mirrors.linode.com/debian stretch InRelease
Hit:2 http://mirrors.linode.com/debian-security stretch/updates InRelease
Hit:3 http://mirrors.linode.com/debian stretch-updates InRelease
Hit:4 http://mirrors.linode.com/debian stretch Release
Get:5 https://packages.sury.org/php stretch InRelease [6,760 B]
Err:5 https://packages.sury.org/php stretch InRelease       
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
Fetched 6,760 B in 0s (9,786 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.sury.org/php stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
W: Failed to fetch https://packages.sury.org/php/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
The new keys resolved the error.

**Comment by larsdesigns** [comment]
Adding more swap will probably relieve the memory issue for the short term but we should consider upgrading the VM to the next tier or higher. It seems like there are more processes (sites and scripts) running than when we started with this VM. 

An alternative would be to move the database to its own dedicated server, offload some processing to github.com if possible and/or optimize the code that is being processed. There are also great performance gains for PHP 7.4 when we get there.

**Comment by larsdesigns** [comment]
I installed apcu to help out with performance.

**Comment by larsdesigns** [comment]
It looks like everything came back online. @jenlampton please confirm.

**Comment by BWPanda** [comment]
B.org is working fine for me, thanks @larsdesigns!

**Comment by larsdesigns** [comment]
Currently there is no swap used and 2.45G/3.86G of memory is used. Nagios seems to be doing a good job of monitoring and notifying us of problem. I think it is okay to close this issue for the time being. We can evaluate again when the PHP 7.4 upgrade occurs.
