### ISSUE TITLE
502/504 errors

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#734]
1. 502 Bad Gateway error is being reported by forum.backdropcms.org users. 
1. 504 messages are being reported by forum.backdropcms.org users.

**Comment by larsdesigns** [comment]
I found these errors in the NGINX error log: 

```
der from upstream, client: 17.58.96.178, server: api.backdropcms.org, request: "GET /api/backdrop/core%21includes%21conf
ig.inc/class/ConfigStorageException/1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock", host: "api.bac
kdropcms.org"
2020/12/07 11:26:00 [error] 1045#1045: *402929 upstream timed out (110: Connection timed out) while reading response hea
der from upstream, client: 208.80.194.29, server: backdropcms.org, request: "GET / HTTP/1.0", upstream: "fastcgi://unix:
/var/run/php/php7.2-fpm.sock", host: "backdropcms.org"
2020/12/07 11:26:02 [error] 1045#1045: *402934 upstream timed out (110: Connection timed out) while reading response hea
der from upstream, client: 2600:3c03::f03c:91ff:fec2:d257, server: api.backdropcms.org, request: "GET /core/cron.php?cro
n_key=QXf7y8JYO8XD_qw4KhyOzErHNdo2OdG2PxOkDkL1Oks HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock", ho
st: "api.backdropcms.org"
2020/12/07 11:26:03 [error] 1045#1045: *402933 upstream timed out (110: Connection timed out) while reading response hea
der from upstream, client: 66.175.208.83, server: backdropcms.org, request: "GET /core/cron.php?cron_key=baZL1QyrnB/8Q H
TTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock", host: "backdropcms.org"
2020/12/07 11:26:03 [error] 1046#1046: *402935 upstream timed out (110: Connection timed out) while reading response hea
der from upstream, client: 2600:3c03::f03c:91ff:fec2:d257, server: localize.backdropcms.org, request: "GET /cron.php?cro
n_key=DA7EQBg0PfTXIdQhRJQfehrILAhrud95D-dwiea4G6k HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock", ho
st: "localize.backdropcms.org"
2020/12/07 11:26:03 [error] 1046#1046: *402939 upstream timed out (110: Connection timed out) while reading response hea
der from upstream, client: 2600:3c03::f03c:91ff:fec2:d257, server: forum.backdropcms.org, request: "GET /core/cron.php?c
ron_key=5_ujEohW1IY7ty0gcqgz8lJ2yIZYZD_Di9LXhQd4oPU HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock",
host: "forum.backdropcms.org"
```

I investigated the cause of the timeout and found the following errors in the php-fpm log: 

```
98:[07-Dec-2020 17:30:04] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

It looks like this is cause nginx to timeout.

I increased the pm.max_children settings for php-fpm from `5` to `10` and restated fpm. 

I will continue to monitor the logs using tail today.

Also, I will configure Nagios to monitor forum.backdropcms.org.

**Comment by larsdesigns** [comment]
Received the following logs: 

```
[07-Dec-2020 18:00:10] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 6 total children
[07-Dec-2020 18:00:11] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 16 children, there are 0 idle, and 7 total children
```

Increased the following:

`pm.start_servers = 4`
`pm.min_spare_servers = 2`
`pm.max_spare_servers = 6`

**Comment by larsdesigns** [comment]
1. Installed the backdropcms drush commands for the backdrop user's drush install. 
1. Created a bash alias so that the forum user has access to drush.

**Comment by findlabnet** [comment]
The same errors 502/504 were on backdropcms.org and api.backdropcms.org (not forum.backdropcms.org only.)

**Comment by larsdesigns** [comment]
I created a Nagios check for HTTPS for each of the sites: forum.backdropcms.org, backdropcms.org, and api.backdropcms.org. This should send us notifications when 500s are returned.

Before, we were only monitoring the IP address for the host to return HTTP response on port 80. Now we are monitoring HTTPS on port 443 for each of the sites. 

This should help us respond faster to problems. It will also notify us if there is a SSL certificate problem.

**Comment by larsdesigns** [comment]
ugh: 

```
[07-Dec-2020 18:50:11] WARNING: [pool www] server reached pm.max_children setting (10), consider raising it
[07-Dec-2020 19:00:09] WARNING: [pool www] server reached pm.max_children setting (10), consider raising it
[07-Dec-2020 20:00:12] WARNING: [pool www] server reached pm.max_children setting (10), consider raising it
[07-Dec-2020 20:35:08] WARNING: [pool www] server reached pm.max_children setting (10), consider raising it
```

I am going to increase it again.

**Comment by larsdesigns** [comment]
I changed the settings to: 

pm.max_children = 20
pm.start_servers = 8
pm.min_spare_servers = 4
pm.max_spare_servers = 12

Let's see how it runs now.

**Comment by larsdesigns** [comment]
Implement New Relic monitoring: 

TO DO: 

1. [ ] Create a free tier New Relic account. 
1. [ ] Implement new relic monitoring service for all of the backdropcms.org sites.
1. [ ] Reach out to the PMC folks and see who would like to have access and notifications.

**Comment by larsdesigns** [comment]
@quicksketch, I would like to help with the cron job that is gobbling up resources. Can you direct me to the Github project?

**Comment by quicksketch** [comment]
Thanks @larsdesigns! The code for updating the download statistics of projects is a likely culprit. You can find it in this repository at https://github.com/backdrop-ops/backdropcms.org/blob/main/www/modules/custom/borg_project_metrics/borg_project_metrics.module#L109

**Comment by larsdesigns** [comment]
Installed Linode's Longview app on the server so we can track performance. Looks like it is a free service for now and it was easy to setup.

**Comment by larsdesigns** [comment]
I am shifting focus to New Relic monitoring.

**Comment by larsdesigns** [comment]
Longview is receiving data.

![Screen Shot 2021-01-14 at 3 38 35 AM](https://user-images.githubusercontent.com/976705/104655246-ae960c00-567a-11eb-9880-fcc71080598d.png)

**Comment by larsdesigns** [comment]
The New Relic account verification e-mail has been sent by e-mail. @jenlampton, please click the link when you have a moment.

**Comment by jenlampton** [comment]
link clicked, and password saved in DevOps 1password.

**Comment by larsdesigns** [comment]
@jenlampton, Can you help me recover my access to 1password?

**Comment by jenlampton** [comment]
Yes, I think so. Ping me on slack?

**Comment by larsdesigns** [comment]
Quicksketch help me with the reset of 1password.

**Comment by larsdesigns** [comment]
Swap is creeping up again. I am looking to see what we can optimize. It seems to have climbed after adding the events to the server. 

I am investigating now.

**Comment by jenlampton** [comment]
@larsdesigns we did get a bunch of Linode credit so that we could double the server size. Would that help in this case?

**Comment by larsdesigns** [comment]
@jenlampton, Completed the steps of my investigation: 

1. Checked memcached memory usage and it is not being used. I am thinking about disabling it.
2. Check APCU memory usage and it is at 0 also but enabled. I am thinking about disabling it. 
3. Check database memory usage which is around 220MB. 
4. Check PHP memory usage which is around 380MB.  
5. I found that php-fpm is what was swapping to disk. When I restarted php-fpm the swap went from 1.3GB to 43MB. 

Steps taken: 

To help prevent swap usage for php-fpm, I changed the process manager to use use `ondemand` instead of dynamic. In theory this will reduce the number idle processes with a solid timeout of 10s and prevent them from piling up and going to swap.

In general active memory usage is around 50% so I think we are okay for now on the level of Linode VM. 

I manually ran the cron job, observed a sizable spike in CPU usage but swap was not increased. I think this a good sign. 

I will keep manually monitoring for a while and move on to install New Relic monitoring. So we will have three monitoring systems in place. Nagios, New Relic and LInode Longview.

**Comment by jenlampton** [comment]
Why don't we start using the performance-enhancing features instead of disabling them? Wouldn't those help us out in this situation?

**Comment by larsdesigns** [comment]
@jenlampton, Good point. I will leave them in place for future use.

**Comment by larsdesigns** [comment]
@jenlampton, I checked in on the server again and found that the swap decreased a little to ~33mb. I am super happy so far with the results of the performance tuning. From 1.3GB to 33MB of swap. Nice...

**Comment by BWPanda** [comment]
Thanks so much for this @larsdesigns! I didn't even know we were having issues. Probably because you're so good and quick at fixing them ❤

**Comment by larsdesigns** [comment]
Completed the following tasks: 

1. installed and configured the New Relic agent. 
2. Installed and configured the New Relic mysql database agent and created a database use for it. 
3. Added the database user credentials to the 1password. 
4. Installed and configure the newrelic nginx agent. 
5. Created an alert that triggers a warning when swap has less than 512MB available and triggers an error when swap has less than 256MB available. 

I think I need to enable alerts for MariaDB and Nginx also. I am reading up on the documentation.

**Comment by larsdesigns** [comment]
1. Configured New Relic agent for Memcahed.

**Comment by larsdesigns** [comment]
The swap is holding at around 489M during the weekend. All of the major components are being monitored in New Relic. I am going to go ahead and close out this issue. 

Linodes Longview is monitoring and Nagios is monitoring with alerts. 

There are no further tasks pending. I am going to go ahead and close this out.

**Comment by jenlampton** [comment]
> The swap is holding at around 489M during the weekend. 

Any suggestions as to what we can do to ensure it stays at zero? Would using any of the performance enhansers that were in place on the pervious server (mamcached, APC) help here? I'll open a separate ticket specifically to prevent swapping.

**Comment by larsdesigns** [comment]
Buying more memory would be necessary to eliminate swap usage. Which is okay but I think the server will remain healthy for a good while at the current swap level. It is lower than it ever has been. However, if the memory is doubled, swap could be avoided altogether.

**Comment by jenlampton** [comment]
Would the Linode server we were planning on upgrading to anyway (2x as large as the current one), also include 2x more memory? Or would we still need additional memory beyond that?
