### ISSUE TITLE
API and Forum repos have different default config dir setting than B.org

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#735]
This repo has the following default config setting in `settings.php`:

```
$config_directories['active'] = '../config/dev-active';
$config_directories['staging'] = '../config/staging';
```

This matches the instructions in https://github.com/backdrop-ops/backdropcms.org/blob/main/config/README.md#setup

However, the API and Forum repos have this as the default config setting:

```
$config_directories['active'] = '../config/live-active';
$config_directories['staging'] = '../config/dev-active';
```

Is that by design, or should we change them to match this repo's setting? Ping @jenlampton 
FTR, each of these 3 sites have their own `settings.local.php` file on the server, so this default config setting is only useful for people installing on their local environments...

**Comment by jenlampton** [comment]
I usually set the defaults to dev-active/staging to prevent anyone from
overwriting live accidentally in a new local set-up.

I would prefer to update api and forum to match b.org.

**Comment by BWPanda** [comment]
Done.
