### ISSUE TITLE
Display content in Mentions feed

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#744]
The Mentions RSS feed doesn't have any content, you just have to click the link in your RSS reader to view the mention on B.org, where you then have to click the link to view the mention on the external site:

![image](https://user-images.githubusercontent.com/2385329/104122211-bbbfac00-5397-11eb-875f-10c6e8359a06.png)

I suggest we add the mention URL, author(s), date and language to the content of the feed, so the mention can be opened directly from the RSS reader.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/backdropcms.org/pull/745

Unfortunately I can't test this on my local since it doesn't have a public URL... Maybe the Tugboart PR will start working soon.

**Comment by BWPanda** [comment]
PR and sandbox works:

![image](https://user-images.githubusercontent.com/2385329/104250297-6bdd0400-54c1-11eb-9216-0b936a884fd0.png)
