### ISSUE TITLE
Theme project nodes not being created

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#75]
On creating a theme release, got these four messages in B.org logs:
> Successfully created release for cleanish 1.x-2.0 and pushed the package to GitHub.

> File temporary://fileuzDm9C could not be copied because the destination directory public://theme-screenshots is not configured correctly.

> Notice: Trying to get property of non-object in borg_github_github_project_validate() (line 107 of /home/backdrop/repo/www/modules/custom/borg_github/borg_github.module).

> Warning: Creating default object from empty value in borg_github_github_project_validate() (line 108 of /home/backdrop/repo/www/modules/custom/borg_github/borg_github.module).

Seems on line 105 of borg_github.module there is: `$uri = 'public://theme-screenshots/' . $filename;` which seems to be either not configured or non-existent (it doesnt exist on the dev site).

**Comment by quicksketch** [comment]
Yeah, looks like we should have a check to create the directory if it doesn't exist. For now, I've simply created this directory so it should pass now.

**Comment by docwilmot** [comment]
Yep. That worked. Cleanish listed now, and release history XML feed working.

**Comment by quicksketch** [comment]
Sweet, I love it when things work. :smile:
