### ISSUE TITLE
Set up new events.backdropcms.org domain for Backdrop LIVE events

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#753]
We're going to need a new subdomain for Backdrop events. I initially thought we should use live.backdropcms.org since the event is called Backdrop Live, but since we'll probably want to have in-person events in the future, maybe events.backdropcms.org is bettter?

We don't have a site ready yet @larsdesigns but we do have a github repo at 
https://github.com/backdrop-ops/events.backdropcms.org

Is that enough to start with or should we get closer beore we set this up?

**Comment by larsdesigns** [comment]
@jenlampton, I suppose events.backdropcms.org is good. I suppose we could go ahead and set up the Nginx, create the subdomain and place a basic landing page there for coincidental traffic.

**Comment by larsdesigns** [comment]
Completed the following: 

1. Created A and AAA records for events.backdropcms.org. 
2. Created events server user. 
3. Configured nginx to server events.backdropcms.org. 
4. Created SSL certificate for events.backdropcms.org with redirect to https. 
5. Created a landing page for events.backdropcms.org at path `/home/events/repo/www/index.php`. 
6. Updated 1password with the new password for the events user.

**Comment by jenlampton** [comment]
You're so fast!

**Comment by larsdesigns** [comment]
No further tasks. Closing...
