### ISSUE TITLE
Many project node pages are missing the download link table from the top

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#755]
I have been finding that some modules are NOT showing up on the modules page AND the download link is not showing up on their Backdropcms.org page. 

For example:

https://backdropcms.org/project/block_embed 
https://backdropcms.org/project/nodeaccess_userreference
https://backdropcms.org/project/views_accordion

There is no download link. It seems like this is a problem for any module that has not been updated since Mid December, 2020. 

EDIT: The following has already been reported in https://github.com/backdrop-ops/backdropcms.org/issues/737 (Thanks @BWPanda for spotting this). I don't know if it is possible that these two issues are related.

1) Go https://backdropcms.org/modules
2) Search "Block Embed" or "Views Accordion" or "JSONPath Parser" or "Focal Point"
3) No results found

This does not effect all of the modules that do not have download links. But, all of the modules I found with this problem, also do not have download links.

**Comment by BWPanda** [comment]
There is an issue with the search: https://github.com/backdrop-ops/backdropcms.org/issues/737, https://github.com/backdrop-ops/backdropcms.org/issues/736

So that part of your issue is a duplicate. First part seems unique though...

**Comment by stpaultim** [comment]
If I am correct. MOST contrib modules do not have a download link right now on the module page. There is a download link on the search results page (that is, if the module shows up in search).

**Comment by laryn** [comment]
Related to the download link portion of the issue?
https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Recommended.20project.20version.20not.20shown

**Comment by jenlampton** [comment]
I don't think the missing download table is related to the Recommended status of the project. 

I edited the block_embed node, changed nothing, and saved it. The download table appeared.

The download table is now appearing again forbackdropcms.org/project/nodeaccess_userreference and
backdropcms.org/project/views_accordion.

**Comment by bugfolder** [comment]
This is the same issue as https://github.com/backdrop-ops/backdropcms.org/issues/799 and should be fixed by https://github.com/backdrop-ops/backdropcms.org/pull/826.
