### ISSUE TITLE
Update Backdrop with better greek transliteration as drupal already did

### ISSUE THREAD

**Issue by cptX** [backdrop-ops/backdropcms.org#765]
Hi, I'm greek and I absolutely agree about the changes that took place in Drupal 7,8 and 9 core regarding the transliteration of some greek letters in urls. The following links show the changes that need to take place and I agree with them.
https://www.drupal.org/project/transliteration/issues/1215872
https://www.drupal.org/project/drupal/issues/2926187

I also have installed Drupal 9 recently and the above transliterations are already in core! We should update Backdrop to include them too!
Actually I don't understand why Backdrop didn't include these changes already.

**Comment by alanmels** [comment]
@cptX, this repository is only for various issues found on the main website backdropcms.org. I believe you could file requests on https://github.com/backdrop-contrib/i18n/issues or https://github.com/backdrop/backdrop-issues/issues

**Comment by cptX** [comment]
OK, I didn't knew it. I have post it here https://github.com/backdrop/backdrop-issues/issues/4947
