### ISSUE TITLE
Newletter form missing

### ISSUE THREAD

**Issue by oadaeh** [backdrop-ops/backdropcms.org#770]
Olaf pointed out that the newsletter form was missing in the footer on the events site, and then I noticed it was also missing on the main site. The block and title are there, but the form is not. I tested both logged in and out.

**Comment by BWPanda** [comment]
This looks like its been fixed now. Can you confirm @oadaeh ?

**Comment by olafgrabienski** [comment]
Just checked: the newsletter form is available on the main site again. (On the Events site, the whole block seems to have been removed.)

**Comment by oadaeh** [comment]
Yep, looks good. I think it's okay that it's not on the events site.
