### ISSUE TITLE
BLIVE - How to help?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#771]
Backdrop LIVE is happening in just over 1 week. We are running a little behind in preparation, but we are not worried, because we know what this community is capable of. We expect the community to pull together and make this event a success. Here are the things that we need help with. 

PRIORITIES:

1) **HOST/FACILITATE TOPICS:** We need folks to pick a topic that they would like to facilitate and time slot that interests them and just add your topic to the Google Sheet (or Mural Schedule). (http://bit.ly/3e5zfrN)

2) **BE A HELP DESK GREETER:** We need people to staff our welcome table (be a greeter). This means that you will be the host in our main Zoom room, answer questions and help people find their way to the various discussions. See RIGHT column on schedule (http://bit.ly/3e5zfrN) and add your name to open slots.

*The help/welcome person will need to stay in the main room to help there. They will not be able to be in the main room and a discussion room at the same time, unless they are using two devices at once (which is possible). I may listen in on a discussion with my phone, while staffing the main room with my desktop.*

3) **SPREAD THE WORD:** We need folks to help us spread the word and invite folks to participate in social media and various online groups that you participate in. Facebook, Twitter, LinkedIn, Slack channels, etc

Other ideas:

4) ~~Does anyone want to create a logo or some graphics for Backdrop LIVE?~~

5) **PLAN SOCIAL EVENT:** It would be great if someone planned a virtual social event, maybe the night before Backdrop LIVE or afterwards, or during one of the breaks?

6) **SEED THE MURAL WITH ACTIVITY:** We need some folks to make their mark on the MURAL board and demonstrate activity for our guests that will be arriving soon. (http://bit.ly/38nLJqV) Users don't like to be the first one to make use of a tool like this, they will participate if they see that other people are participating first. Help be among the first.

**Comment by indigoxela** [comment]
You asked for graphics? .... easy
![backdrop-live-event-16-9](https://user-images.githubusercontent.com/842066/110103826-ac148080-7da6-11eb-8304-8b2c86ffef1f.png)

I bet there are many designers in our community, who could provide something better. :wink:

**Comment by indigoxela** [comment]
Let's spread the word: https://backdrop-cms.de/blog/backdrop-live-am-12-maerz-2021 (german blog)

**Comment by stpaultim** [comment]
Maybe someone could do better, but this is really good. I'm very happy! Thank you!

**Comment by jackaponte** [comment]
Many thanks for the graphic, @indigoxela, and thank you so much for organizing us, @stpaultim! I've got a tweet out and will try to keep it up next week. :)
