### ISSUE TITLE
Please make the listing on https://backdropcms.org/services/hosting random

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/backdropcms.org#774]
It would be only fair if the listing on https://backdropcms.org/services/hosting (and other listing pages) on the main website of the project would be randomized.

**Comment by BWPanda** [comment]
@alanmels It is (should be) random. When I refresh I get a different one listed at the top. It was fixed in https://github.com/backdrop-ops/backdropcms.org/issues/690

Is it not random for you...?

**Comment by olafgrabienski** [comment]
> Is it not random for you...?

Maybe a cache issue. @alanmels – in this case try https://backdropcms.org/services/hosting?xyz

**Comment by alanmels** [comment]
Strange enough as both without and with ?xyz it's showing the same content. Checked with Firefox and Brave.

**Comment by alanmels** [comment]
If it's a cache issue, then it's not on a user's side, but the website itself. I believe any caching should be turned off for the listing pages.

**Comment by BWPanda** [comment]
Huh. I just tested on my phone in a private browser tab and the listing *didn't* change on refresh... Maybe we forgot to make this happen for anonymous users somehow...?

**Comment by BWPanda** [comment]
Ok, I see. It *is* cached for anonymous users, but it's still random.

So when an anonymous user accesses that page for the first time, they'll see a random order. However that random order will stay between subsequent page refreshes.

I don't see that as a bad thing though. I think that's just caching in action. The order of items in the view is still random, which addresses the need for 'fairness'. So I think this is a 'works as designed'...

**Comment by alanmels** [comment]
I guessed so. However how often cache expires? If its too long then it's still not good. Do you think overhead would be too much if cache was turned off for listing pages?

**Comment by BWPanda** [comment]
Looks like it's 5mins:

![image](https://user-images.githubusercontent.com/2385329/111054905-6cdfe100-84c4-11eb-9596-e6e5b716f5a8.png)

**Comment by alanmels** [comment]
Well, 5 minutes seems reasonable, so let's just close this one. Thanks Peter for looking it up.
