### ISSUE TITLE
Spelling Correction - API > GitHub workflow 

### ISSUE THREAD

**Issue by rgeleta** [backdrop-ops/backdropcms.org#78]
In section: Trouble with Tests? > Run the tests locally
change 
and then visitingadmin/config/development/testing
to
and then visiting admin/config/development/testing
(space after visiting)

In section: Making Clean Pull Requests, paragraph 3, 
change
you could clean up it's commits with the following commands
to
you could clean up its commits with the following commands
(no apostrophe in its)

**Comment by docwilmot** [comment]
Fixed, thanks
