### ISSUE TITLE
Prevent the server from swapping

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#780]
> The swap is holding at around 489M during the weekend.

Any suggestions as to what we can do to ensure it stays at zero? 

Would using any of the performance enhancing tools that were in place on the pervious server (mamcached, APC) help here, or would they hurt since they would also be using memory (which is in short supply)? 

Is the problem still the Github project usage counts?  If so, here's how I recommend we proceed:

1) disable project usage for contrib (and hide that field from display on b.org) -- this is probably the fastest/easiest fix and would immediately reduce risk to our server

2) Move the script that gathers download counts per release to a dedicated server, and generate a single, ready-to-use file that b.org can ingest to get the same data without all the external API calls to GitHub. Enable use of this file on b.org to confirm the problem is the contact with GitHub and not the database writes on our end.

3) rewrite the script to be more efficient -- this might be dependant on API changes at GitHub (which may or may not have already happened since this script was written). Depending on what they give us, our options here may be limited.

4) Put the more efficient script back onto backdropcms.org (once we are sure it won't put our server at risk).

**Comment by jenlampton** [comment]
@larsdesigns me know what you need to get started on this task, I can help with #1 today after 4pm PT if that's beneficial, but I'll certainly need your help with #2.

**Comment by larsdesigns** [comment]
@jenlampton, I like your approach to this. Probably a small Linode would be enough for the script processing and it would reduce risk. 

I am happy to help with executing number 2.

**Comment by larsdesigns** [comment]
After completing #786, the swap usage is at 97M. I still like the plan but this gives us some wiggle room.

**Comment by larsdesigns** [comment]
Checked memory usage after 60 days of uptime

```
free -h
 total        used        free      shared  buff/cache   available
Mem:           3.9G        2.8G        141M         49M        949M        815M
Swap:          4.0G        660M        3.4G
```

The host is in great shape.

**Comment by larsdesigns** [comment]
It is still looking good :-)         

```
 total        used        free      shared  buff/cache   available
Mem:           3.8Gi       2.8Gi       209Mi        96Mi       900Mi       755Mi
Swap:          4.0Gi       893Mi       3.1Gi
```
