### ISSUE TITLE
DNS Cleanup and Documentation

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#785]
It has been brought to my attention that ci.backdropcms.org has been flagged by google alerts. Upon investigation it looks there is an A record that is pointing to 23.92.20.128. The Linode IP of 23.92.20.128 not longer belongs to us and it is responding to ping. This would indicate that the IP has been reassigned to an outside party. 

I remember taking down the ci.backdropcms.org but did not have access to the DNS at that time. I have since gained access and can help perform the cleanup. 

To Do: 

1. - [x]  Remove old DNS records that are no longer being used. 
2. - [x] Check with backdropcms.org community to make sure that we are not zapping anything important.
3.  - [ ] Find and update or create DNS and hosting documentation.

**Comment by larsdesigns** [comment]
@jenlampton, Would it be okay if I clean up the DNS tonight?

**Comment by quicksketch** [comment]
@larsdesigns This all sounds good. Please use caution when updating the DNS and post any changes that might be questionable here :+1:

**Comment by larsdesigns** [comment]
Completed the following: 

1. Removed A records for ci.backdropcms.org that was pointing to 23.92.20.128. 
1. I asked @klonos in Zulip if he is using the subdomain for dcu.backdropcms.org and I am waiting for a reply. If not, I will remove that A record also.

**Comment by larsdesigns** [comment]
I verified with @klonos that he intends to use or is using the dcu.backdropcms.org subdomain. I am leaving the A record alone.

**Comment by larsdesigns** [comment]
No further tasks. Closing...
