### ISSUE TITLE
Server Maintenance 

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#786]
Perform the following tasks: 

1. - [x]  Update OS packages. 
2. - [x] Reboot the server.
3. - [x] Check and make sure the sites came back online. 

If it is okay, I will would like to perform the maintenance in around three hours.

**Comment by quicksketch** [comment]
I'm standing by in the event of any problems. Go for it @larsdesigns and thank you!

**Comment by larsdesigns** [comment]
Completed the following tasks: 

1. Updated the OS packages. 
2. Resized the swap partition to 4gb to match the memory and give it a little more padding just incase.
3. Rebooted the server. 
4. Verified that backdropcms.org. docs.backdropcms.org and forum.backdropcms.org have come back online. 
No further tasks...
