### ISSUE TITLE
Add a link to our code of conduct in b.org

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#787]
Now that a link to our CoC has been added to the Backdrop codebase, we should also add a link to it from the main site.

Where should that link live?

**Comment by klonos** [comment]
Seems like the footer could be the place. We already have links there for:

- [Security](https://backdropcms.org/security)
- [Privacy](https://backdropcms.org/privacy)
- [Contact](https://backdropcms.org/contact)
- [Press Kit](https://backdropcms.org/presskit)
- [Thank You](https://backdropcms.org/thank-you)

![image](https://user-images.githubusercontent.com/2423362/113344943-711c5300-933a-11eb-889c-d72893e3ea1d.png)

**Comment by bugfolder** [comment]
This is added:
![footer](https://user-images.githubusercontent.com/29214084/137568680-7de81ea8-7c97-48a1-a26f-421b142f1033.jpg)

**Comment by oadaeh** [comment]
This can be closed now.
