### ISSUE TITLE
Missing Link(?) - API > Contrib Application Process

### ISSUE THREAD

**Issue by rgeleta** [backdrop-ops/backdropcms.org#79]
on page 
https://api.backdropcms.org/node/41809
Section "Contrib application process" > "New project checklist"
in bullet 2, it would appear that either "README.md" or "You can use this example." should be a hyperlink.  Neither is.

in bullet 3, it would appear that "See this article." should be a hyperlink.  it is not.

Section "Backdrop Contributed Project Agreement"
in bullet 6, "6.You may use this example README.md to get started." it would appear that "README.md" should be a hyperlink.  It is not.

Section: "Abandoned Projects"
in bullet 2, word "File" (as a verb) is a hyperlink to (noun)
https://api.backdropcms.org/api/backdrop/core%21modules%21system%21file.entity.inc/class/File/1
probably not the intended connection.

**Comment by jenlampton** [comment]
Links added where needed, inaccurate project module linking removed :)
https://api.backdropcms.org/contrib-application-process
