### ISSUE TITLE
End-user planning for CiviCRM on backdropcms.org

### ISSUE THREAD

**Issue by jackaponte** [backdrop-ops/backdropcms.org#790]
Coming out of #782, we'll use this issue to coordinate our planning for how CiviCRM will be used by the Backdrop community when it's installed on backdropcms.org.

During yesterday's meeting [(full notes here)](https://github.com/backdrop-ops/backdropcms.org/wiki/CiviCRM-for-Backdrop-Planning-Meeting-Notes,-April-13-2021) @stpaultim, @jenlampton and I volunteered to work on this; we thought @cellear might also want to be involved, and other folks are welcome to volunteer!

Yesterday I proposed that our next step here be a realtime brainstorming session (yes, another meeting!) to figure out how we want to use CiviCRM for Backdrop and what components we want enabled and configured from the start. This should involve an assessment of the various kinds of data we already collect (e.g. user accounts on the various sites, event registration, donation info) and how we plan to get that data into CiviCRM one way or another.

Unless folks want to suggest a different approach to this, I'll create and share a Doodle soon so we can schedule a meeting time that works well for all of us, hopefully by early May.

**Comment by jackaponte** [comment]
Here's a Doodle for scheduling our first end-user planning meeting for Civi on BackdropCMS.org:

https://doodle.com/poll/75mgmxyk2cbp672z

@jenlampton, @stpaultim, @cellear and anyone else who would like to join in this planning meeting, please fill out that Doodle as soon as you can! 

Hopefully we'll find a time in early May that works for enough of us, at least the three of us who volunteered for this role at our April 14 meeting.

You'll note that one of the options is Thursday May 13 from 12-1:30pm PT, overlapping with the Backdrop outreach meeting; that's on purpose! I thought that might help folks make room for it, if we use part of the outreach meeting time for this.

**Comment by jackaponte** [comment]
Thanks for responding to the Doodle, @jenlampton! @stpaultim, @cellear and anyone else who is interested in the end-user planning for Civi on backdropcms.org, please check out https://doodle.com/poll/75mgmxyk2cbp672z and respond with your availability in early May.

**Comment by jackaponte** [comment]
Thanks for the response, @stpaultim!

Let's plan to meet by Zoom on **Friday, May 7 from 5 to 6:30pm ET** which works for me, Tim and @jenlampton. [See this date and time in other time zones](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Planning+for+CiviCRM+on+BackdropCMS.org&iso=20210507T14&p1=388&ah=1&am=30).

@cellear and anyone else who would like to join and can make that time, please do! But this is just the first of many conversations about how we'd like to use CiviCRM for our community, so there will also be plenty of chances to participate down the road.

Zoom info below:

Join Zoom Meeting
https://us02web.zoom.us/j/89292075013?pwd=dlF6eVJtQVp2TmVXcWRCV2t5UlgvZz09

Meeting ID: 892 9207 5013
Passcode: 270129
One tap mobile
+13126266799,,89292075013# US (Chicago)
+16468769923,,89292075013# US (New York)

Dial by your location
        +1 312 626 6799 US (Chicago)
        +1 646 876 9923 US (New York)
        +1 301 715 8592 US (Washington DC)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 346 248 7799 US (Houston)
        +1 408 638 0968 US (San Jose)
Meeting ID: 892 9207 5013
Find your local number: https://us02web.zoom.us/u/kebBDI2RfP

**Comment by jenlampton** [comment]
I won't be available at this time anymore :( Thurs/Fri this week are out for me.

**Comment by jackaponte** [comment]
@jenlampton How about next Friday, 5/14 at 2pm PT/5pm ET?

If not, maybe we should go for tomorrow, Tuesday 5/4 at 3:30pm PT/6:30pm ET if we're all still available then. (@stpaultim?)

**Comment by jenlampton** [comment]
Next Friday 5/14 at 2pm PT/5pm ET would work better for me.

**Comment by jackaponte** [comment]
Great! Let's plan to meet next [**Friday, May 14 at 2pm PT/5pm ET.**](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Planning+for+CiviCRM+on+BackdropCMS.org&iso=20210514T14&p1=388&ah=1&am=30)  

We can use the same Zoom connection info that I posted earlier, https://us02web.zoom.us/j/89292075013?pwd=dlF6eVJtQVp2TmVXcWRCV2t5UlgvZz09.

**Comment by jackaponte** [comment]
Just a reminder that we're meeting this [**Friday, May 14 at 2pm PT/5pm ET**](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Planning+for+CiviCRM+on+BackdropCMS.org&iso=20210514T14&p1=388&ah=1&am=30) for our first round of end-user planning for CiviCRM.

Zoom link is https://us02web.zoom.us/j/89292075013?pwd=dlF6eVJtQVp2TmVXcWRCV2t5UlgvZz09, full call-in info is [posted above!](https://github.com/backdrop-ops/backdropcms.org/issues/790#issuecomment-831553474)

**Comment by jackaponte** [comment]
Jen, Tim and I met today for our planning meeting; notes: https://github.com/backdrop-ops/backdropcms.org/wiki/End-user-planning-for-CiviCRM-on-backdropcms.org,-May-14-2021

We've got some tasks coming out of that, including scheduling another end-user planning meeting to make some policy decisions about how we'll be using CiviCRM, who will have access and permissions and authority to do what, etc.

@jenlampton or @stpaultim, would one of you be up for taking point on starting a Doodle or something similar to get that next meeting scheduled?

**Comment by jackaponte** [comment]
Hi again @jenlampton and @stpaultim! Repeating my question from May 14: would one of you be up for taking point on starting a Doodle or something similar to get our next CiviCRM end user planning meeting scheduled? This one will be to make policy decisions about who is using our CiviCRM and how.

Also, @jenlampton, we should sort out our payment processor questions with SFC sooner rather than later. I know they have a PayPal account; we need to figure out what sort of account they're using, make sure they have the right PayPal products on their account so that it works with our CiviCRM, etc. What's the best way to approach that with SFC?

**Comment by stpaultim** [comment]
@jackaponte - I will see what I can do in the 48 hours regarding the Doodle, but I'm far enough behind on my commitments that I'm not yet committing to this one. I'm going to try to set aside a couple of hours tomorrow to work on Backdrop CMS community stuff.

Regarding the SFC. I don't think the lack of progress has been a lack of trying on our part. We need to discuss how to deal with this.

**Comment by jackaponte** [comment]
Hi all -- let's try to keep this CiviCRM work moving! A few things towards that:

1. @jenlampton and @stpaultim, I've been hoping to make it to an Outreach meeting to let folks know about our current plans for CiviCRM and see if other folks want to help out or get involved. But I've had to miss all the recent meetings and also can't make the one this week. Would either of you be up for bringing that to this week's Outreach meeting, just so folks know what we're doing with this?
2. We need to schedule another end-user planning meeting to make policy decisions about how we'll be using CiviCRM once it's launched. [Here's a Doodle I've created with times and dates when I'm available;](https://doodle.com/poll/cssy2vk6vev6g3nm) please fill it out with your availability if you'd like to attend the next meeting! 
3. Re the SFC:

> Regarding the SFC. I don't think the lack of progress has been a lack of trying on our part. We need to discuss how to deal with this.

Agreed for sure, @stpaultim! And thankfully we've recently heard from them again about other stuff. @jenlampton, do you think we should follow up with Karen, Pono or someone else at the SFC about options for using their PayPal account to receive donations via our CiviCRM? If you'd prefer, just let me know who to contact about this and how and I'll take it from here!

**Comment by jenlampton** [comment]
Yes, I think maybe reaching out to Pono and CCing Karen might be where I'd try next.

**Comment by jackaponte** [comment]
> Yes, I think maybe reaching out to Pono and CCing Karen might be where I'd try next.

Sorry I somehow missed this until today @jenlampton! I'm going to email Pono with both you and Karen CCed to see where we get with the PayPal account.

@jenlampton @stpaultim and anyone else who would like to attend the next CiviCRM end-user planning meeting, please [fill out this Doodle](https://doodle.com/poll/cssy2vk6vev6g3nm) for meeting dates in early August!

**Comment by jackaponte** [comment]
@stpaultim, any chance that you're available to meet this Friday August 13 at 3pm or 4pm CT? @jenlampton and I both responded that we're available to meet then (though that response from Jen came a while back!)

Never heard back from Pono after emailing him; going to send a follow-up email today.

**Comment by stpaultim** [comment]
This Friday is a bit busy for me, but I could meet from 4-5pm (Central Time). @jackaponte

**Comment by jackaponte** [comment]
Oh geez--I'm so sorry @stpaultim, somehow I missed that update last Wednesday. Sorry also to @jenlampton since that means we've got to go back to the drawing board with scheduling.

I've created [this new Doodle](https://doodle.com/poll/eg7rhh77rftyd9c6) to give scheduling this meeting another try. Please respond as soon as you can so we can hopefully get this scheduled and successfully talk more soon! (Reminder that the next end-user meeting is to discuss and make some policy decisions about how we'll use CiviCRM as a community.)

**Comment by stpaultim** [comment]
Well, I'm sorry too. Because all day on Friday I was trying to remember what meeting I had scheduled for 4:00pm that afternoon. I never figured it out. Glad that you folks were not in a meeting waiting for me.

I filled out the Doodle.

**Comment by jackaponte** [comment]
Hah, glad we're all equally discombobulated, Tim! :laughing: Thanks for filling out the Doodle!

**Comment by jackaponte** [comment]
Many thanks for that quick response, @stpaultim and @jenlampton!

Our next CiviCRM for Backdrop end-user meeting will be next [Friday, August 27 at 4pm ET/1pm PT.](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Civi+for+Backdrop+End-user+Meeting&iso=20210827T16&p1=179) Zoom connection info below; see y'all then!

https://us02web.zoom.us/j/87656330799?pwd=RkpMaGpoaER3dmdUUE8xWVNDSzJEZz09

Meeting ID: 876 5633 0799
Passcode: 427924
One tap mobile
+13126266799,,87656330799# US (Chicago)
+16468769923,,87656330799# US (New York)

Dial by your location
        +1 312 626 6799 US (Chicago)
        +1 646 876 9923 US (New York)
        +1 301 715 8592 US (Washington DC)
        +1 346 248 7799 US (Houston)
        +1 408 638 0968 US (San Jose)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
Meeting ID: 876 5633 0799
Find your local number: https://us02web.zoom.us/u/kcAgH0qESM

**Comment by stpaultim** [comment]
I added this topic to the agenda for Sept 16th Outreach meeting. I also created an event to help us get the word out about this special discussion. https://backdropcms.org/news/events/discussion-civicrm-for-backdrop-outreach

We don't create events for most of our weekly meetings, but I thought it might make sense for a special topic like this. Any thoughts or concerns?

**Comment by jackaponte** [comment]
Thanks for that, @stpaultim!

As for the event and dashboard notification, on https://backdropcms.org/news/events/discussion-civicrm-for-backdrop-outreach I'd clarify that this is an Outreach meeting where we'll be having a discussion about CiviCRM for the Backdrop community, rather than a meeting focused solely on CiviCRM. 

I'm also figuring that this isn't so much a working meeting like the ones we've been having about Civi, more like a glimpse into the work we're doing, a chance for folks to give input, and an opportunity for people to express interest and get involved in the ongoing work on Civi stuff (by coming to the ongoing working meetings.)

No concerns from me about making events like these to highlight planned discussions at weekly meetings!

**Comment by jackaponte** [comment]
Let's get our next Civi end-user meeting scheduled! Please use [this Doodle link](https://doodle.com/poll/mcngica8d95wpv32?utm_source=poll&utm_medium=link) to share your availability if you're interested in joining us. (@jenlampton and @stpaultim, pinging you both as prior participants!)

At this next meeting we'll be:

- Finishing our the CiviCRM policy discussion we started at our last meeting (see [these notes here in GitHub](https://github.com/backdrop-ops/backdropcms.org/wiki/End-user-planning-for-CiviCRM-on-backdropcms.org,-Aug-27-2021#policy-decisions-we-need-to-make) for what we discussed last time)
- Having some show-and-tell of our existing CiviCRM installations to explore what's possible and consider what we might want to do with our own Civi instance.

**Comment by stpaultim** [comment]
> I'd clarify that this is an Outreach meeting where we'll be having a discussion about CiviCRM for the Backdrop community, rather than a meeting focused solely on CiviCRM.

@jackaponte Good feedback. I tried to do this with the event listing on BackdropCMS.org, but the dashboard notification was not clear at all. I've revised both to make it clear that this will be part of a regular Outreach meeting (although, I suspect it will take up much, but not all, of that specific meeting). I also tried to reinforce that we'll be reporting back on progress and looking for feedback.

**Comment by stpaultim** [comment]
@jackaponte Also note that Friday Oct 1st is Open Source Day sprint for the Grace Hopper Celebration and @jenlampton and I will be mentoring sprinters. This year, we're focusing on Accessibility issues. 

https://anitab-org.github.io/open-source-day/upcoming/

**Comment by jackaponte** [comment]
> @jackaponte Also note that Friday Oct 1st (one of the days on the Doodle) is Open Source Day sprint for the Grace Hopper Celebration and @jenlampton and I will be mentoring new contributors all day. This year, we're focusing on Accessibility issues.
> 
> https://anitab-org.github.io/open-source-day/upcoming/

Ah, very cool, thanks for letting me know @stpaultim! I've removed Oct 1 from the Doodle and added some times the following week. Hopefully that will let the three of us (and anyone else who would like to join us) find a time to meet more easily. (@jenlampton please check out [the Doodle](https://doodle.com/poll/mcngica8d95wpv32) and let us know when you can meet!)

**Comment by jackaponte** [comment]
Thanks for updating the Doodle, Jen!

**Our next Civi end-user meeting will be on [Friday, September 24 at 4pm ET/1pm PT](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Civi+for+Backdrop+End-user+Meeting&iso=20210924T16&p1=179&ah=1).**

We'll be:

- Finishing our the CiviCRM policy discussion we started at our last meeting (see these notes here in GitHub for what we discussed last time)
- Having some show-and-tell of our existing CiviCRM installations to explore what's possible and consider what we might want to do with our own Civi instance.


Zoom connection info for the meeting:

Join Zoom Meeting
https://us02web.zoom.us/j/85978138153?pwd=NFJ6TFIrNHdlZ2FrL0tWSTc5Y3BWQT09

Meeting ID: 859 7813 8153
Passcode: 007364
One tap mobile
+13126266799,,85978138153# US (Chicago)
+16468769923,,85978138153# US (New York)

Dial by your location
        +1 312 626 6799 US (Chicago)
        +1 646 876 9923 US (New York)
        +1 301 715 8592 US (Washington DC)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 346 248 7799 US (Houston)
        +1 408 638 0968 US (San Jose)
Meeting ID: 859 7813 8153
Find your local number: https://us02web.zoom.us/u/kdDMPmeong

**Comment by stpaultim** [comment]
Just a reminder that this topic is on the Agenda for the Outreach meeting today.
https://backdropcms.org/news/events/discussion-civicrm-for-backdrop-outreach (starts in 15 minutes)

**Comment by jackaponte** [comment]
@jenlampton and @stpaultim, as per [our last meeting](https://github.com/backdrop-ops/backdropcms.org/wiki/End-user-planning-for-CiviCRM-on-backdropcms.org,-Aug-27-2021) I've gotten the test site at https://backdropcms.palantetech.coop up to date with the newest versions of Backdrop and CiviCRM.

Now it's time for us to kick the tires on that test site and make sure that installing CiviCRM didn't have any unfortunate or unexpected consequences!

Once we feel we've done sufficient testing, we'll ask Morgan to submit a PR to get the Civi code onto backdropcms.org live, then we can get it installed there.

I sent you both passwords for your accounts on the test site; let me know if you have trouble logging in. If anyone else who is used to using backdropcms.org would also like to log in and test, let me know!

We can check in about this at [this Friday's meeting. :)](https://github.com/backdrop-ops/backdropcms.org/issues/790#issuecomment-917272483)

**Comment by bugfolder** [comment]
I'd be interested to kick the tires. Maybe you can PM me credentials via Zulip?

**Comment by jackaponte** [comment]
> I'd be interested to kick the tires. Maybe you can PM me credentials via Zulip?

Done--thanks @bugfolder!

**Comment by jackaponte** [comment]
Hello to everyone who's working on the end-user planning for CiviCRM on b.org! Two things today:

1. How is the "kicking the tires" going on the test site at https://backdropcms.palantetech.coop/ ?
- Have folks noticed anything amiss with the expected backdropcms.org functionality now that CiviCRM is installed?
- Any questions or concerns about what you've seen? 
- Anyone need more time to check?
- Anyone need guidance on what they _should_ be checking? (I might need that _but_ I also barely ever use b.org so I'm probably not so important a tester!)

Once enough of us feel like we've done enough checking to be comfortable with installing CiviCRM on backdropcms.org itself we can let others know about that on #789 and help move that installation process along.

2. Let's get our next meeting scheduled! Please use [this Doodle](https://doodle.com/poll/ygb5d9z2nyby2p3y) to share your availability. (Pinging @bugfolder, @cellear, @stpaultim and @jenlampton as folks who have expressed interest in attending these end-user planning meetings specifically, but everyone who wants to work on this is welcome!)

Our agenda for this meeting is carried over from last time:

- Finishing our the CiviCRM policy discussion we started at our August 27 meeting (see [these notes here in GitHub](https://github.com/backdrop-ops/backdropcms.org/wiki/End-user-planning-for-CiviCRM-on-backdropcms.org,-Aug-27-2021#policy-decisions-we-need-to-make) for what we discussed then)
- Having some show-and-tell of our existing CiviCRM installations (including the b.org test site!) to explore what's possible and consider what we might want to do with our own Civi instance.

**Comment by bugfolder** [comment]
I’d like to try out the creation of CiviCRM contacts from all user accounts (or am fine if someone else wants to try that). OK? That's a one-time thing, of course.

**Comment by jackaponte** [comment]
> I’d like to try out the creation of CiviCRM contacts from all user accounts (or am fine if someone else wants to try that). OK? That's a one-time thing, of course.

For myself, I'm fine with you giving that a try, @bugfolder! I just dumped the Civi database too so we can restore it to the pre-contacts-creation state if needed.

**Comment by jackaponte** [comment]
Hi all, following up on [last week's update:](https://github.com/backdrop-ops/backdropcms.org/issues/790#issuecomment-932612964)

# Please update https://doodle.com/poll/ygb5d9z2nyby2p3y with your availability for the next Civi end-user planning meeting. Doodle now with more dates not during Backdrop LIVE!
# Anyone need to do any more tire-kicking before we tell folks on #789 that we're ready to create a PR for backdropcms.org that includes Civi? @bugfolder I checked out the test site at https://backdropcms.palantetech.coop and it doesn't seem like you've synced Backdrop users to Civi contacts; let me know if you want me to give that a test instead!

**Comment by bugfolder** [comment]
I"ll just pass on this tidbit: on the CiviCRM site I manage, we collect first, middle, and last names upon user registration. Of course, lots of people leave the middle name blank or just put in an initial, which is totally OK. But bots trying to create bogus accounts for spam purposes often duplicate the first or last name in the middle name field, and that's become a useful tool for detecting, quarantining, and/or blocking bad guys. So, as an anti-spam measure, it's something to consider.

**Comment by jackaponte** [comment]
Ah @ericfg, very sorry we missed you! And thanks for being down to help. I don't think we identified any particular things that we haven't done yet in terms of kicking the tires with Civi installed on the test b.org site, so unless you have something specific you want to try, there might not be anything else for you to do there!

From [that list of tasks,](https://github.com/backdrop-ops/backdropcms.org/issues/789#issuecomment-928499011) it seems like until the beta.backdropcms.org is set up (see #831) we can't actually move forward on the installation and initial configuration side of things besides submitting the pull request that includes the Civi code.

But if you want to create a new, separate issue for the name fields/account registration questions starting [earlier on this issue,](https://github.com/backdrop-ops/backdropcms.org/issues/790#issuecomment-940499130) that would rock!

**Comment by jenlampton** [comment]
> It seems like we might want a whole separate Github issue and/or discussion at a meeting to sort out how to handle name fields for BackdropCMS.org user registration once CiviCRM is installed. Anyone else want to create that separate issue? If not I will soon!

Just noting that we have already been through this discussion once before, and that's why we have the single Full name field that works for everyone. 

> On our site, we dealt with the internationality issue by labeling the fields "First/Given Name", "Middle Name", and "Last/Family Name."

Labeling the name fields to make it clear that they only work for Western or European shaped names might be "dealing with" the issue, but it does not solve the problem.

If my First name is also my Family name, do I put it into the "First/Given Name" field, or "Last/Family Name" field? Either both options are wrong, or both are right, but both are still confusing. 

It's true that people who don't have Western or European shaped names are accustomed to dealing with these kinds of problems with their names everywhere else on the internet, but I'm sure there's a way we can still use Civi without forcing them into that same box here.

**Comment by jackaponte** [comment]
Thank you for opening a new issue for that, @jenlampton!

Let's keep all conversation about the name fields on that new issue, #843.

**Comment by jackaponte** [comment]
Hey all here--sorry it's taken me a while to send out a scheduling link for our next end-user meeting. 

**Please visit [this Doodle](https://doodle.com/poll/gcw8ucfmfht8h34v?utm_source=poll&utm_medium=link) to fill in your availability for our next meeting!** (All dates starting Nov 30, the earliest I can make it.) Our agenda is [carried over from the last two planned meetings!](https://github.com/backdrop-ops/backdropcms.org/issues/790#issuecomment-943692152)

Since I didn't hear back from anyone on [this October 29 post](https://github.com/backdrop-ops/backdropcms.org/issues/790#issuecomment-954909091) I went ahead and marked the "kick the tires"/testing on backdropcms.palantetech.coop step DONE on our list of next steps for installing and configuring Civi on b.org.(https://github.com/backdrop-ops/backdropcms.org/issues/789#issuecomment-928499011)

I'll go ahead and submit a PR soon as outlined in the next step on that list, but I'm not sure that beta.backdropcms.org is actually ready for testing this yet; seems like that part of #831 has been stuck for a while.

Looking forward to keeping this moving!

**Comment by stpaultim** [comment]
I just filled out the Doodle. I see @bugfolder has as well. Let's try to finally land this project. 

Big thanks to @jackaponte for being so patient with all of us. My own attention in the Backdrop world has been so scattered of late, I'll try harder to focus on helping complete this task.

**Comment by jackaponte** [comment]
Thanks so much for moving this along, @stpaultim!

After getting a bunch more RSVPs I've scheduled our next end-user planning meeting for **[next Tuesday, December 7 at 4pm EST/1pm PST](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Civi+for+BackdropCMS.org+End-user+Meeting&iso=20211207T16&p1=179&ah=1).**

Zoom connection info pasted below!

Our meeting agenda:

- Finishing our the CiviCRM policy discussion we started at our August 27 meeting (see [these notes here in GitHub](https://github.com/backdrop-ops/backdropcms.org/wiki/End-user-planning-for-CiviCRM-on-backdropcms.org,-Aug-27-2021#policy-decisions-we-need-to-make) for what we discussed then)
- Having some show-and-tell of our existing CiviCRM installations (including the b.org test site!) to explore what's possible and consider what we might want to do with our own Civi instance.


Connection info:

Topic: Civi for BackdropCMS.org End-User Planning Meeting
Time: Dec 7, 2021 04:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://us02web.zoom.us/j/83134390318?pwd=ajVXM3BUcGptNzJsMW5QSm50N2JSUT09

Meeting ID: 831 3439 0318
Passcode: 147544
One tap mobile
+14086380968,,83134390318# US (San Jose)
+16699006833,,83134390318# US (San Jose)

Dial by your location
        +1 408 638 0968 US (San Jose)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 346 248 7799 US (Houston)
        +1 646 876 9923 US (New York)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
Meeting ID: 831 3439 0318
Find your local number: https://us02web.zoom.us/u/kf3whF9Qr

**Comment by jenlampton** [comment]
I set up a doodle for our next meeting in January, anyone who would like to attend is welcome to specify preferred times:
https://doodle.com/poll/z7qkmvvuid7wsyy4?utm_source=poll&utm_medium=link

@jackaponte @stpaultim @larsdesigns @ericfg @BWPanda @bugfolder

**Comment by jackaponte** [comment]
Thanks for setting up that Doodle, Jen!

And thanks to everyone for a great meeting today! Here are our meeting notes: https://github.com/backdrop-ops/backdropcms.org/wiki/CiviCRM-for-BackdropCMS.org-Planning-Meeting-Notes,-December-7-2021

We feel confident we'll be able to get CiviCRM live on BackdropCMS.org by January!

**Comment by jackaponte** [comment]
Hi all! I nearly lost track of this issue. As I noted during [today's meeting](https://github.com/backdrop-ops/backdropcms.org/issues/782#issuecomment-1049371319) there aren't really separate end-user planning meetings vs technical planning meetings at this point. 

*I propose that we close this issue and continue discussion, meeting planning etc in #782 while keeping #789 as focused as possible on the actual installation and initial config of Civi on BackdropCMS.org.*

Any objections?

**Comment by bugfolder** [comment]
I see no objections, so I'll close this issue.
