### ISSUE TITLE
Free up the placeholder on https://backdropcms.org/project/superfish for newly ported Superfish module

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/backdropcms.org#792]
The text on https://backdropcms.org/project/superfish, namely this part:

> Superfish replaced by System menus in v1.5 

sounds misleading in that the System menus uses the same library  (it uses [SmartMenus](https://www.smartmenus.org/) instead). And even-though it is stated:

> Your custom styles for Superfish menus in Drupal 7 will need to be adjusted for Backdrop.

all the upgrade instructions steps given on the same page could give a wrong impression there is an upgrade path from Superfish to the System menus. There is none and users should create their menus from zero.

However, with the [Superfish](https://github.com/backdrop-contrib/superfish) module ported today, they don't need to delete Superfish database tables as all their Drupal 7 menus will be there available this time on the migrated Backdrop sites. 

So please free up the taken placeholder so released version of Superfish module could take its own address, because it would be wrong to deprive users who for various reasons prefered to stay with Superfish module instead of switching to Backdrop core's system menus.

**Comment by oadaeh** [comment]
Can this be closed?

**Comment by bugfolder** [comment]
Sure, closing. Although I'm re-pinging @alanmels to make a release for https://github.com/backdrop-contrib/superfish.
