### ISSUE TITLE
Watchdog log errors

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#794]
`Notice: Undefined variable: more in include() (line 30 of /home/backdrop/repo/www/themes/borg/templates/node--project-search.tpl.php).`

Lots of those, for every page of every project search. The template in question has a 

`<?php print render($content); ?><?php print $more; ?>` 

but the `template.php` code suggests the `more` link is already part of `$content`, i.e.: 

`$variables['content']['more'] = array(` 

so there isnt really a lone `$more` right?

**Comment by docwilmot** [comment]
Actually this error makes the watchdog list useless. All 22 pages of watchdog notifications are from this morning alone, the majority just this error. Doing a quick PR. @jenlampton.

**Comment by jenlampton** [comment]
This change has been depployed.
