### ISSUE TITLE
Feature request: add Markdown filter to b.org and docs.b.org

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#796]
I'd like to request that we add the [Markdown text filter](https://backdropcms.org/project/markdown) and an associated text format to backdropcms.org and docs.backdropcms.org, to go along with the existing formats Standard and HTML (on b.org) and Standard and Documentation (on docs.b.org).

The rationale is that it makes it much easier to create, edit, review, and discuss changes to documentation pages.

This is related to https://github.com/backdrop-ops/backdropcms.org/issues/256 raised by @klonos, which proposed a different solution (usiing GitBook or ReadTheDocs), and the ensuing discussion raised several pros and cons of that approach: some of those apply as well to this proposal.

Let me start with reasons to do it. First and foremost, for documentation-like pages (READMEs, long comments on GitHub), I really like to do my creation and editing in an offline editor (perhaps saving drafts, snippets, and/or multiple versions), and only when it's really ready to go do I copy and paste it into the editor field of the page it is destined for. For comments in issues and PRs on GitHub, that works great, since GitHub speaks Markdown. It would be nice to be able to use this approach on pages on backdropcms.org and docs.backdropcms.org. One could do this now with offline editing in HTML or RTF, but editing in MD is easier and cleaner.

Markdown also lends itself to a model where one can propose a new documentation page (or major changes to an existing page) as an issue on github.com/backdrop-ops/ because you can put the proposed text directly in the issue in MD format; people can see exactly what you're proposing and how it will look (modulo fonts and type sizes). They can propose changes or further rewrites in the issue in the same way. And then when/if it gets to the stage that it's ready for incorporation into the real documentation, one could then copy/paste the MD text from the issue onto the relevant page on b.org.

My feeling is that this would lower the barrier for people to contribute to b.org pages and documentation, and it provides a streamlined way via the issue queue for people to propose changes for feedback rather than just going in and creating/editing a page on the site and then saying "what do you think of this?" (Or doing discussion in MD on Github, but then converting to HTML or RTF to paste into the page.)

(It would certainly lower the barrier for me. In a recent meeting, the topic of me writing one or more blog posts came up, and I can say I'd much rather do this in an offline MD editor, then copy-paste, versus editing in HTML directly, or editing in a Rich Text editor and then hoping it comes over properly pasted into CKEditor.)

In https://github.com/backdrop-ops/backdropcms.org/issues/256, @jenlampton raised several issues related to GitBook, two of which are particularly relevant here:

> * I feel that a rich-text editor will be easier for people to learn how to use than markdown for writing text. (and we really should be fixing our own rich-text editor if there are significant problems with it)

While it may be true that a RT editor is easier to learn when starting from scratch, I suspect that many (if not most) of the potential contributors already know and are comfortable with MD. After all, it's needed to write READMEs and used to participate in issues and PRs on Github. And if you're editing an existing page, it's way more readable than HTML.

And a big factor in favor of using it is not related to any problem with the existing RT Editor; it's that it streamlines the process of doing creation/editing/discussion of text in offline editors and/or discussions in the issue queue.

> * We already have revisions on backdropcms.org, a better tool for tracking text changes than Git. (We've already learned that Git is not a good tool for managing text - all changes are tracked as entire line additions or removals. That's good for code, but bad for English.)

And while revisions on b.org would certainly be useful in that a change can be rolled back if folks don't like what changed, it would be nice to be able to circulate and socialize potential changes before they ever appear on b.org. Perhaps a future upgrade to b.org could create a system for storing, retrieving, and editing drafts of page nodes, but any solution like that would be a ways off. Whereas adding a Markdown text formatter would be a simple and easy solution with immediate impact.

So, I'd like to suggest we add a Markdown formatter. Further thoughts solicited.

**Comment by jenlampton** [comment]
I've also wanted to use markdown, since I'm so accustomed to it from github. I expect most people working on our documentation will feel the same.

**Comment by klonos** [comment]
> ...I expect most people working on our documentation will feel the same.

Yup, count me among those people 👍🏼

**Comment by klonos** [comment]
Code LGTM, but I will need to find some time to test. Thanks for working on this @bugfolder 🙏🏼

**Comment by quicksketch** [comment]
We have this on the agenda for today's weekly meeting. https://docs.google.com/document/d/1DiA_nD5smp0hUpSelEKWjnsqd-vfGyZevC4-yDhyseQ/edit#

**Comment by BWPanda** [comment]
I love using Markdown, and I'd love to be able to use it in more places. I even added it to my own website a few years ago: https://panda.id.au/posts/creating-a-github-like-editing-experience-in-backdrop

But I hear the concerns raised by @quicksketch and @stpaultim in today's dev meeting (https://www.youtube.com/watch?v=616o0-wvRfs). The problem is that different people have different preferences, and because content is saved in the DB in the format that it's written, you can't really change it after the fact (well, easily anyway).

I have a theoretical solution for this, but it's likely not possible. Let me put it out there anyway...

What if content were saved in the DB as the final, formatted HTML? Then what if, when someone went to edit that content, it was converted into the formatting of thier choice?They could edit it in Markdown, or the GUI editor, then when they press save it's saved back as HTML. This would mean that anyone can edit any content in whatever format they like!

The problem I foresee is in converting the saved HTML into various formats. I imagine there *might* be tools out there that allow, for example, converting HTML to Markdown (I think @bugfolder mentioned this in the meeting), but I also imagine they're not perfect and might be more trouble than they're worth.

Or maybe there's a better, more simple format in which to save content in the DB that can be more easily converted between the different formats? Or maybe that's what Markdown is... Save all content in the DB as Markdown, then convert it to HTML *if* someone wants to edit it that doesn't like using Markdown...

Again, probably not possible, but just a thought I had for an ideal world where everyone can edit everything in their format of choice 🙂

**Comment by quicksketch** [comment]
I forgot during the weekly meeting to mention one of the most important problems with Markdown (as we have it today): Images! They're difficult to embed without the copy/paste or upload support that we get here on GitHub issues. Every time I need to separate upload an image, copy its source URL, paste and format the tag/markdown manually it pains me it's so tedious.

**Comment by bugfolder** [comment]
One of the nice things about Markdown is that you can mix Markdown with HTML. So you can use the "Standard" text format with CKEditor to insert your images (but not the surrounding text), then convert the formatting to Markdown and insert your Markdown text in between the bits of HTML that render the images.

However, you have to do all your image insertion first, because if you switch the editor from Markdown to Standard and then back, CKEditor will have munged all the formerly clean Markdown with added HTML markup.

**Comment by BWPanda** [comment]
What about my solution to inserting images in Markdown? https://panda.id.au/posts/creating-a-github-like-editing-experience-in-backdrop#inserting-images

**Comment by bugfolder** [comment]
I've tested out the [Insert module](https://backdropcms.org/project/insert) described by @BWPanda in his blog post. It works very nicely and, I think, eliminates a lot of the tedium that @quicksketch identifies as a sticking point against Markdown. With the Insert module, to add an image to a Markdown-formatted field, you:

1. Upload the file.
2. Put your cursor where you want the image.
3. Click the "Insert" button.
4. Presto. The Markdown-formatted image code is in place.

That said, there's a bit of preparation that needs to be done on the site to make this work. First, of course, install and enable the Insert module.

Next, to get Markdown-formatted image code, you need to override the image-insert.tpl.php template in the admin theme. I created a simple sub-theme of Seven ("badmin"), put the overridden template file in its templates folder, and set that to be the admin theme (of my local copy of backdropcms.org) to override the template.

Also, to make this work the image file needs to be a field of the content type. The Page content has a Files field already, and we can enable Insert for that field, and it works, but since there is no provision for entering alt or title text with a generic file, there's no alt or title text in the inserted image HTML.

A cleaner solution is to add an Image field to the Page type and then enable Insert for that field. In this case, everything works exactly as desired.

A difference from using the image widget in CKEditor is that when CKeditor uploads an image, it doesn't attach it to the particular content type; it puts all images in One Big Heap. (Personally, when I'm creating page nodes that have bespoke images embedded within them I prefer to have the images attached to the node they go with, but I realize others might not.)

And I realize that adding another field to content types is not something done lightly, since that field will persist forever and we'll now have images in two different places: some in CKEditor's one big heap, some attached to nodes (although that is maybe already the case).

All things considered, though, I think adding the Insert module removes one of the last arguments against Markdown, so I would vote for adding both Markdown and Insert to achieve the least-friction way of adding further content to the *.b.org sites.

**Comment by jenlampton** [comment]
For starters: I don't think the image issue should be a blocker for adding the markdown filter. I'm happy to do this one step at a time :) Maybe we should make a separate issue for inline images, and continue this debate there? 

And on the image issue, I don't think we should add another field to every place that uses the markdown filter. Fortunately, we have a work-around already. This was what we did before we had any image support for the current text formats: upload the necessary files from the Manage files page (admin/content/files) and then enter the HTML for the image tag. Right now, everyone who's working on documentation/content edits can handle this with only a little extra effort, and we can work on a best-practices image uploading feature for markdown without having added any field cruft may be hard to clean up later.

**Comment by jenlampton** [comment]
I've tested, (applied a patch) deployed the change, enabled the module, and syncronized config. I think we still need to do some work to set the default text format for all project nodes to markdown, and write an update hook to set all existing project nodes to use markdown for their body fields as well. Should that be a follow-up issue?

**Comment by bugfolder** [comment]
> set the default text format for all project nodes to markdown, and write an update hook to set all existing project nodes to use markdown for their body fields as well. Should that be a follow-up issue?

Yes. Two follow-up issues:

* https://github.com/backdrop-ops/backdropcms.org/issues/883
* https://github.com/backdrop-ops/backdropcms.org/issues/884
