### ISSUE TITLE
Inappropriate Link (?) - API > PHP Standards

### ISSUE THREAD

**Issue by rgeleta** [backdrop-ops/backdropcms.org#80]
On bottom of page 
https://api.backdropcms.org/php-standards
Section "Naming Conventions"
https://api.backdropcms.org/php-standards#naming-conventions

subsection "File Names", the word "File" in the subsection title is a hyperlink to the "file.entity.inc" file class
it appears this is not the intended connection

**Comment by jenlampton** [comment]
It looks like the `API filter` is not working correctly here either. I've disabled it for now.
