### ISSUE TITLE
Inappropriate link (?) - API > CSS Standards

### ISSUE THREAD

**Issue by rgeleta** [backdrop-ops/backdropcms.org#81]
On page
https://api.backdropcms.org/css-standards

section comments
https://api.backdropcms.org/css-standards#comments

subsection "File Comments", the word "File" in the subsection name is a hyperlink to file.entity.inc file class definition
it appears this is not the intended link

section "File Names" in text (pointed to by link "CSS File Names" in top contents block) at
the word "File" in section name is a hyperlink to file.entity.inc file class definition
it appears this is not the intended link

in the SMACSS numbered list, item 2. Layout is a link to layout.class.inc, does not appear to be the intended connection

same comment for further down in "CSS files for themes"
in bullet 4, Theme rules, the word "file" is a link to php.net/file

**Comment by jenlampton** [comment]
Thanks @rgeleta! It looks like the `API filter` is not working correctly here.  It's what's linking up the word File, and some of these others, though I'm not sure why. I've disabled it for now, we'll see if that causes more problems than it solves :)

**Comment by jenlampton** [comment]
Oh also, this issue should have probably been in the API site issue queue :)
