### ISSUE TITLE
Add Biography field to the user registration page

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#811]
If we add the biography field to the user registration page and make it required, then its content will be tested by Akismet and we can likely catch a bunch of spam accounts before they happen.

PR to follow.

**Comment by jenlampton** [comment]
@bugfolder can you file a similar PR that does not change the text format? I have a solution for the format problem over in https://github.com/backdrop/backdrop-issues/issues/5151

**Comment by jenlampton** [comment]
I've comitted this config directly on the live site, so closing.
