### ISSUE TITLE
Inappropriate Link (?) - API > Javascript Coding Standards

### ISSUE THREAD

**Issue by rgeleta** [backdrop-ops/backdropcms.org#82]
On page 
https://api.backdropcms.org/js-standards
Section Comments
https://api.backdropcms.org/js-standards#comments

sentence beginning "Comment standards are discussed " has word "Comment" hyperlinked to comment.entity.inc class definition.  This may be an inappropriate connection

**Comment by jenlampton** [comment]
Fixed now :)
