### ISSUE TITLE
Project Leadership page layout is broken

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#83]
Missing all of the sidebar nav/logo, etc. Only has page contents.

Screenshot below:
![project leadership backdrop cms](https://cloud.githubusercontent.com/assets/5607236/8636457/c6874c54-282f-11e5-9e2b-01887e3012f6.png)

**Comment by quicksketch** [comment]
Hm, perhaps this was fixed without intervention? The site appears fine now on this page as far as I can tell: https://backdropcms.org/leadership

**Comment by quicksketch** [comment]
Let's reopen this issue if needed, as far as I can tell, things are a-okay at the moment.

**Comment by wesruv** [comment]
Looks good to me too :)
