### ISSUE TITLE
Javascript and spam error creating account on backdropcms.org

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/backdropcms.org#834]
I'm trying to create an account on https://backdropcms.org/user/register

I enter the same username and email address that I've successfully registered for survey, forum, events subsites.  I enter my real name which is pretty English.  I then enter a bio, which I can't think how it could be a spam issue:

`I started dabbling with websites in 2001, writing my first HTML, CSS and JS websites in Notepad over dial up internet. In 2005 I started on my journey with data driven websites with my own PHP and MySQL content management system. By 2009 I have moved to Drupal 7 and many sites were built over the years, with a few static Bootstrap sites built for good measure.

During this time I worked for a range of public sector bodies, first in public rights of way, then rural development (including a lot of renewable energy) before moving into business intelligence for European Structural Funds, followed by business analysis first for European Funds, then for the police. Even during full time employment I often had side projects within my job developing Excel, Access and other Office automation solutions.

In 2021, I started working in Backdrop CMS and while I still have a couple of Drupal 7 sites, all new work is in Backdrop. Also in 2021, I started working full time for my business specialising in data solutions for web and desktop for small business and non-profits.`

First I get the error "You seem to have javascript disabled. Please confirm your form submission." then when I click Create account again I get: "Your submission has triggered the spam filter and will not be accepted."

I have javascript enabled as it is common on many sites I use.  I can't think why I'm triggering the spam filter.

**Comment by bugfolder** [comment]
I've dialed down the Akismet filter. @yorkshire-pudding, would you please try again?
