### ISSUE TITLE
Sync Recent Newsletter Subscriptions

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#836]
Atten: @jenlampton 

I notice that we're not getting any new subscribers to our email list. Are new email subscriptions going somewhere other than SendInBlue and then do we add them manually to SendInBlue?

Is this intentional or something that we simply haven't gotten around to fixing. 

I just tested this by subscribing a new email email address to the newsletter and I got a confirmation, but there is nothing on SendInBlue. 

The confirmation email is a a mailjet.com email address. 

I'll put this on the agenda for the Outreach meeting tomorrow.

**Comment by stpaultim** [comment]
But, if we have a bunch of new subscribers that have NOT been getting our emails, it would be nice if we could send them a Backdrop LIVE announcement.

**Comment by jenlampton** [comment]
Yep!

**Comment by jenlampton** [comment]
307 new subscribers imported :D
