### ISSUE TITLE
Add a link to the Reddit to the front page.

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#84]
Have mentioned this here and on the Reddit, but I think Backdrop (the group) is not social enough.
[This write-up on Monarch digital's site](https://www.monarchdigital.com/blog/2015-07-06/first-look-backdrop-cms) agrees:

> ...while Github is an excellent place to work on open source projects, the seemingly absent interconnectivity that is expected in such an environment seems like it may be a speed bump for Backdrop’s adoption. After all, building out your support and community infrastructure on top of another organization’s proprietary service will inherently limit your options - hence why Drupal’s drupal.org is homegrown and built to do and support what its community needs.

The Reddit has languished sadly since it was built. I think we need to push more the idea of (non-developer) community a bit more. I imagine there may have been persons who either looked for a forum and didnt see or recognize the link, or perhaps reached the Reddit and saw that the last post hasn't been answered for a couple of weeks, and decided not to bother.

Perhaps someone can agree to be the Reddit monitor for at least the next few months?

**Comment by klonos** [comment]
AFAIAC, I think that we should build something "homegrown" on bd.org too. I know, we've been through this discussion before and remember the pros and cons, but still...

**Comment by jenlampton** [comment]
I agree, but don't think we should build it until we can run it. We need a volunteer to watch and answer questions, or bring in the people who can answer them when necessary.

**Comment by docwilmot** [comment]
My very first Backdrop post was asking for a discussion forum. This is obviously my job. Build it I'll moderate it.

**Comment by docwilmot** [comment]
All done
