### ISSUE TITLE
Create job board where projects that "Help needed" posts can be posted

### ISSUE THREAD

**Issue by irinaz** [backdrop-ops/backdropcms.org#842]
I propose to set a ~website jobs.backdrop.org~ place  where employers can post jobs/gigs related to Backdrop CMS. Site would be similar to https://jobs.drupal.org/ 

Posting should have a job description and a way to reach out to the employer. Service providers (https://backdropcms.org/support/services/contractors) can reach out to employers if they are interested in the job.  

Postings can be free for employers or small fee can be charged and used to pay for website hosting.   There should be no other monetary interactions around this website.

**Comment by irinaz** [comment]
@stpaultim , thanks a lot!  https://forum.backdropcms.org/forum/help-wanted-job-listings looks great.  We can close this issue or add link "Jobs" or "job listings"  from backdrop.com Support menu.
thanks again!

**Comment by yorkshire-pudding** [comment]
@stpaultim I notice on https://forum.backdropcms.org/forum/create-backdrop-theme that you said you would reply privately.  Should everyone have this function enabled in the forum?  I checked and it doesn't seem to be there.  See @bugfolder 's comment here: https://github.com/backdrop-ops/backdropcms.org/issues/842#issuecomment-952981138

**Comment by irinaz** [comment]
Thank you, https://forum.backdropcms.org/forum/help-wanted-job-listings will be helpful for now.
