### ISSUE TITLE
Orphaned page on b.org - should it be on docs.b.org?

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/backdropcms.org#849]
I have a link to a page that I think I must have got on the forum somewhere:
https://backdropcms.org/file-permissions-and-ownership

I can't see any link to it on the page it appears to be a child of which is About>Security
![image](https://user-images.githubusercontent.com/20357797/143566087-ba6e8d18-6414-4444-a3c8-af83c3596ee6.png)

I wonder if this belongs on docs.b.org or whether it just needs a link to it from the security page.

It does come up when searching for `backdrop cms file permissions and ownership` on google but it seems odd there is no way to navigate to this page on b.org itself.

**Comment by bugfolder** [comment]
Seems like it belongs on docs.b.org. Maybe as a sub-page of https://docs.backdropcms.org/documentation/site-configuration-and-web-hosting-issues?

**Comment by yorkshire-pudding** [comment]
I would agree with that location.  Would make sense to do a 301 redirect as that page is known to google as well as referred to in forum somewhere.

**Comment by olafgrabienski** [comment]
I'm wondering if there's a link to the page from somewhere in the Backdrop interface. If so, a redirect would be even more important.

**Comment by yorkshire-pudding** [comment]
I did have a good hunt but couldn't find it.  The menu when on that page makes it look like it is under the About>Security page but I can't find any links there to it.  Couldn't find any other logical place for a link either and there doesn't seem to be an easy way to search the b.org content.

**Comment by bugfolder** [comment]
Page is moved to docs: https://docs.backdropcms.org/documentation/file-permissions-and-ownership

301 redirect on b.org: https://backdropcms.org/file-permissions-and-ownership
