### ISSUE TITLE
OS Server Upgrade

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/backdropcms.org#850]
It has become time to upgrade the OS. The following tasks will be performed: 

We are planning to upgrade to Debian Bullseye 

Beta server:

1. Perform a full VM image backup.
1. Perform the Debian OS upgrade. 
1. Check to make sure configuration files have been restore and/or migrated.
1. Check cron jobs to make sure they intact and running. 
1. Test to make sure the beta sites are running within established parameters and expectations. 

If the upgrade of the Beta server is successful, then proceed with the following steps on production: 

1. Notify the community at the time of maintenance in both this issue and in the Zulip channel. 
1. Perform a full VM image backup.
1. Perform the Debian OS upgrade. 
1. Check to make sure configuration files have been restore and/or migrated.
1. Check cron jobs to make sure they intact and running.
1. Test to make sure the beta sites are running within established parameters and expectations.

Notify the community by github issue and Zulip when the maintenance is completed.

**Comment by larsdesigns** [comment]
Completed the following: 

1. Enabled backups for the beta server. 
2. Created a backup image of the beta server 
3. Investigated and found that it is only possible to upgrade to the next version of the OS. Skipping over versions is not possible.
4. Started preparing the beta server for the upgrade from Debian 9 to 10. 

I got a bit of a late start so I will pick this up later in the evening.

**Comment by findlabnet** [comment]
My two cents.
In the same case (upgrade from Debian 9), I've tried this way: https://www.linode.com/docs/guides/manually-upgrading-to-latest-distribution-version/#steps-for-performing-an-upgrade-through-a-clean-install
For me it was smooth way to Debian 11 instead of inline upgrade.

**Comment by larsdesigns** [comment]
I moved the implementation date back to the December 11th.

**Comment by larsdesigns** [comment]
My apologies, I have been super busy. My goal is to have this upgrade done by the new year.

**Comment by larsdesigns** [comment]
Completed the following on the beta.backdropcms.org server: 

1. Upgraded the OS from Debian stretch to bullseye. 
2. Rebooted the server. 
3. Checked NAMP stack and the sites are running well. 
4. Checked IPtables and the rules are still persistent. 
5. Checked fail2ban and it is running without errors.
6. Using `/etc/hosts` on my workstation, the backdropcms.org site on the beta server is running well. 

#### Next Steps
1. Check nginx cache and logs
2. Backup the production host. 
3. Updated

**Comment by larsdesigns** [comment]
Completed the following on the beta.backdropcms.org server: 

1. Upgraded the OS from Debian stretch to bullseye. 
2. Rebooted the server. 
3. Checked NAMP stack and the sites are running well. 
4. Checked IPtables and the rules are still persistent. 
5. Checked fail2ban and it is running without errors.
6. Using `/etc/hosts` on my workstation, the backdropcms.org site on the beta server is running well. 

#### Next Steps
1. Check nginx cache and logs
2. Backup the production host. 
3. Perform the upgrade steps on production.

**Comment by larsdesigns** [comment]
Completed the following on the beta.backdropcms.org server: 

1. Upgraded the OS from Debian stretch to bullseye. 
2. Rebooted the server. 
3. Checked NAMP stack and the sites are running well. 
4. Checked IPtables and the rules are still persistent. 
5. Checked fail2ban and it is running without errors.
6. Using `/etc/hosts` on my workstation, the backdropcms.org site on the beta server is running well. 

#### Next Steps
1. Check nginx cache and logs
2. Backup the production host. 
3. Perform the upgrade steps on production.

**Comment by larsdesigns** [comment]
I had completed the OS upgrade last night to Debian Bullseye on the beta server. I am going to go for the upgrade tonight/this morning for the production server. I am estimating an hour to two hours of downtime.

Getting started now.

**Comment by larsdesigns** [comment]
Completed the following: 

1. Perform the OS upgrade to Debian Bullseye. 
2. I kept all of the custom configuration. 
3. There was a disabled Apache webserver that was installed and was giving error during the upgrade because the required version of python was not longer available. I remove Apache and everything seems fine. 
4. Checked to make sure .htaccess is working at: https://sanitize.backdropcms.org/
5. Logged into backdropcms.org and check the status page and the PHP info page. Everything looks okay to me. 
6. I checked to make sure the firewall rules for IPtables survived. 
7. I had made a complete linode VM snapshot before upgrading and a backup of `/etc/` just in case.
8. Checked docs.backdropcms.org comes up and the redirect from api.backdropcms.org is working. 
9. Checked the mail.log file for errors. I am investigating a small milter service warning. 

Overall, this seems to have been a successful upgrade. Please ping me on Zulip and/or post to this ticket if any issues come up.

**Comment by larsdesigns** [comment]
No further tasks. Closing...
