### ISSUE TITLE
Add 'external' icon to Docs link

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#863]
In the 'Support' sub-menu, the link to the forum has an icon after it, indicating that it's an external site. However the link to the Documentation site (in the same sub-menu) doesn't have such a link:

![image](https://user-images.githubusercontent.com/2385329/146671338-451597ab-2438-4140-a5ed-3b49daea0c60.png)

It seems the code that adds this link (in the Borg theme) wasn't updated for the Docs site renaming...

**Comment by BWPanda** [comment]
This has been fixed.
