### ISSUE TITLE
Set up New Relic on our server(s), so to be able to better troubleshoot issues

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#871]
This was mentioned during the 2022/01/27 weekly dev meeting: https://youtu.be/g3iGZWyaBOk?t=2064

New Relic [has a free plan](https://newrelic.com/pricing), which should be more than enough for our current and immediate future needs.

**Comment by klonos** [comment]
I've taken the liberty to assign this to you @larsdesigns 🙂

**Comment by larsdesigns** [comment]
I had setup newrelic a few years ago. The credentials are in the 1password account. As far as I know it is still running. It could use more checks and though.

**Comment by larsdesigns** [comment]
Should we go ahead and close this one or perhaps we can repurpose it to create more checks within the existing New Relic account?

**Comment by larsdesigns** [comment]
No further tasks. Closing...
