### ISSUE TITLE
`project_github_githubapi_payload()`  needs to specify webhook action on release

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#875]
That function responds to GH webhooks either on `push` to a repo (to check if the README is updated, to update the project node) and on `release` to start the process of creating project nodes, project releases, packaging, etc:
```
  switch ($event_name) {
    case 'push':
      ...
    case 'release':
```

But it turns out that although on `push` one webhook is fired, when you create a full release via the GH UI, **four** webhooks are fired:
- one with the `git ref` info
- a `created` webhook signifying youve created a new release (this fires for drafts, pre-releases and full releases)
- a `published` webhook (fired for pre-releases and full releases)
- a `released` webhook  (full releases)

We should decide if a project node should be created for pre-releases. If so then the code should be something like:
```
  switch ($event_name) {
    case 'push':
      ...
    case 'release':
      if ($payload['action'] == 'published') {
        // Continue ...
```
Or if a project node should only be created for full releases, in which case:
```
  switch ($event_name) {
    case 'push':
      ...
    case 'release':
      if ($payload['action'] == 'released') {
        // Continue ...
```
I think since we already use tags and semver to show our end-users that projects are alpha, beta etc, then pre-releases arent very helpful, but then if a dev creates a pre-release, perhaps he would expect a project node? Not sure.

Would like to hear what we think about this.

In either case, I suspect this explains why we get 3-4 watchdog messages (dont recall how many exactly) for each new release:
> [Successfully created release for token_embed_views 1.x…](https://backdropcms.org/admin/reports/event/2105006)
[Error creating release for token_embed_views 1.x-1.0.1.](https://backdropcms.org/admin/reports/event/2105608)
[Error creating release for token_embed_views 1.x-1.0.1.](https://backdropcms.org/admin/reports/event/2105608)

**Comment by docwilmot** [comment]
Replaced by https://github.com/backdrop-ops/backdropcms.org/issues/948

**Comment by quicksketch** [comment]
Thanks @docwilmot! Sorry I didn't find this issue in my searching!
