### ISSUE TITLE
CiviCRM: Fix .gitignore, restore vendors, add extensions, remove cruft from beta branch

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#886]
Currently the .gitignore file in the beta branch (containing CiviCRM) ignores  `vendor`, which means that the `civicrm/vendor` directory is not part of the repo (though it is on the server beta.backdropcms.org). This means that any local version based on the repo will be missing required files and will fail. So we need to remove that exclusion from .gitignore and restore the vendor folder to `civicrm/vendor`.

Also, there is a `civicrm.settings.local.php example` file in the repo that doesn't do anything and should be removed.

Also, we've added two extensions to the beta branch of CiviCRM, and those should be added to the repo.

PR to follow.

**Comment by larsdesigns** [comment]
@bugfolder, I created civicrm.settings.local.php to distribute instead civicrm.settings.php because it contains credentials.

**Comment by bugfolder** [comment]
I thought that might be the intention, but it isn't currently used, right? The credentials are currently in civicrm.settings.php, which is not part of the repo.

**Comment by bugfolder** [comment]
Maybe add at the beginning of civicrm.settings.php a check for whether civicrm.settings.local.php exists and include it if it does; and then edit the local file down to the bare minimum, so that it's easy for a local installation to see what needs changing?

**Comment by bugfolder** [comment]
^^I'm happy to put that together if you support the approach.

**Comment by larsdesigns** [comment]
I have made a commit and a pull request: https://github.com/backdrop-ops/backdropcms.org/pull/888

**Comment by bugfolder** [comment]
I might not have been clear in my description of what I was thinking for handling CiviCRM's settings file (which I think is applicable to Backdrop's as well):

* `civicrm.settings.php`
  * Goes in the repository
  * Contains **most** of the settings for the site, but nothing sensitive
  * At the beginning of the file, conditionally includes `civicrm.settings.local.php` if it exists
* `civicrm.settings.local.php`
  * Is **not** in the repository
  * Is .gitignored (so it won't be overwritten by `git pull`).
  * Contains all sensitive credentials (and, perhaps, definitions of local file paths)
  * Is edited down to contain the bare minimum of information and explanation, so it's not a duplicate of `civicrm.settings.php`, and it's easy for local dev sites to use their own version of this file.

The idea being that this keeps sensitive info out of the repo ("Don't Fear the Repo"), and it makes it easy to build and update the local dev site(s).

Make sense?

**Comment by larsdesigns** [comment]
@bugfolder, Yes, that sounds like a good plan and @jenlampton and I both worked on that model but found that CiviCRM is not accommodating it. If you would like to give it a try and create a working civicrm.settings.local.php that would be great. 

Otherwise, I am in favor of restoring the civicrm.settings.php.example file to the repository.

**Comment by bugfolder** [comment]
@larsdesign, I've got this approach working locally. I'd like to try it on beta.backdropcms.org, but it looks like I (user backdrop) don't have permissions to overwrite `civicrm.settings.php` or `civicrm.settings.local.php`. Can you adjust those permissions so I can try this? (Of course I'll keep copies of the original files to restore if needed. And I need to upload at least one of them, since the `.local.php` file won't ever be in the repo.)

**Comment by larsdesigns** [comment]
I have adjusted the permissions.

**Comment by jenlampton** [comment]
If your user can't delete the files due to permissions than git won't be able to update them either, running as you. So we need to fix the permissions issue.

**Comment by bugfolder** [comment]
This could become an ongoing issue, then, any time we

* download a new CiviCRM extension, or
* update an existing extension

from the UI. We should be able to avoid the issue going forward by being careful to only download/update extensions locally, commit them to the repo, then pull from the repo, and never use the server UI to download Civi extensions. (So, basically, treat Civi extensions like Backdrop modules.)

**Comment by jenlampton** [comment]
There's some way to set up permissions so that it will work.  It is possible to add Backdrop modules from the UI and then added to git without an issue. (I have a few of my sites on shared hosting doing this...)

I think...  as long as the web-user is part of the same group as the ssh user, and permissions are set appropriately for the group. 

That said, I think it might be a good idea to add and test things on not-the production site anyway, so maybe we do the same thing for beta?

**Comment by bugfolder** [comment]
I would expect we would add and test things locally before adding them to the repo, anyhow, right? But it would certainly be nice to have permissions set so that we could do either.

This raises a related issue. Assuming that it takes us a couple of months to figure out what we want with Civi, including things like CiviCRM extensions, perhaps a helper module added, when we eventually want to put Civi on b.org, will we want to merge all of beta branch into the main branch (which might have had its own commits since then), or create a new PR against main that contains all the repo changes we've added to beta? (Maybe a question for today's meeting.)

**Comment by larsdesigns** [comment]
@bugfolder, I will work on correcting the permissions. It should be completely writable for the backdrop user.

**Comment by larsdesigns** [comment]
I have corrected the file permissions including the `civi-ext` directory. Let me know if anything else comes up. 

Also, I need to setup the cron jobs for civi and I will see if I can get to that this evening.

**Comment by larsdesigns** [comment]
@bugfolder, I appreciate you taking on creating the civicrm.settings.local.php. Kudos!

**Comment by bugfolder** [comment]
Woo-hoo, everything is working! `git pull` was happy, beta.backdropcms.org is still alive and kicking. Thanks @larsdesigns for all the permissions-tweaking!

@larsdesigns, one last question: you said you wanted to keep `civicrm.settings.php example` in the repo. (It's not there now, but I kept a copy and could put it back if needed.) Can you say more about why? My thinking is that the existing `civicrm.settings.php` (which is in the repo) would fulfill the role of providing an example.

**Comment by larsdesigns** [comment]
A civicrm.settings.php that does not contain credentials would be fine to commit instead of the example file. I had written some instructions in the example file that may be help to place in the civicrm.settings.php file.

**Comment by bugfolder** [comment]
OK, thanks. I've put some instructions in the `civicrm.settings.local.php` file for how to localize, so I think we're now covered. Gonna close this issue.
