### ISSUE TITLE
Themes (perhaps all projects in general) listed twice.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#89]
https://backdropcms.org/themes?title=clean

![backdropcms org-themes_listed_twice](https://cloud.githubusercontent.com/assets/2423362/9426922/9ace9a56-49a2-11e5-91c1-89de921562dd.png)

Perhaps something to do with the fact that these are two different major versions of the same project or something.

It would be easier to spot such cases if projects were listed alphabetically. Which BTW raises the question: what are these views listings (modules/themes/layouts) sorted by by default?

**Comment by klonos** [comment]
Related: #90

**Comment by quicksketch** [comment]
> Perhaps something to do with the fact that these are two different major versions of the same project or something.

Yep, that was it exactly. I added a filter to the View to only include the current "recommended" major branch in the listing.

**Comment by klonos** [comment]
Thanx Nate.
