### ISSUE TITLE
Offer a way for visitors to sort projects by different criteria (alphabetical, core compatibility, recent release, most downloaded etc.)

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#90]
Would be nice to offer the same thing as in d.org where people can refine their search by various criteria:

![d org-module_search-sort_criteria](https://cloud.githubusercontent.com/assets/2423362/9426937/de6dc68c-49a3-11e5-862e-f50283861809.png)

Here's the [list of their module categories](https://www.drupal.org/project/project_module/categories) BTW in case we decide to be in parity with them (might also be useful for https://github.com/backdrop/backdrop-issues/issues/870).

**Comment by klonos** [comment]
#65

**Comment by BWPanda** [comment]
I'm going to close this in favour of https://github.com/backdrop-ops/backdropcms.org/issues/442
