### ISSUE TITLE
Module portal does not indicated that a version is unsupported

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/backdropcms.org#901]
The backdropcms.org module page doesn't currently indicate in any way when a module version is unsupported. See attached images. Entity Tokens version 1 is unsupported (meaning that people who have it installed are prompted to update to version 2). However, the portal still shows version one as "Other releases". 

It be great to either hide the unsupported version, or to somehow indicate that it's not supported.

<img width="1185" alt="Screen Shot 2022-03-23 at 9 55 41 AM" src="https://user-images.githubusercontent.com/9938978/159742432-42190059-059f-48f0-9e5c-e96acbd48a0f.png">

<img width="745" alt="Screen Shot 2022-03-23 at 9 55 50 AM" src="https://user-images.githubusercontent.com/9938978/159742459-9af01459-d690-4247-a72b-c480060b787d.png">

**Comment by bugfolder** [comment]
PR submitted that removes unsupported major versions from the "Other releases" downloads on the project page.

**Comment by bugfolder** [comment]
I've made this change directly to the `project_release_download_table` View (display "Other (main)"), so it's effective immediately in config `live-active`.
