### ISSUE TITLE
Block known spammers' IP addresses

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#903]
Follow-on to https://github.com/backdrop-ops/backdropcms.org/issues/815.

Since we installed the IP Address Manager module, we can now see some history on the IP addresses used by visitors, visible at Admin > User accounts > IP addresses. Any address in that list attributed to "Anonymous" is the address used by a spam account that has been deleted.

If one sorts the IP address list in order, you will see examples of duplicate IP addresses for multiple Anonymous users, in some places, several times in a row. This is a sign that there were multiple spam accounts created from that one IP address. Thus, we can cut down on spam accounts by instituting blocking of their IP address. (It won't catch all of them by any means, since there's a lot of solo IP addresses in that list as well.)

At the last outreach meeting, it was suggested that doing server-level blocking is more efficient than blocking within Backdrop. This is true, but at present, my understanding is that our overall traffic level is not high, and the blocking check in the IP Blocking module takes place in `hook_boot()`, so I would like to suggest that we go ahead and implement this blocking using the nearly-there solution provided by IP Blocking module, and then if it becomes evident that it makes a significant difference (so we want to keep it) and it degrades our response time (so we want a different solution), we can investigate changing the integration with a server-level solution.

Meanwhile, the IP Blocking solution is "nearly there," meaning that it needs to be integrated with `hook_form_alter()` and IP Address Manager modules to provide IP blocking as an option when an account is cancelled. I have a PR pending on the module (https://github.com/backdrop-contrib/ip_blocking/pull/13) that provides that integration. So my proposal here is to install the IP Blocking module, plus the patch from that PR (documenting the patch, of course), on backdropcms.org, and then, going forward, when spammers' accounts are deleted, block their IP address.

One of the reasons for selecting IP Blocking (versus Ban IP) is that IP Blocking keeps a log of blockage, which with this patch will include who did the blocking and which user account's IP was blocked, so that (heaven forbid) an IP address ends up blocked in error, it should be relatively easy to find the blockage and unblock.

**Comment by BWPanda** [comment]
Isn't it true that legitimate users can share the IP address of a spammer? I've seen and even experienced this myself when sending emails are blocked because an IP address has been blacklisted, affecting legitimate users and spammers together.

If the same is possible here, I recommend against this approach.

**Comment by bugfolder** [comment]
It is in principle possible, but pretty rare, I think, if blockage is done carefully. On a site I manage where spammers had been a problem, we implemented blocking based on a collection of curated known-bad characteristics, and then on the "this IP has been blocked" page give a contact info if the person thinks they've been blocked in error, and have never had a situation where someone complained via the contact link and the blockage had happened due to shared IP.

**Comment by albanycomputers** [comment]
On a website I created that recently went live... I added a telephone number field... with up to 5 numbers.  I've noticed that all spam accounts always fill in all of the 5 numbers...  This may be another solution to filter spam accounts to make it easier to identify them. In the UK phone numbers always start with a zero... while spam accounts have random numbers... so for us, it's easy to identify them.

I'm not saying use the phone number on BG... but having a field with multiple entries allowed, especially where normally only one entry is needed may help identify them and a view could easily be created to search for multiple entries.

**Comment by findlabnet** [comment]
@albanycomputers you can try something simple, but working well for me: https://github.com/findlabnet/anti_bot

**Comment by bugfolder** [comment]
We'll be collecting address information soon (when CiviCRM is in place), which then gives a lot of fodder for spam detection (or at least, quarantine).

On a site I manage, one of the best spammer-detection schemes is to collect separately first, middle, and last names. A high proportion of spammers fill in the same name for first and middle; very few real people do that (though it is not entirely unknown).

**Comment by stpaultim** [comment]
@bugfolder - Is SPAM still enough of an issue that you would be advocating for this change?

**Comment by bugfolder** [comment]
@stpaultim, maybe. In the last few weeks, we've made some changes to improve spam filtering (only two this morning). We're now collecting data  to see how much repeat-spamming from the same IP addresses is going on. If there's much, then yes, I'd still advocate. If not, then no I won't. Let's check back in a few weeks after we have some data. (If you want to watch progress, visit the Admin > Content > IP Addresses tab.)

**Comment by bugfolder** [comment]
We've now got a few months of the IP Demerits module's record of IP addresses that created accounts that ended up being blocked (so probably spam accounts). Only two IP addresses ever created more than two spam accounts. So that tells me that blocking IP addresses wouldn't add significantly to the anti-spam tactics we're already employing. Closing this issue and its PR.
