### ISSUE TITLE
CiviCRM: needs cron job on beta.backdropcms.org

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#906]
...and, eventually, of course, backdropcms.org.

Currently, the CiviCRM status page for beta.backdropcms.org shows that Civi's own cron job has not been set up:

https://beta.backdropcms.org/civicrm/a/#/status

Documentation for CiviCRM cron is here (no Backdrop-specific instructions yet): 

https://docs.civicrm.org/sysadmin/en/latest/setup/jobs/#url-to-cronphp

There are problems with using HTTP to run the cron job, detailed here:

https://lab.civicrm.org/dev/backdrop/-/issues/8

Haven't yet tried the other methods (`cv`, `drush`, `cli.php`). Input from anyone who has successfully set up CiviCRM cron on a Backdrop site would be most appreciated here!

**Comment by bugfolder** [comment]
As noted in [this CiviCRM issue](https://lab.civicrm.org/dev/backdrop/-/issues/8), there are problems with the usual command-line implementation of CiviCRM's cron job with Backdrop. There are two PRs pending that should fix the problem, but based on past experience, I won't hold my breath on their getting incorporated any time soon.

Tested the [CiviCRM Cron](https://backdropcms.org/project/civicrm_cron) module locally, and it works just fine. I'm going to suggest we just install this module, which ties Civi's cron job to Backdrop's.

**Comment by larsdesigns** [comment]
@bugfolder, I completed the following tasks: 

1. Reviewed the pull request #911. 
2. Merged the pull request into the beta branch. 
3. Performed a `git pull origin beta` on beta.backdropcms.org. 
4. Enabled the module on beta.backdropcms.org.
5. Verified that the site key is loading in the settings form: https://beta.backdropcms.org/admin/config/civicrm/civicrm-cron
6. Verified that the cron job has run at https://beta.backdropcms.org/civicrm/a/#/status `Last cron run at July 9th, 2022 1:12 AM.`

I noticed some other security messages in the status report. I will see if I can clean them up.

**Comment by bugfolder** [comment]
Thanks for all that. I see that CiviCRM 5.51.0 is out, so I expect Eric will be upgrading us shortly, which will eliminate the security warnings related to the version number.

As for the "files should not be downloadable" on the status page, I guess we'll have to move some of Civi's files out of the default file system and update their location at https://beta.backdropcms.org/civicrm/admin/setting/path?reset=1.

**Comment by larsdesigns** [comment]
For the cron job (this issue) should we go and close it?

**Comment by bugfolder** [comment]
Cron is running, so, sure.
