### ISSUE TITLE
Improve "Config Workflow" instructions

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#917]
There are some unclear aspects in the current description of preparing a PR that involves config changes, found at [config/README.md](https://github.com/backdrop-ops/backdropcms.org/blob/main/config/README.md).

* The instructions for "Updating `live-active`" indicate that after "making sure `live-active` is up to date per step 2", the contents of `live-active` and `staging` will be the same. However, this is not necessarily the case after doing the check of Setup, step 2.

* If `live-active` is the same as `staging`, then step Setup, 3 is superfluous.

* Conversely, if `live-active` and `staging` are not the same, then following the current procedure, after "Make your changes" step 4, there can be altered files in `staging` that have nothing to do with the changes one is attempting to make, but instead are a result of discrepancies between `live-active` and `staging.` Here's how that happens:
    - Setup, step 3 puts `live-active` into staging
    - Setup, step 4 moves that copy into `dev-active`
    - Make your changes, step 3 moves that copy into staging (so staging has been replaced by a modified version of `live-active`).
    - So now `staging` will contain the changes you made, PLUS all of the differences between `live-active` and `staging`.

I have a suggested rewrite of the README.md file that explicitly takes into account the possibility that `live-active` and `staging` are not identical after step 2. If they are the same, the procedure is a bit more streamlined; if they're not the same, I think the proposed procedure works.

As long as I'm updating the instructions for working on BackdropCMS.org, I've also added a file describing how to do a core update and handling patches, since that's easy to overlook.

**Comment by jenlampton** [comment]
I don't understand the problem. Here's what I read from above (and the status after --)

* Setup, step 3 puts live-active into staging  -- 2 identical directories (live/staging)
* Setup, step 4 moves (actually *copies*) that copy into dev-active -- 3 three identical directories
* Make your changes, step 3 moves (actually *copies*) that copy BACK into staging  -- 2 identical directories (dev/staging), and the 3rd (live) contains the original

> I have a suggested rewrite of the README.md file that explicitly takes into account the possibility that live-active and staging are not identical after step 2

This should never be the case? We should't ever have a PR that starts with these directories not being identical...

**Comment by bugfolder** [comment]
Sorry, I guess I was unclear in what I was trying to accomplish. I agree that the PR should start with those directories being identical. What I was trying to address was that when you do Setup, Step 2 ("check that live-active is an exact match"), that directs the user to "Updating live-active" (at the bottom of the README file). whose first two steps are:

1. On Backdrop's live server, perform a git status to see if there are any uncommitted changes to the live-active config directory.
2 If there are no uncommitted changes, skip to step 5.

So this can result in live-active not being identical to staging, if there are stale differences in staging.

But yeah, I see that Setup step 3, "copy from live-active to staging," will get rid of those. So maybe I'm over-complicating things with the multiple cases.

Let me do some more rewriting, see if I can streamline it but still put more description into it.

**Comment by jenlampton** [comment]
> So this can result in live-active not being identical to staging, if there are stale differences in staging.

Live active should still always be identical to staging. 
If there are stale differences in staging those can be committed at this point:

> On Backdrop's live server, perform a git status to see if there are any uncommitted changes to the live-active config directory. 
> If there are no uncommitted changes, copy all of live-active into staging, and then perform a git status to see if there are any uncommitted changes.  If there are no uncommitted changes, skip to step 5.

Or, as I prefer to do it, on your local site, as in the steps noted in the previous comment:

1) Setup, step 3 puts live-active into staging -- 2 identical directories (live/staging) **commit here**
2) Setup, step 4 moves (actually copies) that copy into dev-active -- 3 three identical directories 
3) Make your changes, step 3 moves (actually copies) that copy BACK into staging -- 2 identical directories (dev/staging), and the 3rd (live) contains the original

**Comment by bugfolder** [comment]
As I thought more about this, I realized what part of my problem is. When trying to create a PR on a specific issue that involves config, we want the config changes to staging in the PR to relate only to that issue (I think; right?). 

In the current instructions, since we copy `live-active` to `staging`, if there are any `live-active` configurations that haven't yet been copied to staging, they'll be rolled into the PR—which might be on an entirely unrelated topic.

So in the last section, "Updating `live-active`", shouldn't the person either (a) always copy `live-active` to `staging`, then commit both (steps 3–5)? Or at least check to see if there are any differences between `live-active` and `staging`, and if there are, then do steps 3–5?

**Comment by jenlampton** [comment]
That would make the PR easier to read!  As long as the two actions are done
in two separate commits, it's still possible to tell the new changes from
the sync. It's not strictly necessary, but could be recommended (like here
in docs!)

I always do my config commits separately, which I know leads to lots of
commits (so is not everyone's preference).

**Comment by bugfolder** [comment]
Yes. I think two commits are preferable in most cases, because different conditions apply when someone is preparing a PR:

* The `active`-to-`staging` changes should always be committed and merged immediately, because it's fixing an existing inconsistency in the site.
* The changes that are part of the PR might need review, might stick around for a while getting modified (case in point: this PR!), and might not even be applied (if someone fully objects to the proposed change).

I'll take another crack at this PR to make this distinction.

**Comment by bugfolder** [comment]
Instructions updated. Please take another look at the new version.

**Comment by jenlampton** [comment]
These read clearly now, thank you :)

When on the live server I usually want to commit everything before I make any changes (because I might accidentally delete live-active one day instead of staging). So my steps would be:

1) On Backdrop's live server, perform a git status to see if there are any uncommitted changes to the live-active config directory.

2) If there are no uncommitted changes, skip to step 5.

4) Commit any changes to `live-active`. 

3) Copy the contents of the `live-active` directory into the `staging` directory. The best way to do this is to first delete everything in `staging`, then copy `live-active/*.json`. The json files in these two directories need to be an exact match.

4) Commit the changes to `staging`.

5) Inform the user that live-active is up-to-date.

Hence the extra/messy commits :)

**Comment by bugfolder** [comment]
Thanks. I'll go ahead and merge the PR (and then strive to follow it the next time!).

I still always feel like I'm walking on eggshells working with the dance between config, git, local, and prod.
