### ISSUE TITLE
CiviCRM: private CiviCRM files are downloadable

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#929]
On beta.backdropcms.org, [CiviCRM's status report](https://beta.backdropcms.org/civicrm/a/#/status) is issuing warnings about the direct downloadability of some files that ought to be private. Presumably, the .htaccess files in those directories need adjustment.

Ping @larsdesigns, @jenlampton.

 ![civicrm_status_warning](https://user-images.githubusercontent.com/29214084/186213963-354e7c3e-6a71-4d0b-bfa7-11c829e6bd9b.jpg)

**Comment by jenlampton** [comment]
this is an nginx server, so it's likely the `.htaccess` files are correct (but won't be used). We will need to implement something similar in our server configuration instead.

**Comment by larsdesigns** [comment]
Okay, I will have a look at this.

**Comment by bugfolder** [comment]
This is still the case on beta.backdropcms.org, but doesn't seem to be the case on backdropcms.org.

**Comment by larsdesigns** [comment]
I have corrected the messages on backdropcms.org and I am working on the corrections for beta.backdropcms.org.

**Comment by larsdesigns** [comment]
I have made the configuration changes on the beta.backdropcms.org server. The messages are not longer displaying. 

This is ready for review.

**Comment by bugfolder** [comment]
Looks good, thanks!
