### ISSUE TITLE
CiviCRM: Define and create mailing list groups

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#931]
One of the first uses of CiviCRM could be creating multiple mailing list groups that people could sign up to receive various mailings. Details in the following comments.

**Comment by bugfolder** [comment]
One of the first uses of CiviCRM that we've discussed is to create multiple mailing list groups that people could opt into in order to receiving mailings on a particular topic, and/or indicate an interest in helping out in particular ways. Possibilities include:

* Receiving the newsletter
* Being informed of Backdrop LIVE
* Helping out with Backdrop LIVE
* Helping with other volunteer activities
* ...

We can create various opt-in groups, list them on the user registration page, list them as a sub-tab of the user account edit page, and use them for targeted mailings via CiviMail (that is, once CiviCRM's outgoing mail is fully configured, see https://github.com/backdrop-ops/backdropcms.org/issues/930).

We could make one of the groups the desire to receive the newsletter, and then let that replace the "Sign up for newsletter" block that's currently on the bottom of the user registration page.

And we could also expose the "No bulk emails (User OPT OUT)" field to let people entirely opt out of bulk emails.

I would suggest that we put the group settings into their own separate profile, so that they show up as a separate sub-tab of the user account edit page (the way the "Name and Address" profile currently is a separate sub-tab). Once that is done, there will likely be some CSS needed to make the formatting consistent between CiviCRM's attempts and the BackdropCMS theme's attempts at formatting these elements.

But before we get to that, we should define what groups we want at the outset. So the next step of this task would be for people to identify what mailing list group(s) (if any) we should create. Ideally, provide a group name and one-line description of the group (which is what would then be displayed on the user registration form and the user account edit page).

**Comment by stpaultim** [comment]
Here is my first pass, I'm sure I'm missing something. 

Newsletter
Event Updates
Contribution - Core
Contribution - Contrib
Contribution - Design
Contribution - Marketing/Outreach

**Comment by bugfolder** [comment]
From Jen: Receive security updates

**Comment by stpaultim** [comment]
I added "Security Updates" to my list. 

I also added "Office Hours". I have mixed feelings about this one. I think that there are some folks who might be happy for regular updates/reminderes on office hours. However, this might be used too frequently to mix it with the Event Updates.

I'd be ok skipping "Office Hours" at least for now and seeing how things go with the others first.

**Comment by bugfolder** [comment]
I've set up the initial groups above and put them into a Profile titled "Mailings".

As a byproduct, I had to configuration some mailing-related settings, which [I did here](https://beta.backdropcms.org/civicrm/admin/setting/preferences/mailing?reset=1). Changes from default values:

* Turn off "Enable Double Opt-in for Profile Group(s) field" (so that the Profile doesn't need to have a redundant email field)
* Turn off "Enable click-through tracking by default"
* Turn off "Enable open tracking by default"

You can see the selection form by going to your user account, clicking the Edit tab, then the Mailings sub-tab.

@stpaultim, could you suggest some descriptions for for the four Contribution groups?

Incidentally, it looks like the order in which the groups are presented is alphabetical. I don't think there's a way to rearrange their order.

**Comment by bugfolder** [comment]
@stpaultim, per the previous comment, could you provide description of the four "Contribution" groups you requested? They're the TBD ones [listed here](https://beta.backdropcms.org/civicrm/group?reset=1).

**Comment by bugfolder** [comment]
Done and implemented on b.org.
