### ISSUE TITLE
Drawer for Modules / Themes / Layout

### ISSUE THREAD

**Issue by wesruv** [backdrop-ops/backdropcms.org#94]
Having Modules / Themes / Layouts in the top level of the nav is a bit odd, thinking we could do a drawer. Suggestions below...

**Comment by wesruv** [comment]
Extend Backdrop
Projects
Components
Add-Ons
Contributed Projects
Contributed Code

**Comment by klonos** [comment]
Although "Projects" might make perfect sense to us long-time users of Drupal/Backdrop, I think that something like "Extend Backdrop" might make more sense to newcomers and is in tandem with the "Extend Drupal" sub-section of the download section of D.org.

**Comment by serundeputy** [comment]
Extend Backdrop++;

**Comment by docwilmot** [comment]
Extend Backdrop

**Comment by quicksketch** [comment]
Pictures of our current sidebar and the proposed "Extend Backdrop"

Current:
![screenshot4](https://cloud.githubusercontent.com/assets/100206/9537017/36d4aad8-4ce8-11e5-8160-a14b637d011c.png)

Proposed(?):
![screenshot5](https://cloud.githubusercontent.com/assets/100206/9537018/421922a2-4ce8-11e5-952a-877c83f9fffd.png)

This would probably look a lot better if Modules, Themes, and Layouts links were horizontally even with the "Extend Backdrop" item, but that's a bit more on the tricky side (in the event that a window isn't tall enough or there is a scrollbar present).

The search box is there from our current drawer (under handbook). That should probably be integrated in some way also, or omitted.

**Comment by quicksketch** [comment]
It would be great if the theme designer @dariusgarza could give an opinion here as well.

**Comment by docwilmot** [comment]
I know I agreed with "Extend Backdrop" but two queries:
- Are we not concerned about the "noun vs verb" difference with the menu items? 
- Is the "Backdrop" a bit superfluous here? What else could we possibly be extending?

And, hijacking this thread, sorry, the "Resources" link in the Handbook, should have its own front page menu link, possibly renamed as "Support". And "Press Kit" should be in the handbook.

**Comment by sutibun** [comment]
Here is what's currently up
----

![original](https://cloud.githubusercontent.com/assets/14132746/10063468/a629a248-6233-11e5-8cf7-4655b7fdf926.png)

Not bad.

My thoughts plus suggestions:
------

First, I've adjusted the actual drawer slightly. Not sure if that's any good but main focus is on the name.

1. **"Extend Backdrop"**
    
    ![extend-backdrop](https://cloud.githubusercontent.com/assets/14132746/10063502/1c9c8f94-6234-11e5-87b9-fa9f99016c2b.png)
    - Initial reaction is "Extend Backdrop" looks ugly. Almost out of place. Not sure why. Maybe because I see "backdrop" above and below. 
2. **"Extend"**
    
    ![extend](https://cloud.githubusercontent.com/assets/14132746/10063541/963d093c-6234-11e5-8b13-3abb16e479e2.png)
  - To me, this has an almost elegant look. I like "Extend" by itself. I'm not too concerned with noun vs verb. As long as it isn't confusing
3. **"CMS Extensions"**
    
    ![cms-extensions](https://cloud.githubusercontent.com/assets/14132746/10063551/d3aa46fe-6234-11e5-9a27-fe94e29bd833.png)
  - It's ok. Why suggest it?
        1. It's a noun so there is consistency.
        2. Boost SEO friendliness. Haven't done an extensive SEO site audit but initial impression of bcms.org is it's lacking. Site doesn't appear for search phrases like "CMS". SEO is one way to freely garner attention. This menu name will help a bit in that regard.

What gets my final vote?
-------

I go for number two: "Extend"

However, taking into consideration SEO-purposes, how about appending CMS to backdrop. However, deemphasizing it. In the short time I had, I didn't get the visual correctly but something like below

![final](https://cloud.githubusercontent.com/assets/14132746/10063783/0a7e4908-6237-11e5-8e76-33d7293c3b36.png)

Except what I had in mind was "cms" on the line below and aligned right. (smaller font size) Just like you tend to see the Trademark symbol (tm) above, "cms" can be a little bit below.

Just an idea

**Comment by docwilmot** [comment]
Has this fallen off the radar?

**Comment by serundeputy** [comment]
we are no longer using drawers in the new design.
closing.
