### ISSUE TITLE
CiviCRM: Workflow for bringing up CiviCRM on b.org

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#941]
The various tasks to bring up CiviCRM on backdropcms.org are distributed among various in-progress tasks in [our GitHub project](https://github.com/backdrop-ops/backdropcms.org/projects/3). It would be useful to have everything in one place, as a step-by-step workflow for bringing up CiviCRM and doing all the configuration that we've worked out over the past many months. So I'm creating this issue and will put the workflow in the next comment (and edit, as needed).

I think we're pretty close to ready to roll, but it would be nice to get some eyes on the listing to see if anything is apparently missing.

**Comment by bugfolder** [comment]
Workflow follows. Review and input solicited from @jackaponte, @larsdesigns, @laryn, @jenlampton, @ericfg, @cellear, @stpaultim, @oadaeh (and anyone else who's been involved in this project who I may have missed).

# CiviCRM import and setup process

## Update BackdropCMS to latest CiviCRM version

CiviCRM releases new versions monthly (and sometimes bugfixes during the month), so we should start the process of putting CiviCRM on backdropcms.org by adding the latest version of CiviCRM to the server codebase.

To match what's on beta.b.org, it should be at `www/modules/civicrm`. Also create 

* the extension directory at `www/civi-ext`
* the custom templates directory at `www/civi-templates`

These will be under version control.

Then run the CiviCRM installer.

Check the Resources settings at CiviCRM > Administer > System SEttings > Resource URLs. They should be:

* CiviCRM Resource URL: [civicrm.root]/
* Image Upload URL: [civicrm.files]/persist/contribute/
* Custom CSS URL: _leave blank_
* Disable CiviCRM css: No
* Force Secure URLs (SSL): No
* Verify SSL Certs: Yes
* Extern URL Style: Prefer normal router

Check the Directory settings at CiviCRM > Administer > System Settings > Directories. They should be:

* Temporary Files Directory: [civicrm.files]/upload/
* Image Directory: [civicrm.files]/persist/contribute/
* Custom Files Directory: [civicrm.files]/custom/
* Custom Template Directory: [cms.root]/civi-templates
* Custom PHP Directory: _leave blank_
* Extensions Directory: [cms.root]/civi-ext/


## Configuration

Most of CiviCRM's configuration information is stored in the CiviCRM db, so we'll need to manually configure things like profiles, groups, etc., on the production server in the same way we did on beta.b.org during setup/evaluation.

Start configuration by converting all existing users to CiviCRM contacts, link them via the `civicrm_uf_match` table, and copy user account fields into corresponding CiviCRM contact fields.

## Synchronize Backdrop user accounts to CiviCRM contacts

[See here in the User Guide.](https://docs.civicrm.org/user/en/latest/initial-set-up/users-contacts/#synchronize-users-to-contacts_1)

Go to CiviCRM > Administer > Users and Permissions > Sychronize users to contacts. This will create contacts for all user accounts, but that doesn't include the data from the user accounts.

However, on my local, this times out (max execution time = 300) after 638 contacts, and there are 5907 user accounts.

There doesn't appear to be a command-line equivalent of this action (not in api3, api4, or cv). Or a way to throttle it to a certain number of attempts.

2nd attempt stops at a total of 1291 contacts, so we could do repetitive runs. Or set PHP's `max_execution_time` temporarily.

Can't seem to affect timeout time (even editing php.ini). But repeatedly restarting the command after it times out eventually gets through them all. So we can do that.

(Turns out that was only a limitation on the local machine; the beta.backdropcms.org server manages this conversion all in one go, see below.)

Note that it puts the Username into the "Nickname" field of the account.

If you did multiple runs, do a Search for duplicates, then do a batch merge to merge possible duplicate contacts created if a partial contact creation timed out.

**Notes**

In `civicrm/CRM/Utils/System/Backdrop.php`, function `synchronizeUsers()`, there is `set_time_limit(300)`. This looks like the thing to patch to avoid this limit.

Even better. Set `max_execution_time = 5000` in php.ini, then run `drush civicrm-sync-users-contacts`, and it all goes through.

Wasn't necessary to change `max_execution_time` on beta.backdropcms.org.


## Export user account data from Backdrop

User account fields to move into CiviCRM:

* Full name (which will become Last Name in CiviCRM; First Name will be blank.)
* Email address
* Street
* City
* State
* ZIP code
* Country

To do this:

* Install Views Data Export module.
* Create a View, `Users to CiviCRM` to export a CSV table consisting of these account rows:
    * Email
    * First name (use Global Text, leave blank)
    * Full name (label = Last Name)
    * Street address
    * City
    * State
    * Postal code (label = Postal code)
    * Country
    * Uid (label = External identifier)
* Export the table of users.

## Import user account data into CiviCRM

Import the table into CiviCRM at CiviCRM > Contacts > Import Contacts, with:
    * For Duplicate Contacts: Update
    * Dedupe Rule: Email (reserved) - Unsupervised

This will put the User account fields into the right corresponding contact records.

There are 229 import errors (which will be skipped) when we include full location information. By far the majority of them are from Vietnam (and many also have problematic names). A very small number might be "real", though. Nevertheless, skipping these records will just leave their CiviCRM information blank (beyond their names). So no harm in skipping them (even if there are a few non-spammers tucked away in the group). If they belong to a real person, that person can fill in their data fields if they ever edit their user account again.

This is done using the batch processing, so it should in principle go through in a single run without timeouts, but some of the individual steps still issue timeout errors after 30 seconds (on my local site).

** Notes**

But we can reduce the batch size. In file `civicrm/CRM/Parser.php`, function `CRM_Parser_Import::queue()`, set `$batch_size = 25` instead of the current value of 50 and re-start the import from scratch.

Wasn't necessary to reduce the batch size on beta.backdropcms.org.


## New user registration page

CiviCRM automatically creates a Profile for the user registration page, titled "Name and Address," containing:

* Email (primary)
* Full Name (Individual)
* Street Address (Home)
* City (Home)
* Postal Code (Home)
* Country (Home)
* State (Home)
* Group(s)

We can/should remove the corresponding User account fields (Location group) after copying the data into CiviCRM.

Note that we should edit the field labels to remove the parenthesed qualifiers from the display.

This profile information is displayed by default on the user page.

This information should not be visible to anyone. If we use standard permissions, then it's visible to the user, but not to other non-admins.

## Add custom module

A somewhat user-unfriendly aspect of CiviCRM's default profile handling is that this profile information is on its own edit page, at `http://beta.backdropcms.org/user/%/edit/name_and_address`, accessible via a "Edit Name and Address" link on the view page, but not via the Edit tab (which is where I would expect it). And it has the admin theme (Seven), rather than the public theme, like the regular user edit page.

To fix this, we need some code, which is implemented via a new custom module, `borg_civicrm`, which implements some hooks:

* `borg_civicrm_admin_paths()` sets the CiviCRM profile edit pages to render in the front-end theme;
* `borg_civicrm_menu_alter()` makes the CiviCRM profile edit pages sub-tabs of the main user edit page;
* `borg_civicrm_module_implements_alter()` ensures that our `hook_menu_alter` runs after CiviCRM's.

Custom module is added in [issue 927](https://github.com/backdrop-ops/backdropcms.org/issues/927) via [PR 928](https://github.com/backdrop-ops/backdropcms.org/pull/928) and subsequent updates to the module.

We also implement some custom CSS, which is in a file `css/borg_civicrm.css` in the `backdropcms` theme; added in [Issue 932](https://github.com/backdrop-ops/backdropcms.org/issues/932), [PR 933](https://github.com/backdrop-ops/backdropcms.org/pull/933).

## Mailing groups

We create mailing groups from the get-go (which are under CiviCRM > Contacts > Manage groups) with these access settings:

User and User Admin Only (only administrators can add/remove contacts):

* Administrators
* CiviCRM Team
* Contrib

See beta.backdropcms.org for description text.

Expose publicly (users can choose to join/leave):

* Contribution - Contrib
* Contribution - Core
* Contribution - Design
* Contribution - Marketing/Outreach
* Event Updates
* Newsletter
* Security Updates

See beta.backdropcms.org for description text.

Also configure Mailing preferences at `civicrm/admin/setting/preferences/mailing`:

Changes from default values:

* Turn off "Enable Double Opt-in for Profile Group(s) field" (so that the Profile doesn't need to have a redundant email field)
* Turn off "Enable click-through tracking by default"
* Turn off "Enable open tracking by default"

[See comment on issue 931.](https://github.com/backdrop-ops/backdropcms.org/issues/931#issuecomment-1232253072)

## Mailings profile

In additional to the CiviCRM-created profile, we create a second profile specifically for mailings, titled "Mailings" for "Mailing list groups and settings". It contains these fields:

* Contacts | Groups
* Contacts | No Bulk Emails (User Opt Out)

See beta.backdropcms.org for the wording of the field pre-help.

Check the "Backdrop User Registration" and "View/Edit Backdrop User Account" options for the profile.

When we're done, the user edit tab at `user/N/edit` will have three sub-tabs:

* Settings (which is the Backdrop-specific settings)
* Name and Address (CiviCRM's name and address profile)
* Mailings (CiviCRM's mailing group settings)

## Permissions

There is a new role, "Civi Admin". Need to give that role all CiviCRM permissions.

Note that "Developer" role should always have all permissions.

Need to give "Authenticated" these CiviCRM permissions:

* view my contact
* edit my contact

Both Anonymous and Authenticated should have these CiviCRM permissions:

* access uploaded files
* profile create
* profile edit
* profile viww
* access all custom data
* register for events
* view event info
* view event participants
* make online contributions
* access CiviMAil subscribe/unsubscribe pages

## Remove user account fields

We can now remove Backdrop user account fields that are (now) duplicates of those in CiviCRM, found at `admin/config/people/manage`.

* Full Name (`field_name`)
* Location (`field_location`)

## Import the Newsletter listing

In this step, we'll import the Newsletter recipients into CiviCRM, creating contact records, and then assign them to the Newsletter group (which is a mailing list).

Get the latest CSV export file from our current Newsletter email provider.

The CSV columns are:

* CONTACT ID
* EMAIL
* LASTNAME
* FIRSTNAME
* COUNTRY
* DOUBLE_OPT-IN
* OPT_IN
* ADDED_TIME
* MODIFIED_TIME

We'll discard most of these columns, except the email, and we'll create a new "Full name" column from the existing LASTNAME and FIRSTNAME columns (by concatenating them with a space). So, we'll do some editing. Convert CSV to an editable form (e.g., .xlsx), and create a new file with just two columns:

* EMAIL
* FULLNAME

where FULLNAME = CONCAT(FIRSTNAME, " ", LASTNAME). 

Most of the names will end up blank (or rather, a single space). We don't want to overwrite existing names for existing contact with blank values, so sort the file by FULLNAME, then split it into two parts, one with names, one without; we'll import them separately.

Examine the one with names and delete (or edit) any entries with bogus names, like "NFL-FREE-Houston Texans vs Miami Dolphins Live Stream NFL Texans vs Miami Dolphins Live Stream NFL 2018" (which is a real value in our list).

Import the table into CiviCRM at CiviCRM > Contacts > Import Contacts, with:
    * For Duplicate Contacts: Update
    * Dedupe Rule: Email (reserved) - Unsupervised

Map EMAIL to Email (primary) and FULLNAME to Last Name. Click to proceed.

On the Preview (step 3 of 4) page, expand the "Add imported records to existing group(s)" section and select the "Newsletter" group.

Then click Import Now. Repeat for the second table. Both tables should import successfully.


## Set CiviCRM scheduled jobs

Initially, the only scheduled jobs that need to be enabled (at CiviCRM > Administer > System Settings > Scheduled Jobs) are:

* CiviCRM Update Check
* Clean-up Temporary Data and Files
* Send Scheduled Mailings
* Send Scheduled Reminders
* Validate Email Address from mailings

Note that as we add functionality, we may need to enable some of the other scheduled jobs.

## Install CiviCRM extensions

We install these extensions in addition to the CiviCRM default extensions (at CiviCRM > Administer > System Settings > Extensions):

* AirMail (used for bounce processing, see configuration at CiviCRM > Mailings > Airmail Configuration)
* FlexMailer
* General Data Protection Regulation

The GDPR extension has a ton of settings (at CiviCRM > System Settings > GDPR). Still TBD is what values we want to fill in for those.

## Configure Sendgrid bounce handling

Need to update Sendgrid so that it passes bounce information back to CiviCRM.

This start by configuring the Airmail extension to receive and process bounce information sent by Sendgrid. Go to CiviCRM > Mailings > Airmail Configuration, and set:

* External SMTP Service: SendGrid
* Secret Code: _enter a 16-character random string_

Save the configuration. Record the URL from the Airmail Event Notification Configuration (which is going to be https://backdropcms.org/civicrm/airmail/webhook?reset=1&secretcode=_the secret code_).

Then log into SendGrid.

Enter the Airmal Event Notification URL at the appropriate place.
Follow SendGrid's instructions for modifying DNS records (adding CNAMEs)

In Sendgrid:

Go to [Mail Settings](https://app.sendgrid.com/settings/mail_settings) and select "Event Webhook".

* Authorization method: None
* HTTP Post URL: _the URL from the AirMail extension_
* Events to be posted:
    * Dropped
    * Bounced
    * Opened
    * Clicked
    * Unsubscribed

[See Issue 930 for further details](https://github.com/backdrop-ops/backdropcms.org/issues/930#issuecomment-1230937718) and [PR 934](https://github.com/backdrop-ops/backdropcms.org/pull/934) for code changes.

## Update CiviCRM mailing settings

Set CiviCRM to use our SMTP provider, SendGrid, at CiviCRM > Administer > System Settings > Outbound Email (SMTP/Sendmail):

Under "General", set "Allow mail from logged in contact" to "No" (we don't want users attempting to send emails from their own address via our SMTP provider).

* Select Mailer: SMTP
* SMTP server: smtp.sendgrid.net
* SMTP port: 587
* Authentication: yes
* SMTP username: apikey
* SMTP password: _enter the appropriate password_

Verify by clicking the "Save & Send Test Email" button.

**Comment by bugfolder** [comment]
This is mostly done: CiviCRM is now installed and mostly configured on b.org. There's a few missing pieces:

* Need to set up CiviCRM's cron job. This is under way (working with @larsdesigns).
* Still need to configure Sendgrid's bounce handling. (This will matter once we start sending out CiviMails.)
* There is a bug (?) in that the CiviCRM status page is coming up blank. I'll dig into this further.
* Something is amiss in the profile settings: on the user profile page, the Subscriptions settings are hyperlinked to bad links. They're not on beta.backdropcms.org (so they're behaving there), but it's not clear yet what's different.

**Comment by bugfolder** [comment]
Woo-hoo. Turns out that the SearchKit CiviCRM extension was automatically installed during CiviCRM installation of 5.55.0 (but hadn't been automatically installed on beta.backdropcms.org), and that was causing both of the problems listed above. Disabling the SearchKit extension solves both the blank status page issue and the CiviMail issue.

**Comment by laryn** [comment]
- I think it would be good to register the site.
 - For Geocoding, we can also consider this extension and avoid needing to use Google:
   https://github.com/eileenmcnaughton/org.wikimedia.geocoder
 - I also think switching to CiviMail might make sense and may be able to do some help on a basic header/footer.

**Comment by bugfolder** [comment]
> I ... may be able to do some help on a basic header/footer.

@laryn, please go ahead (if you have the relevant access). We're not sending any mailings out yet, but may well do so soon.

**Comment by bugfolder** [comment]
> For Geocoding, we can also consider this extension and avoid needing to use Google:...

I've tried [org.wikimedia.geocoder](https://github.com/eileenmcnaughton/org.wikimedia.geocoder) out locally; works nicely. I'll install it on b.org.

**Comment by bugfolder** [comment]
@laryn, @jenlampton, after org.wikimedia.geocoder failed to install on b.org and some subsequent investigation, I found the issue: the b.org repo was gitignoring .sql files, thinking (per a comment in .gitignore) that they were backups. But CiviCRM contains lots of functional .sql files. (Including org.wikimedia.geocoder, which was why it was failing to install: those files had been ignored, so weren't on the server.) So I've removed ".sql" from the repo's .gitignore paths, and then committed all of the missing .sql files that were part of CiviCRM and its extensions. And this allowed org.wikimedia.geocoder to be installed, so it's now doing it's thing on b.org.

Incidentally, the repo's .gitignore also include the path "modules/contrib/devel", which was presumably intended so local copies could use the devel module. If that's the case, that path should be "www/modules/contrib/devel", so I made that change, too.

**Comment by jenlampton** [comment]
Do we need geocoding on b.org? I don't think we have any features that use
it. Seems like a lot of unnecessary bloat?

**Comment by jenlampton** [comment]
Also, good catch on devel. I expect that .gitignore was intended to be in
the web root, and was either moved or copied to the git root at some point.

**Comment by bugfolder** [comment]
> Do we need geocoding on b.org? I don't think we have any features that use
it. Seems like a lot of unnecessary bloat?

I turned it on on general principles (it was part of the Civi checklist). I think the nearest-term use case for it would be sending emails to everyone in a particular region (origamiusa.org uses it to notify people of events in their area). I don't feel strongly about it, so would be happy to turn it off and deinstall if bloat concerns override potential future usage.

**Comment by jenlampton** [comment]
I'd prefer we leave it off until "potential future usage" becomes "current
usage" :)

**Comment by bugfolder** [comment]
> I'd prefer we leave it off until "potential future usage" becomes "current usage" :)

Fair enough. I'll turn it off and uninstall.

**Comment by bugfolder** [comment]
It's off and uninstalled.

Interestingly, though, if I hadn't installed geocoding, I wouldn't have discovered the .gitignore issue that was causing the loss of .sql files from CiviCRM. Those are used to set up tables in the installation of various things, including extensions (that initially broke the geocoder).

It occurred to me that that problem might also have broken the original installation of SearchKit in such a way that the result broke the status page (hence, the observed blank page). I had disabled SearchKit to bring back the status page. Now I deinstalled it entirely, and then (after the .gitignore fix and restoring the missing .sql files sprinkled throughout Civi) reinstalled SearchKit extension from scratch.

Ta-da! Status page still works now with SearchKit enabled.

Since the initial installation of CiviCRM 5.55.0 enabled SearchKit by default (and Civi has stated that SearchKit is the way of the future for Civi and will eventually be merged into Civi core), I'm going to assume we're better off having it enabled.

**Comment by jenlampton** [comment]
Nice sleuthing!

**Comment by bugfolder** [comment]
And I think that since we're up and running with an entirely happy CiviCRM status page, we can close this issue. There are some remaining follow-up issues, which are [in the CiviCRM project](https://github.com/backdrop-ops/backdropcms.org/projects/3).
