### ISSUE TITLE
Race-condition in GitHub Webhooks sometimes double-creates releases and project nodes 

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdropcms.org#948]
We've seen an issue intermittently with two project nodes getting created for a single project. This appears to be because GitHub has increased the granularity of their "release" events. Previously, there was only a single event when a release was created, now there are several:

- published
- unpublished
- created
- edited
- deleted
- prereleased
- released

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

It seems as though our code is only set up to handle a generic "release" event, which might happen on any of the above event types.

**Comment by quicksketch** [comment]
This PR adds a wrapping `if {}` statement around our response to release events: https://github.com/backdrop-ops/backdropcms.org/pull/949

**Comment by quicksketch** [comment]
@bugfolder Maybe you could take a look at this and check if it looks right to you? The GitHub documentation for the contents of the payload I think are validation enough for us to confirm that `$payload['action']` exists and should be set to `published`. See https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release

**Comment by docwilmot** [comment]
Thanks @quicksketch I'd meant to do this after https://github.com/backdrop-ops/backdropcms.org/issues/875. I think `published` is right (unless GH has changed things again since then) to allow a project node to be created on pre-release as well.

**Comment by quicksketch** [comment]
Yeah there are a number of "warnings" on the documentation page:

![image](https://user-images.githubusercontent.com/100206/199886556-b995df24-8fad-4d06-a91c-eb6bb2435f0d.png)

The last one in particular covers this situation:

> Note: The prereleased type will not trigger for pre-releases published from draft releases, but the published type will trigger. If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.


Since we want to make a package on both stable and pre-release creation, I think `published` is the right event type.

**Comment by bugfolder** [comment]
All the above makes sense to me, albeit subject to my very limited expertise/experience with GHA and this process. But I infer from the discussion above that it also makes sense to those who do have expertise/experience with GHA and this process, so unless I hear otherwise in the next few days, I will merge this (unless someone else beats me to it).

**Comment by quicksketch** [comment]
Oops, this fix should have gone into project module. Now that we have a new release I noticed this was going to get reverted. I'll cherry-pick this commit over to project.module and make another release.
