### ISSUE TITLE
CIviCRM: do security mailings from CiviCRM group members

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#958]
Per @jenlampton:

Here's the code that pulls the old field value for security updates: https://github.com/backdrop-ops/backdropcms.org/blob/209c63a1b965fda9bfca2c6df900602dbf0f3f3c/www/modules/custom/borg_mailers/borg_mailers_security/borg_mailers_security.module#L68

backdropcms.org/borg_mailers_security.module at 209c63a1b965fda9bfca2c6df900602dbf0f3f3c · backdrop-ops/backdropcms.org

it looks like we could just use another database query?

Yes, we can do this from a CiviCRM API call. RJL to take on.

Some urgency to get this implemented.

**Comment by bugfolder** [comment]
@jenlampton, I've posted a PR that gets the list of emails, keyed on the uid, from CiviCRM, for the recipients of security updates.

**Comment by jenlampton** [comment]
@bugfolder the PR looks great, thank you so much! I've merged it. Feel free to deploy when suitable.
