### ISSUE TITLE
Layout previews not shown in layout list

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#97]
Layouts have a `preview.png` (https://api.backdropcms.org/layouts) which isn't being used on .backdropcms.org/layouts.

**Comment by jenlampton** [comment]
Layout projects can be a set of layouts, with one preview.png per layout. Do we just show the first one, all of them, or how do we decide?

**Comment by docwilmot** [comment]
If there's one in the project root use that, if not use the first one in the next. Let the layout developers worry about that. 
I also think there should be a default icon/graphic for projects which dont provide one. Like Gmail provides a squarish thing with the first letter of the name of the emailer if they dont have a profile pic.

**Comment by jenlampton** [comment]
Also related: https://github.com/backdrop/backdrop-issues/issues/1517

**Comment by docwilmot** [comment]
Dupe of https://github.com/backdrop/backdrop-issues/issues/1517
