### ISSUE TITLE
Error message when attempting to add a mention on LIVE site

### ISSUE THREAD

**Issue by Wylbur** [backdrop-ops/backdropcms.org#970]
Today, I tried to add a new External mention to the LIVE backdropcms.org website.  

URL:  https://backdropcms.org/node/add/external-mention
Error Message:
```
Error
count(): Argument #1 ($value) must be of type Countable|array, string given
```
Error log: https://backdropcms.org/admin/reports/event/2799160
Error Log Details:
```
TypeError: count(): Argument #1 ($value) must be of type Countable\|array, string given in _restrict_abusive_words_node_form_submit() (line 376 of /home/backdrop/repo/www/modules/contrib/restrict_abusive_words/restrict_abusive_words.module).
--
```

It looks like a PHP 8.1 error, so I will add this to the restrict_abusive_words project website.

**Comment by bugfolder** [comment]
This isn't a PHP issue; it's a bug in RAW that happens in all PHP versions. Creating a new issue (the fix is simple and will follow).

**Comment by bugfolder** [comment]
Closing in favor of https://github.com/backdrop-contrib/restrict_abusive_words/issues/13.

**Comment by bugfolder** [comment]
Well, I'll leave it open until the fix is actually applied to b.org.

**Comment by bugfolder** [comment]
It's on b.org. Closing.
