### ISSUE TITLE
Changing checkbox on Subscriptions profile causes CiviCRM crash

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#981]
Going to one's Subscriptions profile at `https://backdropcms.org/user/UID/edit/Subscriptions_15` and trying to change a subscription results in a crash with watchdog error

TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in include() (line 15 of /home/backdrop/repo/www/files/civicrm/templates_c/en_US/%%4D/4DC/4DC76B26%%body.tpl.php).

**Comment by docwilmot** [comment]
Also, that link works just as it is there (with the string "UID" instead of a number), and shows form with a Save button. I put in random strings, same result. Put in random integers, and some give a page not found, others a PHP error.

**Comment by bugfolder** [comment]
Same behavior on beta.backdropcms.org. Oddly, though, this works just fine on my local copy of b.org (which makes me wonder if there's a file permissions issue going on).

**Comment by bugfolder** [comment]
Interesting. If you check/uncheck a box and click "Save", we get the error, but the check/uncheck was properly recorded.

**Comment by bugfolder** [comment]
Same behavior after updating CiviCRM to 5.58.1. Crashes on b.org, beta.b.org, no crash on a local installation.

Ah, but there is a watchdog warning on the local:

Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 15 of /mysite/files/civicrm/templates_c/en_US/%%4D/4DC/4DC76B26%%body.tpl.php).

Same underlying problem; it's just a warning, not a crash. The local is on PHP 7.4, b.org is on PHP 8.1. So presumably stricter PHP 8.1 explains the difference. Let's check:

Setting the local to PHP 8.1.13 reproduces the error now on the local, same as on b.org.

Same error with PHP 8.0.24.

Well, now it's reproducible for further investigation.

**Comment by docwilmot** [comment]
Could you post what on that line though? Dont think all of us brave enough to install Civi locally.

**Comment by bugfolder** [comment]
Sure. Line 15 is:

```
<?php if (( $this->_tpl_vars['snippet'] !== 'json' ) && ! $this->_tpl_vars['suppressForm'] && count ( $this->_tpl_vars['form']['errors'] ) > 0): ?>
```

That's a compiled template file. CiviCRM uses Smarty as its templating system and creates compiled versions of templates for messages, pages, and the like (which are all stored within `files/civicrm/templates_c` directory). So that file isn't in the CiviCRM module codebase; it's generated. (In fact, it is safe to completely delete the `templates_c` directory, because Civi will regenerate the compiled template files as needed.)

The "local" that I'm using is a local version of b.org, using the sanitized databases and the b.org repo. So it's got CiviCRM in it (and that page, "Subscriptions," is generated by CiviCRM, as a CiviCRM "Profile").

**Comment by bugfolder** [comment]
OK, got some information. That compiled template is generated from template `templates/CRM/Form/body.tpl`, which has this corresponding line:

```
{if ($snippet !== 'json') and !$suppressForm and count($form.errors) gt 0}
```

The problem was that `$this->_tpl_vars['form']['errors']` didn't exist. So this error can be suppressed by changing the line in the template file to

```
{if ($snippet !== 'json') and !$suppressForm and count($form.errors ?? []) gt 0}
```

and wiping out `templates_c` (thereby forcing regeneration of the compiled templates). But the are still a lot of watchdog PHP warnings like this:

Warning: Undefined array key "options_per_line" in include() (line 58 of /mysite/files/civicrm/templates_c/en_US/%%0A/0AF/0AF6F87E%%Dynamic.tpl.php).

7 such warnings each time the page is loaded (not even submitted); 43 of them if the page is submitted (with no changes to the form elements). So there's still something amiss.

**Comment by bugfolder** [comment]
This looks similar to a bug that was reported in CiviCRM GitLab just 6 days ago:

https://lab.civicrm.org/dev/backdrop/-/issues/78

I've added this report over there.

**Comment by bugfolder** [comment]
CiviCRM Core PR submitted: https://github.com/civicrm/civicrm-core/pull/25606

**Comment by bugfolder** [comment]
I've created PR against b.org with the fix and deployed it to b.org. It appears to have fixed the issue; altering one's Subscriptions no longer crashes or puts warnings into watchdog.
