### ISSUE TITLE
Update feed and Project feed inconsistencies

### ISSUE THREAD

**Issue by ericfoy** [backdrop-ops/backdropcms.org#987]
## Update:
This issue is not an issue at all for a different website, so maybe it's just a twenty-four hour delay thing, or maybe there's something really weird about the site (mysite.com, below) upon which the problem is (was) experienced. Either way, this issue should probably be ignored. If I encounter it again, I'll repost.

### Summary
Backdrop downloads the correct version, but installs the previous version, even though displaying the correct one everywhere.
### The Story
I discovered this issue when attempting to update my theme on an existing site (mysite.com) from Modoc ver. 1.x-1.0.1 to ver. 1.x-1.1.0.
Looking at "available updates" at mysite.com, it informed me that an update was available. It correctly showed that the installed version was 1.x-1.0.1, and that ver. 1.x-1.1.0 was available. Upon installing the update, however, nothing happened. Then "available updates" continued the same result, showing that 1.0.1 is installed, and 1.1.0 is available.

So I disabled the current version and deleted the modoc folder from the themes folder on the server. I then went to "install new themes", and installed the latest version, which reported itself to be 1.x-1.1.0.  --> instead, it installed ver. 1.0.1

### Now going to backdropcms.org/project/modoc we see the following correct-looking screen:
---
![image](https://user-images.githubusercontent.com/60248933/232641443-b2f90aec-e7c8-48d8-a72e-a2b9be4d5590.png)

---
### Then, clicking on "releases," we get
---
![image](https://user-images.githubusercontent.com/60248933/232641605-a11dc9d8-d4f7-4b8f-92e4-8d7a65dd2226.png)

# ...

**Comment by jenlampton** [comment]
We actually have two different feeds (as I learned today) one for updates at https://updates.backdropcms.org, and one for installing things at https://projects.backdropcms.org. 

I suspect there was a small period of time where the two were out of sync. Or maybe one cache had cleared, but the other had not. 

Definitely worth looking into as what you experienced sounds frustrating.

**Comment by ericfoy** [comment]
I think I must have simply been impatient. Er'thang seems to work fine now.

**Comment by ericfoy** [comment]
This doesn't seem to be a persistent issue, so I think it should not remain open.
