### ISSUE TITLE
Permissions check for all backdropcms.org properties.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#991]
It is theoretically possible that a file could be created within `home/repo/config/live-active` that has the owner and group of the shell user, making the file no longer web-writable, which can cause failures on the production site. However, this **should** never happen, as all config files should either be created by install or update actions (by the web server) or be added first into `home/repo/config/staging` and then a config-sync will write them to `home/repo/config/live-active` (also done by the web server). If w do ever encounter this problem, we should investigate how it happened and see if we can prevent that :)

Shell user information:
- Each site has its own shell user. 
- The web server operates as `www-data`. 
- The shell user should be a member of the `www-data` group. 

Our permissions should be set up as follows:

The parent directories should not be web writable, so both owner and group should be only the shell user.  Within those directories, we have three locations that need to be writable by the web server, so these need to have the group `www-data` instead of the shell user. (Owner should still be the shell user.)
- The public files directory. (inside web root)
- The private files directory. (outside web root)
- The config directory. (outside web root)

Notes:
- If a site has the project browser installed (none of ours do) then the `modules`, `themes`, and `layouts` directories would also need to be web-writable (this does not apply to backdropcms.org properties - noting here for public reference).
- If a site has the self-update feature enabled (none of ours do) then the `core` directory would also need to be web-writable (this does not apply to backdropcms.org properties - noting here for public reference).
- if the git repository directory is not owned by the shell user, we will have problems using Git.

Review all sites to confirm they are set up properly:

- [x] Review backdropcms.org file permissions
- [x] Review docs.backdropcms.org file permissions
- [x] Review forum.backdropcms.org file permissions
- [x] Review events.backdropcms.org file permissions
- [x] Review localize.backdropcms.org file permissions

**Comment by jenlampton** [comment]
The events site was fine, but all the others needed a little adjusting.

**Comment by bugfolder** [comment]
I'm reopening this because the file permissions on b.org are not correct in their present state. In particular, there are subdirectories of `www/files/civicrm/templates_c/...` that are not writeable by the `www-data` user, and that is causing CiviCRM to tantrum (as of 2023-04-25).

One can see examples (at least right now) by running this on the server:

```
ls -la ~/repo/www/files/civicrm/templates_c/en_US
```

**Comment by jenlampton** [comment]
I'll have a look...

**Comment by jenlampton** [comment]
I've updated the permissions on the whole `civicrm` directory to be writable by the `www-data` user. Is there a way to test the civi tantrum to see if this change resolves those issues?

**Comment by bugfolder** [comment]
Yes, hang on...

**Comment by bugfolder** [comment]
I've been DMing with @cellear, who uncovered the tantrum. He reports it working now!

**Comment by cellear** [comment]
Looks like it worked: 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/757296/234404785-0ba84693-7b45-44bc-8cb5-876cea1def5a.png">

**Comment by jenlampton** [comment]
Phew!
