### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#993]
During the SEO meeting yesterday I ran an accessibility test with Lighthouse, these broken links were called out. 

The icons are links, that result in a 'page not found' error. The right icon is working for some reason, despite the fact the other two are not. I can't see where these links are created, which suggests to me that this is a custom block in custom code. 

@jenlampton is this something you can fix quickly?

![image](https://user-images.githubusercontent.com/3144571/233455921-bff38921-90a1-4dcd-a17a-a889856e696c.png)

**Comment by jenlampton** [comment]
I can update them, I think these pages moved to the docs site. There should be redirects in place, so I'll add those too.

**Comment by jenlampton** [comment]
As a quick fix I have added redirects from the old nodes to the docs site, and clicking those icons will no longer 404.

**Comment by jenlampton** [comment]
I have also updated the custom code and pushed the change to production.
